### ISSUE TITLE
Load balancer certificate with private key triggers replace after import

### ISSUE THREAD

**Issue by lucianf** [oracle/terraform-provider-oci#1024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.12.24
+ provider.oci v3.70.0

### Affected Resource(s)

oci_load_balancer_certificate

### Terraform Configuration Files

```hcl
resource "oci_load_balancer_certificate" "xxx" {
  certificate_name = "xxx"
  load_balancer_id = oci_load_balancer_load_balancer.xxx.id

  ca_certificate     = file("xxx")
  public_certificate = file("xxx")
  private_key        = file("xxx")
  passphrase         = ""

  lifecycle {
    create_before_destroy = true
  }
}
```

Imported with

```
terraform import oci_load_balancer_certificate.xxx "loadBalancers/ocid1.loadbalancer.oc1.xxx/certificates/xxx"
```

### Expected Behavior

No diff after import

### Actual Behavior

`plan/apply` trigger a resource replace due to a diff picked up on `private_key`.

### Steps to Reproduce

1. `terraform apply`

```
Terraform will perform the following actions:

  # xxx must be replaced
+/- resource "oci_load_balancer_certificate" "xxx" {
        ca_certificate     = <<~EOT
            -----BEGIN CERTIFICATE-----
            MII...
            -----END CERTIFICATE-----
        EOT
        certificate_name   = "xxx"
      ~ id                 = "loadBalancers/ocid1.loadbalancer.oc1.xxx/certificates/xxx" -> (known after apply)
        load_balancer_id   = "ocid1.loadbalancer.oc1.xxx"
      + private_key        = (sensitive value)
        public_certificate = <<~EOT
            -----BEGIN CERTIFICATE-----
            MII...
            -----END CERTIFICATE-----
        EOT
      + state              = (known after apply)

      - timeouts {}
    }
```

**Comment by afedorch** [comment]
@lucianf Thanks for reporting the problem!

The `private_key` argument is `ForceNew` in the schema: https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/load_balancer_certificate_resource.go#L59
It means that any diff in the value will result in resource recreation. 
The `private_key` value is not returned by the service (what probably makes sense for the `private_key`) you can check the API here: 
https://docs.cloud.oracle.com/en-us/iaas/api/#/en/loadbalancer/20170115/Certificate/ it means that after the `import` terraform will detect a diff between the configuration and state value for the `private_key` and will suggest to recreate the resource.

I am not sure that anything could be done on provider side if there is no value from the service, for example if we add `DiffSuppressFunc` for the argument to ignore empty value users will be able to specify any `private_key` without the diff and assume that the specified one is correct.

You can update configuration by removing `private_key` or adding `ignore_changes = ["private_key"]` to the `lifecycle` - it will not allow to re-verify the `private_key` value but will stop resource recreation after the import.

**Comment by lucianf** [comment]
Thanks @afedorch I ended up marking it for ignore - this is a similar situation with #58, I guess there's not much you can do for these one-time, one-way fields.

One question though (I'm lazy to test): if said resource had been provisioned through the provider rather than imported, would it have come back with the same diff on subsequent checks?

**Comment by afedorch** [comment]
@lucianf during resource creation provider will get `confirmation` from the service that the resource is created (with specified `private_key`) and will be able to track any local change for the `private_key` value. It means that you should not see any diff until you modify the `private_key` (provider will suggest recreating the resource for any change in `private_key` value). You can check the example in the repo: https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/load_balancer/lb_full/lb_full.tf#L247

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
