### ISSUE TITLE
Unable to create oci_file_storage_export with squash that allows write. Why?

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1038]
I have tried to define File Storage Service filesystem, mount, export with all_squash enabled and find the resulting folder is un-writable.

```hcl
resource "oci_file_storage_file_system" "fs" {
  availability_domain = var.availability_domain
  compartment_id      = var.compartment_id
  display_name        = "FS Test"
}

resource "oci_file_storage_mount_target" "mount" {
  availability_domain = var.availability_domain
  compartment_id      = var.compartment_id
  subnet_id           = var.subnet_id
  display_name        = "Mount. Test"
}

resource "oci_file_storage_export" "export" {
  export_set_id  = oci_file_storage_mount_target.mount.export_set_id
  file_system_id = oci_file_storage_file_system.fs.id
  path           = "/fs"

  export_options {
    source                         = "0.0.0.0/0"
    access                         = "READ_WRITE"
    anonymous_gid                  = 1001 #opc
    anonymous_uid                  = 1001 #opc
    identity_squash                = "ALL"
    require_privileged_source_port = true
  }
}
```

After creating along with appropriate Security List/NSG, I can mount to a local folder but cannot write to it (not even as root) nor can I change ownership of the mounted folder. If I umount then I can adjust permissions and ownership on folder but it is reset to root:root when mounted. Argh!

The only option I've found is to mount with squash off _then_ set ownership/permissions the unmount _then_ update the script to enable squash _then_ apply _then_ remount. Argh! again.

Any other suggestions how to mount a folder with all_squash on that is accessible for any write operations?

**Comment by rashik-bhasin** [comment]
Thanks for asking this question. 
I discussed with the service team and this is the desired behavior. FSS file systems start with the root directory being owned by root. Setting `identity_squash="All"` causes all users to get mapped to a single user. This user is typically not root, so you can't do anything with a new file system.
The work around is as you describe, export the file system w/o identity_squash , access the file system as root, set the ownership and permissions as desired, and then change the client option to do the desired identity_squash. 
Or you can do it with no squash then chown and then add squash. unmounting won't be required this way.
Thanks!

**Comment by jeliker** [comment]
Thank you for your thoughts on this. Where I am torn is how to achieve the above through Terraform without having to manually edit to remove squash, apply, manually edit to add back squash, apply again.

Is that truly my only option?

**Comment by rashik-bhasin** [comment]
Thanks for the response.
Currently, manual editing it the only option. I have raised this issue with service team once they resolve it on there part, only then it can be handled better on terraform-provider side. 
Thanks!

**Comment by jeliker** [comment]
Thank you. I hope my rationale is apparent. That is, I expect my Terraform files to represent the final state not an intermediate state that requires manual changes. I understand the dilemma here in wanting behavior the same for FSS as it is for NFS proper but also think there is a place for option variables like this example

```hcl
variable "owner_uid" {
  description = "User ID of owning user for export folder."
  type        = number
  default     = 101
}

variable "owner_gid" {
  description = "Group ID of owning group for export folder."
  type        = number
  default     = 1001
}

variable "permissions" {
  description = "Permission string of three digits."
  type        = string
  default     = "751"
}

resource "oci_file_storage_export" "test_export" {
  #Required
  export_set_id  = var.export_set_id
  file_system_id = var.file_system_id
  path           = var.export_path

  #Optional
  export_options {
    #Required
    source          = var.source

    #Optional
    access          = var.access
    anonymous_gid   = var.anonymous_gid
    anonymous_uid   = var.anonymous_uid
    identity_squash = var.identity_squash
    permissions     = var.permissions
    require_privileged_source_port = var.require_privileged_source_port
  }

  owner_gid = var.owner_gid
  owner_uid = var.owner_uid 
}
```

**Comment by rashik-bhasin** [comment]
Thank you for the response. 
Surely your ask is taken. As the terraform is able to create the resources you want to create, it's working fine from our side. The issue is with the service implementation and we have raised the issue with the service team. Once they resolve it, we will be integrating that in terraform as well. 

Closing this issue. Feel free to ask any follow up questions.

**Comment by jeliker** [comment]
Unable to be resolved because of constraints on upstream API
