### ISSUE TITLE
Local Peering Gateway not able to import peer_id

### ISSUE THREAD

**Issue by pranavsriram8** [oracle/terraform-provider-oci#1081]
Community Note

    Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
    Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
    If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform Version and Provider Version

Terraform v0.12.24

    provider.oci v3.78.0

Affected Resource(s)

    oci_core_local_peering_gateway

When I try to import an LPG from an existing infrastructure, the peer_id seems to be null, can this information be extracted somehow?

the command I ran 
`terraform import  module.lpgs.oci_core_local_peering_gateway.secedge_lpg "ocid1.localpeeringgateway.________wshd4o5jt5u2vgoy________"`

"module": "module.lpgs",
      "mode": "managed",
      "type": "oci_core_local_peering_gateway",
      "name": "secedge_lpg",
      "provider": "provider.oci",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "compartment_id": "ocid1.compartment.oc1..a______________qguw5cngffgpnpqtop7divnbyyr____",
            "defined_tags": {},
            "display_name": "secedge-peer",
            "freeform_tags": {},
            "id": "ocid1.localpeeringgateway.________________ucagbkjbf3zlkufk3fhgwshd4o5jt_______",
            "is_cross_tenancy_peering": true,
            "peer_advertised_cidr": "xxx.xxx.xxx.0/26",
            "peer_advertised_cidr_details": [
              "xxx.xxx.xxx.0/26"
            ],
            "peer_id": null,
            "peering_status": "PEERED",
            "peering_status_details": "Connected to a peer.",
            "route_table_id": null,
            "state": "AVAILABLE",
            "time_created": "2020-04-15 22:26:49.626 +0000 UTC",
            "timeouts": {
              "create": null,
              "delete": null,
              "update": null
            },
            "vcn_id": "ocid1.vcn._______________oqa3fv6u3tej5h______l337pefkkfb5yk7yc_______"
          },
          "private": "........"
        }
      ]
    }

**Comment by mulpk** [comment]
Hi @pranavsriram8

Thanks for reaching out.
this is happening as peer_Id is currently not part of GET for LPG resource. 
we have raised a ticket with the service team. For now, the workaround is to manually add the peer_id in the state file.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
