### ISSUE TITLE
Data Guard Association - terraform destroy not working

### ISSUE THREAD

**Issue by simon-neto** [oracle/terraform-provider-oci#1089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
$ terraform version
Terraform v0.12.24
+ provider.oci v3.78.0

### Affected Resource(s)

oci_database_data_guard_association
### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
resource "oci_database_db_system" "home_db_system" {
    #Required
    availability_domain = data.oci_identity_availability_domains.AvailabilityDomains.availability_domains[0].name
    compartment_id = var.compartment_ocid
    database_edition = var.database_edition
    db_home {
        #Required
        database {
            #Required
            admin_password = var.db_home_database_admin_password

            #Optional
            db_backup_config {

                #Optional
                auto_backup_enabled = true

            }
            db_name = "HomeDB"
            db_workload = "OLTP"
        }
        #Optional
        db_version = var.db_version
        display_name = "HOME-DB"
    }
    hostname = "homedb"
    shape = var.instance_shape
    ssh_public_keys = [var.ssh_key]
    subnet_id = local.home_private_sn_id
    data_storage_size_in_gb = var.data_storage_size_in_gb
    #Optional
    display_name = "HomeDB"
    license_model = var.license_model
    node_count = var.node_count
}
locals {
  database_id = oci_database_db_system.home_db_system.db_home[0].database[0].id
}


# DR
resource "oci_database_data_guard_association" "home_data_guard_association" {
    #Required
    creation_type = "NewDbSystem"
    database_admin_password = var.db_home_database_admin_password
    database_id = local.database_id
    delete_standby_db_home_on_delete = "true"
    protection_mode = "MAXIMUM_PERFORMANCE"
    transport_type = "ASYNC"

    #Optional
    availability_domain = var.remote_availability_domain
    display_name = "RemoteDB"
    hostname = "remotedb"
    shape = var.instance_shape
    subnet_id = var.remote_private_subnet_id
}
```

### Debug Output

provider-oci_v3.78.0_x4
2020-06-10T16:29:25.208+1000 [DEBUG] plugin.terraform-provider-oci_v3.78.0_x4: 2020/06/10 16:29:25 [INFO] terraform-provider-oci 3.78.0
2020-06-10T16:29:25.208+1000 [DEBUG] plugin.terraform-provider-oci_v3.78.0_x4: 2020/06/10 16:29:25 Executable runs in Terraform plugin mode by default. For additional usage options, please run with the '-help' flag.
2020-06-10T16:29:25.211+1000 [INFO]  plugin.terraform-provider-oci_v3.78.0_x4: configuring server automatic mTLS: timestamp=2020-06-10T16:29:25.211+1000
2020-06-10T16:29:25.270+1000 [DEBUG] plugin.terraform-provider-oci_v3.78.0_x4: plugin address: address=/tmp/plugin888910323 network=unix timestamp=2020-06-10T16:29:25.270+1000
2020-06-10T16:29:25.270+1000 [DEBUG] plugin: using plugin: version=5
module.Home.oci_database_data_guard_association.home_data_guard_association: Destroying... [id=ocid1.dgassociation.oc1.ap-sydney-1.abzxsljrampo6zax3pj2uldek3tmnjj2whknq5w4n4vquwwerthndf4pukna]
2020/06/10 16:29:25 [DEBUG] module.Home.oci_database_data_guard_association.home_data_guard_association: applying the planned Delete change
2020/06/10 16:29:25 [DEBUG] module.Home.oci_database_data_guard_association.home_data_guard_association: apply errored, but we're indicating that via the Error pointer rather than returning it: could not delete standby DB System to delete the data guard association: Service error:InvalidParameter. Expected region ap-sydney-1 but found region ap-melbourne-1. http status code: 400. Opc request id: a1390ba35594adff9a7a22500fc09ca4/60F3F0A7DC6C25C0617D27F7E997D185/5CF72F972DF9D9E8AAC401B615DA6AA0
2020/06/10 16:29:25 [ERROR] module.Home: eval: *terraform.EvalApplyPost, err: could not delete standby DB System to delete the data guard association: Service error:InvalidParameter. Expected region ap-sydney-1 but found region ap-melbourne-1. http status code: 400. Opc request id: a1390ba35594adff9a7a22500fc09ca4/60F3F0A7DC6C25C0617D27F7E997D185/5CF72F972DF9D9E8AAC401B615DA6AA0
2020/06/10 16:29:25 [ERROR] module.Home: eval: *terraform.EvalSequence, err: could not delete standby DB System to delete the data guard association: Service error:InvalidParameter. Expected region ap-sydney-1 but found region ap-melbourne-1. http status code: 400. Opc request id: a1390ba35594adff9a7a22500fc09ca4/60F3F0A7DC6C25C0617D27F7E997D185/5CF72F972DF9D9E8AAC401B615DA6AA0
2020/06/10 16:29:25 [ERROR] module.Home: eval: *terraform.EvalOpFilter, err: could not delete standby DB System to delete the data guard association: Service error:InvalidParameter. Expected region ap-sydney-1 but found region ap-melbourne-1. http status code: 400. Opc request id: a1390ba35594adff9a7a22500fc09ca4/60F3F0A7DC6C25C0617D27F7E997D185/5CF72F972DF9D9E8AAC401B615DA6AA0

### Expected Behavior

I expect that when issuing terraform destroy, terraform would destroy the data guard association first, then the primary database.

### Actual Behavior

Unable to perform terraform destroy, instead, if I drop the standby database system either via the console or via the cli, I can come back and run terraform destroy and the rest of the resources, including the primary database, gets destroyed.

### Steps to Reproduce

terraform apply using the script above
after build run terraform destroy

### Important Factoids

Using VM DB System
Launching VM DB System as standby via Data Guard creation process (i.e. am not using existing DB System for standby)

**Comment by alexng-canuck** [comment]
Hi @simon-neto , by any chance, are your primary and standby db systems in different OCI regions?
This may be a possible bug in how the dataguard association resource deals with cross-region peering relationships.

**Comment by simon-neto** [comment]
Hi Alex, yes it's in a remote region.

**Comment by sbemarkar** [comment]
I still face the same issue with primary and standby db in different OCI regions...This is the error I get 

"**_Error: could not delete standby DB System to delete the data guard association: Service error:InvalidParameter. Expected region iad but found region phx. http status code: 400. Opc request id:_** "

Is this issue resolved and if so kindly provide the terraform solution.
