### ISSUE TITLE
Do multiple oci_waas_protection_rule resources process together when added/changed?

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1150]
I intend to update multiple ```oci_waas_protection_rule``` resources using a pattern like this:

```hcl
variable "projection_rules" {
  default = [
    {key    = "90001"
     action = "DETECT"},
    {key    = "90004"
     action = "DETECT"},
    {key    = "90006"
     action = "DETECT"}
  ]
}

resource "oci_waas_protection_rule" "the_protection_rule" {
  count          = length(var.protection_rules)
  
  #Required
  waas_policy_id = var.waas_policy_id
  key            = var.protection_rules[count.index].key

  #Optional
  action         = var.protection_rules[count.index].action
}
```

In OCI Console, we would change the action on a set of rules then publish all at once. If I change rule states via Terraform provider, does this cause one publish action for each new rule resource or are they somehow batched?

**Comment by govindrao55** [comment]
Hi @jeliker, specifying `count` is same as having the representation for the resource as many times in the configuration. The terraform will cause one publish action for each new rule. In theory, terraform may paralellize provisioning multiple resources if they are independent. The parallelism is based on the value set for [-parallelism](https://www.terraform.io/docs/commands/apply.html#parallelism-n) flag which defaults to 10, meaning 10 threads would be walking the dependency graph. Does this answer your question?

**Comment by jeliker** [comment]
That matches my understanding. Thank you for confirming.

My follow-up is to ask if that is proper behavior given the nature of how protection rules are applied via the other API interfaces. Since the publishing process runs between 15 and 30 minutes, adding 20 rules is a serious commitment when they are being published one at a time (8-10 hrs to complete)?

For comparison, with the OCI CLI tool I can submit a group of rules all at once in a single publishing step (i.e. 15-30 minutes vs. 8-10 hrs).

My work-around was to publish all rules via the CLI tool then import all rules via "terraform import" as individual resources. While this worked, it seemed like an unnecessarily complex method to avoid the multiple hours it would have otherwise taken to complete.

**Comment by govindrao55** [comment]
Hi @jeliker , This is a good question. The OCI CLI tool and Console leverage the update API that can publish multiple protection rules in a single call. Though `oci_waas_protection_rule` resource is based on the same API, unfortunately, there is no straight forward way to leverage the API as is in terraform. 
Also, the protection rules are created by the service when the waas policy resource is created by the user. There were constraints that prevented the protection rules to be supported under waas policy resource which led to protection rule as a top level resource in terraform. 
The work around that you suggest is the right thing to do for now to save the time. I will internally raise this as an enhancement request with the waas service team.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
