### ISSUE TITLE
If a running instance dies with an attached volume, then `terraform destroy` fails

### ISSUE THREAD

**Issue by devcamcar** [oracle/terraform-provider-oci#116]
## Description of the bug:

I ran into a scenario where a VM had died with an attached volume.  Upon issuing `terraform destroy`, I received the message at the bottom of this ticket.  Basically, if the instance is gone then there is no need to try to detach the volume, or at the very least if it fails to detach because it isn't currently attached, then this should not be a failure scenario.

    Error applying plan:

    1 error(s) occurred:

    * baremetal_core_volume_attachment.bosh_cli_vol_attach (destroy): 1 error(s) occurred:

    * baremetal_core_volume_attachment.bosh_cli_vol_attach: Code: Conflict; OPC Request ID: /95EA2983DC80459E8FAF4A76DDB2FC56/429BB70B336D4A46BA507248EE1D5369; Message: Volume attachment ocid1.volumeattachment.oc1.phx.abyhqljt657wag25sbqzvmkfxsp42ix4hm6vn72wkpz2rpg3iiucsyxq5tra is not currently attached

**Comment by craigcarl-oracle** [comment]
Terraform refresh should manage this, need to test. I'll own the test.

**Comment by codycushing** [comment]
Block storage team says when a compute instance dies with a volume attached, the attachment remains so it will be available to the instance when it is restored. 

We will need to recreate this scenario to investigate the provider behavior and debug with the service teams.

**Comment by alexng-canuck** [comment]
I'm picking this issue up from @kohashim.

@craigcarl-oracle, did you end up getting a repro of this?

So far, I've tried following cases but still couldn't see the reported error:
Case 1: Run `echo b > proc/sysrq-trigger` to cause the instance to break while volume was attached. I noticed the volume was still attached after the break. `terraform destroy` was successful.

Case 2: Manually detach the volume from instance via cloud console and then run `terraform destroy`. This was also successful.

**Comment by alexng-canuck** [comment]
It seems the original report had 2 issues:
1) Instance dying shouldn't result in volume being detached.
2) Even if volume were detached, terraform should have detected it before attempting to destroy it.

We were unable to repro either issue. Since this issue is 6 months old, it's possible we may have inadvertently fixed it.

@devcamcar, please feel free to reopen this if you see it again.
