### ISSUE TITLE
ADB resource `oci_database_autonomous_database_backup` failing with Error: unexpected state 'FAILED', wanted target 'ACTIVE'.

### ISSUE THREAD

**Issue by pguerin3** [oracle/terraform-provider-oci#1255]
I'm applying the scripts in terraform-provider-oci\examples\database\adb

The script successfully creates the following databases:
2 JSON Database
1 Transaction Processing
1 Data Warehouse
Then the error occurs "Error: unexpected state 'FAILED', wanted target 'ACTIVE'."
The error is related to the backups

My version of Terraform is:
>terraform -v
Terraform v0.12.29
+ provider.local v2.0.0
+ provider.oci v4.7.0
+ provider.random v3.0.0

The full log is here:
[error.txt](https://github.com/terraform-providers/terraform-provider-oci/files/5733221/error.txt)

**Comment by parrneet** [comment]
Hi @pguerin3 Database back failed due to an error from service. Please share the debug log that I can pass on to service team for investigation. 
`TF_LOG=DEBUG`
`OCI_GO_SDK_DEBUG=v`

**Comment by pguerin3** [comment]
[debug.txt](https://github.com/terraform-providers/terraform-provider-oci/files/5737817/debug.txt)

The head of the log is missing but I think this is enough for support to work on.

**Comment by srishtipmishra** [comment]
@pguerin3 - Can you please provide the tf config file? The service team needs info on the database name that this backup resource was being created from. Thanks
