### ISSUE TITLE
the call oci_load_balancer_listener is wrong on SSL cert settings

### ISSUE THREAD

**Issue by eugsim1** [oracle/terraform-provider-oci#1265]
Hi I m getting this error over and over :

```
Error: Service error:InvalidParameter. Invalid SSL configuration:
[Constraint sslConfiguration violation: Empty CA certificate. CA certificate is required for client validation.]. http status code: 400. Opc request id: 91bd3a595e968d1afe7b3debda0062a0/F78FD7BF07F224620F88AE708353D2C8/78E32CD2CFA85D176D2E35DC1B8A8A44

  on modules/loadbalancer/loadbalancer.tf line 115, in resource "oci_load_balancer_listener" "lb-httpslistener":
 115: resource "oci_load_balancer_listener" "lb-httpslistener" {
```
My Code :
```
resource "oci_load_balancer_listener" "lb-httpslistener" {
  depends_on =[oci_load_balancer_certificate.all_certificates]
  for_each = var.oci_load_balancer_hostname
  default_backend_set_name = oci_load_balancer_backend_set.load_balancer_backend_set[0].name  
  load_balancer_id         = oci_load_balancer.load_balancer.id
  name                     = format("%s_%s",each.value.name,"_HTTPS")

##  hostname_names           = [each.value.name]
  port     = 443#var.lbhttplisterner_port ##80
  protocol = "HTTP"
  //rule_set_names           = [oci_load_balancer_rule_set.test_rule_set.name]
  connection_configuration {
    idle_timeout_in_seconds = "2"
  }
    ssl_configuration {
        #Required
        certificate_name = each.value.name

        #Optional
        #cipher_suite_name = var.listener_ssl_configuration_cipher_suite_name
       # protocols = var.listener_ssl_configuration_protocols
        #server_order_preference = var.listener_ssl_configuration_server_order_preference
       # verify_depth = var.listener_ssl_configuration_verify_depth
       # verify_peer_certificate = var.listener_ssl_configuration_verify_peer_certificate
    }  
}
```

There is no reference in the docs about the CA certificate , the CA cert is optional and needed only in the cert creation.
If i created manually the listener with the SAME CERTIFICATE then everything is FINE !!
So the terraform call is wrong or the doc is wrong

**Comment by jotruon** [comment]
Hi @eugsim1, 
is your question about how to create `oci_load_balancer_certificate`? If that's the case then you can refer to the docs here:
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/load_balancer_certificate 

There is example on how you can create load_balancer with/without ssl_configuration as well: https://github.com/terraform-providers/terraform-provider-oci/blob/14a52c4069399be90472891f378e4127b8000b60/examples/load_balancer/lb_full/lb_full.tf#L398 

Let me know if you have any other questions

**Comment by eugsim1** [comment]
Hello
Please read carefully the bug report before to respond back with a reference on how to create a cert.
I will rephrase so i hope that you will understand the issue:
1/ I have created the certs for the LB, during the upload of the certs, if you read the docs, you will see that uploading the CA part of a cert is not mandatory - i haven't then uploaded this part as ITS NOT MANDATORY , in the example that ou send me you are uploading this non mandatory part 
2/I have tried to create a HTTP listener using this cert, but FROM THE API ITS NOT POSSIBLE AS AN EXCEPTION IS RAISED SEE THE DUMP THAT I HAVE ATTACHED, AS the API complained about missing CA certs. 
BUT IF I CREATE THE LISTENER WITH THE SAME CERTIFICATE FROM THE OCI CONSOLE  without the CA part, the listener is created without issues

SO what i m writting is EITHER there is an ISSUE with the API DESCRIPTION ` resource "oci_load_balancer_listener"` which DOESNT NOT STATES THAT "BEFORE TO USE THE CALL with SSL"  THE CA PART OF THE CERT HAS TO BE UPLOADED, or the call is bugged 

if i have upload the CA PART THE CALL WORKS, so for me there is an issue either in the DOCS, or in the CALL ( the CA part it not manadatory) 

Why then the manual creation of a listener associated with a cert doesn't need a CA ?

Why The TF creation of a listener associated with a cert need a CA and this is not written in the docs ( this is not the first time that i finding glitches ...) ?

**Comment by jotruon** [comment]
Thanks for clarification, I will forward to service team to fix document.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
