### ISSUE TITLE
oci_containerengine_node_pool_option needs filtering options on attributes

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#1285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating a node pool, we cannot use the oci_images data source. This is because sometimes, for a short period of time, the latest image returned by oci_images is not the same as what is available for nodepools. So, instead we have to use ```oci_containerengine_node_pool_option``` datasource and ```data.oci_containerengine_node_pool_option.node_pool_options.sources[0].image_id``` to get the latest image available to create node pools. 

However, there are many available versions of the images but we are not able to filter based on version e.g. Oracle Linux 7.8, Oracle Linux 7.9 etc. For now, we have to hard code the version which is not ideal. 

It would be better if the ```oci_containerengine_node_pool_option``` datasource is able to filter based on version of the image.

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

### References

https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/263

**Comment by govindrao55** [comment]
Hi @hyder , thanks for reaching out. I've internally raised an enhancement request with the `Container Engine for Kubernetes` team. Once filtering is supported at the API level, `oci_containerengine_node_pool_option` can be enhanced to support the same.

**Comment by hyder** [comment]
for a fix, you can use the following as for 

node_source_details.image_id  = element([for source in data.oci_containerengine_node_pool_option.node_pool_options.sources : source.image_id if length(regexall(var.node_pools.node_pool_os_version, source.source_name)) > 0], 0)

**Comment by hyder** [comment]
Hi, 

I'm reopening this issue. We need better filtering capabilities on this data source.

The above workaround has been working until recently when OKE added support for GPU. The problem is that now GPU images is being returned first and since we've been picking the 1st element in the from the data source that's returning image ids, it's now returning an image that is targeted at GPU and doesn't work with normal nodes anymore. 

We've created another workaround: (var.node_pools.node_pool_image_id == "none" && length(regexall("GPU",lookup(each.value,"shape"))) == 0) ? (element([for source in local.node_pool_image_ids : source.image_id if length(regexall("Oracle-Linux-${var.node_pools.node_pool_os_version}-20[0-9]*.*", source.source_name)) > 0], 0)) : (var.node_pools.node_pool_image_id == "none" && length(regexall("GPU",lookup(each.value,"shape"))) > 0) ? (element([for source in local.node_pool_image_ids : source.image_id if length(regexall("Oracle-Linux-${var.node_pools.node_pool_os_version}-Gen2-GPU-20[0-9]*.*", source.source_name)) > 0], 0)) : var.node_pools.node_pool_image_id

However, this issue will keep repeating when we eventually add ARM support to OKE. 

Please consider making the images for OKE a first class data source instead of us having to create workarounds.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
