### ISSUE TITLE
Ability to retrieve secret's content via GetSecretBundle API endpoint

### ISSUE THREAD

**Issue by cloud-account** [oracle/terraform-provider-oci#1298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently "oci_vault_secret" and "oci_vault_secret_version" data sources cannot retrieve secret's content.
These data sources provide generic information about the secret/version but not the content itself.
The ability to retrieve secret's content can be implemented using the following API:
https://docs.oracle.com/en-us/iaas/api/#/en/secretretrieval/20190301/SecretBundle/GetSecretBundle

### New or Affected Resource(s)

"oci_vault_secret" 
 "oci_vault_secret_version"

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

### References

#1266

**Comment by jotruon** [comment]
Hi @cloud-account,
Thanks for suggestion, I am investigate the API you propose https://docs.oracle.com/en-us/iaas/api/#/en/secretretrieval/20190301/SecretBundle/GetSecretBundle.

**Comment by jotruon** [comment]
Here is the response from service team:
`From terraform is a lot different from using OCI CLI/JDK. Api supports it, doesn't mean terraform would. Terraform is more like a client for our service, with limited operation allowed.

Let me clarify one thing. Currently, Oci Terraform only support get meta data from secret. You cannot create/ update secret via terraform. State file is tf file. In order to create secret, you need to store the secret in the .tf file, which is a violation of a lot of security if we store password in a state file. Same idea for retrieve secret from terraform, which it would also store in a state file for terraform, which is also security violation.`

**Comment by cloud-account** [comment]
Hi, 

Interesting point of view.

"In order to create secret, you need to store the secret in the .tf file, which is a violation of a lot of security if we store password in a state file. "
Yet, the passwords and secrets are stored in state files for multiple OCI resources, e.g.
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/database_db_system
The resource responsible for provisioning a DB System requires the following attribute:
admin_password - (Required) A strong password for SYS, SYSTEM, PDB Admin and TDE Wallet. 

Other vendors implement similar functionality in their Terraform Providers, e.g.:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/secretsmanager_secret_version
data "aws_secretsmanager_secret_version" "creds" {
# Fill in the name you gave to your secret
secret_id = "db-creds"
}

**Comment by mattiarossi** [comment]
Hi, I understand the reservations the OCI team may have in allowing VAULT secrets to be fetched from terraform and potentially stored insecurely in a tfstate file.
@cloud-account , If you are in control of who gets access to your tfstate file, you can work around this by using a helper script that fetches the secrets you need and assigns them to standard terraform variables to be used in your automation. This can be done using the Python or Go SDKs.

**Comment by cloud-account** [comment]
Hi mattiarossi,

> If you are in control of who gets access to your tfstate file, you can work around this by using a helper script

That would be option # 1 as defined in https://blog.gruntwork.io/a-comprehensive-guide-to-managing-secrets-in-your-terraform-code-1d586955ace1#3073 :

> Drawbacks to this technique
> - Not everything is defined in the Terraform code itself. This makes understanding and maintaining the code harder.
> - Everyone using your code has to know to take extra steps to either manually set these environment variables or run a wrapper script.
> - No guarantees or opinions around security. Since all the secrets management happens outside of Terraform, the code doesn’t enforce any security properties, and it’s possible someone is still managing the secrets in an insecure way (e.g., storing them in plain text).

<br>
<br>

> I understand the reservations the OCI team may have in allowing VAULT secrets to be fetched from terraform and potentially stored insecurely in a tfstate file.

The secrets can be accessed via CLI, SDK, API and injected into a state file. There is no way we can prevent storing secrets in a state file.
I think we should be focused on securing state files (encryption at rest/in transit, access control), not on making the use of secrets impossible with OCI Provider.

Besides, the Vault service can be used to generate short-lived secrets:

> "Secret Expiry Rule". This type of rule restricts how long the secret contents of a particular secret version can remain in use. This rule can also block the retrieval of secret contents for a secret or secret version past the configured expiration date.
> https://docs.oracle.com/en-us/iaas/Content/KeyManagement/Concepts/secretrules.htm

Seems like a great option for resource provisioning.

<br>

Below is a short list of providers that support secrets retrieval:
Azure:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_secret
AWS:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/secretsmanager_secret_version
GCP:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/secret_manager_secret_version
Hashicorp Vault:
https://registry.terraform.io/providers/hashicorp/vault/latest/docs/data-sources/generic_secret

**Comment by jeliker** [comment]
Agreed security is a concern but generally the security of state file ought to be well-defined regardless of individual resource or data source behaviors. The examples above about storing DB SYS password and also noting that Load Balancer private key and passphrase are stored suggest this is an existing issue not necessarily that "security concerns" ought to be the formal stance of only one service (retrieving secrets from the vault).

Note the precedent already exists for vault-decrypted data landing in the state file through `oci_kms_decrypted_data` as shown in this (modified) example from the documentation:

```hcl
data "oci_kms_decrypted_data" "test_decrypted_data" {
    #Required
    ciphertext = "QQqzaYCH+0rZbhjJ9qOmyAxuu/2G3JRoMmXhzU8c/AOPk2BNuj5o85iSuQku"
    crypto_endpoint = "https://aaquefbdkzxjk-crypto.kms.us-ashburn-1.oraclecloud.com"
    key_id = "ocid1.key.oc1.iad.bfqdkzxjaaeuk.ksypiccljs5msyctjf57cxz5povyhna5y3g7abuw3jftikxn36dtv3ziahoq",
}
```

Include that in your scripts and you'll find a block like this in your state (note the plaintext block which is base64 encoded decrypted value:

```json
{
  "mode": "data",
  "type": "oci_kms_decrypted_data",
  "name": "test_decrypted_data",
  "provider": "provider[\"registry.terraform.io/hashicorp/oci\"]",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "associated_data": null,
        "ciphertext": "QQqzaYCH+0rZbhjJ9qOmyAxuu/2G3JRoMmXhzU8c/AOPk2BNuj5o85iSuQku",
        "crypto_endpoint": "https://aaquefbdkzxjk-crypto.kms.us-ashburn-1.oraclecloud.com",
        "id": "2021-02-26 13:08:32.716865 +0000 UTC",
        "key_id": "ocid1.key.oc1.iad.bfqdkzxjaaeuk.ksypiccljs5msyctjf57cxz5povyhna5y3g7abuw3jftikxn36dtv3ziahoq",
        "plaintext": "eWUF6OXzdDE=",
        "plaintext_checksum": "1646300224"
      }
    }
  ]
}
```

**Comment by dhoogfr** [comment]
I must say that the reason for not adding this is a bit strange.
After all, the secret (eg a DB password for a DBCS resource) is already in the state file.
What this feature would do is to give a more secure way in passing this password to Terraform and a easier way to maintain it.
Making the overall situation more secure, not less.

In my opinion: not having a way to read the decrypted value from vault in Terraform is a real missing piece of functionality. And it's forcing your users to use less secure and more cumbersome methods.

**Comment by jotruon** [comment]
Hi all, Terraform now support get secret content at https://registry.terraform.io/providers/hashicorp/oci/latest/docs/data-sources/secrets_secretbundle

**Comment by dhoogfr** [comment]
@jotruon I totally missed that data source
Sorry for that, and many thanks for the pointer

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
