### ISSUE TITLE
Discovery of oci_database_db_system includes invalid db_version value

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/oci v4.18.0
```

### Affected Resource(s)

* oci_database_db_system (via resource discovery)

### Terraform Configuration Files

After resource discovery, discovered `oci_database_db_system` contains the following
```hcl
resource oci_database_db_system export_MyDB1-202102101122 {

. . .

  data_storage_size_in_gb = "256"
  database_edition        = "ENTERPRISE_EDITION"
  db_home {

. . .

    db_version = "18.12.0.0.0"

. . .

  }
```

If I modify the output only enough to make this unique (i.e. `hostname`, add missing values like `admin_password`) then apply I get this error:

```
oci_database_db_system.export_MyNewDB-202102101122: Creating...

Error: 400-InvalidParameter 
Service: DatabaseDbSystem 
Error Message: The database version must be one of 11.2.0.4 or 11.2.0.4.200114 or 11.2.0.4.200414 or 11.2.0.4.200714 or 11.2.0.4.201020 or 12.1.0.2 or 12.1.0.2.200114 or 12.1.0.2.200414 or 12.1.0.2.200714 or 12.1.0.2.201020 or 12.2.0.1 or 12.2.0.1.200114 or 12.2.0.1.200414 or 12.2.0.1.200714 or 12.2.0.1.201020 or 18.0.0.0 or 18.10.0.0 or 18.11.0.0 or 18.12.0.0 or 18.9.0.0 or 19.0.0.0 or 19.6.0.0 or 19.7.0.0 or 19.8.0.0 or 19.9.0.0 or 21.0.0.0 or 21.1.0.0. 
OPC request ID: 58568bac419ee82fed98058c992479f0/23D3A16BA360/2AC32671DA821EB9C9F0D729F22E839891886F301F55CB76798B 
Suggestion: Please update the parameter(s) in the Terraform config as per error message The database version must be one of 11.2.0.4 or 11.2.0.4.200114 or 11.2.0.4.200414 or 11.2.0.4.200714 or 11.2.0.4.201020 or 12.1.0.2 or 12.1.0.2.200114 or 12.1.0.2.200414 or 12.1.0.2.200714 or 12.1.0.2.201020 or 12.2.0.1 or 12.2.0.1.200114 or 12.2.0.1.200414 or 12.2.0.1.200714 or 12.2.0.1.201020 or 18.0.0.0 or 18.10.0.0 or 18.11.0.0 or 18.12.0.0 or 18.9.0.0 or 19.0.0.0 or 19.6.0.0 or 19.7.0.0 or 19.8.0.0 or 19.9.0.0 or 21.0.0.0 or 21.1.0.0.
```

To correct I have to change this:
```
db_version = "18.12.0.0.0"
```
…to this…
```
db_version = "18.12.0.0"
```

### Expected Behavior
Discovered database system script should be valid (except for unavailable attributes like `admin_password`, etc.)

### Actual Behavior
Discovered database system script has invalid value for `db_version`

### Steps to Reproduce

1. Execute discovery using Terraform OCI provider. Optionally limit discovery to single OCID of an existing DB System
2. Modify created database system script to represent a distinct resource (i.e. minimal changes such as `hostname` and providing `admin_password` and other missing attributes)
3. `terraform apply`

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
