### ISSUE TITLE
Allow data provider oci_core_instances to return instance IP's

### ISSUE THREAD

**Issue by thegrumpydev** [oracle/terraform-provider-oci#1331]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When provisioning LB Backend's it requires the IP of the instance. Due to certain limitations I am forced to use the data provider to gather the instances that I would like to make LB Backends. When doing this the data provider [oci_core_instances](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/data-sources/core_instances) retrieves the instances that I want however, the IP addresses aren't populated. This then requires me to iterate over the list of instances and use data provider [oci_core_instance](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/data-sources/core_instance) just to get the IP address. 

The ask would be to either include the IP addresses in the `oci_core_instances` or to allow the backend to use ocid instead of IP. This is how GCP and AWS have also implemented it.

### New or Affected Resource(s)

Data:
"oci_core_instances"
"oci_core_instance"

### Potential Terraform Configuration

Currently have to do something like this:
```
data "oci_core_instances" "instances" {
  compartment_id = <compartment ocid>
}

locals {
  instances = toset([
    for instance in data.oci_core_instances.v1_instances[0].instances:
    instance.id
  ])
}

data "oci_core_instance" "instances" {
  for_each    = local.instances
  instance_id = each.value
}

resource "oci_load_balancer_backend" "backends" {
  for_each = data.oci_core_instance.instances

  load_balancer_id = <lb ocid>
  backendset_name  = "foo"
  ip_address       = each.value.private_ip
  port             = 8443
}

```
and would prefer something more like
```
data "oci_core_instances" "instances" {
  compartment_id = <compartment ocid>
}

resource "oci_load_balancer_backend" "backends" {
  count = length(data.oci_core_instances.instances)

  load_balancer_id = <lb ocid>
  backendset_name  = "foo"
  ip_address       = data.oci_core_instances.instances[count.index].private_ip
  port             = 8443
}
```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
