### ISSUE TITLE
Documentation Error: data-sources/core-private-ips

### ISSUE THREAD

**Issue by jstadt** [oracle/terraform-provider-oci#1338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

N/A

### Affected Resource(s)

"oci_core_private_ips" (data source)

One of the examples for the "oci_core_private_ips" data sources specifies:
```
# Filter on private IP address and Subnet OCID
data "oci_core_private_ips" "test_private_ips_by_ip_address" {
    #Optional
    ip_address = var.private_ip_ip_address
    subnet_id = oci_core_subnet.test_subnet.id
    vlan_id = oci_core_vlan.test_vlan.id
    vnic_id = oci_core_vnic_attachment.test_vnic_attachment.id
}
```

In this example, the VNIC Attachment ID is provided as the `vnic_id` to the data source, but this will cause a GET failure against the vnics endpoint because a vnicattachment ID is provided.

Instead, the relevant line of the example should read:
```
    vnic_id = oci_core_vnic_attachment.test_vnic_attachment.vnic_id
```

per the attributes reference of https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_vnic_attachment

**Comment by varmax2511** [comment]
thanks for reporting this, we will fix it

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
