### ISSUE TITLE
Adding additional oci_core_volume_group causes destroy/create not update

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/oci v4.21.0
```

### Affected Resource(s)
`oci_core_volume_group`

### Terraform Configuration Files

```hcl
resource "oci_core_volume_group" "the_volume_group" {
  availability_domain = var.volume_group_availability_domain
  compartment_id = var.compartment_id
  source_details {
    type = "volumeIds"
    volume_ids = [
       "ocid1.volume.oc1.phx.ocid1ocid1ocid1ocid1ocid1ocid1ocid1ocid1ocid1ocid1"
    ]
  }
}
```
Create above then update
```hcl
resource "oci_core_volume_group" "the_volume_group" {
  availability_domain = var.volume_group_availability_domain
  compartment_id = var.compartment_id
  source_details {
    type = "volumeIds"
    volume_ids = [
      "ocid1.volume.oc1.phx.ocid1ocid1ocid1ocid1ocid1ocid1ocid1ocid1ocid1ocid1",
      "ocid1.volume.oc1.phx.ocid2ocid2ocid2ocid2ocid2ocid2ocid2ocid2ocid2ocid2"
    ]
  }
}
```
Result is destroy/replace not update as is readily possible in OCI Console
```hcl
oci_core_volume_group.the_volume_group must be replaced

. . . 

      ~ volume_ids          = [
          - "ocid1.volume.oc1.phx.ocid1ocid1ocid1ocid1ocid1ocid1ocid1ocid1ocid1ocid1",
        ] -> (known after apply)
        # (3 unchanged attributes hidden)

      ~ source_details {
          ~ volume_ids = [ # forces replacement
              + "ocid1.volume.oc1.phx.ocid2ocid2ocid2ocid2ocid2ocid2ocid2ocid2ocid2ocid2",
                # (1 unchanged element hidden)
            ]
            # (1 unchanged attribute hidden)
        }

. . .
```
### Expected Behavior
I expect addition or removal of volumes from a volume group to trigger update not destroy/create. This is problematic because we are now relying on volume group backup policies and new volume group breaks consistency between backup source and initial volume group OCID.

### Actual Behavior
Adding a new volume to existing volume group triggers destroy/create of existing volume group whereas it should trigger only update

### Steps to Reproduce

1. `terraform apply` initial script containing single volume
2. Edit script to add a second volume keeping original volume in script
3. `terraform apply` and not the prompt to destroy/create not update

**Comment by varmax2511** [comment]
Hi @jeliker -- thanks for reporting this. In terraform provider, the parameter `volume_ids` is not updatable per https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_volume_group#argument-reference

We can look into enhancing the behavior to support updating this parameter

**Comment by jeliker** [comment]
Great! Thank you.

As I interpret the API docs, volumeIds should be updatable, correct? In other words, the immutable behavior we see now is in error? I ask to understand if this is considered an "enhancement" or "bug fix."

See API doc here I'm referencing. I interpret the inclusion of volumeIds in the UpdateVolumeGroup operation to mean volumeIds is an updatable attribute (i.e. that attribute wouldn't be listed if it were not updatable).

https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/VolumeGroup/UpdateVolumeGroup

**Comment by varmax2511** [comment]
Thanks for reporting this. We will treat it as a bug and update once fixed.

**Comment by jeliker** [comment]
This issue persists with [v4.56.0](https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v4.56.0)

@varmax2511 I think the issue is that API docs show `volume_ids` is updatable but in Terraform the only means of specifying `volume_ids` is through the `source_details` block which, as a whole, is not updatable. See here:

* [CreateVolumeGroupDetails](https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/CreateVolumeGroupDetails)
* [UpdateVolumeGroupDetails](https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/UpdateVolumeGroupDetails)

I would suggest adding optional parameter `volume_ids` similar to now `oci_core_instance` has both `hostname_label` and  `create_vnic_details.hostname_label`. However, seems that the "loose" `hostname_label` is a deprecated attribute from before the resource was refactored.

Can `source_details` be treated as `source_details` in entirely for create then map `source_details.volume_ids` to the attribute `volume_ids` for update operations? As I say, the API shows `volume_ids` is a valid attribute for update though not for create.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
