### ISSUE TITLE
Add private_ip argument to oci_core_public_ip

### ISSUE THREAD

**Issue by fcecagno** [oracle/terraform-provider-oci#1350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, when it's desired to use a reserved public IP, the following steps are required:

1. create the instance using the resource `oci_core_instance`
2. fetch the instance private IP using the data source `oci_core_private_ips`
3. create the public IP using the resource `oci_core_public_ip`

Step 2 is only required because the `oci_core_instance` has the private IP as an attribute, but `oci_core_public_ip` requires the private IP's ID instead, so step 2 translates IP to OCID. If `oci_core_public_ip` could receive the parameter `private_ip`, it would simplify the configuration and make it more straightforward.

### New or Affected Resource(s)

oci_core_public_ip

### Potential Terraform Configuration

```hcl
resource "oci_core_public_ip" "test_public_ip" {
    #Required
    compartment_id = var.compartment_id
    lifetime = var.public_ip_lifetime

    #Optional
    defined_tags = {"Operations.CostCenter"= "42"}
    display_name = var.public_ip_display_name
    freeform_tags = {"Department"= "Finance"}
    #Set private_ip_id or private_ip to assign the public_ip to a private IP
    private_ip_id = oci_core_private_ip.test_private_ip.id
    private_ip = oci_core_instance.test_instance.private_ip
    public_ip_pool_id = oci_core_public_ip_pool.test_public_ip_pool.id
}
```

**Comment by rashik-bhasin** [comment]
Hi,
We have asked the service team to address this enhancement request.

Thanks!

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
