### ISSUE TITLE
Imported detached oci_core_boot_volume cannot be imported because it does not contain source_details (which is required)

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1352]
If I must relaunch a Compute instance and preserve the bootVolume, I can terminate the Compute instance and preserve the bootVolume. However, following this I cannot import the bootVolume to be a Terraform-managed resource.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.22.0
```

### Affected Resource(s)
* oci_core_boot_volume

### Expected Behavior
Resource bootVolume should be importable even when launched from Compute whereby sourceDetails are null.

### Actual Behavior
Detached bootVolume (as launched from Compute instance) cannot be imported because it does not contain sourceDetails block yet sourceDetails is a required attribute for `oci_core_boot_volume` resource type.

### Steps to Reproduce
1. Create bootVolume by launching instance
2. Create Terraform script to match launched bootVolume. For example:

```hcl
resource "oci_core_boot_volume" "the_boot_volume" {
    #Required
    availability_domain = var.boot_volume_availability_domain
    compartment_id = var.compartment_id
    source_details {
        #Required
        id = "Not sure what to provide; Boot Volume was launched from Image but type does not support 'image'"
        type = "Not sure what to provide"
    }
    display_name = var.boot_volume_display_name
}
```

3. `terraform import oci_core_boot_volume.the_boot_volume OCID_OF_EXISTING_BOOT_VOLUME`
4. Note error about missing or bad `source_details`

Output from `oci bv boot-volume get --boot-volume-id OCI_OF_EXISTIN_BOOT_VOLUME` shows this:

```
. . .

  "source_details": null,

. . .
```

1. `terraform apply`

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
