### ISSUE TITLE
oci provider -generate_state doesn't generate terraform.tfstate

### ISSUE THREAD

**Issue by kashijr** [oracle/terraform-provider-oci#1360]
I am trying to do resource discovery of object storage bucket in one compartment using following command:

terraform-provider-oci_v4.23.0_x4.exe -command=export -compartment_id=<copartment_ocid> -services=object_storage -output_path=<path> -generate_state

The output of above command is as below:

2021/04/29 12:20:20 [INFO] terraform-provider-oci 4.23.0
INFO 2021/04/29 12:20:22.248688 [INFO] root compartment found ocid1.........................................................................................
INFO 2021/04/29 12:20:22.248688 [INFO] validating Terraform CLI
INFO 2021/04/29 12:20:22.710092 [INFO] resource discovery retry timeout duration set to 15s
INFO 2021/04/29 12:20:22.710092 [INFO] Running export command
INFO 2021/04/29 12:20:22.711095 [INFO] parallelism: 1
INFO 2021/04/29 12:20:22.711095 [INFO] resource discovery: visiting oci_identity_compartment.export
INFO 2021/04/29 12:20:22.711095 [INFO] discovering resources with data source 'oci_objectstorage_namespace'
INFO 2021/04/29 12:20:24.103281 [INFO] resource discovery: visiting oci_objectstorage_namespace.export_namespace
INFO 2021/04/29 12:20:24.104285 [INFO] discovering resources with data source 'oci_objectstorage_bucket_summaries'
INFO 2021/04/29 12:20:24.105284 [INFO] adding datasource query attribute 'namespace' from parent attribute 'namespace'
INFO 2021/04/29 12:20:25.024091 [INFO] resource discovery: visiting oci_objectstorage_bucket.export_script-state-bucket
INFO 2021/04/29 12:20:25.024091 [INFO] discovering resources with data source 'oci_objectstorage_objects'
INFO 2021/04/29 12:20:25.026094 [INFO] adding datasource query attribute 'bucket' from parent attribute 'name'
INFO 2021/04/29 12:20:25.026094 [INFO] adding datasource query attribute 'namespace' from parent attribute 'namespace'
INFO 2021/04/29 12:20:25.359688 [INFO] discovering resources with data source 'oci_objectstorage_object_lifecycle_policy'
INFO 2021/04/29 12:20:25.360691 [INFO] adding datasource query attribute 'namespace' from parent attribute 'namespace'
INFO 2021/04/29 12:20:25.361690 [INFO] adding datasource query attribute 'bucket' from parent attribute 'name'
2021/04/29 12:20:25 ERROR IN GET: Service error:LifecyclePolicyNotFound. The bucket 'script-state-bucket' does not define a lifecycle policy.. http status code: 404. Opc request id: sjc-1:wTSgNytTthj1AVDSezd9_hCqU_ZuR96ieKP-B3NIrQUc5N9-6ovB_JRd2oJOaeb-
2021/04/29 12:20:25 [DEBUG] Object does not exist, voiding resource and nullifying error
INFO 2021/04/29 12:20:25.661746 [INFO] discovering resources with data source 'oci_objectstorage_preauthrequests'
INFO 2021/04/29 12:20:25.661746 [INFO] adding datasource query attribute 'namespace' from parent attribute 'namespace'
INFO 2021/04/29 12:20:25.662750 [INFO] adding datasource query attribute 'bucket' from parent attribute 'name'
INFO 2021/04/29 12:20:25.976987 [INFO] discovering resources with data source 'oci_objectstorage_replication_policies'
INFO 2021/04/29 12:20:25.976987 [INFO] adding datasource query attribute 'namespace' from parent attribute 'namespace'
INFO 2021/04/29 12:20:25.978986 [INFO] adding datasource query attribute 'bucket' from parent attribute 'name'
INFO 2021/04/29 12:20:26.300511 [INFO] Discovery complete for step root object_storage
INFO 2021/04/29 12:20:26.511565 === COMPLETED ===
INFO 2021/04/29 12:20:26.511565 Usage: terraform [global options] init [options]

  Initialize a new or existing Terraform working directory by creating
  initial files, loading any remote state, downloading modules, etc.

  This is the first command that should be run for any new or existing
  Terraform configuration per machine. This sets up all the local data
  necessary to run Terraform that is typically not committed to version
  control.

  This command is always safe to run multiple times. Though subsequent runs
  may give errors, this command will never delete your configuration or
  state. Even so, if you have important information, please back it up prior
  to running this command, just in case.

Options:

  -backend=true        Configure the backend for this configuration.

  -backend-config=path This can be either a path to an HCL file with key/value
                       assignments (same format as terraform.tfvars) or a
                       'key=value' format. This is merged with what is in the
                       configuration file. This can be specified multiple
                       times. The backend type must be in the configuration
                       itself.

  -force-copy          Suppress prompts about copying state data. This is
                       equivalent to providing a "yes" to all confirmation
                       prompts.

  -from-module=SOURCE  Copy the contents of the given module into the target
                       directory before initialization.

  -get=true            Download any modules for this configuration.

  -input=true          Ask for input if necessary. If false, will error if
                       input was required.

  -no-color            If specified, output won't contain any color.

  -plugin-dir          Directory containing plugin binaries. This overrides all
                       default search paths for plugins, and prevents the
                       automatic installation of plugins. This flag can be used
                       multiple times.

  -reconfigure         Reconfigure the backend, ignoring any saved
                       configuration.

  -upgrade=false       If installing modules (-get) or plugins, ignore
                       previously-downloaded objects and install the
                       latest version allowed within configured constraints.

  -lockfile=MODE       Set a dependency lockfile mode.
                       Currently only "readonly" is valid.

The above command generates only one file called object_storage.tf and the contents of object_storage.tf are as follows:

## This is tmp config to run import for resources

data oci_objectstorage_namespace export_namespace {}

resource oci_objectstorage_bucket export_script-state-bucket {}

There is no terraform.tfstate file generated. 

I would like to know if there is any mistake I am making or is there a bug in terraform-provider-oci_v4.23.0_x4.exe ?

**Comment by varmax2511** [comment]
Hi @kashijr -- Please try passing the `output_path` to store the state file.
reference: https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/resource_discovery

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
