### ISSUE TITLE
oci_load_balancer_listener  has wrong resource type mentioned in it

### ISSUE THREAD

**Issue by vickyvikas7988** [oracle/terraform-provider-oci#1374]
Hi team,

While creating oci_load_balancer_listener I see a option to select routing_policy_name but i don;t find an option for oci_routing_policy in OCI resource type.

```
resource "oci_load_balancer_listener" "test_listener" {
    routing_policy_name = oci_routing_policy.test_routing_policy.name

```

Can you please check it?

**Comment by Maxrovr** [comment]
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/load_balancer_load_balancer_routing_policy. Thank you, I will update the example to use the latest `oci_load_balancer_load_balancer_routing_policy` resource name.
