### ISSUE TITLE
A tiny bug of example code of autonomous_database.tf

### ISSUE THREAD

**Issue by leonyk** [oracle/terraform-provider-oci#1377]
Hi Team, 
These examples of terraform codes for OCI are really helpful. I just found a tiny issue as below.

The "**high**" in line of 133 of [autonomous_database.tf](https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/database/adb/autonomous_database.tf) should be all in capital like "**HIGH**". Otherwise, it will be "**unavailable**" always!

I have submitted a [pull request](https://github.com/terraform-providers/terraform-provider-oci/pull/1378) to fix it.

**Comment by Maxrovr** [comment]
@leonyk You are right in saying that `high` will not work. But, why do you think it would work with `HIGH` ?

**Comment by Maxrovr** [comment]
```
output "autonomous_database_high_connection_string" {
  value = lookup(oci_database_autonomous_database.autonomous_database.connection_strings[0].all_connection_strings, "${oci_database_autonomous_database.autonomous_database.db_name}_high", "unavailable")
}
```

or 

```
output "autonomous_database_high_connection_string" {
  value = lookup(oci_database_autonomous_database.autonomous_database.connection_strings[0], "high", "unavailable")
}
```

Either of these work depending on what you want.

**Comment by leonyk** [comment]
As I have verified all the options of the connection strings. And "HIGH" not "high" is in the list. 

![image](https://user-images.githubusercontent.com/39024218/122896589-cab17e00-d37b-11eb-9171-7da9f62630bd.png)

**Comment by Maxrovr** [comment]
Can you share the terraform config file you are using?

**Comment by Maxrovr** [comment]
`"HIGH"` is a key that is specific to your usecase. Not every `connection_strings[0].all_connection_strings` will have a `"HIGH"` key. But according to the [docs](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/database_autonomous_database#connection_strings) `"high"` will always be a key in connection_strings[0]

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
