### ISSUE TITLE
Creating "nested" compartment resources in same run fails with 404-NotAuthorizedOrNotFound

### ISSUE THREAD

**Issue by ped998** [oracle/terraform-provider-oci#1380]
Terraform v0.15.4

tf file contents:
resource "oci_identity_compartment" "digital_compartment" {
  compartment_id = var.tenancy_ocid
  name           = "${var.service_label}-Digital"
  description    = "Compartment for Digital Technology"
  enable_delete  = true
}

resource "oci_identity_compartment" "digital_platform1_subcompartment" {
  compartment_id = oci_identity_compartment.digital_compartment.id
  name           = "${var.service_label}-Platform1"
  description    = "Digital subcompartment for Platform1"
  enable_delete  = true
}

resource "oci_identity_compartment" "digital_platform2_subcompartment" {
  compartment_id = oci_identity_compartment.digital_compartment.id
  name           = "${var.service_label}-Platform2"
  description    = "Digital subcompartment for Platform2"
  enable_delete  = true
}

Results:
oci_identity_compartment.digital_compartment: Creating...
oci_identity_compartment.digital_compartment: Creation complete after 2s [id=ocid1.compartment.oc1..aaaaaaaaigkjtjbjdyn4qrrybqi4435s6u353bi45drwytinfwnmpq36scha]
oci_identity_compartment.digital_platform2_subcompartment: Creating...
oci_identity_compartment.digital_platform1_subcompartment: Creating...

│ Error: 404-NotAuthorizedOrNotFound 
│ Provider version: 4.28.0, released on 2021-05-26.  
│ Service: Identity Compartment 
│ Error Message: Authorization failed or requested resource not found 
│ OPC request ID: f4547e5eee56a2bdd61f2d4e4a5ff979/97F4C496FC126D5C02689B9D582D9A33/2FABA0F28B1E2AE538852931B566E32F 
│ Suggestion: Either the resource has been deleted or service Identity Compartment need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm
│ 
│ 
│   with oci_identity_compartment.digital_platform1_subcompartment,
│   on sw_digital_compartments.tf line 8, in resource "oci_identity_compartment" "digital_platform1_subcompartment":
│    8: resource "oci_identity_compartment" "digital_platform1_subcompartment" {
│ 
╵
╷
│ Error: 404-NotAuthorizedOrNotFound 
│ Provider version: 4.28.0, released on 2021-05-26.  
│ Service: Identity Compartment 
│ Error Message: Authorization failed or requested resource not found 
│ OPC request ID: 819ae5daf067aa739c367fe1b5c2d478/11247BAE2FDBE71E64647FBB31250C72/725021A1B08A3AA70C6DE3EC07E6C2F7 
│ Suggestion: Either the resource has been deleted or service Identity Compartment need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm
│ 
│ 
│   with oci_identity_compartment.digital_platform2_subcompartment,
│   on sw_digital_compartments.tf line 15, in resource "oci_identity_compartment" "digital_platform2_subcompartment":
│   15: resource "oci_identity_compartment" "digital_platform2_subcompartment" {
│ 

This appears to be similar to https://github.com/terraform-providers/terraform-provider-oci/issues/1373 and https://github.com/terraform-providers/terraform-provider-oci/issues/1371

**Comment by ped998** [comment]
Re-executing a little later creates the nested compartments without any issue (with the parent compartment already existing).   I am testing with adding a "sleep 60" between parent and child compartment creation to allow my project to proceed, however, it is only a workaround.

**Comment by varmax2511** [comment]
Hi @ped998 -- Identity resources are eventually consistent in nature, meaning it takes a delay for them to propagate and be fully available across all regions upon creation. 
For now adding a sleep / delay would be the path forward.

**Comment by sgaetjen** [comment]
If the path forward is to use sleep, can we you please document this, the why and the how, e.g. add a section here:
https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformtroubleshooting.htm
and here https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/identity_compartment ?

**Comment by ped998** [comment]
I have seen this behavior with other resource combinations as well.   Other than reactively adding sleeps between them, is there a way for the provider to not proceed until the parent resource is "fully propagated"?

**Comment by nicbrown** [comment]
This has been opened a while. Adding a sleep resource shouldn't really be unused in place of proper hierarchy management.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
