### ISSUE TITLE
Outputs for oci_database_db_system node(s) IP addresses

### ISSUE THREAD

**Issue by evansalda** [oracle/terraform-provider-oci#1382]
Hi everyone,

I am currently working on creating Exadatas and VMDBs with terraform and I am outputing several information for further use in my automation chain. The problem is, the following information are currently not available as outputs for the oci_database_db_system resource type : 

- The private IP address of each node
- The floating IP address of each node
- The public IP address of each node
- The name of each node
- The scan IP address of the DB system

The only interesting outputs I found were scan_ip_ids and vip_ids but it actually provides the OCID and not the IPs directly, and they are actually empty when creating a single node DB System.

I think it would be very helpful to provide users with such outputs !

**Comment by dhoogfr** [comment]
Hi @twandja 

I'm currently using the following to get information fir a single node DBCS guest.
Maybe it can help you.

But an easier, more direct method would certainly be welcome. 

```
# get the list of database nodes in the gdb_db1 database system
data "oci_database_db_nodes" "gdb_db1_nodes" {
  compartment_id = oci_database_db_system.gdb_db1.compartment_id
  db_system_id   = oci_database_db_system.gdb_db1.id
}

# get the vnic of the first node in the gdb_db1 database system
data "oci_core_private_ips" "gdb_db1_node_ip" {
  vnic_id = data.oci_database_db_nodes.gdb_db1_nodes.db_nodes[0]["vnic_id"]
}

# get the list of database homes in the gdb_db1 database system
data "oci_database_db_homes" "gdb_db1_node_db_home" {
  compartment_id = oci_database_db_system.gdb_db1.compartment_id
  db_system_id   = oci_database_db_system.gdb_db1.id
}

data "oci_database_databases" "oci_databases_gdb_db1" {
  compartment_id = oci_database_db_system.gdb_db1.compartment_id
  system_id = oci_database_db_system.gdb_db1.id
  db_home_id = data.oci_database_db_homes.gdb_db1_node_db_home.db_homes[0]["id"]
  db_name = var.gdb_cdb_name
}

output "gdb_db1_connection_strings" {
  description = "The different connection strings for the gdb_db1 database"
  value = data.oci_database_databases.oci_databases_gdb_db1.databases.0.connection_strings
}

output "gdb_db1_private_ip" {
  value = data.oci_core_private_ips.gdb_db1_node_ip.private_ips[0]["ip_address"]
}
```

**Comment by AshishTDBA** [comment]
I am trying to get the output for below section of VM_DB but not succeeding 

 db_home {
    database {
      admin_password = var.db_admin_password
      db_name        = "DevOPSDB"
      character_set  = var.character_set
      ncharacter_set = var.n_character_set
      db_workload    = var.db_workload
      pdb_name       = var.pdb_name
 

**********
For password I am using below ,if I do not use sensitive=true ,  the plan errors 

output "db_password" {
        value = oci_database_db_system.test_db_system.db_home[0]
        sensitive = true
        }

*********** 
To pick additional values from the same block I tried using  with and without index 

Error: Invalid operation
│
│   on output.tf line 6, in output "dbname":
│    6:         value = oci_database_db_system.test_db_system.db_home.db_name
│
│ Block type "db_home" is represented by a list of objects, so it must be indexed using a numeric key, like .db_home[0].
╵


│ Error: Invalid index
│
│   on output.tf line 7, in output "dbname":
│    7:         value = oci_database_db_system.test_db_system.db_home[1]
│     ├────────────────
│     │ oci_database_db_system.test_db_system.db_home is list of object with 1 element
│
│ The given key does not identify an element in this collection value.
╵


 Error: Invalid index
│
│   on output.tf line 7, in output "dbname":
│    7:         value = oci_database_db_system.test_db_system.db_home[2]
│     ├────────────────
│     │ oci_database_db_system.test_db_system.db_home is list of object with 1 element



Can we get the right syntax to output the values DB created , node_id , password , etc

**Comment by AshishTDBA** [comment]
Hi @twandja ,

Were you able to get a solution for this .

Regards,
Ashish

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
