### ISSUE TITLE
database_db_system db_home.0.database.0.db_unique_name cannot be set?

### ISSUE THREAD

**Issue by gabetocci** [oracle/terraform-provider-oci#1383]
I'm not finding any documentation on this, api, or otherwise. 

### Error: "db_home.0.database.0.db_unique_name": this field cannot be set. 

Am I correct that db_unique_name is not a valid attribute of database_db_system? 
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/database_db_system

 We possibly could have created a new database, set the unique name,  and attached it, to the db_system, but that seems like we would be jumping through hoops.  
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/database_database#db_unique_name

When I create a db_system via the console, I can set the db_unique_name suffix.

**Comment by gabetocci** [comment]
Looks like its an option in the api, no?  
https://docs.oracle.com/en-us/iaas/tools/python/2.38.4/api/database/models/oci.database.models.CreateDatabaseDetails.html#oci.database.models.CreateDatabaseDetails.db_unique_name

**Comment by bjamb** [comment]
Did you get a solution on this? I get the same error while using db_unique_name  in the tf script 

Error: "db_home.0.database.0.db_unique_name": this field cannot be set

**Comment by gabetocci** [comment]
I did not figure out a solution. I created it via the console :-(

**Comment by bjamb** [comment]
I think it is not under resource database_db_system but database_database. Probably this is applicable for provisioning a database in ExaCS. VM-DBSystem may not have that in API is what I think,

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
