### ISSUE TITLE
Raise condition when creating a public nlb with oci_network_load_balancer_network_load_balancer & oci_core_public_ip

### ISSUE THREAD

**Issue by salindaliyanage** [oracle/terraform-provider-oci#1385]
### Problem

When creating a public network load balancer with a reserved ip using oci_network_load_balancer_network_load_balancer and oci_core_public_ip resources, raise condition occurs in argument in oci_core_public_ip resource.

### Terraform Version and Provider Version

Terraform v0.12.20
terraform-provider oci_v4.23.0_x4

### Affected Resource(s)

oci_network_load_balancer_network_load_balancer
oci_core_public_ip

### Terraform Configuration Files

```hcl
variable "nlb_private_ip_id" {
  default = ""
}

resource "oci_core_public_ip" "nlb" {
  compartment_id = var.compartment_id
  lifetime       = "RESERVED"
  display_name   = var.public_ip_name
}

resource "oci_network_load_balancer_network_load_balancer" "public_nlb" {

  compartment_id                 = var.compartment_id
  display_name                   = var.public_nlb_name
  subnet_id                      = oci_core_subnet.subnet-public_nlb.id
  is_preserve_source_destination = false
  is_private                     = false
  network_security_group_ids     = [oci_core_network_security_group.public_nlb_nsg.id]
  reserved_ips {
    id = oci_core_public_ip.nlb.id
  }
}
```

When terraform is used to create a public network load balancer having a reserved public ip, we need to use "oci_core_public_ip" resource to create the reserved public IP, and "oci_network_load_balancer_network_load_balancer" resource to create the network load balancer, providing ID of public IP in "reserved_ips" argument. A public network load balancer created in a public subnet consumes one private IP address from the host subnet. When terraform create the network load balancer, this private IP is picked and assigned to a VNIC and and updates in "private_ip_id" argument in "oci_core_public_ip" resource. When next time terraform apply is performed, it removes the "private_ip_id" from "oci_core_public_ip" resource as "oci_core_public_ip" resource is not aware of this private IP. 

```hcl
  # oci_core_public_ip.nlb1 will be updated in-place
  ~ resource "oci_core_public_ip" "nlb" {
        assigned_entity_id   = "ocid1.privateip.oc1.iad.xxxxx"
        assigned_entity_type = "PRIVATE_IP"
        compartment_id       = "ocid1.compartment.oc1..xxxxx"
        defined_tags         = {}
        display_name         = "XXXX"
        freeform_tags        = {}
        id                   = "ocid1.publicip.oc1.iad.xxxxxx"
        ip_address           = "xxx.xxx.xxx.xxx"
        lifetime             = "RESERVED"
      - private_ip_id        = "ocid1.privateip.oc1.iad.xxxxx" -> null
        scope                = "REGION"
        state                = "ASSIGNED"
        time_created         = "yyyy-mm-dd hh:mm:ss.xyz +0000 UTC"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```
This can be workaround by manually identifying and setting the variable nlb_private_ip_id using following code before next terraform apply, but it is good to improve the code to avoid this raise condition and manual step.

```hcl
resource "oci_core_public_ip" "nlb" {
  compartment_id = var.compartment_id
  lifetime       = "RESERVED"
  display_name   = var.public_ip_name
  private_ip_id = var.nlb_private_ip_id == "" ? null : var.nlb_private_ip_id
}
```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
