### ISSUE TITLE
oci_bastion_bastion replacement forced every time because bastion_type

### ISSUE THREAD

**Issue by garthk** [oracle/terraform-provider-oci#1396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

I'm using Terraform 0.14.11 and the provider `hashicorp/oci v4.31` inside the Oracle console.

### Affected Resource(s)

`oci_bastion_bastion`

### Terraform Configuration Files

This problem occurs whether I give the `bastion_type` in lower case or upper case:

```hcl
resource "oci_bastion_bastion" "this" {
  bastion_type = "standard"
```
or
```hcl
resource "oci_bastion_bastion" "this" {
  bastion_type = "STANDARD"
```

### Expected Behavior

I should be able to create a standard bastion, and have it not forcibly re-created on my next apply.
 
### Actual Behavior

My state shows `attributes.bastion_type` of `"STANDARD"` regardless of the capitalisation of my Terraform. On every plan, I get forced replacement:

```plain
  # oci_bastion_bastion.this must be replaced
-/+ resource "oci_bastion_bastion" "this" {
      ~ bastion_type                  = "STANDARD"" -> ""standard" # forces replacement
```

### Steps to Reproduce

`terraform apply`

### References

* [`oci_ bastion_bastion`](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/bastion_bastion)

**Comment by garthk** [comment]
Workaround: ignore changes to `bastion_type` as shown below:
```hcl
resource "oci_bastion_bastion" "this" {
  bastion_type = "standard"
  # ...
  lifecycle { ignore_changes = [bastion_type] }
}
```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
