### ISSUE TITLE
oci_identity_identity_provider does not create Oracle Cloud Service in IDCS

### ISSUE THREAD

**Issue by sgaetjen** [oracle/terraform-provider-oci#1404]
I am able to configure an Identity Provider in a single IDCS and then configurated IAM Federation to this via the OCI Console using IDCS url and Client ID and Client Secret from COMPUTEBAREMETAL. I am trying to automate this configuration, Terraform or OCI Command Line. The Terraform approach configures the Federation but does not work. In comparing the configuration of the Federation in the OCI Console the federation with the manual approach shows the following: IDCS service identifier: XXXXXX , while after the Terraform approach does not show this. It appears the OCI-V2-<tenancy-name> Oracle Cloud Service is not being created in IDCS in the Terraform path as it is with the OCI Console/manual path. The IDCS service identifier would have the ID of this Oracle Cloud Service

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/oci v4.33.0

### Affected Resource(s)

oci_identity_identity_provider

### Terraform Configuration Files

variable "tenancy_ocid" {}

variable "identity_provider_metadata_file" {
  default = "metadata.xml"
}

variable "id_url" {
  default = "https://idcs-XXXXXXXXXXXXXXXXXXXXXXXXXX.identity.oraclecloud.com"
}
variable "oci_wldev_group" {
  default = "XXXX-OCI-GROUP"
}

data "oci_identity_groups" "all_groups" {
    compartment_id = var.tenancy_ocid
}

locals {
  wldev_group_id = data.oci_identity_groups.all_groups.groups[index(data.oci_identity_groups.all_groups.groups.*.name,var.oci_wldev_group)].id
}

resource "oci_identity_identity_provider" "identity_provider" {
  name           = "EnterpriseIDP"
  description    = "EnterpriseIDP"
  compartment_id = var.tenancy_ocid
  metadata       = file(var.identity_provider_metadata_file)
  metadata_url   = var.id_url
  product_type   = "IDCS"
  protocol       = "SAML2"
}

resource "oci_identity_idp_group_mapping" "idp_group_mapping" {
    group_id = local.wldev_group_id
    identity_provider_id = oci_identity_identity_provider.identity_provider.id
    idp_group_name = "XXXX_IDCS"
}
### Expected Behavior

The Oracle Cloud Service in IDCS OCI-V2-<tenancy_name> would be created. 

### Actual Behavior
terraform apply completes, IAM federation resources is created but "IDCS service identifier:" is null (due to lack of 

### Steps to Reproduce
Download IDCS provider metadata XML and save to metadata.xml 
terraform plan
terraform apply 

### Important Factoids

Works in the manual path in OCI Console but have to use Client ID and Client Secret which Terraform provider does not prompt for or support

### References

https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/federatingIDCS.htm#top

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
