### ISSUE TITLE
Cannot delete oci_sch_service_connector logRule tasks once defined

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.34.0
```

### Affected Resource(s)
* oci_sch_service_connector

### Terraform Configuration Files

```hcl
resource "oci_sch_service_connector" "the_connector" {
  compartment_id = var.compartment_id
  display_name = var.display_name
  source {
    kind = "logging""
    log_sources {
      compartment_id = var.compartment_id
      log_group_id = oci_logging_log_group.test_log_group.id
    }
    stream_id = oci_streaming_stream.test_stream.id
  }
  target {
    kind = "streaming"
    stream_id = var.stream_id
  }
  tasks {
    kind = "logRule"
    condition = "data.action != 'ACCEPT'"
  }
}
```

create resource above then attempt to remove the condition:

```hcl
resource "oci_sch_service_connector" "the_connector" {
  compartment_id = var.compartment_id
  display_name = var.display_name
  source {
    kind = "logging""
    log_sources {
      compartment_id = var.compartment_id
      log_group_id = oci_logging_log_group.test_log_group.id
    }
    stream_id = oci_streaming_stream.test_stream.id
  }
  target {
    kind = "streaming"
    stream_id = var.stream_id
  }
}
```

…after apply to above, `condition` is still present. Try this instead:

```hcl
resource "oci_sch_service_connector" "the_connector" {
  compartment_id = var.compartment_id
  display_name = var.display_name
  source {
    kind = "logging""
    log_sources {
      compartment_id = var.compartment_id
      log_group_id = oci_logging_log_group.test_log_group.id
    }
    stream_id = oci_streaming_stream.test_stream.id
  }
  target {
    kind = "streaming"
    stream_id = var.stream_id
  }
  tasks {
    kind = "logRule"
    condition = ""
  }
}
```

…and still the condition is present (assuming `condition = ""` is same as `condition = null` so is unchanged). Finally made it work this way (kludgy):

```hcl
resource "oci_sch_service_connector" "the_connector" {
  compartment_id = var.compartment_id
  display_name = var.display_name
  source {
    kind = "logging""
    log_sources {
      compartment_id = var.compartment_id
      log_group_id = oci_logging_log_group.test_log_group.id
    }
    stream_id = oci_streaming_stream.test_stream.id
  }
  target {
    kind = "streaming"
    stream_id = var.stream_id
  }
  tasks {
    kind = "logRule"
    condition = "source='*'"
  }
}
```

While the above change doesn't _remove_ the filter, it does at least prevent logs from being filtered.

### Expected Behavior
* I expect to have means to remove `logRule` tasks once they have been defined in a `oci_sch_service_connector` resource

### Actual Behavior
* Once defined, I cannot find the means to remove a `logRule` from the `tasks` block in a `oci_sch_service_connector` resource

### Steps to Reproduce

1. Create `oci_sch_service_connector` resource contains a `tasks` block of `kind = "logRule"` with any valid `condition`
2. Attempt to remove the `condition` via updates to the Terraform script so that logs are no longer filtered

### Important Factoids
* From the OCI Console, you can remove the Filter by blanking out the Property, Operator, and Value fields on the (notably, optional) "Log Filter Task" when editing a Service Connector

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
