### ISSUE TITLE
oci_core_instance -> create_vnic_details -> nsg_ids populated outside of Terraform

### ISSUE THREAD

**Issue by andycoates** [oracle/terraform-provider-oci#1421]
```
Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.36.0
```
When building an instance we don't specify `nsg_ids` under `create_vnic_details`, but once the instance is built, the next run of Terraform detects it "changed outside of Terraform" showing `nsg_ids` as the change with an empty list:
```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.xxx.oci_core_instance.instance[0] has been changed
  ~ resource "oci_core_instance" "instance" {
        id                                  = "xxxxxxxxxxxxxxxxx"
        # (20 unchanged attributes hidden)



      ~ create_vnic_details {
          + nsg_ids                   = []
            # (9 unchanged attributes hidden)
        }




        # (6 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.
```
Even if I try and pass `nsg_ids` with an empty list on instance creation it just doesn't even show in the plan and the above still happens.

At this point further runs don't show any "outside" changes, but the fact it initially shows an "outside change" that either can't be specified for its intended state or that it thinks its an "outside change" feels wrong.

**Expected Behavior**

After instance creation it should not detect any changes (including "outside changes").

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
