### ISSUE TITLE
Unable to set launch_options for oci_core_image

### ISSUE THREAD

**Issue by thomasdstewart** [oracle/terraform-provider-oci#1423]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Using OCI Resource Manager (as of today shows): Provider version: 4.37.0, released on 2021-07-28. Terraform set to: 1.0.x

### Affected Resource(s)

oci_core_image

### Terraform Configuration Files

```hcl
resource "oci_core_image" "debian_image_arm" {
    compartment_id = var.compartment_id
    launch_mode = "CUSTOM"

    image_source_details {
        source_type = "objectStorageTuple"
        bucket_name = "images"
        namespace_name = var.namespace_name
        object_name = var.image_name
        source_image_type = "QCOW2"
    }
}
```

```hcl
resource "oci_core_image" "debian_image_arm" {
    compartment_id = var.compartment_id
    launch_mode = "CUSTOM"
    launch_options {
        network_type = "PARAVIRTUALIZED"
    }

    image_source_details {
        source_type = "objectStorageTuple"
        bucket_name = "images"
        namespace_name = var.namespace_name
        object_name = var.image_name
        source_image_type = "QCOW2"
    }
}
```

### Expected Behavior

I expect to be able to set launch_mode to "CUSTOM" as per https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_image#CUSTOM

### Actual Behavior

When setting launch_mode to "CUSTOM" as per the first config snippet above I get this error:
```
Error: 400-MissingParameter
Provider version: 4.37.0, released on 2021-07-28.
Service: Core Image
Error Message: Missing launchOptions: launchOptions must be provided when using CUSTOM launchMode
```

However when setting the (undocumented argument but documented attribute) launch_options as per the second config snippet above I get this error:

```
Error: "launch_options": this field cannot be set
```

### Steps to Reproduce

Trying to plan or apply a Terraform templates that try to use the custom launch mode.

### Why

As per https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_image#launch_mode when setting launch_mode to PARAVIRTUALIZED the firmware is set to BIOS and network_type set to virtio. When set to NATIVE firmware is set to UEFI_64 but network_type is set to VFIO. However https://cloud.debian.org/images/cloud/buster/20210721-710/debian-10-generic-arm64-20210721-710.qcow2 requires firmware as UEFI_64 and network_type as virtio.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
