### ISSUE TITLE
`objectstorage_preauthrequest` example includes deprecated attribute `object` - and that deprecation is not listed in the CHANGELOG

### ISSUE THREAD

**Issue by ghost** [oracle/terraform-provider-oci#1431]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform version does not matter.
OCI provider version: change introduced in `4.34.0` (commit `b73cc0479243cc4bc38720b69915f13c487732c1`)

### Affected Resource(s)

`oci_objectstorage_preauthrequest`

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

(a) the example for `oci_objectstorage_preauthrequest` should work without warnings.
(b) no deprecation warning without a notice in the CHANGELOG file.

### Actual Behavior

```
Warning: oci_objectstorage_preauthrequest.provisioning_ansible_playbooks_par_iad: "object": [DEPRECATED] The 'object' field has been deprecated. Please use 'object_name' instead.
```

### Steps to Reproduce

Create an `oci_objectstorage_preauthrequest` object following the example in https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/objectstorage_preauthrequest

Run `terraform plan`.

### Important Factoids

N/A

### References

N/A

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
