### ISSUE TITLE
Data Safe CLOUDDB target database fails to register then registers if I apply a second time

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1433]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.39.0
```

### Affected Resource(s)
* oci_data_safe_target_database

### Terraform Configuration Files

```hcl
resource "oci_data_safe_target_database" "the_target" {
    #Required
    compartment_id = var.compartment_id
    database_details {
        #Required
        database_type = "DATABASE_CLOUD_SERVICE"
        infrastructure_type = "ORACLE_CLOUD"

        #Optional
        db_system_id = var.db_system_id
        service_name = var.service_name
    }

    #Optional
    connection_option {
        #Required
        connection_type = "PRIVATE_ENDPOINT"

        #Optional
        datasafe_private_endpoint_id = var.private_endpoint_id
    }
    credentials {
        #Required
        password = var.password
        user_name = var.user_name
    }
}
```

### Debug Output
```hcl
$ terraform apply

. . .

oci_data_safe_target_database.the_target: Still creating... [1m10s elapsed]
oci_data_safe_target_database.the_target: Still creating... [1m20s elapsed]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the
│ output values may not be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│ 	
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering
│ from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: work request did not succeed, workId: ocid1.coreservicesworkrequest.oc1..aaaaaaaazqzi3l4av5kompwseeadm2vlrpk6efhiqwyonsped2ukfpmqkgcq, entity: target-database, action: CREATED. Message: Error occurred while registering the target database
│ 
│   with oci_data_safe_target_database.the_target,
│   on targetdb.tf line 1, in resource "oci_data_safe_target_database" "the_target":
│    1: resource "oci_data_safe_target_database" "the_target" {
```
…then check OCI console and find that the resource was created but is flagged **NEEDS ATTENTION**. I get the OCID from the resource and proceed below.
```hcl
$ terraform import oci_data_safe_target_database.the_target ocid1.datasafetargetdatabase.oc1.iad.amaaaaappb3iotaru77pd4bn6bvvgw4s37pbadly3vcyaoe2m6e5w7lwrwxa
module.dsafe_target_edws.oci_data_safe_target_database.the_target: Importing from ID "ocid1.datasafetargetdatabase.oc1.iad.amaaaaappb3iotaru77pd4bn6bvvgw4s37pbadly3vcyaoe2m6e5w7lwrwxa"...
oci_data_safe_target_database.the_target: Import prepared!
  Prepared oci_data_safe_target_database for import
oci_data_safe_target_database.the_target: Refreshing state... [id=ocid1.datasafetargetdatabase.oc1.iad.amaaaaappb3iotaru77pd4bn6bvvgw4s37pbadly3vcyaoe2m6e5w7lwrwxa]
```
…now I can run apply again and see the credentials are not included from above apply:
```hcl
$ terraform apply

Terraform will perform the following actions:

  # oci_data_safe_target_database.the_target will be updated in-place
  ~ resource "oci_data_safe_target_database" "the_target" {
        id                = "ocid1.datasafetargetdatabase.oc1.iad.amaaaaappb3iotaru77pd4bn6bvvgw4s37pbadly3vcyaoe2m6e5w7lwrwxa"
        # (10 unchanged attributes hidden)


      + credentials {
          + password  = (sensitive value)
          + user_name = "DATASAFE_USER"
        }


        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

. . . 

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
When I check the OCI console again the resource is ACTIVE.

### Expected Behavior
* I exepect `oci_data_safe_target_database` resources to create with first apply command and not require a manual import then apply a second time to attach DB credentials

### Actual Behavior
* When I apply configuration to create `oci_data_safe_target_database` the process fails as shown above. If I then import the resource that is created (but which shows as NEEDS ATTENTION in the OCI console) then apply the configuration unchanged I see 

### Steps to Reproduce

1. `terraform apply`
2. When error occurs, check OCI console to get OCID of the resource that was created
3. `terraform import oci_data_safe_target_database.the_target THE_OCID`
4. `terraform apply`

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
