### ISSUE TITLE
Documentation bug:  "oci_core_drg_attachment_management" resource documentation does not show drg_id in examples, and improperly lists it as optional

### ISSUE THREAD

**Issue by ghost** [oracle/terraform-provider-oci#1435]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Provider version: 4.40.0
Documentation version: 4.40.0

### Affected Resource(s)

oci_core_drg_attachment_management

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The documented example should work.  The documented parameter list should properly tag the `drg_id` parameter as required.

### Actual Behavior

The documented example will not work due to the missing required parameter `drg_id`.  Any resource that follows the parameter list's specification of `drg_id` as optional and chooses to not include that parameter will fail.

### Steps to Reproduce

Create an `oci_core_drg_attachment_management` resource without specifying `drg_id`, as is allowed per the documentation, but is not permitted by the resource code.

### Important Factoids

N/A

### References

N/A

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
