### ISSUE TITLE
streaming_pool example doesn't include public endpoint creation

### ISSUE THREAD

**Issue by dralquinta** [oracle/terraform-provider-oci#1436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
$ terraform -v
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/oci v4.40.0
### Affected Resource(s)
oci_streaming_stream_pool

### Terraform Configuration Files

The following code creates an optional private_endpoint_settings block inside stream pool configuration. The following is an example code of my own. 

```hcl
resource "oci_streaming_stream_pool" "StreamingPool" {
  compartment_id = local.compartment_id
  name           = var.stream_pool_display_name
  
  kafka_settings {
    auto_create_topics_enable = var.auto_create_topics_enable
    log_retention_hours       = var.spool_log_retention_hours
    num_partitions            = var.spool_num_partitions
  }
  dynamic "private_endpoint_settings" {
    for_each = var.is_private_endpoint ? [1] : []
    content {
      nsg_ids   = [local.nsg_id]
      subnet_id = local.subnet_ocid
    }

  }
}
```

I'm looking to add support to public stream creation

### Debug Output

N/A

### Panic Output
N/A

### Expected Behavior

Terraform registry documentation doesn't include any reference in how to make a public stream pool available through code. What's referenced is this: 

```hcl
resource "oci_streaming_stream_pool" "test_stream_pool" {
    #Required
    compartment_id = var.compartment_id
    name = var.stream_pool_name

    #Optional
    custom_encryption_key {
        #Required
        kms_key_id = oci_kms_key.test_key.id
    }
    defined_tags = var.stream_pool_defined_tags
    freeform_tags = {"Department"= "Finance"}
    kafka_settings {

        #Optional
        auto_create_topics_enable = var.stream_pool_kafka_settings_auto_create_topics_enable
        bootstrap_servers = var.stream_pool_kafka_settings_bootstrap_servers
        log_retention_hours = var.stream_pool_kafka_settings_log_retention_hours
        num_partitions = var.stream_pool_kafka_settings_num_partitions
    }
    private_endpoint_settings {

        #Optional
        nsg_ids = var.stream_pool_private_endpoint_settings_nsg_ids
        private_endpoint_ip = var.stream_pool_private_endpoint_settings_private_endpoint_ip
        subnet_id = oci_core_subnet.test_subnet.id
    }
}
```
It's only including private endpoints settings. I see that API has support to return if either the pool is or not private so I'm inferring the provider has support for creating public pools as well. 

Examples under: https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/streaming/main.tf do not include any reference to public pools either. 

### Actual Behavior

N/A

### Steps to Reproduce

N/A

### References

See the following links: 

https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/streaming_stream_pool
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/streaming/main.tf

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
