### ISSUE TITLE
What are the potential values for access_type  under https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/objectstorage_bucket

### ISSUE THREAD

**Issue by dralquinta** [oracle/terraform-provider-oci#1439]
Hi, 

I'm trying to understand (without getting to see the code of the API), what are the potential values for bucket_access_type under: https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/objectstorage_bucket 

Even Though default one that directs to private access is there (See: `NoPublicAccess`) there is no real mention for programatic creation for public access. 

Can you please share the values (and maybe) update the documentation as well with such values?

Thanks ,

DA.

**Comment by dralquinta** [comment]
Same thing happens for `auto_tiering` variable. Default `Disabled`goes by fine, however the logical one that negates such (`Enabled`) breaks the provider execution by showing this error: 


```hcl
╷
│ Error: 400-InvalidBucketProperty 
│ Provider version: 4.40.0, released on 2021-08-18.  
│ Service: Object Storage Bucket 
│ Error Message: Invalid value for property autoTiering: Enabled 
│ OPC request ID: scl-1:1t04uJ6u4xBS2ecmpSUdrIqQpg-v68Hnci-RtHIdJnrilQoLPYe9weiE93UROQZK 
│ Suggestion: Please retry or contact support for help with service: Object Storage Bucket
│ 
│ 
│   with oci_objectstorage_bucket.Bucket,
│   on objectstorage.tf line 9, in resource "oci_objectstorage_bucket" "Bucket":
│    9: resource "oci_objectstorage_bucket" "Bucket" {
│ 
```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
