### ISSUE TITLE
Can the oci terraform provider documentation can be amended to include example values please?

### ISSUE THREAD

**Issue by codingarchitect** [oracle/terraform-provider-oci#1441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can the oci terraform provider documentation can be amended to include example values.
```
resource "oci_containerengine_cluster" "test_cluster" {
    #Required
    compartment_id = var.compartment_id
    kubernetes_version = var.cluster_kubernetes_version
```
If instead of the above, if it says
```
var compartment_id = {
    type=string
    default="ocid1.compartment.oc1..aaaaaaaa...."
}
var cluster_kubernetes_version = {
    type=string
    default="v1.20.8"
}
resource "oci_containerengine_cluster" "test_cluster" {
    #Required
    compartment_id = var.compartment_id
    kubernetes_version = var.cluster_kubernetes_version
    ....
```
It will be useful to see the example values

Similarly 
instead of 
```
kubernetes_version - (Required) (Updatable) The version of Kubernetes to install into the cluster masters.
```
this will be more useful
```
kubernetes_version - (Required) (Updatable) The version of Kubernetes to install into the cluster masters. ex: v.1.20.8
```

### New or Affected Resource(s)

N/A

### Potential Terraform Configuration

N/A

### References

For ex:
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/containerengine_cluster

Thanks,

**Comment by varmax2511** [comment]
Provider documentation is generic and cannot pin to specific values as this may confuse users on applicable values. You may refer to our https://github.com/terraform-providers/terraform-provider-oci/tree/master/examples which are more tailored for specific use cases.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
