### ISSUE TITLE
Can terraform based upgrades be linked to from the Main OCI documentation please?

### ISSUE THREAD

**Issue by codingarchitect** [oracle/terraform-provider-oci#1442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can terraform based upgrades be linked to from the Main OCI documentation please?
Ex: 
- https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengupgradingk8smasternode.htm 
can have an additional section of how to do it using terraform.
- https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengupgradingk8sworkernode.htm can have an additional section of how to do it using terraform.
- https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengmigratingclusters.htm can have an additional section on how to do it using terraform.
    - What additional attributes or blocks are required in the terraform for the migration?
    - Will the migration result a destroy and re-create or will it be an in-place upgrade?
    - What will be the minimum terraform oci provider version required for the upgrade?

Information like the above in addition to how to do this using the web console and API will be really helpful.

### Potential Terraform Configuration
N/A

### References
N/A

**Comment by hyder** [comment]
We have implemented cluster upgrade here: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/docs/upgrade.adoc

Hope that helps.

**Comment by codingarchitect** [comment]
Thanks for the response hyder.
I had seen them before yes.
Is there any documentation on how to do it with terraform when not using the terraform-oci-oke module, the vanilla terraform oci provider?

Thanks & Regards,
Sendhil
