### ISSUE TITLE
OCI DB version no longer available?

### ISSUE THREAD

**Issue by revchris** [oracle/terraform-provider-oci#1447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform 0.13.7
OCI Provider 4.43.0

### Affected Resource(s)

oci_database_db_system

### Terraform Configuration Files

Trying to install db_version = "12.1.0.2.201020"

### Debug Output

Error: 400-InvalidParameter 
Provider version: 4.43.0, released on 2021-09-08.  
Service: Database Db System 
Error Message: The database version must be one of 11.2.0.4 or 11.2.0.4.201020 or 11.2.0.4.210119 or 11.2.0.4.210420 or 12.1.0.2 or 12.1.0.2.210119 or 12.1.0.2.210420 or 12.1.0.2.210720 or 12.2.0.1 or 12.2.0.1.210119 or 12.2.0.1.210420 or 12.2.0.1.210720 or 18.0.0.0 or 18.12.0.0 or 18.13.0.0 or 18.14.0.0 or 19.0.0.0 or 19.10.0.0 or 19.11.0.0 or 19.12.0.0 or 21.0.0.0 or 21.3.0.0. 
OPC request ID: 90518078d6df36c292db3d80b1d43db6/9C5F90C486160D7AAD5D749C49AC6E4A/790C44AFD6C0D20F93B20DC1268DE813 
Suggestion: Please update the parameter(s) in the Terraform config as per error message The database version must be one of 11.2.0.4 or 11.2.0.4.201020 or 11.2.0.4.210119 or 11.2.0.4.210420 or 12.1.0.2 or 12.1.0.2.210119 or 12.1.0.2.210420 or 12.1.0.2.210720 or 12.2.0.1 or 12.2.0.1.210119 or 12.2.0.1.210420 or 12.2.0.1.210720 or 18.0.0.0 or 18.12.0.0 or 18.13.0.0 or 18.14.0.0 or 19.0.0.0 or 19.10.0.0 or 19.11.0.0 or 19.12.0.0 or 21.0.0.0 or 21.3.0.0.

### Expected Behavior
It should have installed a DBAAS system with version "12.1.0.2.201020", like it did 2 weeks ago.

### Actual Behavior
Received the error:
Error Message: The database version must be one of 11.2.0.4 or 11.2.0.4.201020 or 11.2.0.4.210119 or 11.2.0.4.210420 or 12.1.0.2 or 12.1.0.2.210119 or 12.1.0.2.210420 or 12.1.0.2.210720 or 12.2.0.1 or 12.2.0.1.210119 or 12.2.0.1.210420 or 12.2.0.1.210720 or 18.0.0.0 or 18.12.0.0 or 18.13.0.0 or 18.14.0.0 or 19.0.0.0 or 19.10.0.0 or 19.11.0.0 or 19.12.0.0 or 21.0.0.0 or 21.3.0.0.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
