### ISSUE TITLE
oci_integration_integration_instance will remove existing defined_tags when set to null

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1451]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.44.0
```

### Affected Resource(s)

```hcl
resource "oci_integration_integration_instance" "the_instance" {
  #Required
  compartment_id            = var.compartment_id
  display_name              = var.display_name
  integration_instance_type = var.integration_instance_type
  is_byol                   = var.is_byol
  message_packs             = var.message_packs

  #Optional
  defined_tags = null
}
```

```
terraform apply
```

```hcl
  # oic_c2m_prod.oci_integration_integration_instance.the_instance will be updated in-place
  ~ resource "oci_integration_integration_instance" "the_instance" {
      ~ defined_tags              = {
          - "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/someone@example.com" -> null
          - "Oracle-Tags.CreatedOn" = "2021-09-17T00:44:25.158Z" -> null
        }
        id                        = "ocid1.integrationinstance.oc1.iad.amaaaaaafpjjcohdjjqh4u74a4fqhbraaglb7hoe45kdaesesajcjkbyw24a"
        # (13 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior
I expect an attribute such as `defined_tags` set to `null` should not change the underlying resource attribute (or should apply the default for required attributes). Instead, `null` should imply "no value specified"

### Actual Behavior
Setting `defined_tags = null` causes change operation to remove any existing `defined_tags` (notably the compartment default tags.

### Steps to Reproduce

1. Ensure HCL contains `defined_tags = null` and that existing instance has at least one defined tag assigned
2. `terraform apply`
3. Note that  resource is flagged to change and to remove defined_tags 

### Important Factoids
* Am using work-around as mentioned elsewhere to `ignore_changes` for `defined_tags`. However, this is very incomplete as it will soon lead to multiple scripts that cannot accommodate updating `defined_tags` because of the substantially-embedded "ignores" across multiple stacks.

### References
* https://github.com/terraform-providers/terraform-provider-oci/issues/1283
* https://github.com/terraform-providers/terraform-provider-oci/issues/1334
* https://github.com/terraform-providers/terraform-provider-oci/issues/1394

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
