### ISSUE TITLE
Cannot remove path_route_set_name from oci_load_balancer_listener

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1454]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.46.0
```

### Affected Resource(s)
* oci_load_balancer_listener

### Terraform Configuration Files

```hcl
resource "oci_load_balancer_listener" "the_listener" {
  #Required
  default_backend_set_name = var.default_backend_set_name
  load_balancer_id         = var.load_balancer_id
  name                     = var.name
  port                     = var.port
  protocol                 = var.protocol

  #Optional
  path_route_set_name      = "A_ROUTE_SET"
}
```
…apply then change above to...
```hcl
resource "oci_load_balancer_listener" "the_listener" {
  #Required
  default_backend_set_name = var.default_backend_set_name
  load_balancer_id         = var.load_balancer_id
  name                     = var.name
  port                     = var.port
  protocol                 = var.protocol

  #Optional
  path_route_set_name      = null
}
```
### Expected Behavior
* I expect setting `path_route_set_name` to `null` will remove the associated Path Route Set from the Listener

### Actual Behavior
* Setting `path_route_set_name` to `null` does not remove an associated Path Route Set from the Listener. _Note, this will be essential when Path Route Sets are retired._

### Steps to Reproduce

1. `terraform apply` with `oci_load_balancer_listener` setting `path_route_set_name` to non-null value
2. Set `path_route_set_name` to `null` then `terraform apply` and note that Path Route Set is not removed from the Listener

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
