### ISSUE TITLE
Option to Choose IP address when creating compute instance

### ISSUE THREAD

**Issue by edercervantes** [oracle/terraform-provider-oci#1458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently when creating a compute instance using ```oci_core_instance```, it is not possible to choose an existing reserved public IP address for the "assign_public_ip" field.

An ideal solution would be another field that works with "assign_public_ip" field to choose what IP address existing within a tenancy to assign to a compute instance's private ip.

### Potential Terraform Configuration

```hcl
resource "oci_core_instance" "test_instance" {
    availability_domain = var.instance_availability_domain
    compartment_id = var.compartment_id
    shape = var.instance_shape

    create_vnic_details {
        private_ip = var.instance_create_vnic_details_private_ip
        assign_public_ip = var.instance_create_vnic_details_assign_public_ip
        
        #only used when assign_public_ip is true
        #if not used, then random IP is assigned
        choose_public_ip = var.existing_reserved_public_ip_address
    }
}
```

**Comment by edercervantes** [comment]
Hello, just following up to see if there has been any traction on this request?

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
