### ISSUE TITLE
oci_database_database errors with unexpected state: BACKUP_IN_PROGRESS

### ISSUE THREAD

**Issue by krilor** [oracle/terraform-provider-oci#1467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/oci v4.47.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* oci_database_database

### Terraform Configuration Files

Not really sure if it is relevant here.

```hcl
resource "oci_database_database" "test" {

  db_home_id = data.oci_database_db_homes.test.db_homes.0.id
  source     = "NONE"

  database {

    db_name = "TEST"
    db_unique_name = "TEST_TEST"
    pdb_name       = "PDB01"
    admin_password = "******"
    db_workload = "OLTP"

    db_backup_config {
      auto_backup_enabled     = true
      auto_backup_window      = "SLOT_ONE"
      recovery_window_in_days = "15"
    }
  }
}
```

### Expected Behavior

Resource created ok and terraform exiting without error and tainted resources.

### Actual Behavior

Resource goes directly into backup and terraform ends with error

`Error Message: During creation, Terraform expected the resource to reach state(s): AVAILABLE, but the service reported unexpected state: BACKUP_IN_PROGRESS.`

We then have to untaint the resource before moving on.

### Steps to Reproduce

We are seeing this every now and then when we (re)create a CDB on Exa CS.

### Important Factoids

It looks like it is valid behavior for the database to go directly into BACKUP_IN_PROGRESS.
I think this is basically a missing target in DatabaseDatabaseResourceCrud.CreateTarget().
Adding oci_database.DatabaseLifecycleStateBackupInProgress would likely fix this.

Would you accept a PR for that?

ref:
* https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/database_database_resource.go#L456
* https://github.com/oracle/oci-go-sdk/blob/master/database/database.go#L102

**Comment by barlowgl** [comment]
I believe this issues was fixed in oracle/oci v4.102.0.

New code now checks the OPC request status instead of the resource status.

Also there has been a change in the automatic running of the initial "automatic backup". It will wait a short time to see if a PDB creation task follows the CDB creation, If so it will block the initial automatic backup.
