### ISSUE TITLE
Failed to create a private endpoint for the Autonomous Database because OBO tokens are not supported for use with a private endpoint.

### ISSUE THREAD

**Issue by kshinkr** [oracle/terraform-provider-oci#1471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform version : 1.0.x
Provider version: 4.49.0, released on 2021-10-20.

### Affected Resource(s)

Service: Database Autonomous 

### Terraform Configuration Files
 Plan output 
  + create
Terraform will perform the following actions:
  # module.dsafeadb1.oci_database_autonomous_database.adb_pe will be created
  + resource "oci_database_autonomous_database" "adb_pe" {
      + admin_password                                 = (sensitive value)
      + apex_details                                   = (known after apply)
      + are_primary_whitelisted_ips_used               = (known after apply)
      + autonomous_container_database_id               = (known after apply)
      + autonomous_database_backup_id                  = (known after apply)
      + autonomous_database_id                         = (known after apply)
      + autonomous_maintenance_schedule_type           = (known after apply)
      + available_upgrade_versions                     = (known after apply)
      + backup_config                                  = (known after apply)
      + clone_type                                     = (known after apply)
      + compartment_id                                 = "ocid1.compartment.*********************************************cy2zlq"
      + connection_strings                             = (known after apply)
      + connection_urls                                = (known after apply)
      + cpu_core_count                                 = 1
      + data_safe_status                               = (known after apply)
      + data_storage_size_in_gb                        = (known after apply)
      + data_storage_size_in_tbs                       = 1
      + db_name                                        = "dsafeadb1"
      + db_version                                     = "19c"
      + db_workload                                    = "OLTP"
      + defined_tags                                   = {
          + "Applications.AppID"            = "3999"
          + "Applications.ApplicationName"  = "Rundeck"
          + "Applications.CreateDateTime"   = "${oci.datetime}"
          + "Applications.CreateUserType"   = "${iam.principal.type}"
          + "Applications.CreatedBy"        = "${iam.principal.name}"
          + "Applications.EnvironmentGroup" = "CS*****eck"
          + "Applications.EnvironmentName"  = "proda**********deck"
          + "Applications.EnvironmentType"  = "Prod"
          + "Applications.Keywords"         = "rundeck, devops"
          + "Applications.Lob"              = "Cloud************rations"
          + "Applications.Org"              = "OIT"
          + "Applications.Requestor"        = "pe-*****************************************************@oracle.com"
          + "Applications.ServiceArea"      = "Cloud Management Apps"
        }
      + display_name                                   = "dsafeadb1"
      + failed_data_recovery_in_seconds                = (known after apply)
      + freeform_tags                                  = (known after apply)
      + id                                             = (known after apply)
      + infrastructure_type                            = (known after apply)
      + is_access_control_enabled                      = (known after apply)
      + is_auto_scaling_enabled                        = true
      + is_data_guard_enabled                          = (known after apply)
      + is_dedicated                                   = (known after apply)
      + is_free_tier                                   = (known after apply)
      + is_mtls_connection_required                    = (known after apply)
      + is_preview                                     = (known after apply)
      + is_preview_version_with_service_terms_accepted = (known after apply)
      + is_refreshable_clone                           = (known after apply)
      + key_history_entry                              = (known after apply)
      + key_store_id                                   = (known after apply)
      + key_store_wallet_name                          = (known after apply)
      + kms_key_id                                     = (known after apply)
      + kms_key_lifecycle_details                      = (known after apply)
      + license_model                                  = "LICENSE_INCLUDED"
      + lifecycle_details                              = (known after apply)
      + nsg_ids                                        = [
          + "ocid1.networksecuritygroup*****************************************************i54kzrmq",
        ]
      + ocpu_count                                     = (known after apply)
      + open_mode                                      = (known after apply)
      + operations_insights_status                     = (known after apply)
      + permission_level                               = (known after apply)
      + private_endpoint                               = (known after apply)
      + private_endpoint_ip                            = (known after apply)
      + private_endpoint_label                         = (known after apply)
      + refreshable_mode                               = (known after apply)
      + refreshable_status                             = (known after apply)
      + role                                           = (known after apply)
      + service_console_url                            = (known after apply)
      + source                                         = (known after apply)
      + source_id                                      = (known after apply)
      + standby_db                                     = (known after apply)
      + standby_whitelisted_ips                        = (known after apply)
      + state                                          = (known after apply)
      + subnet_id                                      = "ocid1.subnet.oc1.*****************************************************mgzkri6a"
      + system_tags                                    = (known after apply)
      + time_created                                   = (known after apply)
      + time_deletion_of_free_autonomous_database      = (known after apply)
      + time_maintenance_begin                         = (known after apply)
      + time_maintenance_end                           = (known after apply)
      + time_of_last_failover                          = (known after apply)
      + time_of_last_refresh                           = (known after apply)
      + time_of_last_refresh_point                     = (known after apply)
      + time_of_last_switchover                        = (known after apply)
      + time_of_next_refresh                           = (known after apply)
      + time_reclamation_of_free_autonomous_database   = (known after apply)
      + timestamp                                      = (known after apply)
      + used_data_storage_size_in_tbs                  = (known after apply)
      + vault_id                                       = (known after apply)
      + customer_contacts {
          + email = "jerry.*****@oracle.com"
        }
    }
Plan: 1 to add, 0 to change, 0 to destroy.
─────────────────────────────────────────────────────────────────────────────
Saved the plan to: <path hidden>
To perform exactly these actions, run the following command to apply:
    terraform apply "<path hidden>"

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Panic Output

Initializing modules...
- dsafeadb1 in ../../../modules/database/adb_pe
Initializing provider plugins...
- Finding latest version of hashicorp/oci...
- Installing hashicorp/oci v4.49.0...
- Installed hashicorp/oci v4.49.0 (unauthenticated)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
module.dsafeadb1.oci_database_autonomous_database.adb_pe: Creating...
Error: 400-InvalidParameter 
Provider version: 4.49.0, released on 2021-10-20.  
Service: Database Autonomous 
Error Message: Failed to create a private endpoint for the Autonomous Database because OBO tokens are not supported for use with a private endpoint. 
OPC request ID: 6c1f2c2b91634e7fc70b59f8d613e89c/0A3A11C62203BDA1ABE0D5EBDD8C6833/04C7EFE5C1FD7270F65D4EB37EE2CD56 
Suggestion: Please Update the parameter(s) in the Terraform config as per error message Failed to create a private endpoint for the Autonomous Database because OBO tokens are not supported for use with a private endpoint.
  with module.dsafeadb1.oci_database_autonomous_database.adb_pe,
  on ../../../modules/database/adb_pe/main.tf line 17, in resource "oci_database_autonomous_database" "adb_pe":
  17: resource "oci_database_autonomous_database" "adb_pe" {
*** End Job Output ***

### Expected Behavior

ADB-PE supposed to be provisioned but it is not going through.

### Steps to Reproduce

Every time it fails

1. `terraform apply`

### References

First thing, what is the meaning of OBO token,
Second, OBO tokens are not supported for use with a private endpoint, why did it happen ?

We are running this TF via gitlab repository and repo has been configured correct oci config to provision.
Can you check what is the issue here ?

Cheers
Jerry

**Comment by KirankBadiger** [comment]
Team, Same issue here, we are running terraform code in OCI Resource Manager stack, getting the same error

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
