### ISSUE TITLE
Is Vault/Secret resource creation not supported?

### ISSUE THREAD

**Issue by hitsumabushi845** [oracle/terraform-provider-oci#1472]
I'm looking [oci provider document](https://registry.terraform.io/providers/hashicorp/oci/latest/docs), it has only data resource about Vault service.  

Is Vault/Secret resource creation not supported for now?  
Or is there some way to create those resources with terraform?

**Comment by et304383** [comment]
@Maxrovr how is this the answer?  AWS secrets manager is supported in the AWS provider.  Why can't the same be done with OCI vault secrets?

If the sensitive nature of the decrypted value is an issue, you hash it before storing in the state.  No one would expect the plaintext value to be stored in the state.

**Comment by Maxrovr** [comment]
Hi @et304383 , I have gotten in touch with the team and exploring how we could get this implemented and how long it will take

**Comment by et304383** [comment]
@Maxrovr is this actually supported and you just haven't updated the docs correctly?

https://github.com/oracle/terraform-provider-oci/issues/1551

This is VERY confusing, and you need to get your docs in line with what's functionally supported in the provider

**Comment by dhoogfr** [comment]
When recently checking for how to get a secret via terraform, I found that the documentation is spread over 3 groups:

* KMS
* Secrets
* Vault

Eg, to datasource to get the list of secrets you need to use oci_vault_secrets, documented under vault.
But to get the actual secret contents you need to use oci_secrets_secretbundle, documented under secrets...
Simular with vault resources themselves.

This is indeed very confusing.

**Comment by Maxrovr** [comment]
@jotruon Can I get your input here?

**Comment by jotruon** [comment]
We use oci_secrets_secretbundle to match the API which is using across all other platform (SDK, CLI, Ansible...) https://docs.oracle.com/en-us/iaas/api/#/en/secretretrieval/20190301/SecretBundle/GetSecretBundle

**Comment by et304383** [comment]
> We use oci_secrets_secretbundle to match the API which is using across all other platform (SDK, CLI, Ansible...) https://docs.oracle.com/en-us/iaas/api/#/en/secretretrieval/20190301/SecretBundle/GetSecretBundle

That's a data source.  Not useful for **writing** a secret?

**Comment by dhoogfr** [comment]
@et304383 if you want to write a secret, you can use the oci_vault_secret resource: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/vault_secret

I know that the documentation states that the operation is not supported by the OCI Terraform provider, but that is wrong.
There is also missing information on the content_type and incorrect information on what is optional and what is required.

But the below minimal example works

```
resource "oci_vault_secret" "test_secret" {
  compartment_id = data.oci_identity_compartment.ora_apps.id
  secret_content {
    content_type = "Base64"
    content      = base64encode("this is a test")
  }
  key_id       = oci_kms_key.dbcs_creds_master.id
  secret_name = "test"
  vault_id    = oci_kms_vault.dbcs_creds.id

}
```

**Comment by jotruon** [comment]
correct, to write secret you can use https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/vault_secret which match this API https://docs.oracle.com/en-us/iaas/api/#/en/secretmgmt/20180608/Secret/CreateSecret 
Terraform is matching with API.
