### ISSUE TITLE
Core VCN CIDR Blocks - Order Variance

### ISSUE THREAD

**Issue by steve-gray** [oracle/terraform-provider-oci#1493]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When using a core_vcn resource with multiple subnets, it appears that sometimes the subnets come back from the OCI endpoints in a different order. This causes the module to do an add/delete for each of them, and causes a failure due to "multiple changes" / hitting the one subnet added or removed at a time limit. Manually removing the subnet it wants to re-order from the OCI interface then letting the module re-add it to the back of the list works, but is a pain.

Ideally the provider should be order-invariant and store the state internally in a sorted fashion. and not care if the order of the subnets in the list is different, as it has no semantic relevance.

### Terraform Version and Provider Version

1.0.11

### Affected Resource(s)

- oci_core_vn

### Terraform Configuration Files

```
resource "oci_core_vcn" "example" {
    compartment_id  = oci_identity_compartment.compartment.id
    display_name    = "Example"
    is_ipv6enabled  = true

    cidr_blocks     = [
        var.subnet_a,
        var.subnet_b,
        var.subnet_c,
    ]
}```

**Comment by hyder** [comment]
Please note that cidr_blocks != subnets. You can further carve out a subnet's cidr block from 1 of the VCN's cidr blocks as long as it's at least a /29 (see https://erikberg.com/notes/networks.html). But I agree with your comment about the order invariance. Have you tried using the sort function in the meantime and see if this addresses your issue?

**Comment by steve-gray** [comment]
Thats just the naming of the variable, I basically just put in three dummy names to raise the issue when scrubbing out all the actual data.

The sort function won't help because they were already sorted in my TF script, but they just happened to not be the order that it came back from OCI's infrastructure with. I'd created 10.201/16, 10.202/16, 10.203/16 in sequence - only to find that it'd just intermittently start failing due to the order from the API not being that (though the change it wanted to make was effectively a no-op!)

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
