### ISSUE TITLE
Resource oci_core_drg_attachment network_details type to be one of [VCN], got VIRTUAL_CIRCUIT

### ISSUE THREAD

**Issue by mhomaid1** [oracle/terraform-provider-oci#1495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.55.0
```

### Affected Resource(s)

`oci_core_drg_attachment`

### Terraform Configuration Files

```hcl
resource "oci_core_drg_attachment" "x_drg_attachment_virtual_circuit" {
    drg_id = oci_core_drg.x_drg.id

    display_name = "DRG Attachment for Virtual Circuit: X VCN - X Virtual Circuit"
    network_details {
        id = oci_core_virtual_circuit.x_virtual_circuit.id
        type = "VIRTUAL_CIRCUIT"
    }
}
```

### Debug Output

[Debug Output Gist](https://gist.github.com/mhomaid1/f1c2469f805cb08d741c4ccb93fa9d0b)

### Expected Behavior

Based on [resource documentation](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_drg_attachment#type), the type can be one of these values: `IPSEC_TUNNEL`, `REMOTE_PEERING_CONNECTION`, `VCN`, `VIRTUAL_CIRCUIT` so `VIRTUAL_CIRCUIT` should be accepted.

### Actual Behavior

``` 
Error: expected network_details.0.type to be one of [VCN], got VIRTUAL_CIRCUIT

   with module.env.module.fast_connect.oci_core_drg_attachment.x_drg_attachment_virtual_circuit,
   on ../../modules/oci_fast_connect/main.tf line 38, in resource "oci_core_drg_attachment" "x_drg_attachment_virtual_circuit":
   38: resource "oci_core_drg_attachment" "x_drg_attachment_virtual_circuit" {
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I have created this DRG manually and attached it to the virtual circuit and VCN manually, but when I tried to import these changes to terraform, I got this error

**Comment by rajaramanlala** [comment]
For non-vcn attachments, there is a different resource  named oci_core_drg_attachment_mangement

**Comment by rajaramanlala** [comment]
Is the config missing compartment id?

**Comment by mhomaid1** [comment]
@rajaramanlala Do you mean terraform config? if that's so, I tried both before importing the resource providing `compartment_id`, and without it, I think the issue is for some reason, OCI doesn't return the `compartment_id` while importing it to terraform state, and this cause the issue
```
resource "oci_core_drg_attachment_management" "x_drg_attachment_virtual_circuit" {
drg_id = oci_core_drg.x_drg.id
compartment_id = var.compartment_id
attachment_type = "VIRTUAL_CIRCUIT"
network_id = oci_core_virtual_circuit.x_virtual_circuit.id
display_name = "DRG Attachment for Virtual Circuit:  VCN"
}
```

**Comment by rajaramanlala** [comment]
@mhomaid1  That is right. By specifying the comp id in terraform config. 
.  We will need someone from the oci team to confirm this.

**Comment by mhomaid1** [comment]
Again same issue with different attachment type
```
resource "oci_core_drg_attachment_management" "y_drg_attachment_ipsec_2" {
  drg_id = oci_core_drg.y_drg.id
  compartment_id = oci_identity_compartment.main.id
  display_name = "DRG Attachment for IPSec Tunnel: ipsectunnel20220127070422-2"
  attachment_type = "IPSEC_TUNNEL"
  network_details {
    id   = module.vcn.vcn_id
    ipsec_connection_id = oci_core_ipsec.y_ipsec_connection.id
    type = "IPSEC_TUNNEL"
  }
}
```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
