### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by socratesx** [oracle/terraform-provider-oci#1498]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if documentation examples were providing some value on how to use the provider's resources. All arguments in all examples are just pointing to variables that are missing form the example. 

For example, from oci_core_drg_route_table_route_rule the following code is provided. 

```hcl
resource "oci_core_drg_route_table_route_rule" "test_drg_route_table_route_rule" {
    #Required
    drg_route_table_id = oci_core_drg_route_table.test_drg_route_table.id
    destination = var.drg_route_table_route_rule_route_rules_destination
    destination_type = var.drg_route_table_route_rule_route_rules_destination_type
    next_hop_drg_attachment_id = oci_core_drg_attachment.test_drg_attachment.id

```

How I am supposed to know what is the value of  `var.drg_route_table_route_rule_route_rules_destination` & ` var.drg_route_table_route_rule_route_rules_destination_type` if it is not defined in the example? 

Also the resource depends on other resources to work.  Where are these resources declared in the example code? 
`oci_core_drg_route_table.test_drg_route_table`
`oci_core_drg_attachment.test_drg_attachment`

A useful example would declare these as well and present a working use case.

What I was expecting to see as a truly working example is the following:

```hcl
variable "drg_route_table_route_rule_route_rules_destination" {
<definition>
}
variable "drg_route_table_route_rule_route_rules_destination_type" {
<definition>
}

resource "oci_core_drg_route_table" "test_drg_route_table" {
<definition>
}

resource "oci_core_drg_attachment" "test_drg_attachment" {
<definition>
}

resource "oci_core_drg_route_table_route_rule" "test_drg_route_table_route_rule" {
    #Required
    drg_route_table_id = oci_core_drg_route_table.test_drg_route_table.id
    destination = var.drg_route_table_route_rule_route_rules_destination
    destination_type = var.drg_route_table_route_rule_route_rules_destination_type
    next_hop_drg_attachment_id = oci_core_drg_attachment.test_drg_attachment.id
```

Please provide all context to the provider's modules, otherwise the examples are not helpful at all.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
