### ISSUE TITLE
TF Plug in  is failing with LB and Traffic shift stage 

### ISSUE THREAD

**Issue by RahulMR42** [oracle/terraform-provider-oci#1499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/oci v4.34.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/tls v2.0.1
### Affected Resource(s)

oci_load_balancer_load_balancer
oci_devops_deploy_stage - With Traffic shift stage.

### Terraform Configuration Files

```hcl
resource "oci_load_balancer_load_balancer" "test_load_balancer" {
    #Required
    compartment_id = var.compartment_ocid
    display_name = "${var.app_name}_application_lb"
    shape = var.load_balancer_shape
    subnet_ids = [oci_core_subnet.subnet.id,]

    #Optional
    defined_tags = { "${oci_identity_tag_namespace.ArchitectureCenterTagNamespace.name}.${oci_identity_tag.ArchitectureCenterTag.name}" = var.release }
    ip_mode = var.load_balancer_ip_mode
    is_private = var.load_balancer_is_private
     
    shape_details {
        #Required
        maximum_bandwidth_in_mbps = var.load_balancer_shape_details_maximum_bandwidth_in_mbps
        minimum_bandwidth_in_mbps = var.load_balancer_shape_details_minimum_bandwidth_in_mbps
    }
}
```

### Debug Output
https://gist.github.com/RahulMR42/2d059eb7af869cb4d13d6e789621aabf 

### Panic Output
```
╷
│ Error: Plugin did not respond
│ 
│   with oci_devops_deploy_stage.ts-demo,
│   on devops.tf line 189, in resource "oci_devops_deploy_stage" "ts-demo":
│  189: resource "oci_devops_deploy_stage" "ts-demo" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with oci_load_balancer_load_balancer.test_load_balancer,
│   on loadbalanace.tf line 2, in resource "oci_load_balancer_load_balancer" "test_load_balancer":
│    2: resource "oci_load_balancer_load_balancer" "test_load_balancer" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-oci_v4.34.0_x4 plugin:

panic: interface conversion: interface {} is float64, not float32

````
### Expected Behavior

Create a new LB or add anew TS stage to devops deploy pipeline.

### Actual Behavior

TF apply panicked.

### Important Factoids

Its failed with LB or while adding Traffic Shift to the deployment pipeline 

### References

code repo - https://github.com/RahulMR42/OCI-Deployment-WithTraffic-Shift/tree/lb

**Comment by RahulMR42** [comment]
Any updates ?

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
