### ISSUE TITLE
Error on Dataintegration component. Nested entry is required

### ISSUE THREAD

**Issue by dralquinta** [oracle/terraform-provider-oci#1500]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```shell
Terraform v1.1
on linux_amd64
```

### Affected Resource(s)

- oci_dataintegration_workspace

## Issue description and solution

On documentation [here](https://github.com/terraform-providers/terraform-provider-oci/blob/master/website/docs/r/dataintegration_workspace.html.markdown) Whenever using property `is_private_network_enabled` set to true, this makes both `subnet_id` and `vcn_id` variables mandatory. Current documentation suggests that you can combine `is_private_network_enabled` in `false` and passing on `subnet_id` and `vcn_id` values which will create the following error: 

```shell
╷
│ Error: 400-InvalidParameter 
│ Provider version: 4.56.0, released on 2021-12-08.  
│ Service: Dataintegration Workspace 
│ Error Message: Invalid Argument [Subnet Id] should be null.. 
│ OPC request ID: ef70f856475b7cc566dc71a5e85ef3b3/FEC7DC50AC7D9462B8E168E5AF5B1E4B/F846A95E71418A95192DAC09347ED50E 
│ Suggestion: Please Update the parameter(s) in the Terraform config as per error message Invalid Argument [Subnet Id] should be null..
│ 
│ 
│   with oci_dataintegration_workspace.Workspace,
│   on dataintegrationwp.tf line 9, in resource "oci_dataintegration_workspace" "Workspace":
│    9: resource "oci_dataintegration_workspace" "Workspace" {
```

or

```shell
╷
│ Error: 400-InvalidParameter 
│ Provider version: 4.56.0, released on 2021-12-08.  
│ Service: Dataintegration Workspace 
│ Error Message: Invalid Argument [Subnet Id] should be null.. 
│ OPC request ID: ef70f856475b7cc566dc71a5e85ef3b3/FEC7DC50AC7D9462B8E168E5AF5B1E4B/F846A95E71418A95192DAC09347ED50E 
│ Suggestion: Please Update the parameter(s) in the Terraform config as per error message Invalid Argument [Vcn Id] should be null..
│ 
│ 
│   with oci_dataintegration_workspace.Workspace,
│   on dataintegrationwp.tf line 9, in resource "oci_dataintegration_workspace" "Workspace":
│    9: resource "oci_dataintegration_workspace" "Workspace" {
```

In order to fix this, you need to say that if `is_private_network_enabled` is `false` then both `subnet_id` and `vcn_id` should be `null`

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
