### ISSUE TITLE
`oci_core_shape_management` does not allow removing shapes from image

### ISSUE THREAD

**Issue by aw1cks** [oracle/terraform-provider-oci#1505]
The [oci_core_shape_management](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_shape_management) resource does not allow removing shapes from an image.
This means that the default list of shapes when the image is created are left here.
In my case, this means that an X86 instance could inadvertently be created against my ARM image.

Surely this module should take a list of shapes, and override the configuration of the image to match that list.

**Comment by danielwoodz** [comment]
This is also impacting our deployments of custom aarch64 images. 

We can add VM.Standard.A1.Flex, but we cant remove all the automatically added amd64 without a separate golang app that I wrote that:
1. Lists all Shapes Associated with the Image
1. Removes all Shapes Associated with the Image
1. Lists all Shapes Available in the region
1. Filters the region shapes to only names containing "\.A1\."
1. Adds those shapes to the Image

Ideally I would be able to just do:
```hcl
variable "shape_names" {
    type = list
    default = ["VM.Standard.A1.Flex","BM.Standard.A1.160"]
}
"oci_core_shape_management" "test_shape" {
    #Required
    compartment_id = var.compartment_id
    image_id = oci_core_image.test_image.id
    shape_names = var.shape_names
}
```

**Comment by sprat** [comment]
@ravinitp What is the progress on this subject?

**Comment by tf-oci-pub** [comment]
Hi @sprat,
The Imaging development team that owns this resource has decided to leave oci_core_shape_management  untouched. There is no great way to change this provider without significantly changing the behavior and affecting backwards compatibility.

Closing as `Cannot do`
