### ISSUE TITLE
Error: 404-NotAuthorizedOrFoundKmsKey

### ISSUE THREAD

**Issue by nvkanumuri** [oracle/terraform-provider-oci#1514]
I am working on creating a object storage bucket with encryption option using customer managed keys. As per documention I assume we need to pass kms_key_id while creating a bucket. But I am getting an error **Error: 404-NotAuthorizedOrFoundKmsKey** 

Error: 404-NotAuthorizedOrFoundKmsKey 
Provider version: 4.57.0, released on 2021-12-15. This provider is 4 version(s) old.  
Service: Object Storage Bucket 
Error Message: Caught RestClientException exception 
Suggestion: Either the resource has been deleted or service Object Storage Bucket need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm

This is how my declarations looks like..
resource "oci_objectstorage_bucket" "vault_bucket" {
  compartment_id = module.compartment.compartment_id
  namespace      = data.oci_objectstorage_namespace.object_namespace.namespace
  name           = "vault"
  access_type    = "NoPublicAccess"
  versioning     = "Enabled"
  kms_key_id = data.oci_kms_key.vault_devops_key.id
}

I also created policy as well
    "Allow dynamic-group ${oci_identity_dynamic_group.vault_dynamic_group.name} to use keys in compartment id ${module.compartment.compartment_id} where target.key.id = '${data.oci_kms_key.vault_devops_key.id}'",

Am I using the correction option to enable encryption with customer managed keys?

Thanks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
