### ISSUE TITLE
system_tags on oci_containerengine_cluster triggers a modification request every time

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#1536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

v1.1.3
v 4.64

### Affected Resource(s)

oci_containerengine_cluster

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Expected Behavior

Nothing should happen since no changes were made to the cluster.

### Actual Behavior
Every terraform run results in a modification. Adding system_tags to 
`
  lifecycle {
    ignore_changes = [system_tags]
  }
`
doesn't help. Still triggers the modification request though.

### Steps to Reproduce

1. Use https://github.com/oracle-terraform-modules/terraform-oci-oke 
2. Follow configuration instructions
3. Run `terraform apply` once to create the cluster
4. Run `terraform apply` again - this should not result in any modification.

**Comment by pavanm-huma** [comment]
I am impacted with this issue as well.  Would be really helpful if this is prioritised.

**Comment by karthicgit** [comment]
Could someone look into this please.

**Comment by et304383** [comment]
It should be noted that `oci_containerengine_node_pool` is impacted by the very same issue.

**Comment by bluedot09** [comment]
I am also impacted with this issue. Affects cluster and node pool to be changed. Ignore_changes also doesn't work.

**Comment by fabienpelletier** [comment]
I'm also impacted by this, this turns what should be a 30s terraform apply into a 30mn wait.

**Comment by et304383** [comment]
I agree with @fabienpelletier.  This is wasting productive hours when applying dozens of changes per day. I actually finished my day yesterday waiting an hour for a cluster update that was triggered by this bug. That's completely unacceptable.

**Comment by christi4n** [comment]
I'm also impacted because of this problem. Please, solve it because It's a non sense to have alerts for both "oci_containerengine_cluster" and "oci_containerengine_node_pool", nothing was changed so Terraform should be silent.

**Comment by XinruXiao-9** [comment]
Sorry for the inconvenience. We already have a fix pending release. The release is scheduled on 3.10. For now, people can try below workaround to unblock.

1. Try to add the below code change to your terraform code for clusters and nodepools.
   lifecycle {
     ignore_changes = [system_tags]
   }
2. If ignore_changes didn’t work and you don’t need the feature after provider 4.61.0, try to downgrade the terraform provider to 4.61.0  and do a terraform init -upgrade .

**Comment by et304383** [comment]
> Sorry for the inconvenience. We already have a fix pending release. The release is scheduled on 3.10. For now, people can try below workaround to unblock.
> 
> 1. Try to add the below code change to your terraform code for clusters and nodepools.
>    lifecycle {
>    ignore_changes = [system_tags]
>    }
> 2. If ignore_changes didn’t work and you don’t need the feature after provider 4.61.0, try to downgrade the terraform provider to 4.61.0  and do a terraform init -upgrade .

It's already been stated in this thread that ignore changes doesn't work on system tags.  It's an attribute reference, not a property.

Downgrading isn't an option for those of us on ARM M1 macs as you just added support in the latest release 6 days (!) ago.

**Comment by blabu23** [comment]
problem still exits with version 4.66.0 released today :-(

**Comment by XinruXiao-9** [comment]
The fix has already been merged however it requires a complete testing process. The fix will be released on March 10th, the version should be 4.67.0.

**Comment by XinruXiao-9** [comment]
The fix has been deployed today for 4.67.0. Please try to update it to 4.67.0 and feel free to reach out to me if there is any problem.

**Comment by blabu23** [comment]
works like a charm! Thank you very much 🥇

**Comment by hyder** [comment]
hi @blabu23, 

The 4.67 version has been released and it removed system_tags. https://github.com/oracle/terraform-provider-oci/releases/tag/v4.67.0 

Can you please confirm this release fixes the problem?

**Comment by hyder** [comment]
I can confirm this as well. I'll close the issue. 

Thanks.

**Comment by hyder** [comment]
hi @XinruXiao-9,

This issue is also affecting node pools.

**Comment by hyder** [comment]
Hi, this was incorrect. The user has confirmed it's working now in https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/495. I'm closing it again. 

Sorry for the trouble.
