### ISSUE TITLE
oci_containerengine_node_pool should support initialization script

### ISSUE THREAD

**Issue by et304383** [oracle/terraform-provider-oci#1541]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The console allows specifying an initialization script when creating a node pool.  The resource should support the same.  If this is a limitation of the API for node pool create/update then please let me know so I can complain to Oracle to fix the API to provide feature parity with the console.

### New or Affected Resource(s)

`oci_containerengine_node_pool`

### Potential Terraform Configuration

```hcl
resource "oci_containerengine_node_pool" "pool" {
  initialization_script = "blah blah blah"
}
```

**Comment by hyder** [comment]
All done here for you: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/docs/instructions.adoc#configuring-cloud-init-for-the-nodepools

**Comment by et304383** [comment]
@hyder thanks for this!  I highly recommend we include a link to these instructions in the Terraform provider docs for `oci_containerengine_node_pool`.

**Comment by et304383** [comment]
@hyder so digging through the code of that module, I discovered that one simply has to set node_metadata.user_data to pass in an initialization script.

This is a severe shortfall in documentation, and something Oracle really needs to work on with regards to the Terraform provider.  This isn't the first time a lack of documentation has burned me working with this provider.

**Comment by hyder** [comment]
@et304383 If you can provide further examples of the provider's insufficient documentation, I'll pass this to our documentation team.

**Comment by et304383** [comment]
@hyder this issue and I already created another issue for another documentation issue I came across.  Going forward, I will create tickets as I see the issues.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI.

If you are still experiencing this issue, please create a new issue and label it as Bug.
