### ISSUE TITLE
Destroy fails for oci_dns_resolver_endpoint forwarding endpoint

### ISSUE THREAD

**Issue by slevey** [oracle/terraform-provider-oci#1557]
Setup:

```
resource "oci_dns_resolver_endpoint" "dns_fwd" {
  is_forwarding      = true
  is_listening       = false
  name               = local.dns_fwd["name"]
  subnet_id          = local.dns_fwd["subnet"]
  resolver_id        = data.oci_dns_resolvers.resolver_list.resolvers[0].id
  scope              = "PRIVATE"
  forwarding_address = local.dns_fwd["address"]
  nsg_ids = []
}

resource "oci_dns_resolver" "resolver" {
  resolver_id = data.oci_dns_resolvers.resolver_list.resolvers[0].id
  scope       = "PRIVATE"

  # attached_views {
  #     view_id = oci_dns_view.test_view.id
  # }
  rules {
      action                 = "FORWARD"
      destination_addresses  = [var.local_oci_dns_listener]
      source_endpoint_name   = oci_dns_resolver_endpoint.dns_fwd.name
      qname_cover_conditions = []
  }

  lifecycle {
    ignore_changes = [
      resolver_id
    ]
  }
}
```

When triggering a destroy, the oci_dns_resolver is destroyed almost immediately (the provider can't / doesn't destroy the resource in OCI).  The oci_dns_resolver_endpoint is unable to be removed due to the existence of a rule in the oci_dns_resolver.

To destroy both resource, you must first update the oci_dns_resolver to remove any rules.  Performing an "apply" in order to perform a "destroy" is not ideal.

Can the destroy action of the oci_dns_resolver be updated to reset/remove the "rules"?

**Comment by ITD27M01** [comment]
@slevey 
Check this: https://github.com/oracle/terraform-provider-oci/issues/1240

**Comment by vsin12** [comment]
Fix for the issue has been released with terraform version https://registry.terraform.io/providers/oracle/oci/latest
