### ISSUE TITLE
Defined tags for OCI K8s node pool nodes are not being updated - new added tags are not being set

### ISSUE THREAD

**Issue by p4ulie** [oracle/terraform-provider-oci#1559]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
[0] % terraform -v                                                                                                                                                                     14335ms 
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/oci v4.69.0
```
### Affected Resource(s)

```hcl
Terraform will perform the following actions:

  # module.environment.module.k8s[0].oci_containerengine_node_pool.this will be updated in-place
  ~ resource "oci_containerengine_node_pool" "this" {
        id                  = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        name                = "k8s-nodepool-dev"
        # (14 unchanged attributes hidden)

      ~ node_config_details {
          ~ defined_tags                        = {
              + "DevOps.availability_zone" = "xxxxxxxxxx"
              + "DevOps.region"            = "xx"
                # (2 unchanged elements hidden)
            }
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Apply finishes sucessfully:

```
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
But next plan is the same, adding the tags again.

### Terraform Configuration Files

```hcl
resource "oci_containerengine_node_pool" "this" {
  #Required
  cluster_id         = oci_containerengine_cluster.this.id
  compartment_id     = var.compartment_id
  kubernetes_version = var.k8s_version
  name               = var.custom_cluster_name != null ? "${var.custom_cluster_name}-nodepool" : "k8s-nodepool-${var.environment}"
  node_shape         = var.instance_shape

  #Optional
  # initial_node_labels {

  #     #Optional
  #     key =
  #     value =
  # }

  node_config_details {
    #Required
    placement_configs {
      #Required
      availability_domain = var.availability_domains[0].name
      subnet_id           = var.subnet_id_k8s
    }
    size = var.node_count

    defined_tags = {
      "DevOps.Environment"       = var.environment
      "DevOps.Purpose"           = var.tag_purpose
      "DevOps.region"            = var.business_region
      "DevOps.availability_zone" = split(":", var.availability_domains[0].name)[1]
    }

    #Optional
    nsg_ids = [module.nsg_k8s_workers.id]
  }

  node_metadata = {
    user_data = data.cloudinit_config.k8s_node.rendered
  }

  node_shape_config {

    #Optional
    memory_in_gbs = var.instance_mem_gb
    ocpus         = var.instance_cpus
  }

  node_source_details {
    #Required
    image_id    = var.instance_image
    source_type = "IMAGE"

    #Optional
    boot_volume_size_in_gbs = var.instance_boot_volume_gb
  }

  ssh_public_key = var.ssh_public_key
}
```

### Debug Output

Relevant part of the debug output says:
```
2022-03-25T10:38:50.862+0100 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/oci\"]" produced an unexpected new value for module.environment.module.k8s[0].oci_containerengine_node_pool.this, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .node_config_details[0].defined_tags: element "DevOps.availability_zone" has vanished
      - .node_config_details[0].defined_tags: element "DevOps.region" has vanished
module.environment.module.k8s[0].oci_containerengine_node_pool.this: Modifications complete after 3s 
```
[Gist](https://gist.github.com/p4ulie/686a28f23310adce000f36b393262c03)

### Expected Behavior

Defined tags should be updated - new tags "DevOps.availability_zone" and "DevOps.region" should be set.

### Actual Behavior

Although no error is produced, defined tags are not being updated, "DevOps.availability_zone" and "DevOps.region" are not being set.
Subsequent runs of the Terraform show again the tags are planned to be added. (See "Affected Resource" section above, output is always the same)

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### Important Factoids

I can add one of the tags manually, then Terraform will try to add the second one, still unsuccessfully, so it does not seem to be issue with Oracle Cloud API.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
