### ISSUE TITLE
Use reserved public IP when creating instance

### ISSUE THREAD

**Issue by OscarB7** [oracle/terraform-provider-oci#1565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to use a reserved public IP for an instance to keep the same IP if the instance is re-created. I can create the reserved public IP with `resource "oci_core_public_ip"`. Now for the instance, the block `resource "oci_core_instance"` does not have an option to attach or associate the existing VNIC.
Is there another `resource` block to attach the existing VNIC to the instance? I see the opcion in the OCI web console as explained in this [article](https://docs.oracle.com/en/learn/reserved-pub-ip/index.html#unassign-reserved-public-ip)

### New or Affected Resource(s)

resource "oci_core_instance" could be modified to allow this option. Maybe a new resource to assign and unassign public ip.

### Potential Terraform Configuration

A new section that assign a VNIC. This would be the most basic since OCI allows more VNIC.

```hcl
resource "oci_core_instance" "test_instance" {
    ...
    assign_vnic_details {
        public_ip = oci_core_public_ip.test_public_ip.id
        ...
    }
    ...
}
```

**Comment by dhoogfr** [comment]
@OscarB7 

When reserving the public IP, you can assign it to a private IP (from the host).
So it works the other way around

example on how to attach a reserved public IP to the first private IP of a guest:

```
data "oci_core_private_ips" "bastion" {
  ip_address = oci_core_instance.bastion.private_ip
  subnet_id  = oci_core_subnet.bastion.id
}

resource "oci_core_public_ip" "bastion" {
  compartment_id = var.network_compartment_id != "" ? var.network_compartment_id : var.compartment_id
  display_name   = var.bastion_identifier != "" ? join("-", ["ip-bastion-pub", var.bastion_identifier]) : "ip-bastion-pub"
  lifetime       = "RESERVED"
  private_ip_id  = data.oci_core_private_ips.bastion.private_ips[0]["id"]

  defined_tags = var.defined_tags
}
```

**Comment by OscarB7** [comment]
thank you, @dhoogfr ! I appreciate it. I will try that

**Comment by dhoogfr** [comment]
@OscarB7
When I need to destroy the instance, I need to first change the oci_core_public_ip configuration to remove the private_ip_id relation.
After that the instance can be destroyed / recreated without destroying the reserved public IP.

To prevent accidental destruction you could try to add a lifecycle clause with "prevent_destroy = true" attribute to the oci_core_public_ip resource

```
resource "oci_core_public_ip" "bastion" {
  compartment_id = var.network_compartment_id != "" ? var.network_compartment_id : var.compartment_id
  display_name   = var.bastion_identifier != "" ? join("-", ["ip-bastion-pub", var.bastion_identifier]) : "ip-bastion-pub"
  lifetime       = "RESERVED"
  private_ip_id  = data.oci_core_private_ips.bastion.private_ips[0]["id"]

  defined_tags = var.defined_tags

  lifecycle {
    prevent_destroy = true
  }
}
```

But, I have not actually tried this myself.

**Comment by OscarB7** [comment]
Thank you very much @dhoogfr !

**Comment by brokedba** [comment]
> resource "oci_core_public_ip" "bastion" {
>   compartment_id = var.network_compartment_id != "" ? var.network_compartment_id : var.compartment_id
>   display_name   = var.bastion_identifier != "" ? join("-", ["ip-bastion-pub", var.bastion_identifier]) : "ip-bastion-pub"
>   lifetime       = "RESERVED"
>   private_ip_id  = data.oci_core_private_ips.bastion.private_ips[0]["id"]
> 
>   defined_tags = var.defined_tags
> 
>   lifecycle {
>     prevent_destroy = true
>   }
> }

I you apply and destroy 5 times ,  you will probably not reuse the public IP that you prevented from being destroyed. It will be a clutter of public IPs at the end .

**Comment by brokedba** [comment]
@dhoogfr , I can confirm that the destroy fails with prevent destroy clause .  
````
│ Error: Instance cannot be destroyed
│
│   on compute.tf line 91:
│   91: resource "oci_core_public_ip" "untrust_public_ip" {
│
│ Resource oci_core_public_ip.untrust_public_ip has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To
│ avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
````
I am going to open an enhancement issue
