### ISSUE TITLE
oci_core_instance -> create_vnic_details -> assign_public_ip does NOT default to false for private subnets with prohibit public IP set true, despite what documentation says

### ISSUE THREAD

**Issue by et304383** [oracle/terraform-provider-oci#1569]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

TF -> 1.17
OCI -> 4.70.0

### Affected Resource(s)

oci_core_instance

### Terraform Configuration Files

```hcl
#Subnet
resource "oci_core_subnet" "private" {
  cidr_block = local.private_subnet_cidr_block
  compartment_id = var.compartment_ocid
  display_name = "${var.env_name}-private-regional"
  dns_label = "private"
  prohibit_public_ip_on_vnic = "true"
  route_table_id = oci_core_route_table.private.id
  security_list_ids = [oci_core_security_list.private.id]
  vcn_id = oci_core_vcn.vcn.id
}

#Instance
resource "oci_core_instance" "mon" {
  availability_domain = var.availability_domains[2]
  compartment_id = var.compartment_ocid
  shape = var.common_config["shape"]
  create_vnic_details {
    display_name = "${var.env_name}-mon"
    subnet_id = oci_core_subnet.private.id
  }
  display_name = "${var.env_name}-mon"

  metadata = {
    ssh_authorized_keys = file(var.public_key_file)
  }

  shape_config {
    ocpus = var.common_config["ocpus"]
    memory_in_gbs = var.common_config["memory"]
  }
  source_details {
    source_id = data.oci_core_images.centos_images.images[0].id
    source_type = "image"
    boot_volume_size_in_gbs = var.common_config["boot_disk"]
  }
}
```

### Expected Behavior

As per the docs, it should have worked with assign_public_ip defaulting to false.

### Actual Behavior

Fails with error:

```

Error: Work Request error
Provider version: 4.70.0, released on 2022-04-07.
Service: Core Instance
Error Message: work request did not succeed, workId: <OCID>, entity: instance, action: CREATED. Message: A problem occurred while preparing the instance's VNIC.  (Public IP addresses are prohibited in this subnet {<OCID>})
Resource OCID: <OCID>
Suggestion: Please retry or contact support for help with service: Core Instance

```

### Important Factoids
Running in resource manager.

The TF plan even shows that it's setting the value to true:

```
      + create_vnic_details {
          + assign_public_ip       = "true"
```

**Comment by et304383** [comment]
lol @ closing an issue with a guess that it might be fixed and placing the burden on the community to do your backlog grooming for you.

**Comment by teliov** [comment]
Using the provider version from `2024-03-13`, this issue still persists. `assign_public_ip` defaults to "true" always as opposed to null - which I imagine will then allow the documented logic to kick in
