### ISSUE TITLE
Plan error in provider 4.70.0 with enable_management in oci_database_cloud_database_management resource

### ISSUE THREAD

**Issue by rnmakino** [oracle/terraform-provider-oci#1572]
Hi,

I'm getting an error after update to provider 4.70.0 with enable_management in oci_database_cloud_database_management resource, downgrading to 4.69.0 works well.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.1.8
Provider 4.70.0

### Affected Resource(s)

oci_database_cloud_database_management 

### Terraform Configuration Files

```hcl
resource "oci_database_cloud_database_management" "cloud_database_management" {
  database_id           = var.database_id
  management_type       = var.database_cloud_database_management_details_management_type[0]
  private_end_point_id  = oci_database_management_db_management_private_endpoint.db_management_private_endpoint.id
  service_name          = var.database_cloud_database_management_details_service_name
  credentialdetails {
    user_name           = var.database_cloud_database_management_details_user_name
    password_secret_id  = var.oracle_enterprise_secret_id
  }
  enable_management     = var.database_cloud_database_management_details_enable_management
}
```

### Expected Behavior

Plan run without errors.

### Actual Behavior

Terraform v1.1.8
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...

│ Error: Value for unconfigurable attribute
│ 
│   with module.oracle_db_enterprise.oci_database_cloud_database_management.cloud_database_management,
│   on modules/oracle_db_enterprise/database_management.tf line 10, in resource "oci_database_cloud_database_management" "cloud_database_management":
│   10:   enable_management     = var.database_cloud_database_management_details_enable_management
│ 
│ Can't configure a value for "enable_management": its value will be decided
│ automatically based on the result of applying this configuration.

**Comment by rashik-bhasin** [comment]
This was fixed as part of v4.86.0. Please try using the latest provider. Thanks!
