### ISSUE TITLE
data read no longer seems to wait until resource info is available in different region

### ISSUE THREAD

**Issue by dhoogfr** [oracle/terraform-provider-oci#1604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

```### Terraform Version and Provider Version
Terraform v1.2.1
on linux_amd64
+ provider registry.terraform.io/oracle/oci v4.77.0
```

### Affected Resource(s)

oci_identity_compartment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Expected Behavior
Some resources are not bound to a region and need always to be created in the home region (eg compartments).
When you need to use those resources in a different region, there can be a delay before the information for those resources are replicated, causing the creation of the depended resource to fail.

To work around this, I use a data source to retrieve the information instead of referencing the resource directly.
As the data source would wait until the information was known by the target region.

eg

```hcl
data "oci_identity_compartment" "network" {
  id = oci_identity_compartment.network.id
}

resource "oci_core_vcn" "this" {
  cidr_blocks    = var.cidr_blocks
  compartment_id = data.oci_identity_compartment.network.id
  display_name   = "vcn2"
  dns_label      = "vcn2"

  defined_tags = var.env_default_tags
}
```

### Actual Behavior

With the current version, the data source no longer waits and the creation of the dependent resource fails

```
...
oci_identity_compartment.network: Still creating... [10s elapsed]
oci_identity_compartment.network: Still creating... [20s elapsed]
oci_identity_compartment.network: Still creating... [30s elapsed]
oci_identity_compartment.network: Still creating... [40s elapsed]
oci_identity_compartment.network: Still creating... [50s elapsed]
oci_identity_compartment.network: Creation complete after 57s [id=ocid1.compartment.oc1..aaaaaaaaXXXXXXx5iofek5gcjrnb6q]
data.oci_identity_compartment.network: Reading...
data.oci_identity_compartment.network: Read complete after 0s
╷
│ Error: Missing required argument
│ 
│   with oci_core_vcn.this,
│   on network_general.tf line 5, in resource "oci_core_vcn" "this":
│    5:   compartment_id = data.oci_identity_compartment.network.id
│ 
│ The argument "compartment_id" is required, but no definition was found.
╵
```

Applying the same configuration again succeeds

### Steps to Reproduce

1. `terraform apply`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by aabulbul** [comment]
Please allow sometime between creation and reading for compartments by using [time_sleep](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) terraform resource utility: 

```typescript
resource "oci_identity_compartment" "network" {
# Usual arguments
}

resource "time_sleep" "wait_1_minute" {
  depends_on = [oci_identity_compartment.network]

  create_duration = "1m"
}

# This resource will create (at least) 1 minute after oci_identity_compartment.network
data "oci_identity_compartment" "network" {
  id = oci_identity_compartment.network.id
  depends_on = [time_sleep.wait_1_minute]
}

**Comment by becky-intelletive** [comment]
Is using time_sleep the officially-recommended solution to this problem?

**Comment by becky-intelletive** [comment]
Related:
https://github.com/oracle/terraform-provider-oci/issues/2065
