### ISSUE TITLE
oci_cloud_guard_security_zone stays permanently out of sync - system_tags

### ISSUE THREAD

**Issue by chrisbulgaria** [oracle/terraform-provider-oci#1612]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

4.79
### Affected Resource(s)

oci_cloud_guard_security_zone 

### Terraform Configuration Files
resource "oci_cloud_guard_security_zone" "test_security_zone" {
    compartment_id = oci_identity_compartment.parent_compartment.id
    display_name = "Main security zone"
    security_zone_recipe_id = "ocid1.securityzonessecurityrecipe.oc1..xxx" 

     lifecycle {
    ignore_changes = [
      system_tags,
    ]
  }
}

### Debug Output

 oci_cloud_guard_security_zone.test_security_zone will be updated in-place
  ~ resource "oci_cloud_guard_security_zone" "test_security_zone" {
        id                        = "ocid1.securityzonessecurityzone.oc1..xxx"
      + system_tags               = (known after apply)
        # (12 unchanged attributes hidden)
    }

Appears to be similar like #1536 , just on another resource

**Comment by chrisbulgaria** [comment]
This is fixed in the latest release , thanks !

**Comment by chrisbulgaria** [comment]
Sorry was supposed to be fixed in 4.88 but doesnt work in 4.89 ( see below)   - reopening


terraform will perform the following actions:
  # module.code.oci_cloud_guard_security_zone.test_security_zone will be updated in-place
  ~ resource "oci_cloud_guard_security_zone" "test_security_zone" {
        id                        = "ocid1.securityzonessecurityzone.oc1..xxxxx"
      + system_tags               = (known after apply)
        # (12 unchanged attributes hidden)
    }

**Comment by chrisbulgaria** [comment]
btw - in case anyone is interested - the same issue exists as well in oci_cloud_guard_security_recipe  . And its still there in 4.100.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by rramge** [comment]
This issue still exists in provider version 4.121.0

**Comment by ravinitp** [comment]
Issue is resolved in v4.122.0.
