### ISSUE TITLE
db_backup_config Not working as expected with a source

### ISSUE THREAD

**Issue by JonathanManass** [oracle/terraform-provider-oci#1616]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Provider version: 4.79.0
Terraform version: v1.1.2

### Affected Resource(s)

affected_resources = oci_database_db_system

### Terraform Configuration Files

```hcl
resource oci_database_db_system database {
    db_home {
        database {
            backup_id = "ocid............."
            db_backup_config {
               auto_backup_enabled       = true
               recovery_window_in_days = "true"
            }
        }
    }
    source = "DB_BACKUP"
}
```

### Expected Behavior

Database automated backups should be configured when first applying the database, even if the source is a database backup (of a database where backups are themselves enabled).

### Actual Behavior

The backups are not enabled on the first terraform apply, but are enabled when rerunning the terraform apply.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We observed the affected resources are not provided in the description or it's incorrect. We request you to add it in issue description as mentioned in below format.
Example: affected_resources = oci_core_instance , oci_core_instances
 
If it's not related to any particular resource then mention affected resource as terraform.
Example: affected_resources = terraform
 
As this works through automation, request you to follow exact syntax.

**Comment by JonathanManass** [comment]
Hi @ravinitp, could the issue not be on the side of the automation?
I'm not quite sure how to write it as oci_database_db_system is the name of a terraform ressource :
https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_db_system
