### ISSUE TITLE
environment variable TF_VAR_private_key_password is not working

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
terraform {
  required_version = "~> 1.2.3"

  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 4.84.0"
    }
  }
}
```

### Affected Resource(s)

All resources. This is related to terraform oci provider authentication to OCI

### Terraform Configuration Files

```hcl
environment variables:
export TF_VAR_tenancy_ocid="ocid1.tenancy.oc1.."
export TF_VAR_user_ocid="ocid1.user.oc1.."
export TF_VAR_fingerprint="73:5b:df:01:XX:XX:XX"
export TF_VAR_private_key_path="~/.oci/mykey.pem"
export TF_VAR_private_key_password="mypasssword" <---- This is NOT working



test.tf

data "oci_identity_compartments" "test_compartments" {
  #Required
  compartment_id = var.compartment_id
}




```

### Expected Behavior

the TF_VAR_private_key_password environment variable should work

### Actual Behavior

TF_VAR_private_key_password does NOT work with Error: 401-NotAuthenticated, The required information to complete authentication was not provided or was incorrect. Instead, put private_key_password in provider block as below works
```hcl

provider.tf

provider "oci" {
   private_key_password = "mypassword"
}
```

### Steps to Reproduce

```
1. put any test code, such as test.tf as below and run "terraform plan"
```hcl
data "oci_identity_compartments" "test_compartments" {
  #Required
  compartment_id = var.compartment_id
}
```
2. export environment variables:
export TF_VAR_tenancy_ocid="ocid1.tenancy.oc1.."
export TF_VAR_user_ocid="ocid1.user.oc1.."
export TF_VAR_fingerprint="73:5b:df:01:XX:XX:XX"
export TF_VAR_private_key_path="~/.oci/mykey.pem"
export TF_VAR_private_key_password="mypasssword" <---- This is NOT working and gives 401-NotAuthenticated error.

3. create provider.tf as below and run terraform plan, it will work
```
provider "oci" {
   private_key_password = "mypassword"
}
```

**Comment by NagendraNigade** [comment]
Hi,
As per the Hashicorp documentation, Direct fetch of env variable even without declaring it, is limited to required parameters of provider block.

`Terraform configuration file [provider blocks](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformconfig.htm#terraformconfig_topic_Configuration_File_Requirements_Provider) can be completely removed if all [API Key Authentication](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformproviderconfiguration.htm#APIKeyAuth) required values are provided as environment variables`

https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformproviderconfiguration.htm#environmentVariables__settingenvironmentvariablesinlinux

If we want to use `private_key_password` then we have to defined it as variable to get it fetched from the env variable.

> variable "private_key_password" {}
> 
> provider "oci" {
>    private_key_password = "${var.private_key_password}"
> }

If you use `private_key_path` without `passphrase` then you can completely remove the provider block.

Thanks.
