### ISSUE TITLE
New resource to create a FastConnect Connections

### ISSUE THREAD

**Issue by rjouhann** [oracle/terraform-provider-oci#1653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a new resource to create a FastConnect Connections in Oracle Cloud Infrastructure Core service.

FastConnect is a connection between a customer's on-premises network and Oracle Cloud Infrastructure over a private physical network instead of the internet.

Support both FastConnect Partner or FastConnect Direct.

### References

- https://docs.oracle.com/en-us/iaas/Content/Network/Concepts/fastconnect.htm
- https://docs.packetfabric.com/cloud/oracle/hosted/create/
- https://registry.terraform.io/providers/PacketFabric/packetfabric

**Comment by chrisbulgaria** [comment]
This should maybe cover at least a good part of what is needed ? https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_virtual_circuit

**Comment by rjouhann** [comment]
@chrisbulgaria thanks for the pointer! I was able to use this resource to create my FastConnect connection in Oracle Cloud.
