### ISSUE TITLE
New resource to create a Dynamic Routing Gateways (DRGs)

### ISSUE THREAD

**Issue by rjouhann** [oracle/terraform-provider-oci#1654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a new resource to create a Dynamic Routing Gateways (DRGs) in Oracle Cloud Infrastructure Core service.

A DRG is a virtual router to which you can attach the following resources:

- [VCNs](https://docs.oracle.com/en-us/iaas/Content/Network/Tasks/managingVCNs.htm#VCNs_and_Subnets)
- [Remote Peering Connections](https://docs.oracle.com/en-us/iaas/Content/Network/Tasks/remoteVCNpeering.htm#Remote_VCN_Peering_Across_Regions)
- Site-to-Site VPN [IPSec tunnels](https://docs.oracle.com/en-us/iaas/Content/Network/Tasks/managingIPsec.htm#VPN_Connect)
- Oracle Cloud Infrastructure FastConnect [virtual circuits](https://docs.oracle.com/en-us/iaas/Content/Network/Concepts/fastconnect.htm#FastConnect)

This will enable full automation & management via terraform of a FastConnect Connection (see other RFE open [here](https://github.com/oracle/terraform-provider-oci/issues/1653))

### References

- https://docs.oracle.com/en-us/iaas/Content/Network/Tasks/managingDRGs.htm
- https://docs.packetfabric.com/cloud/oracle/hosted/create/
- https://registry.terraform.io/providers/PacketFabric/packetfabric

**Comment by chrisbulgaria** [comment]
Maybe I'm stupid ... but doesn't that exist already ? https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_drg

**Comment by rjouhann** [comment]
Thanks @chrisbulgaria i just didn't find it originally, didn't look for `drg` in `core`. I will give it a try!!

**Comment by hyder** [comment]
We have a reusable module for DRG here: https://github.com/oracle-terraform-modules/terraform-oci-drg
