### ISSUE TITLE
https://www.terraform.io/docs/providers/oci/index.html goes to broken link, needs to be updated

### ISSUE THREAD

**Issue by rodrigc** [oracle/terraform-provider-oci#1706]
The following link:

https://www.terraform.io/docs/providers/oci/index.html

redirects to:

https://registry.terraform.io/providers/hashicorp/oci/latest/docs

which is a broken link.

The fix should be:

https://registry.terraform.io/providers/hashicorp/oci/latest/docs

should redirect to:

https://registry.terraform.io/providers/oracle/oci/latest/docs

**Comment by rodrigc** [comment]
This link is at the bottom of this page:
https://github.com/oracle/terraform-provider-oci#developing-the-provider

It would be good to fix this link, because it is referred to all over the Terraform OCI Provider documentation

**Comment by rodrigc** [comment]
So it looks like on this line:

https://github.com/hashicorp/terraform-website/blob/fdc6edc02b29425993fac59e30fd31f5ec52565b/redirects.next.js#L76

redirects.next.js needs to be changed

**Comment by rodrigc** [comment]
I submitted this fix to the terraform web site:
https://github.com/hashicorp/terraform-website/pull/2437

**Comment by vsin12** [comment]
this is fixed.
