### ISSUE TITLE
 An argument named "xxx" is not expected here. Terraform module

### ISSUE THREAD

**Issue by maykonrds** [oracle/terraform-provider-oci#1717]
Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/oci v4.100.0
+ provider registry.terraform.io/oracle/oci v4.100.0

File Structure: 
├── main.tf
├── provider.tf
├── .terraform
│   ├── modules
│   │   ├── modules.json
│   │   ├── object_storage
│   │   │   ├── main.tf
│   │   │   └── variables.tf
│   │   ├── oci_network_lb
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   └── vcn
│   │       ├── CHANGELOG.adoc
│   │       ├── CONTRIBUTING.adoc
│   │       ├── CONTRIBUTORS.adoc
│   │       ├── docs
│   │       ├── examples
│   │       ├── .git
│   │       ├── .github
│   │       ├── .gitignore
│   │       ├── LICENSE
│   │       ├── locals.tf
│   │       ├── modules
│   │       ├── outputs.tf
│   │       ├── README.adoc
│   │       ├── README.md
│   │       ├── schema.yaml
│   │       ├── terraform.tfvars.example
│   │       ├── variables.tf
│   │       ├── vcn_defaultresources.tf
│   │       ├── vcn_gateways.tf
│   │       ├── vcn.tf
│   │       └── versions.tf
│   └── providers
│       └── registry.terraform.io
│           ├── hashicorp
│           └── oracle
├── .terraform.lock.hcl
├── terraform.tfstate
├── terraform.tfstate.backup
└── variables.tf
-------------
main.tf on the root module:

module "vcn" {
  source  = "oracle-terraform-modules/vcn/oci" 
  version = "3.5.0"
  compartment_id = var.compartment_id
  vcn_cidrs      = var.vcn_cidrs
  vcn_dns_label  = var.vcn_dns_label 
  vcn_name       = var.vcn_name
  subnets = {
  sub1 = {name = "subnet1",cidr_block = "10.0.4.0/24"}
  sub2 = {cidr_block="10.0.5.0/24",type="private"}   
  }
  create_nat_gateway = true
}

module "object_storage" {
  source = "./.terraform/modules/object_storage"
  compartment_id = var.compartment_id  
  name = var.bucket_name
  namespace = var.bucket_namespace
}

I have the variables.tf on the root module with the values.
When I try to run terraform plan I got this:
Error: Unsupported argument
│ 
│   on main.tf line 27, in module "object_storage":
│   27:   name = var.bucket_name
│ 
│ An argument named "name" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 28, in module "object_storage":
│   28:   namespace = var.bucket_namespace
│ 
│ An argument named "namespace" is not expected here.

Looks like when I have a module that the source is a local file system the variables on the root modules do not pass to the child module.
The module "vcn" is working fine the issue is with object_storage module.

**Comment by rramge** [comment]
This is not a provider issue. Your object_storage module is broken. The variables "name" and "namespace" are not declared as variables in the module and, as a result, not expected.

**Comment by rramge** [comment]
No you don't. Just read and understand your code.
You declare the variables "bucket_name" and "bucket_namespace" in the module, but in main.tf lines 27 and 28 you try to assign the values to the undeclared "name" and "namespace" (without bucket_ prefix) instead.

**Comment by maykonrds** [comment]
> No you don't. Just read and understand your code. You declare the variables "bucket_name" and "bucket_namespace" in the module, but in main.tf lines 27 and 28 you try to assign the values to the undeclared "name" and "namespace" (without bucket_ prefix) instead.

I got it. I understand what my mistake was, I was confused about the values on resource parameters and variable names, now I am good, and I will close the issue. tks.
