### ISSUE TITLE
Cannot update public IP assigned to an entity of type NAT_GATEWAY

### ISSUE THREAD

**Issue by rhiser** [oracle/terraform-provider-oci#1738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Brief Description of error
I have a terraform module that creates a number of networking bits. I recently ran into a bug where I want to add/update/delete a set of `freeform_tags` for my resources. 

This issue specifically occurred when I created a `oci_core_public_ip` with a set of `freeform_tags` and then I updated those tags to include more. 

### Terraform Version and Provider Version

```
Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.48.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/oracle/oci v4.102.0
```

### Affected Resource(s)

`oci_core_public_ip`

### Terraform Configuration Files

**These are not all the resources included in my configuration**

```hcl
resource "oci_core_nat_gateway" "vcn" {
  compartment_id = local.compartment[var.environment.env]
  display_name   = local.name
  freeform_tags  = local.tags
  public_ip_id   = oci_core_public_ip.nat.id
  vcn_id         = oci_core_vcn.vcn.id
}

resource "oci_core_public_ip" "nat" {
  compartment_id = local.compartment[var.environment.env]
  lifetime       = var.vcn.public_ip_lifetime
  display_name   = "${local.name}-nat"
  freeform_tags  = local.tags
}

resource "oci_core_vcn" "vcn" {
  cidr_blocks    = [var.vcn.cidr]
  compartment_id = local.compartment[var.environment.env]
  display_name   = local.name
  dns_label      = local.dns_label
  freeform_tags  = local.tags
  is_ipv6enabled = false

  timeouts {}
}
```

### Debug Output

```hcl

│ Error: 404-NotAuthorizedOrNotFound, Cannot update public IP assigned to an entity of type NAT_GATEWAY
│ Suggestion: Either the resource has been deleted or service Core Public Ip need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_public_ip
│ API Reference: https://docs.oracle.com/iaas/api/#/en/iaas/20160918/PublicIp/UpdatePublicIp
│ Request Target: PUT https://iaas.us-ashburn-1.oraclecloud.com/20160918/publicIps/foo
│ Provider version: 4.102.0, released on 2022-12-14. This provider is 1 Update(s) behind to current.
│ Service: Core Public Ip
│ Operation Name: UpdatePublicIp
│ OPC request ID: x
│
│
│   with module.vcn.oci_core_public_ip.nat,
│   on .terraform/modules/vcn/nat-gateway.tf line 9, in resource "oci_core_public_ip" "nat":
│    9: resource "oci_core_public_ip" "nat" {
│
╵
Releasing state lock. This may take a few moments...
```

### Expected Behavior

Should be able to update tags for a reserved public ip even if reserved ip is in use

### Actual Behavior

Can't update tags for reserved public ip

### Steps to Reproduce

1. create the `oci_core_public_ip` resource without any tags and assign to `oci_core_nat_gateway` resource
2. update `oci_core_public_ip` resource to use `freeform_tags` attribute
3. running `terraform plan` will show expected output but `terraform apply` will fail

### Important Factoids

Nope, pretty straight forward configuration

**Comment by niskulka71** [comment]
Please open a ticket with OCI customer support. Please make sure to include the opc-request-id of the failed request.
