### ISSUE TITLE
Stack Monitoring documentation page shows a merge conflict ;o)

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1747]
affected_resources = stack_monitoring_discovery_job

See here

https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/stack_monitoring_discovery_job

![image](https://user-images.githubusercontent.com/590333/211177189-5b954592-60b0-47c3-bd89-cb9ae923b948.png)

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We observed the affected resources are not provided in the description or it's incorrect. We request you to add it in issue description as mentioned in below format.
Example: affected_resources = oci_core_instance , oci_core_instances
 
If it's not related to any particular resource then mention affected resource as terraform.
Example: affected_resources = terraform
 
As this works through automation, request you to follow exact syntax.

**Comment by jeliker** [comment]
See where I've added affected_resources following the pattern you provided. Note you may want to update your "bug" template to reflect that requirement if it is, as you imply, essential.

**Comment by jeliker** [comment]
Documentation has been corrected

**Comment by jeliker** [comment]
Documentation has been corrected
