### ISSUE TITLE
The provider oracle/oci does not support resource type "oci_marketplace_listing_package_agreement".

### ISSUE THREAD

**Issue by pezinek** [oracle/terraform-provider-oci#1766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Using oracle/oci v4.108.0

### Affected Resource(s)

resource oci_marketplace_listing_package_agreement

### Terraform Configuration Files

https://pastebin.com/w37JR8Yt

### Expected Behavior

VM from marketplace gets provisioned, the same way as it was in version v.4.107.0
Or there is a clear note in the release notes that a breaking change has been introduced

### Actual Behavior

Terraform fails like this:
```
│ Error: Invalid resource type
│ 
│   on ../oci_marketplace_host/marketplace.tf line 12, in resource "oci_marketplace_listing_package_agreement" "test_listing_package_agreement":
│   12: resource "oci_marketplace_listing_package_agreement" "test_listing_package_agreement" {
│ 
│ The provider oracle/oci does not support resource type
│ "oci_marketplace_listing_package_agreement".
│ 
│ Did you intend to use the data source
│ "oci_marketplace_listing_package_agreement"? If so, declare this using a
│ "data" block instead of a "resource" block.
```

as well the release notes for v4.108.0 is kind of truncated and doesn't contain any mention about any breaking change affecting resource "oci_marketplace_listing_package_agreement"

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It started to fail on 2023-02-15 (which corresponds with the release v4.108.0)

**Comment by pezinek** [comment]
Seems that the solution to this is to change the "resource" to "data" like this:

https://github.com/oracle/terraform-provider-oci/commit/29bd8bc9c8c8635ea1921a255b4179835e450472?diff=split#diff-088f324e7df6ecf6a0cda838a79a24c8b9c236e8cca03fd715e51b42e0744705

**Comment by marcransome** [comment]
I don't think this should be classified as a bug as such, but rather a breaking change. This required some manual intervention to prune resources from Terraform state (i.e.`terraform state rm ...`) as well as switching to the `data` resource in code to resolve. Whether changes like this should necessitate a major version bump—as a _breaking_ change—could be debated, but regardless, some visibility of changes like this in future release notes would certainly help.

As an aside, it never really made sense as a `resource` as such, so a `data` resource certainly makes more sense from a functional point of view. It also led to the discover of an [inaccuracy in the documentation](https://github.com/oracle/terraform-provider-oci/pull/1769) related to this resource.

**Comment by marcransome** [comment]
The reversion in https://github.com/oracle/terraform-provider-oci/commit/ab5dc630935e3a23890bb5829e1e184615fb6086 has addressed this a a bug. Are there any plans to switch back  to a `resource` in a future provider release?

**Comment by pezinek** [comment]
@MeharwadeDivya @Priyanka : would you mind to explain what was going on with oci_marketplace_listing_package_agreement in v4.108.0 and what are the future plans ?
Will it stay "resource" or are you planning to change it back to "data" in the future again ?

**Comment by sklett-oci** [comment]
The issue was identified internally around the time of this posting, and was rolled back. The bug has been resolved and @pezinek  should not see this error anymore

**Comment by ravinitp** [comment]
As mentioned by @sklett-oci , Issue is resolved in latest provider. Therefore please upgrade the provider version and retry. Closing this issue now. Please reopen if issue still persist.
