### ISSUE TITLE
Problem when using output value from network_firewall_policy module with a network_firewall module

### ISSUE THREAD

**Issue by kanne09** [oracle/terraform-provider-oci#1772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/oracle/oci v4.105.0
```

### Affected Resource(s)
`oci_network_firewall_network_firewall`

### Terraform Configuration Files

```hcl
(local.net_firewall_name3) = {
      compartment_id             = local.security_compartment_id
      display_name               = local.net_firewall_name3
      network_firewall_policy_id = module.lz_network-firewall-policy["firewall_policy"].emna-euzrh-hub-east-west-front-fpl.id
      network_security_group_ids = []
      firewall_subnet_id         = "xxxxx"
      defined_tags   = local.buckets_defined_tags
      freeform_tags  = local.buckets_freeform_tags
    },
```

### Expected Behavior

When I do my terraform apply the firewall module is supposed to read this output value from the oci_network_firewall_network_firewall_policy module which is written like this
```hcl
output "firewall_policy" {
    description = "firewall policy ocid"
    value = { for v in oci_network_firewall_network_firewall_policy.firewall-policy : v.display_name => { id = v.id } }
}
```
And then it should use that output value here with the oci_network_firewall_network_firewall module
```hcl
network_firewall_policy_id = module.lz_network-firewall-policy["firewall_policy"].emna-euzrh-hub-east-west-front-fpl.id
```

### Actual Behavior

When I do the apply it returns this error

```hcl
 Error: Configuration contains unknown value
│
│ configuration for module.lz_network-firewall.oci_network_firewall_network_firewall.these["emna-euzrh-hub-east-west-front-fw"] still contains unknown values during apply (this is a bug in Terraform; please
│ report it!)
│ The following paths in the resource configuration are unknown:
│ cty.Path{cty.GetAttrStep{Name:"network_firewall_policy_id"}}

```
After this apply if I do a second apply without changing anything it does create the firewall associated with the firewall policy created in the first apply without any issues. But I would like to be able to do it in one apply.

### Steps to Reproduce

1. ` terraform apply -var-file=euzrh-global-hub-landing-lab.tfvars`

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by niteverm** [comment]
@kanne09 Based on the little limited informaiton you provided in the files, I can suggest to use the following appraoch to create a firewall and policy together. Please modify based on your variables.

network_firewall.tf
`
module "network_firewall_policy" {
    source = "./policies"
}

resource "oci_network_firewall_network_firewall" "network_firewall_1" {
    depends_on = [
        module.network_firewall_policy
    ]
    compartment_id = <redacted>
    display_name = "network_firewall_test"
    network_firewall_policy_id = "${module.network_firewall_policy.network_firewall_policy_id}"
    subnet_id = <redacted>
}
`

policies/network_firewall_policy.tf file:

`
output "network_firewall_policy_id" {
    description = "firewall policy ocid"
    value = "${oci_network_firewall_network_firewall_policy.policy_1.id}"
}

resource "oci_network_firewall_network_firewall_policy" "policy_1" {
    compartment_id = <redacted>
    display_name = "network_firewall_policy_test"
}
`
