### ISSUE TITLE
-filter flag for export is not documented

### ISSUE THREAD

**Issue by ITD27M01** [oracle/terraform-provider-oci#1778]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
> terraform version
Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/oracle/oci v4.109.0

Your version of Terraform is out of date! The latest version
is 1.3.9. You can update by downloading from https://www.terraform.io/downloads.html
> terraform providers

Providers required by configuration:
.
└── provider[registry.terraform.io/oracle/oci] ~> 4.0
```

### Affected Resource(s)

affected_resources = terraform

### Expected Behavior

There is no any documentation for -filter flag of `export` command. Only source code is available:

https://github.com/oracle/terraform-provider-oci/blob/master/internal/commonexport/export_filter_parser.go#L14
https://github.com/oracle/terraform-provider-oci/blob/master/internal/commonexport/export_filters.go#L13
### Actual Behavior

No any documentation for -filter flag of `export` command.

### Steps to Reproduce

1. `terraform-provider-oci -help`

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We observed the affected resources are not provided in the description or it's incorrect. We request you to add it in issue description as mentioned in below format.
Example: affected_resources = oci_core_instance , oci_core_instances
 
If it's not related to any particular resource then mention affected resource as terraform.
Example: affected_resources = terraform
 
As this works through automation, request you to follow exact syntax.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by jotruon** [comment]
Hi @ITD27M01 , here is the document for filter tag https://registry.terraform.io/providers/oracle/oci/latest/docs/guides/resource_discovery#filtering-resources-discovered-via-resource-discovery
