### ISSUE TITLE
How to set ipv6 in oci_core_ipsec_connection_tunnel_management

### ISSUE THREAD

**Issue by draemi** [oracle/terraform-provider-oci#1787]
I'm trying to use ipv6 for creating an ipsec tunnel and cannot figure out how to set below parameters for **bgp_session_info** in resource **oci_core_ipsec_connection_tunnel_management** ?

- **customer_interface_ipv6** and
- **oracle_interface_ipv6**  

https://registry.terraform.io/providers/oracle/oci/latest/docs/data-sources/core_ipsec_connection_tunnels#ipsecconnectiontunnel-reference

I got an error "Unsupported argument" when trying to set them, it seems they cannot be added in resource? If that is the case, how can I set ipv6 for ipsec tunnel?
`An argument named "customer_interface_ipv6" is not expected here`

Thanks!

**Comment by iejones** [comment]
A bug fix to add customer_interface_ipv6 and oracle_interface_ipv6 will be released on November 15th, 2023

**Comment by iejones** [comment]
This fix was released with version [v5.21.0](https://github.com/oracle/terraform-provider-oci/releases/tag/v5.21.0). See customer_interface_ipv6 and oracle_interface_ipv6 in the [documentation](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_ipsec_connection_tunnel_management) and the [example](https://github.com/oracle/terraform-provider-oci/blob/v5.21.0/examples/networking/ipsec_connections/ipsec_connection.tf#L94).
