### ISSUE TITLE
Unable to create instance with bootVolume

### ISSUE THREAD

**Issue by peruchi** [oracle/terraform-provider-oci#1803]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v1.3.9 on windows_amd64
provider registry.terraform.io/hashicorp/oci v4.111.0

### Affected Resource(s)
oci_core_instance

### Terraform Configuration Files

```hcl
resource "oci_core_instance" "restore-vm" {
    display_name = "restore-vm"        
    availability_domain = var.availability_domain
    compartment_id = var.compartment
    shape = var.shape
    source_details {
      source_id = var.boot_volume_ocid
      source_type = "bootVolume"  
    }
    shape_config {
        ocpus = "1"
        memory_in_gbs = "2"
    }
    create_vnic_details {
      assign_public_ip = false
      subnet_id = var.subnet
      private_ip = "10.0.0.20"
      assign_private_dns_record = false
      skip_source_dest_check = true
    }
    metadata = {
      ssh_authorized_keys = file(var.ssh_authorized_pub_keys)
    }    
}
```

### Expected Behavior
Create an instance based on an existing Boot Volume, as shown in the source_details parameter.
_Through the Oracle panel, it is possible to create the instance._

### Actual Behavior
Even though terraform plan worked, terraform apply failed (see error below) with error: **400-CannotParseRequest, Incorrectly formatted request**

Error: 400-CannotParseRequest, Incorrectly formatted request. Please refer to our documentation for help.
│ Suggestion: Please retry or contact support for help with service: Core Instance
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance
│ API Reference: https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/LaunchInstance
│ Provider version: 4.111.0, released on 2023-03-08.
│ Service: Core Instance
│ Operation Name: LaunchInstance
│ OPC request ID: 348ed80dae0c5244be06cd4122319539/E398BFC4C34D7B8B167576DAABEDA569/5531B908FF17D562EC0585327B00CF77
│
│   with oci_core_instance.restore-vm,
│   on restorevm.tf line 1, in resource "oci_core_instance" "restore-vm":
│    1: resource "oci_core_instance" "restore-vm" {

### Steps to Reproduce

1. Create a Boot Volume Replicated to Another Region
2. Activate Boot Volume in another region
3. Copy OCID from Activated Boot Volume
4. Run the terraform command: `terraform apply`

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by dennis-mac-oracle** [comment]
Can I get a recent OPC request ID along with a region/availability domain?

**Comment by peruchi** [comment]
@dennis-mac-oracle 

Error: 400-CannotParseRequest, Incorrectly formatted request. Please refer to our documentation for help.
│ Suggestion: Please retry or contact support for help with service: Core Instance
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance
│ API Reference: https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/LaunchInstance
│ Request Target: POST https://iaas.sa-vinhedo-1.oraclecloud.com/20160918/instances
│ Provider version: 4.117.0, released on 2023-04-20.
│ Service: Core Instance
│ Operation Name: LaunchInstance
│ OPC request ID: 58423db3e0ac44153efa668ca9e665d2/6869645A321DA9824F832E75CAE9560E/11E0B7E38A920E1237A3AD11798DC40D
│
│
│   with oci_core_instance.nginx-restore-vd,
│   on restorevm.tf line 1, in resource "oci_core_instance" "restore-vm":
│    1: resource "oci_core_instance" "restore-vm" {
│

**Comment by peruchi** [comment]
@dennis-mac-oracle This compartment exists in SAOPAULO

![image](https://user-images.githubusercontent.com/11572645/233088684-c42129b5-37d0-46eb-96b3-d7f9d0081e66.png)

or am i looking in the wrong place?

**Comment by peruchi** [comment]
thank you very much for your help, it worked.
