### ISSUE TITLE
oci_cloud_guard_data_source cannot be set to "ENABLED"

### ISSUE THREAD

**Issue by chrisbulgaria** [oracle/terraform-provider-oci#1804]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
4.111
### Affected Resource(s)

oci_cloud_guard_data_source 

### Expected Behavior

the API (in UpdateDataSource) support the data source to be ENABLED. This is currently impossible with terraform.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by Aaron1284** [comment]
Hi, 
To debug the issue, we might want to have a look at your terraform configuration.
Also, it would be great if you can share some more details about the error and config.
Maybe share the stack trace from Shepherd logs.

**Comment by Aaron1284** [comment]
Hi, thank you for reporting the issue. 
This is a known issue we located last week. And we are actively working on a fix.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by Aaron1284** [comment]
Hi, [chrisbulgaria](https://github.com/chrisbulgaria) - currently we don't allow setting data source to “enable” or “disable” via terraform provider. The only way to enable/disable the data source is doing it via console.

**Comment by kmujumda** [comment]
https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/cloud_guard_data_source

`status` parameter has been added to help customer to enable/disable the DataSource using TF script
