### ISSUE TITLE
change on network_security_group_ids attribute for oci_analytics_analytics_instance resource forces replacement

### ISSUE THREAD

**Issue by dhoogfr** [oracle/terraform-provider-oci#1808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v1.4.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/oracle/oci v4.111.0

### Affected Resource(s)

oci_analytics_analytics_instance

### Terraform Configuration Files

```hcl
variable "oac_1_config" {
  description = "The config attributes for the OAC instance"
  type        = map(any)
  default = {
    name           = "oactst1"
    description    = "oac-tst-1"
    capacity_type  = "OLPU_COUNT"
    capacity_value = 1
    feature_set    = "ENTERPRISE_ANALYTICS"
    license_type   = "LICENSE_INCLUDED"
    email          = "xxxxxxx"
  }
}

resource "oci_analytics_analytics_instance" "oac_1" {

  capacity {
    capacity_type  = var.oac_1_config.capacity_type
    capacity_value = var.oac_1_config.capacity_value
  }

  compartment_id     = oci_identity_compartment.oacinst.id
  feature_set        = var.oac_1_config.feature_set
  idcs_access_token  = data.local_file.idcs_access_token.content
  license_type       = var.oac_1_config.license_type
  name               = var.oac_1_config.name
  description        = var.oac_1_config.description
  email_notification = var.oac_1_config.email

  network_endpoint_details {
    network_endpoint_type      = "PRIVATE"
    network_security_group_ids = [data.terraform_remote_state.bastion.outputs.security_group_bastion_endpoint_id]
    subnet_id                  = oci_core_subnet.oac_1.id
    vcn_id                     = data.terraform_remote_state.shared.outputs.vcn_id
  }

}

```

### Debug Output

https://gist.github.com/dhoogfr/eee5b3eab90387abaae4aa3bb10aa1b6

### Expected Behavior
The change on the attached network_security_group_ids should be updated in-place
Which is the way it works when making this change via the OCI console

### Actual Behavior

The OAC resource is destroyed and recreated

### Steps to Reproduce

1. create the OAC instance
2. Change the network_security_group_ids attribute (eg remove the attached security group)
3. run terraform apply

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by indermalviya** [comment]
could you please confirm if the entire analytics instance is getting deleted and recreated in this case, or if it's just the network endpoint details that are getting deleted and recreated?

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by dhoogfr** [comment]
@indermalviya the entire analytics instance is deleted

**Comment by dhoogfr** [comment]
The issue is still occurring with the latest Terraform \ OCI release

```
~/oac_dev{main *}$ terraform --version
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/oracle/oci v4.118.0
```

**Comment by indermalviya** [comment]
NSG ID update is not yet supported in TF Provider since there is a separate API that handles this use case. We are evaluating the support for the update of this attribute via TFprovider.

**Comment by ravinitp** [comment]
Resolution has been pushed into v5.21.0
