### ISSUE TITLE
`oci_identity_domains_user` updates fail because it expects optional parameters to be present

### ISSUE THREAD

**Issue by F21** [oracle/terraform-provider-oci#1812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
`oci_identity_domains_user`

### Terraform Configuration Files

```hcl
resource "oci_identity_domains_user" "secrets_image_builder" {
  idcs_endpoint = oci_identity_domain.secrets.url
  schemas = [
    "urn:ietf:params:scim:schemas:core:2.0:User",
    "urn:ietf:params:scim:schemas:oracle:idcs:extension:userState:User",
    "urn:ietf:params:scim:schemas:oracle:idcs:extension:OCITags",
    "urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User",
  ]
  description = "Description"
  name {
    family_name = "smith"
  }
  emails {
    type    = "work"
    value   = "email@example.com"
    primary = true
  }
  user_name = "jsmith"
}
```

### Debug Output
https://gist.github.com/F21/9acb31b823e70f4291ede8b44a65e16e

### Panic Output
n/a

### Expected Behavior
The update should be succesful

### Actual Behavior
Updating the resource fails because it expects optional parameters such as `name.given_name` to have a minimum length of 1

### Steps to Reproduce
1. `terraform apply`
2.  Change `oci_identity_domains_user.test_user.name.family_name`.
3. Run `terraform apply` and confirm the apply.
4. Apply fails due to optional parameters having a miminum length of less than 1.

### Important Factoids
N/a

### References
Relates to #1811
Relates to https://github.com/oracle/oci-go-sdk/issues/416

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
We have notified our service engineer. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by wynnewang** [comment]
We are tracking this bug internally and working on a fix.

**Comment by vsin12** [comment]
Closing as per above comment.
