### ISSUE TITLE
autonomous database operations insight not enabled on the first run

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1819]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/oracle/oci v4.113.0

### Affected Resource(s)

oci_database_autonomous_database

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 


resource "oci_database_autonomous_database" "primary" {
.....

  compartment_id = "compartment_ocid"
  db_name        = "testdb"
  display_name   = "my test db"
  db_workload = "OLTP"
  source          = "NONE"
  database_management_status = "ENABLED"
  operations_insights_status = var.db_workload == "AJD" || var.db_workload == "APEX" ? "NOT_ENABLED" : "ENABLED"

```

### Expected Behavior

When creating a new autonomous database with both data management and operations insights enabled, they both should be enabled when database was created.

### Actual Behavior

data management was enabled as expected, but operations insight was NOT enabled. NO error during terraform plan and apply.
terraform plan output also showed the operations insight as "ENABLED"
On the 2nd terraform plan/apply, it enables the operations insights correctly.

### Steps to Reproduce

1. use the code snippet above to create a brand new ADB.
2. `terraform plan` output shows the operations insights should be "ENABLED"
3. terraform apply
4. check the operations insight is NOT enabled.'
5. run terraform plan again and it now shows operations insights to be changed from "NOT_ENABLED" to "ENABLED"
6. terraform apply now correctly set the operations insight to ENABLED.

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by luckeyca** [comment]
Thanks @ravinitp. just a note. the issue exists on creating new ADB regardless what the source is set to. I tested NONE, BACKUP_FROM_ID and BACKUP_FROM_TIMESTAMP.

**Comment by luckeyca** [comment]
This bug also triggered another bug in standby database creation. When standby database was created, the operations insight was not enabled and deployment has to be run the 2nd time, then error when updating the standby database, Error: During update, Terraform expected the resource to reach state(s): AVAILABLE, but the service reported unexpected state: STANDBY.
however, when checking the database settings, operations insights has already been enabled.
