### ISSUE TITLE
oci_core_ipsec_connection_tunnel_management not changing oracle_can_initiate

### ISSUE THREAD

**Issue by simonneto** [oracle/terraform-provider-oci#1822]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

% terraform -v
Terraform v1.4.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/oci v4.113.0

### Affected Resource(s)

oci_core_ipsec_connection_tunnel_management

### Terraform Configuration Files

resource "oci_core_ipsec_connection_tunnel_management" "phx_chi_ipsec_connection_tunnel1" {
    #Required
    ipsec_id = local.phx_chi_ipsec_id
    tunnel_id = data.oci_core_ipsec_connection_tunnels.phx_chi_ipsec_tunnels.ip_sec_connection_tunnels[0].id
    routing = "STATIC"
    #Optional
    bgp_session_info {
        #Optional
        customer_interface_ip = "10.143.254.117/30"
        oracle_interface_ip = "10.143.254.118/30"
    }
    display_name = "phx-chi-tunnel1" 
    shared_secret = data.oci_core_ipsec_config.phx_chi_ipsec_device_config.tunnels[0].shared_secret
    ike_version = "V2"
    oracle_can_initiate = "RESPONDER_ONLY"
}

### Debug Output

[](https://gist.github.com/simonneto/77b5df0a421e7b5d7f8339af0a719ca5)

### Expected Behavior

Be able to change the tunnel configuration from INITIATOR_OR_RESPONDER to RESPONDER_ONLY

### Actual Behavior

Receive an error message
│ Error: Value for unconfigurable attribute
│
│   with module.Home.module.NETWORK.module.IPSEC.oci_core_ipsec_connection_tunnel_management.phx_chi_ipsec_connection_tunnel1,
│   on home/network/ipsec/phx-chi-ipsec.tf line 41, in resource "oci_core_ipsec_connection_tunnel_management" "phx_chi_ipsec_connection_tunnel1":
│   41:     oracle_can_initiate = "RESPONDER_ONLY"
│
│ Can't configure a value for "oracle_can_initiate": its value will be decided automatically based on the result of applying this configuration.

### Steps to Reproduce

resource "oci_core_ipsec_connection_tunnel_management" "phx_chi_ipsec_connection_tunnel1" {
    #Required
    ipsec_id = local.phx_chi_ipsec_id
    tunnel_id = data.oci_core_ipsec_connection_tunnels.phx_chi_ipsec_tunnels.ip_sec_connection_tunnels[0].id
    routing = "STATIC"
    #Optional
    bgp_session_info {
        #Optional
        customer_interface_ip = "10.143.254.117/30"
        oracle_interface_ip = "10.143.254.118/30"
    }
    display_name = "phx-chi-tunnel1" 
    shared_secret = data.oci_core_ipsec_config.phx_chi_ipsec_device_config.tunnels[0].shared_secret
    ike_version = "V2"
    oracle_can_initiate = "RESPONDER_ONLY"
}

1. `terraform apply`

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by iejones** [comment]
oracle_can_initiate field is computed only. It should be optional. Bug fix is coded and currently being tested alongside other bug fixes for the oci_core_ipsec_connection_tunnel_management resource

**Comment by iejones** [comment]
A bug fix including the change to make oracle_can_initiate optional will be released on November 15th, 2023

**Comment by iejones** [comment]
This fix was released with version [v5.21.0](https://github.com/oracle/terraform-provider-oci/releases/tag/v5.21.0)
