### ISSUE TITLE
oci_core_ipsec_connection_tunnel_management not changing bgp_session_info

### ISSUE THREAD

**Issue by simonneto** [oracle/terraform-provider-oci#1823]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

% terraform -v
Terraform v1.4.2
on darwin_arm64

provider registry.terraform.io/hashicorp/oci v4.113.0

### Affected Resource(s)

oci_core_ipsec_connection_tunnel_management

### Terraform Configuration Files

resource "oci_core_ipsec_connection_tunnel_management" "iad_chi_ipsec_connection_tunnel1" {
    #Required
    ipsec_id = local.iad_chi_ipsec_id
    tunnel_id = data.oci_core_ipsec_connection_tunnels.iad_chi_ipsec_tunnels.ip_sec_connection_tunnels[0].id
    routing = "STATIC"
    #Optional
    bgp_session_info {
        #Optional
        customer_interface_ip = "10.143.254.117/30"
        oracle_interface_ip = "10.143.254.118/30"
    }
    display_name = "iad-chi-tunnel1" 
    shared_secret = data.oci_core_ipsec_config.iad_chi_ipsec_device_config.tunnels[0].shared_secret
    ike_version = "V2"
}

### Debug Output

https://gist.github.com/simonneto/4c7e1046617ec35d47c03502e46ecdf9

### Expected Behavior

Create/Modify the CPE and Oracle inside tunnel interface

### Actual Behavior

The tunnel gets created without that information and we can even change it manually that terraform ignores it

### Steps to Reproduce

1. `terraform apply`

Please let me know if you prefer to create one generic issue for this one and https://github.com/oracle/terraform-provider-oci/issues/1822 which is another issue I opened with the same resource.

Thanks,

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by iejones** [comment]
The oci_core_ipsec_connection_tunnel_management resource only updates the bgp_sesion_info fields when routing is BGP. 

A bug fix is in progress to allow passing bgp no matter the routing type

**Comment by andrecorreaneto** [comment]
Is there an ETA for this bug fix?

**Comment by iejones** [comment]
A bug fix including the change to make routing optional and always use bgp_session_info will be released on November 15th, 2023

**Comment by iejones** [comment]
This fix was released with version [v5.21.0](https://github.com/oracle/terraform-provider-oci/releases/tag/v5.21.0)
