### ISSUE TITLE
creating new autonomous database using source=DATABASE doesn't work

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/oracle/oci v4.113.0

### Affected Resource(s)

oci_database_autonomous_database

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 

resource "oci_database_autonomous_database" "this" {
....

   source = "DATABASE"
   source_id = "ocid_of_the_source_database"
...
}
```

### Expected Behavior

When creating new autonomous database on shared infrastructure using source = "DATABASE" and the source_id = "ocid_of_the_source_database", the new database should be created.

### Actual Behavior

it failed to create the new database and the error message doesn't provide any useful information. Even turning on terraform debug, the error messages are identical.

### Steps to Reproduce

1. use the code snippet about specifying source = "DATABASE" to create a new ADB
2. terraform plan will pass
3. terraform apply fails with the following error. Debug shows NO additional info.

│ Error: 400-InvalidParameter, Unable to process JSON input
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message Unable to process JSON input
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_autonomous_database
│ API Reference: https://docs.oracle.com/iaas/api/#/en/database/20160918/AutonomousDatabase/CreateAutonomousDatabase
│ Request Target: POST https://database.ca-toronto-1.oraclecloud.com/20160918/autonomousDatabases
│ Provider version: 4.113.0, released on 2023-03-22. This provider is 1 Update(s) behind to current.
│ Service: Database Autonomous
│ Operation Name: CreateAutonomousDatabase
│ OPC request ID: 3c4a799073557928d0497840bd498495/6404F9C4EA597D51B233856EC00174AF/62698E69256D7186E0EB4513ECE897AA

**Comment by ravinitp** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by navg-orcl** [comment]
Clone Type is marked as a mandatory attribute. The Error looks like thrown from the parser. We will review it .

**Comment by luckeyca** [comment]
understood it's a mandatory field. my comment on the lack of meaningful error and/or debug message is in general to this resource. for many failures, error messages were not helpful at all which is a big problem with this resource
