### ISSUE TITLE
db_name only allows 14 characters

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/oracle/oci v4.113.0

### Affected Resource(s)

oci_database_autonomous_database

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 

N/A
```

### Expected Behavior

As per oracle documentation, autonomous database name should be 30 characters max. This is also the experience when creating database from OCI console.  https://docs.oracle.com/en/cloud/paas/autonomous-database/adbsa/autonomous-provision.html#GUID-0B230036-0A05-4CA3-AF9D-97A255AE0C08

### Actual Behavior

database name only allows 14 characters.

### Steps to Reproduce

The current limit is documented here which contradicts the document above: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_autonomous_database

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by xiaoditao1** [comment]
"database name only allows 14 characters." Please provide opc-request-id or the full error message.

**Comment by sreenvas** [comment]
@xiaoditao1 The 14 character limitation is mentioned against the db_name argument in the official ADB terraform resource documentation below. You can search for the argument name and it mentions _"The name must begin with an alphabetic character and can contain a maximum of 14 alphanumeric characters. "_
[(https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_autonomous_database)]

**Comment by xiaoditao1** [comment]
I tried to reproduce it, but everything looks fine. I used terraform with provider version of 5.9.0, I created an autonomous database with db_name larger than 14 characters and it succeeded. Also see https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_autonomous_database, the db_name maximum length is 30 characters. So this issue already been fixed. Please close this ticket, thans.

**Comment by luckeyca** [comment]
Hi @xiaoditao1, thanks for the update. it's working with 30-characeter name now with terraform and I did see the terraform documentation was updated. Just a note. on the cli ticket for the same issue: https://github.com/oracle/oci-cli/issues/663, it looks like the cli documentation is still outdated here with 14-characters written. https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.33.2/oci_cli_docs/cmdref/db/autonomous-database/create.html#cmdoption-db-name

same for the ansible documentation: https://oci-ansible-collection.readthedocs.io/en/latest/collections/oracle/oci/oci_database_autonomous_database_module.html#parameter-db_name

please update them to avoid confusion. Thanks

**Comment by xiaoditao1** [comment]
Working on the fix for https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.33.2/oci_cli_docs/cmdref/db/autonomous-database/create.html#cmdoption-db-name
It will take 2-3 weeks to make the change deployed to public.
