### ISSUE TITLE
oci_devops_deploy_artifact INLINE artifact base64encoded_content is not decoded 

### ISSUE THREAD

**Issue by streamnsight** [oracle/terraform-provider-oci#1842]
### Terraform Version and Provider Version

```
Terraform v1.2.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.116.0
```

### Affected Resource(s)

```hcl
resource oci_devops_deploy_artifact cluster-autoscaler-manifest {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  deploy_artifact_source {
    base64encoded_content = "xyz" #<-- should NOT be base64 encoded, the string is sent as-is, or should be decoded on creation
    deploy_artifact_source_type = "INLINE"
  }
  deploy_artifact_type = "KUBERNETES_MANIFEST"
  description          = "manifest"
  display_name         = "manifest"
  freeform_tags = {
  }
  project_id = var.project_id
}
}
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.2"
  required_providers {
    oci = {
      source  = "hashicorp/oci"
      version = ">= 4.114.0"
      # https://registry.terraform.io/providers/hashicorp/oci/4.85.0
      configuration_aliases = [oci.current_region, oci.home_region]
    }
}
```

### Actual Behavior

content is provided as-is in the artifact, not base64decoded

### Steps to Reproduce

1. `terraform apply`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by pruthvigh** [comment]
@streamnsight trying to understand /confirm the issue here: Are you expecting the artifact content to be base64 decoded upon resource creation through Terraform but, you're currently getting the base64 string content as is that you passed in the resource definition?

**Comment by streamnsight** [comment]
@pruthvigh 
The issue is that the variable is either badly named (i.e. it should not be base64 encoded content) or it the provider should decode the base64 content, because the content is sent as-is as the artifact.
Currently, I use it, and send plain text, and it works fine. 
Changing the behavior now would cause backward compatibility issues i guess, so maybe deprecate the variable and rename it `content` and it'll be more logical.

**Comment by pruthvigh** [comment]
@streamnsight I have taken an action item on this on our end and we're thinking of implementing it in a way something similar to what you suggested. This will soon be triaged. Thanks for surfacing this.
