### ISSUE TITLE
Unable to create ExaCS VM Cluster Data Safe target

### ISSUE THREAD

**Issue by davcosentino** [oracle/terraform-provider-oci#1853]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform version: 1.3.5
Go runtime version: go1.19.3
Provider version: 4.117.0, released on 2023-04-20

### Affected Resource(s)

affected_resources = oci_data_safe_target_database

### Terraform Configuration Files

```hcl
resource "oci_data_safe_target_database" "test_target_database" {
    #Required
    compartment_id = var.compartment_id
    database_details {
        #Required
        database_type = var.target_database_database_details_database_type
        infrastructure_type = var.target_database_database_details_infrastructure_type

        #Optional
        autonomous_database_id = oci_database_autonomous_database.test_autonomous_database.id
        db_system_id = oci_database_db_system.test_db_system.id
        instance_id = oci_core_instance.test_instance.id
        ip_addresses = var.target_database_database_details_ip_addresses
        listener_port = var.target_database_database_details_listener_port
        service_name = oci_core_service.test_service.name
        vm_cluster_id = oci_database_vm_cluster.test_vm_cluster.id
    }

    #Optional
    connection_option {
        #Required
        connection_type = var.target_database_connection_option_connection_type

        #Optional
        datasafe_private_endpoint_id = oci_dataflow_private_endpoint.test_private_endpoint.id
        on_prem_connector_id = oci_data_safe_on_prem_connector.test_on_prem_connector.id
    }
    credentials {
        #Required
        password = var.target_database_credentials_password
        user_name = oci_identity_user.test_user.name
    }
    defined_tags = {"Operations.CostCenter"= "42"}
    description = var.target_database_description
    display_name = var.target_database_display_name
    freeform_tags = {"Department"= "Finance"}
    tls_config {
        #Required
        status = var.target_database_tls_config_status

        #Optional
        certificate_store_type = var.target_database_tls_config_certificate_store_type
        key_store_content = var.target_database_tls_config_key_store_content
        store_password = var.target_database_tls_config_store_password
        trust_store_content = var.target_database_tls_config_trust_store_content
    }
}
```

### Expected Behavior

With infrastructure_type=ORACLE_CLOUD and database_type=DATABASE_CLOUD_SERVICE, I should be able to create an ExaCS VM Cluster Data Safe target by setting vm_cluster_id=\<VM Cluster OCID\>.

### Actual Behavior

When I try to create ExaCS VM Cluster Data Safe target by setting infrastructure_type=ORACLE_CLOUD, database_type=DATABASE_CLOUD_SERVICE and vm_cluster_id=\<VM Cluster OCID\>, I get the following error: **400-InvalidParameter, The cloud database system id or cloud vmcluster id cannot be null**.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Reading the code in the **internal/service/data_safe/data_safe_target_database_resource.go** file, I noticed that, in the **DatabaseDetailsToMap** and **mapToDatabaseDetails** functions, the handling of the **vm_cluster_id** field is missing. Could this be the cause of the problem?

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We observed the affected resources are not provided in the description or it's incorrect. We request you to add it in issue description as mentioned in below format.
Example: affected_resources = oci_core_instance , oci_core_instances
 
If it's not related to any particular resource then mention affected resource as terraform.
Example: affected_resources = terraform
 
As this works through automation, request you to follow exact syntax.

**Comment by tf-oci-pub** [comment]
affected_resources=oci_data_safe_target_database

**Comment by davcosentino** [comment]
The terraform variables are initialized correctly, I put:
- infrastructure_type = ORACLE_CLOUD
- database_type = DATABASE_CLOUD_SERVICE
- vm_cluster_id = \<id of the vmcluster\>

If I use these parameters on OCI Console, REST APIs, CLI or SDK it works. But when I try to use these parameters on this tf provider I receive this error:  **400-InvalidParameter, The cloud database system id or cloud vmcluster id cannot be null**.

In addition, reading the code in the **internal/service/data_safe/data_safe_target_database_resource.go** file, it seems that in the DatabaseDetailsToMap and mapToDatabaseDetails functions the handling of the vm_cluster_id field is missing (this field is not inserted in the payload that's sent to OCI APIs).

**Comment by sagarp337** [comment]
Fixed is merged in v.4.121.0
