### ISSUE TITLE
oci_data_safe_target_database resource has no proper validation and error handling

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1854]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/oracle/oci v4.117.0

### Affected Resource(s)

oci_data_safe_target_database

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 

as per example code in the resource documentation
```

### Expected Behavior

any terraform resource should do proper validation during terraform plan and error handling when doing terraform apply.
This is not the case with this resource and the autonomous database resource which defeats the purpose of using terraform.

This is a negative testing by putting autonomous database in standby and tried to register it with data safe.
what should happen is terraform plan should fail at least given it's not active, but in standby mode. 

ideally, as how terraform should work as declarative programming language, this resource should handle the remote standby registration at the backend just as how it handles the local standby.

### Actual Behavior

terraform plan passed, but apply failed as expected with no meaningful error, but simply says "contact support..." which is very bad coding.

 Error: Work Request error
│ Provider version: 4.117.0, released on 2023-04-20.
│ Service: Data Safe Target Database
│ Error Message: work request did not succeed, workId: ocid1.coreservicesworkrequest.oc1.ca-toronto-1.ab2g6ljrtbd56lhe6aeglmfsmp2wz3tupsffzjfm76sknfb2bpfn6shxowlq, entity: target-database, action: CREATED. Message: Error occurred while registering the target database
│ Resource OCID:
│ Suggestion: Please retry or contact support for help with service: Data Safe Target Database

### Steps to Reproduce

1. use this resource to register the standby instance.
2. `terraform plan`
3. terraform apply.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ManjunathGoudar88** [comment]
@luckeyca Could you please provide a sample terraform code.?

**Comment by ManjunathGoudar88** [comment]
Now we added a fix to validate the autonomous database if it is on standby and tried to register it with data safe.

**Comment by ManjunathGoudar88** [comment]
Fix will be available by jun 15th.

**Comment by luckeyca** [comment]
Hi @ManjunathGoudar88, thanks for the update. could you please clarify what fix you put in as you said "terraform plan will not do validation" which is the problem. Without properly validation during plan phase, the apply will fail if it's standby which defeats the purpose of terraform plan.

**Comment by ManjunathGoudar88** [comment]
Either Terraform plan, not Datasafe service does not do DB calls to check the availability of resource state until we Apply/Post  calls where validation is taken care during the POST call.

To validate whether a resource exists or is not found during a Terraform plan, you can use Terraform's data sources and data blocks. Data sources allow you to query the state of the existing resources in the target infrastructure, and data blocks retrieve information without creating or managing any actual resources. You can then use the data retrieved to conditionally decide whether to proceed with the creation or modification of certain resources based on the presence or absence of existing resources.
