### ISSUE TITLE
oci_data_safe_target_database failed to handle staled database registration

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.4.5
on linux_amd64

provider registry.terraform.io/oracle/oci v4.117.0
### Affected Resource(s)
oci_data_safe_target_database

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
use the sample code in the resource documentation
```

### Expected Behavior

 oci_data_safe_target_database should check and handle if the database is in standby mode before creating new registration or destroying the existing registration

### Actual Behavior

terraform plan always works even if the target database is actually in standby mode which means there is NO proper validation code in place. As a result, if a previously registered database fails over to remote standby, and run "terraform destroy" to destroy the existing registration, the destroy will work. Then after the database fails back to be primary, it still shows as registered in data safe. In this case, when re-running terraform apply to register, even though terraform plan works, terraform apply will failed with only timeout error which again shows there is no error handling whatsoever which is very bad coding.

### Steps to Reproduce

1. `terraform apply` to register autonomous database primary
2. failover the database to remote standby
3. terraform destroy to destroy the registration
4. failback the database to primary
5. terraform apply to register. this will fail with timeout error only. no extra info given
6. on oci console, manually de-register the data safe registration
7. terraform apply again. this will succeed.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ManjunathGoudar88** [comment]
Now we added a fix to validate the autonomous database if it is on standby and tried to register it with data safe.
Please note that, terraform plan will not do validations such as state, provider APIs, etc. After apply, we validate the ADB role and return the error messages.

**Comment by ManjunathGoudar88** [comment]
Fix will be available by jun 15th.

**Comment by ManjunathGoudar88** [comment]
@luckeyca Please let us know if any assistance from the Oracle side on this issue, or else request to close this issue.
