### ISSUE TITLE
[oci_data_safe_alert]documentation issue on multiple data safe terraform resources.

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1858]
1. In the oci_data_safe_alert resource document here: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/data_safe_alert, in the code example, the mandatory field "alert_id" is coming from the resource itself. How does that work?
2. same for oci_data_safe_audit_trail documentation https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/data_safe_audit_trail, the audit_trail_id is coming from the resource itself.
3. oci_data_safe_audit_profile.... 

please double check all the data safe related documentations.
affected_resource= oci_data_safe_alert

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by sagappat** [comment]
we released the management resource to change the retention for audit profile resource, please find documentation -

https://registry.terraform.io/providers/oracle/oci/5.20.0/docs/resources/data_safe_audit_profile_management

Provision policy - 

https://registry.terraform.io/providers/oracle/oci/5.20.0/docs/resources/data_safe_audit_policy_management

Start trail - 

https://registry.terraform.io/providers/oracle/oci/5.20.0/docs/resources/data_safe_audit_trail_management

**Comment by luckeyca** [comment]
you were looking at it wrong. the wrong code are in these two documents as per reported issue: In the oci_data_safe_alert resource document here: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/data_safe_alert, in the code example, the mandatory field "alert_id" is coming from the resource itself. How does that work?
same for oci_data_safe_audit_trail documentation https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/data_safe_audit_trail, the audit_trail_id is coming from the resource itself.
