### ISSUE TITLE
oci_objectstorage_object_lifecycle_policy resource doesn't have proper terraform plan validation

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#1873]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/oracle/oci v4.120.0

### Affected Resource(s)

oci_objectstorage_object_lifecycle_policy

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 

variable "object_storage_bucket_lifecycle_policy_rules" {
  type = list(object({
    action      = string
    is_enabled  = bool
    name        = string
    time_amount = string
    time_unit   = string
    target      = string
    object_name_filter = optional(object({
      exclusion_patterns = list(string)
      inclusion_patterns = list(string)
      inclusion_prefixes = list(string)
      }), {
      exclusion_patterns = []
      inclusion_patterns = []
      inclusion_prefixes = []
    })
  }))
  description = "object Storage Bucket Lifecycle Policy Rules"
  default = [
    {
      action      = "INFREQUENT_ACCESS"
      is_enabled  = true
      name        = "Move Infrequent Access Objects Rule"
      time_amount = "45"
      time_unit   = "DAYS"
      target      = "objects"
    },
    {
      action      = "ARCHIVE"
      is_enabled  = true
      name        = "Archive Objects Rule"
      time_amount = "90"
      time_unit   = "DAYS"
      target      = "objects"
    },
    {
      action      = "DELETE"
      is_enabled  = true
      name        = "Delete Objects Rule"
      time_amount = "120"
      time_unit   = "DAYS"
      target      = "objects"
    },
    {
      action      = "INFREQUENT_ACCESS"
      is_enabled  = true
      name        = "Move Infrequent Access Objects Rule"
      time_amount = "45"
      time_unit   = "DAYS"
      target      = "previous-object-versions"
    },
    {
      action      = "ARCHIVE"
      is_enabled  = true
      name        = "Archive Objects Rule"
      time_amount = "90"
      time_unit   = "DAYS"
      target      = "previous-object-versions"
    },
    {
      action      = "DELETE"
      is_enabled  = true
      name        = "Delete All Previous Objects Versions Rule"
      time_amount = "240"
      time_unit   = "DAYS"
      target      = "previous-object-versions"
    }
  ]

  validation {
    condition = alltrue([
      for rules in var.object_storage_bucket_lifecycle_policy_rules : contains(["ABORT", "ARCHIVE", "INFREQUENT_ACCESS", "DELETE"], rules.action)
    ])
    error_message = "Valid object storage bucket lifecycle rules actions are ABORT, ARCHIVE, INFREQUENT_ACCESS and DELETE"
  }

  validation {
    condition = alltrue([
      for rules in var.object_storage_bucket_lifecycle_policy_rules : can(regex("^[1-9][0-9]*$", rules.time_amount))
    ])
    error_message = "Valid object storage bucket lifecycle rules time amount is a string with only numbers"
  }

  validation {
    condition = alltrue([
      for rules in var.object_storage_bucket_lifecycle_policy_rules : contains(["DAYS", "YEARS"], rules.time_unit)
    ])
    error_message = "Valid object storage bucket lifecycle rules time units are DAYS and YEARS"
  }

  validation {
    condition = alltrue([
      for rules in var.object_storage_bucket_lifecycle_policy_rules : contains(["objects", "object-versions", "multipart-uploads", "previous-object-versions"], rules.target)
    ])
    error_message = "Valid object storage bucket lifecycle rules targets are objects, object-versions, previous-object-versions and multipart-uploads"
  }
}

resource "oci_objectstorage_bucket" "this" {
  count          = var.object_storage_bucket_deploy ? 1 : 0
  compartment_id = var.object_storage_bucket_compartment_ocid
  name           = var.object_storage_bucket_name
  namespace      = var.object_storage_bucket_namespace

  access_type           = "NoPublicAccess"
  auto_tiering          = var.object_storage_bucket_storage_tier == "Standard" ? "Disabled" : null
  metadata              = var.object_storage_bucket_metadata
  freeform_tags         = var.object_storage_bucket_freeform_tags
  object_events_enabled = var.object_storage_bucket_object_events_enabled
  storage_tier          = var.object_storage_bucket_storage_tier
  versioning            = var.object_storage_bucket_versioning
}

resource "oci_objectstorage_object_lifecycle_policy" "this" {
  count     = length(var.object_storage_bucket_lifecycle_policy_rules) == 0 ? 0 : 1
  bucket    = oci_objectstorage_bucket.this[0].name
  namespace = oci_objectstorage_bucket.this[0].namespace

  dynamic "rules" {
    for_each = var.object_storage_bucket_lifecycle_policy_rules
    content {
      action      = rules.value.action
      is_enabled  = rules.value.is_enabled
      name        = rules.value.name
      time_amount = rules.value.time_amount
      time_unit   = rules.value.time_unit

      object_name_filter {
        exclusion_patterns = toset(rules.value.object_name_filter.exclusion_patterns)
        inclusion_patterns = toset(rules.value.object_name_filter.inclusion_patterns)
        inclusion_prefixes = toset(rules.value.object_name_filter.inclusion_prefixes)
      }
      target = rules.value.target
    }
  }
}

resource "oci_objectstorage_object_lifecycle_policy" "multipart_uploads" {
  bucket    = oci_objectstorage_bucket.this[0].name
  namespace = oci_objectstorage_bucket.this[0].namespace

  rules {
    action      = "ABORT"
    is_enabled  = true
    name        = "Delete uncommitted or failed multipart uploads Rule"
    time_amount = "7"
    time_unit   = "DAYS"
    target      = "multipart-uploads"
  }
}

```

### Debug Output

N/A
### Panic Output

N/A
### Expected Behavior

In an attempt to workaround a bug(reported as: https://github.com/oracle/terraform-provider-oci/issues/1872), I use the oci_objectstorage_object_lifecycle_policy twice in the same module hoping they will append(which didn't happen exactly as described per documentation as it's only to create or replace). However, as side effect, I uncovered a general "terraform plan" issue as also reported on the other bug. Terraform plan should report properly when the resource is being used more than once in the same run which didn't happen.

### Actual Behavior

As per my test code, I used the same oci_objectstorage_object_lifecycle_policy resource twice in the same module, at the very first run, terraform plan reports the code will create the bucket, along with both policies set by the two resources, totally 3 items. However, actually it only created the bucket and the first policy. Then on the 2nd run, terraform plan properly reported it will replace the first policy with the 2nd policy. Then on the terraform destroy(3rd run), even though the first policy was already replaced by the 2nd policy(verified on the console), it still reported that it will destroy 3 items. 

### Steps to Reproduce

use the test code above, do terraform plan / apply twice and then destroy.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by nandini12396** [comment]
Hi @luckeyca thanks for creating this issue. This is intentional behavior.

By default, when Terraform creates a plan it:

- Reads the current state of any already-existing remote objects to make sure that the Terraform state is up-to-date.
- Compares the current configuration to the prior state and noting any differences.
- Proposes a set of change actions that should, if applied, make the remote objects match the configuration.

Now, when you used the same oci_objectstorage_object_lifecycle_policy resource twice in the same module, the plan just compares the state with the current state and suggests proposed changes. Thus for each resource, it compares with the current state and reports that it will create the bucket with the specified policy. Only at the time of the execution of the release, the resource id is analyzed and identified and it updates the plan accordingly.

Regarding the issue you mentioned with Terraform destroy reporting the destruction of three items even after the first policy was replaced, this is a known behavior. The destroy plan is based on the prior state and the actions needed to revert to that state. In this case, even though the state was updated during the apply phase, the destroy plan still considers the original state where the first policy existed.

If you have verified that the first policy was indeed replaced by the second policy, you can safely ignore the destroy plan's suggestion to destroy the first policy. Terraform will not attempt to destroy resources that do not exist in the current configuration.

If you have any further questions or concerns, feel free to let me know.

**Comment by nandini12396** [comment]
Resolving the ticket. Please reach out if there are questions.
