### ISSUE TITLE
Error: 400-InvalidParameter, Invalid instanceConfigurationId: null Core.instance

### ISSUE THREAD

**Issue by brenwell** [oracle/terraform-provider-oci#1899]
First up thanks for the hard work!

I am a proper noob and seeing this error when trying to apply a core.instance. Please share your wisdom and save my predicament!

Apologies if this has been a waste of your time

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
Terraform v1.5.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v5.2.1
```

### Affected Resource(s)

oci_core_instance

### Terraform Configuration Files

```hcl
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}

provider "oci" {
  tenancy_ocid     = var.tenancy_ocid
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  region           = var.region
}

resource "oci_identity_compartment" "tf-compartment" {
    compartment_id = var.tenancy_ocid
    description = "Compartment for Terraform resources."
    name = "terraform"
}

output "compartment-OCID" {
  value = oci_identity_compartment.tf-compartment.id
}

data "oci_identity_availability_domains" "ads" {
  compartment_id = oci_identity_compartment.tf-compartment.id
}

output "name-of-first-availability-domain" {
  value = data.oci_identity_availability_domains.ads.availability_domains[0].name
}

resource "oci_core_instance" "ubuntu_instance" {
    availability_domain = data.oci_identity_availability_domains.ads.availability_domains[0].name
    compartment_id = oci_identity_compartment.tf-compartment.id
    shape = "VM.Standard.E2.1.Micro"

    source_details {
        # Canonical-Ubuntu-22.04-Minimal-2023.05.20-0
        # https://docs.oracle.com/en-us/iaas/images/image/0a61a44e-9c64-4d32-b518-424f0d1bfa9c/
        source_id = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa3bm2rqezknstfm2hepnpqculkohounwezbdfpv5vg6u5mnfzumfq"
        source_type = "image"
    }
}
```

### Debug Output

https://gist.github.com/brenwell/cc450b428b8dcc7e0b55a7f8cfae54de

### Expected Behavior

Creates instance

### Actual Behavior

```╷
│ Error: 400-InvalidParameter, Invalid instanceConfigurationId: null
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message Invalid instanceConfigurationId: null
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance
│ API Reference: https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/LaunchInstance
│ Request Target: POST https://iaas.eu-frankfurt-1.oraclecloud.com/20160918/instances
│ Provider version: 5.2.1, released on 2023-06-21.
│ Service: Core Instance
│ Operation Name: LaunchInstance
│ OPC request ID: 03d89b0c44886308ba127963fe7f32a6/3AAEDAFC597B2F4CE65E56532DC8F165/7A413897AB8B4CA94A440A5FE7ABBA32
│
│
│   with oci_core_instance.ubuntu_instance,
│   on main.tf line 34, in resource "oci_core_instance" "ubuntu_instance":
│   34: resource "oci_core_instance" "ubuntu_instance" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by toleksa** [comment]
@brenwell I came here investigating same issue and found that it should work after adding vnic config to instance:

`  create_vnic_details {                                                                                                                                                                    
    subnet_id         = var.compute_subnet_id                                                                                                                                             
    assign_public_ip  = true                                                                                                                                                               
  }  `

However error is quite misleading.

**Comment by tf-oci-pub** [comment]
Closing the issue as @brenwell mentioned https://github.com/oracle/terraform-provider-oci/issues/1899#issuecomment-1609389761 issue has been resolved after adding vnic config to instance.
