### ISSUE TITLE
Update bmc provider reference to oracle/bmcs-go-sdk repo

### ISSUE THREAD

**Issue by gliptak** [oracle/terraform-provider-oci#192]
http://github.com/MustWin/baremetal-sdk-go repo doesn't seem to be accessible. Are there plans to open that repo? Thanks

**Comment by codycushing** [comment]
We will be updating the reference to https://github.com/oracle/bmcs-go-sdk this week and are looking making that repo public.

**Comment by FrenchBen** [comment]
Still getting a 404 on https://github.com/oracle/bmcs-go-sdk - Is this normal?

**Comment by FrenchBen** [comment]
For those interested, I started working on the SDK:
https://github.com/frenchben/oracle-sdk-go

**Comment by codycushing** [comment]
Completed in v2.0.2

@FrenchBen Can you contact @jodoglevy about the SDK work to make sure your effort is not wasted? His team is working on a OCI swagger spec generated Go SDK.

**Comment by FrenchBen** [comment]
@codycushing slightly difficult to do via github, so I sent him a tweet 😅

**Comment by gabriel-samfira** [comment]
Hi @codycushing 

Is there any progress on this? Is the Go SDK available anywhere?
