### ISSUE TITLE
Updating oci_core_vnic_attachment display_name causes destroy/create (vs. modify)

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1922]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
Terraform v1.3.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v5.2.1
```

### Affected Resource(s)
affected_resources = oci_core_vnic_attachment

### Terraform Configuration Files

```hcl
resource "oci_core_vnic_attachment" "the_vnic_attachment" {
  #Required
  create_vnic_details {
    subnet_id = var.subnet_id
  }
  instance_id = var.instance_id

  #Optional
  display_name = var.vnic_attachment_display_name
}
```

### Expected Behavior

When I update `oci_core_vnic_attachment` parameter `display_name` the resource should be modified to have the new value.

### Actual Behavior

When I update `oci_core_vnic_attachment` parameter `display_name` the resource triggers a destroy/create instead of modifying the existing resource.

### Steps to Reproduce

1. `terraform apply` using above sample
2. Update `var.vnic_attachment_display_name` to a new value
3. `terraform apply` and note trigger to destroy/create vs. modify as expected 

### Important Factoids
Documentation for `AttachVnicDetails` says `display_name` parameter "[d]oes not have to be unique, and it's changeable."

### References
 * [AttachVnicDetails Reference](https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/AttachVnicDetails)

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by nolancaster** [comment]
I also just noticed the link to the AttachVnicDetails doc indicating the display name is changeable. I'm guessing that's a copy/paste error from CreateVnicDetails (where the display name actually is changeable). I will look into getting this doc changed to be accurate.
