### ISSUE TITLE
oci_functions_function provider doc says image is Optional but Error: 400-InvalidParameter without it 

### ISSUE THREAD

**Issue by shankar96** [oracle/terraform-provider-oci#1928]
If not using image as documentation says it's Optional I got the following error while applying: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/functions_function

`Error: 400-InvalidParameter, image is required.
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message image is required.
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/functions_function 
│ API Reference: https://docs.oracle.com/iaas/api/#/en/functions/20181201/Function/CreateFunction 
│ Request Target: POST https://functions.us-phoenix-1.oci.oraclecloud.com/20181201/functions 
│ Provider version: 4.113.0, released on 2023-03-22. This provider is 18 Update(s) behind to current. 
│ Service: Functions Function 
│ Operation Name: CreateFunction 
│ OPC request ID: d16d656bfff61bc312c5dc6308628f23/69E5319FBFC764905949C8F9C9784710/E92FA5DF9B79805BB65CEFCE39BC5D67 `

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ahjones** [comment]
Image is required if you don't provide `source details`. That is: you must supply either `image` _or_ `source_details` but not both.

**Comment by vsin12** [comment]
closing the issue as per last comment.
