### ISSUE TITLE
oci_containerengine_node_pool initial_node_labels not working

### ISSUE THREAD

**Issue by cebrat** [oracle/terraform-provider-oci#1966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/oci v5.14.0
+ provider registry.terraform.io/hashicorp/vault v3.20.1

### Affected Resource(s)

oci_containerengine_node_pool

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```
resource "oci_containerengine_node_pool" "oke-node-pool" {
    initial_node_labels {
        app = "primion"
        env = "primion-dev"
    } 
}

### Debug Output

╷
│ Error: Unsupported argument
│
│   on node-pool.tf line 41, in resource "oci_containerengine_node_pool" "oke-node-pool":
│   41:         appir = "primion"
│
│ An argument named "appir" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on node-pool.tf line 42, in resource "oci_containerengine_node_pool" "oke-node-pool":
│   42:         envir = "primion-dev"
│
│ An argument named "envir" is not expected here.

### Expected Behavior

Create the initial labels

### Actual Behavior

Terraform is failing

### Steps to Reproduce

1. `terraform plan`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.
