### ISSUE TITLE
REMOTE_CLONE_PDB is performing a local clone from the seed database

### ISSUE THREAD

**Issue by hal9000jw** [oracle/terraform-provider-oci#1971]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/oracle/oci v5.16.0

### Affected Resource(s)

oci_database_pluggable_database

### Terraform Configuration Files

```
resource "oci_database_pluggable_database" "pluggable_database_cdb1_pdb2" {
  container_database_id = data.oci_database_databases.database1.databases[0].id
  pdb_name              = "pdb2"

  pdb_creation_type_details {
    creation_type                            = "REMOTE_CLONE_PDB"
    source_pluggable_database_id             = data.oci_database_pluggable_databases.database2_pdb.pluggable_databases[0].id
    source_container_database_admin_password = base64decode(oci_vault_secret.db_pw_secret.secret_content[0].content)

    refreshable_clone_details {
      is_refreshable_clone = false
    }
  }

  should_pdb_admin_account_be_locked = true
  tde_wallet_password                = base64decode(oci_vault_secret.tde_pw_secret.secret_content[0].content)
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The remote cloning operation should use a database link to create the pluggable database.

### Actual Behavior

The remote cloning operation performed a local clone from the seed database.

### Steps to Reproduce

1. terraform apply

### Important Factoids

N/A

### References

None

**Comment by hal9000jw** [comment]
I have tried numerous resource permutations unsuccessfully to achieve the desired results.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by vijayganesh77** [comment]
@hal9000jw would you be able to replicate this issue and provide the OCID of the newly created Pluggable Database so that we could investigate this further?

**Comment by vijasank** [comment]
@hal9000jw Yeah, this is not expected. Would you be able to reproduce this issue and provide the resource OCID so that we could investigate further on this issue?

**Comment by hal9000jw** [comment]
@vijasank The resource is functional now.  The testing conditions are different than the previous which used the default PDB.  I am going to continue testing and most likely close this issue.

**Comment by hal9000jw** [comment]
I have confirmed the oci_database_pluggable_database resource for remote cloning is working as intended.
