### ISSUE TITLE
OCI Redis Terraform

### ISSUE THREAD

**Issue by teresa-magicbeans** [oracle/terraform-provider-oci#1979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Addition of new resources to manage Redis clusters in Oracle Cloud Infrastructure (OCI) Cache with Redis. Currently, there is only two data sources available (oci_redis_redis_cluster; oci_redis_redis_clusters).

### New or Affected Resource(s)

resource:  oci_redis_redis_cluster (suggested name)

### Potential Terraform Configuration
```hcl
resource "oci_redis_redis_cluster" "test_redis_cluster" {
  compartment_id = var.compartment_ocid
  display_name = var.redis_cluster_display_name
  node_count = 1
  // or other required configurations for a Redis cluster in OCI.
}
```

### References

https://registry.terraform.io/providers/oracle/oci/latest/docs/data-sources/redis_redis_cluster
https://registry.terraform.io/providers/oracle/oci/latest/docs/data-sources/redis_redis_clusters
https://www.oracle.com/cloud/redis/

**Comment by malaiwah** [comment]
I do notice as well the resource is not in the documentation and only data sources are listed, but it is indeed in the example at: https://github.com/oracle/terraform-provider-oci/blob/d25a2316e70c22806dde09112413dcb8e878229d/examples/redis/redis_cluster/main.tf#L77

```
resource "oci_redis_redis_cluster" "test_redis_cluster" {
```

I tested using the `oci` provider 5.17 and the resource is a valid one.
All in all, it seems the miss is on the documentation listed on the Terraform site, as the documentation exists in the GitHub at: https://github.com/oracle/terraform-provider-oci/blob/d25a2316e70c22806dde09112413dcb8e878229d/website/docs/r/redis_redis_cluster.html.markdown

**Comment by lra** [comment]
The documentation does exists: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/redis_redis_cluster
But it's not searchable or cannot be discovered.
This must be a doc bug.

**Comment by teresa-magicbeans** [comment]
Thank you @malaiwah and @lra.
