### ISSUE TITLE
5.17.0 and 5.18.0 documentation page is missing oci_osmanagement_managed_instance from navigation tree

### ISSUE THREAD

**Issue by jeliker** [oracle/terraform-provider-oci#1981]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v1.5.3
on darwin_amd64
+ provider registry.terraform.io/oracle/oci v5.17.0

### Affected Resource(s)
affected_resources = oci_osmanagement_managed_instance, oci_osmanagement_managed_instance_group, oci_osmanagement_managed_instance_management, oci_osmanagement_software_source

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Expected Behavior
Documentation should have oci_osmanagement_managed_instance (and other osmanagement resources) in navigation tree.

### Actual Behavior
Documentation does not have oci_osmanagement_managed_instance (and other osmanagement resources) in navigation tree.

### Steps to Reproduce
I can browse directly to the resource here https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/osmanagement_managed_instance

. . . but I cannot find it in the navigation tree. See here where it is present in 5.16.0 version https://registry.terraform.io/providers/oracle/oci/5.16.0/docs/data-sources/osmanagement_managed_instance
![image](https://github.com/oracle/terraform-provider-oci/assets/590333/94bbd4b0-f6b8-414a-b33d-91158380a0d3)

Notice is missing from navigation tree here in 5.18.0 (and 5.17.0) versions https://registry.terraform.io/providers/oracle/oci/5.18.0/docs/data-sources/osmanagement_managed_instance
![image](https://github.com/oracle/terraform-provider-oci/assets/590333/a997c659-6e95-4214-93cc-6eec76f85a07)

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
Issue is resolved now
