### ISSUE TITLE
Add support for OCI Database with PostgreSQL

### ISSUE THREAD

**Issue by lra** [oracle/terraform-provider-oci#1995]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We need to terraform some PostgreSQL resources using the newly released [OCI Database with PostgreSQL](https://blogs.oracle.com/cloud-infrastructure/post/oci-database-postgres).

Or is it already supported under the `oci_psql_db_*` set of resources? It's unclear.

Thanks!

**Comment by dhoogfr** [comment]
@lra The oci_psql_db_* resources are indeed the ones intended for the PostgreSQL database systems and configurations

**Comment by lra** [comment]
OK thanks for clarifying.
