### ISSUE TITLE
Running resource manager stack from the console fails

### ISSUE THREAD

**Issue by pguerin3** [oracle/terraform-provider-oci#1999]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Resource manager stack  from the console:

https://github.com/oracle/terraform-provider-oci/tree/master/examples/always_free

This is the setting in the console:

![2023-11-29_18-14](https://github.com/oracle/terraform-provider-oci/assets/47326729/17c597c4-c65a-447a-8613-f960418244af)

### Affected Resource(s)

affected_resources = terraform

### Terraform Configuration Files

This is the setting in the console:

![2023-11-29_18-16](https://github.com/oracle/terraform-provider-oci/assets/47326729/9ad08a65-f99b-47b3-94ab-1fd4753b90bf)

https://github.com/oracle/terraform-provider-oci/tree/master/examples/always_free

### Debug Output

The resource stack job has the following log:

```
Getting providers from hashicorp registry and/or custom terraform providers
Initializing provider plugins...
- Finding latest version of hashicorp/oci...
- Finding latest version of hashicorp/tls...
- Installing hashicorp/oci v5.21.0...
- Installed hashicorp/oci v5.21.0 (unauthenticated)
- Installing hashicorp/tls v4.0.5...
- Installed hashicorp/tls v4.0.5 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
Warning: Incomplete lock file information for providers
Due to your customized provider installation methods, Terraform was forced to
calculate lock file checksums locally for the following providers:
  - hashicorp/oci
The current .terraform.lock.hcl file only includes checksums for linux_amd64,
so Terraform running on another platform will fail to install these
providers.
To calculate additional checksums for another platform, run:
  terraform providers lock -platform=linux_amd64
(where linux_amd64 is the platform to generate)
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Error: Invalid Configuration for Read-Only Attribute
  with tls_self_signed_cert.example,
  on main.tf line 301, in resource "tls_self_signed_cert" "example" 
 301:   key_algorithm   = "ECDSA"
Cannot set value for this attribute as the provider has marked it as
read-only. Remove the configuration line setting the value.
Refer to the provider documentation or contact the provider developers for
additional information about configurable and read-only attributes that are
supported. 

```

### Panic Output

none

### Expected Behavior

The resource stack is supposed to complete successfully.

### Actual Behavior

```
Error: Invalid Configuration for Read-Only Attribute
  with tls_self_signed_cert.example,
  on main.tf line 301, in resource "tls_self_signed_cert" "example" 
 301:   key_algorithm   = "ECDSA"
```

### Steps to Reproduce

https://github.com/oracle/terraform-provider-oci/tree/master/examples/always_free

Start at the magic button:

![2023-11-29_18-28](https://github.com/oracle/terraform-provider-oci/assets/47326729/44028241-111a-4ffc-b501-a7b990c73b80)

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by ravinitp** [comment]
tls is not managed by OCI. This is managed by hashicorp.

https://github.com/hashicorp/terraform-provider-tls

Please report your issue here
https://github.com/hashicorp/terraform-provider-tls/issues
