### ISSUE TITLE
oci_log_analytics_namespaces attributes are wrong

### ISSUE THREAD

**Issue by lawsontyler** [oracle/terraform-provider-oci#2022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/consul v2.20.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/oracle/oci v5.21.0

### Affected Resource(s)

oci_log_analytics_namespaces

### Expected Behavior

https://registry.terraform.io/providers/oracle/oci/latest/docs/data-sources/log_analytics_namespaces#attributes-reference

According to the docs, it looks like we should have:
```
data "oci_log_analytics_namespaces" "foo" {
  compartment_id = "..."
}

resource "oci_log_analytics_namespace" "audit_logs" {
  compartment_id = "..."
  is_onboarded   = true
  namespace      = data.oci_log_analytics_namespaces.foo.namespace_collection[0].namespace
}
```

### Actual Behavior
The resource is actually accessed like this:
```
data "oci_log_analytics_namespaces" "foo" {
  compartment_id = "..."
}

resource "oci_log_analytics_namespace" "audit_logs" {
  compartment_id = "..."
  is_onboarded   = true
  namespace      = data.oci_log_analytics_namespaces.foo.namespace_collection[0].items[0].namespace
}
```

There's no reference to "items" in the documentation at all.  Why is there a list inside a list?  It doesn't make a lot of sense to the end user and I was forced to discover the right thing by interpreting the error messages of successive `terraform plan`s.

Please either update the documentation to let the user know that `namespace_collection` is a list of `items` lists or fix the results so that `namespace_collection` _is_ the list of items, making it align with the documentation.

### Steps to Reproduce

1. `terraform apply`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by vneekhra1** [comment]
Hi @lawsontyler,

Thanks for reporting the Issue. 

Indeed there is an issue with the documentation. We have the changes ready, waiting for it to be release.

**Comment by vneekhra1** [comment]
Hi @lawsontyler, 

we have release the documentation fix. Please have look [here](https://registry.terraform.io/providers/oracle/oci/latest/docs/data-sources/log_analytics_namespace).
