### ISSUE TITLE
resource oci_log_analytics_namespace doesn't support import

### ISSUE THREAD

**Issue by lawsontyler** [oracle/terraform-provider-oci#2023]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/oracle/oci v5.24.0

### Affected Resource(s)

resource oci_log_analytics_namespace

### Expected Behavior

Resource is imported

### Actual Behavior

```
╷
│ Error: resource oci_log_analytics_namespace doesn't support import
│
│
╵
```

### Steps to Reproduce

With a resource like:
```
resource "oci_log_analytics_namespace" "audit_logs" {
  compartment_id = "..."
  is_onboarded   = true
  namespace      = "ax..."
}
```
When I run:
```
terraform import oci_log_analytics_namespace.audit_logs ax...
```

I get the error above.

### Important Factoids

Somebody onboarded us in the GUI, but now I can't track that in Terraform.  I can't do `terraform apply` because I get a _different_ error about already being onboarded.

### References
https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/log_analytics_namespace#import

Your documentation explicitly says it can be imported.  Please either remove this from the documentation or update the resource so it can be imported.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by vneekhra1** [comment]
Hi @lawsontyler, 

Thanks for reporting the issue. 

In the terraform-provider-oci version - 5.42.0, I have the fixed the import issue for the oci_log_analytics_namespace

Example -
```shell
terraform import oci_log_analytics_namespace.test_namespace "compartmentId/{compartmentId}/namespace/{namespace}"
```
