### ISSUE TITLE
remote pdb clone completes prematurely

### ISSUE THREAD

**Issue by hal9000jw** [oracle/terraform-provider-oci#2034]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.6.4
on linux_amd64

provider registry.terraform.io/oracle/oci v5.26.0

### Affected Resource(s)

oci_database_pluggable_databases_remote_clone

### Terraform Configuration Files

```hcl
resource "oci_database_pluggable_databases_remote_clone" "remote_clone" {
  cloned_pdb_name                    = "pdb1"
  pluggable_database_id              = data.terraform_remote_state.db_erp_dev.outputs.pdbs["pdb2"].pdb_id
  source_container_db_admin_password = data.terraform_remote_state.db_erp_dev.outputs.admin_password
  should_pdb_admin_account_be_locked = true
  target_container_database_id       = module.database.cdb_id
  target_tde_wallet_password         = module.database.tde_wallet_password
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The terraform resource should report successful completion only when the PDB transitions from the provisioning to available state.  If the PDB fails to provision, the failure should be reported.

### Actual Behavior

Regardless of the PDB's end state, the resource reports successful completion within seconds of execution.  This causes problems for subsequent resource executions that depend on the remote clone's results.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

None

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by hal9000jw** [comment]
Since the `oci_database_pluggable_database` resource has replaced the `oci_database_pluggable_databases_remote_clone` resource for remote pdb cloning and the `oci_database_pluggable_database` resource does not exhibit the issue, I am closing this bug request.
