### ISSUE TITLE
oci_network_load_balancer_network_load_balancer : request_endpoint : no such host

### ISSUE THREAD

**Issue by neleshgoel** [oracle/terraform-provider-oci#2037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/oracle/oci v5.24.0

i've tried also oracle/oci module v5.26.0and the latest oracle oci module

### Affected Resource(s)

oci_network_load_balancer_network_load_balancer

### Terraform Configuration Files
nlb.tf

```hcl
resource "oci_network_load_balancer_network_load_balancer" "network_load_balancer" {
  compartment_id = var.compartment_id
  display_name   = var.network_load_balancer_display_name
  subnet_id      = var.subnet_id

  is_preserve_source_destination = var.network_load_balancer_is_preserve_source_destination
  is_private                     = var.network_load_balancer_is_private
  network_security_group_ids     = var.network_load_balancer_network_security_group_ids
  nlb_ip_version                 = var.network_load_balancer_nlb_ip_version

  reserved_ips {
    id = var.network_load_balancer_reserved_ips_id
  }

  defined_tags  = var.defined_tags
  freeform_tags = var.freeform_tags
}
```

### Debug Output

Tried creating a Network Load Balancer using OCI CLI and  request endpoint is different than the one using terraform
request_endpoint": "POST https://network-load-balancer-api.eu-amsterdam-1.oci.oraclecloud.com/20200501/networkLoadBalancers",

nslookup network-load-balancer-api.eu-amsterdam-1.oci.oraclecloud.com
Server:         fe80::3aa6:59ff:fec2:5947%14
Address:        fe80::3aa6:59ff:fec2:5947%14#53

Non-authoritative answer:
network-load-balancer-api.eu-amsterdam-1.oci.oraclecloud.com    canonical name = splat-api.eu-amsterdam-1.oci.oraclecloud.com.
Name:   splat-api.eu-amsterdam-1.oci.oraclecloud.com
Address: 140.204.36.196
### Panic Output

module.network_load_balancer.oci_network_load_balancer_network_load_balancer.network_load_balancer: Creating...
╷
│ Error: Post "https://network-load-balancer-api.eu-amsterdam.oci.oraclecloud.com/20200501/networkLoadBalancers": dial tcp: lookup network-load-balancer-api.eu-amsterdam.oci.oraclecloud.com: no such host

### Expected Behavior

Oracle Network Load Balancer should have been created

### Actual Behavior

TF APPLY fails with error Error: Post "https://network-load-balancer-api.eu-amsterdam.oci.oraclecloud.com/20200501/networkLoadBalancers": dial tcp: lookup network-load-balancer-api.eu-amsterdam.oci.oraclecloud.com: no such host.

 nslookup network-load-balancer-api.eu-amsterdam.oci.oraclecloud.com
Server:         fe80::3aa6:59ff:fec2:5947%14
Address:        fe80::3aa6:59ff:fec2:5947%14#53

** server can't find network-load-balancer-api.eu-amsterdam.oci.oraclecloud.com: NXDOMAIN

### Steps to Reproduce

1. `terraform apply`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by neleshgoel** [comment]
Tried a redeployment and apparently request_endpoint": "POST https://network-load-balancer-api.eu-amsterdam-1.oci.oraclecloud.com/20200501/networkLoadBalancers" is correct and able to create a NLB.

Issue can be closed !!
