### ISSUE TITLE
oci_dns_record nor oci_dns_rrset are able to create NS records with the 4 nameservers

### ISSUE THREAD

**Issue by Pela2silveira** [oracle/terraform-provider-oci#2039]
### Terraform Version and Provider Version 

I am using latest suported by Oracle Resource Manager

terraform version
Terraform v1.2.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/helm v2.12.1
+ provider registry.terraform.io/hashicorp/http v3.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/time v0.10.0
+ provider registry.terraform.io/oracle/oci v5.21.0

### Affected Resource(s)

 - oci_dns_record
 - oci_dns_rrset 

### Terraform Configuration Files

```hcl


resource "oci_dns_rrset" "preprod_record" {
  #Required
  zone_name_or_id = var.root_zone_ocid
  domain          = "test.app.com.ar"
  rtype           = "NS"

   items {
        #Required
        domain = "test.app.com.ar"
        rdata = <<-EOT
                ns1.xx.dns.oraclecloud.net.
                ns2.xx.dns.oraclecloud.net.
                ns3.xx.dns.oraclecloud.net.
                ns4.xx.dns.oraclecloud.net.
            EOT
        rtype           = "NS"
        ttl = "3600"    
  }
```

### Debug Output

It creates the resource but with only one nameserver, the first one

### Expected Behavior

a flag is missing to accept rdata advance mode input

### Actual Behavior

It took only the first nameserver
### Steps to Reproduce

1. `terraform apply --auto-approve`

### Important Factoids

no special considerations

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by tfountain** [comment]
An rrset is a collection of DNS records with the same domain (FQDN) and rtype. You are trying to create four records, so you need four items:

```
resource "oci_dns_rrset" "preprod_record" {
  #Required
  zone_name_or_id = var.root_zone_ocid
  domain          = "test.app.com.ar"
  rtype           = "NS"

  items {
        domain = "test.app.com.ar"
        rdata = "ns1.xx.dns.oraclecloud.net."
        rtype = "NS"
        ttl = "3600"    
  }
  items {
        domain = "test.app.com.ar"
        rdata = "ns2.xx.dns.oraclecloud.net."
        rtype = "NS"
        ttl = "3600"    
  }
 [etc...]
}
```
The "advanced mode" you mentioned is a UI-specific thing where you can add multiple entries into a single text box. The UI translates those into individual records behind the scenes.

**Comment by Pela2silveira** [comment]
Thank you @tfountain

**Comment by Pela2silveira** [comment]
Perhaphs is useful to someone

```hcl
resource "oci_dns_rrset" "preprod_record" {
  #Required
  zone_name_or_id = var.root_zone_ocid
  domain          = var.preprod_zone_name
  rtype           = "NS"

  dynamic "items" {
    for_each = oci_dns_zone.preprod_zone.nameservers
    content {
      # Required
      domain = var.preprod_zone_name
      rdata  = items.value.hostname
      rtype  = "NS"
      ttl    = "3600"
    }
  }
}
```
