### ISSUE TITLE
data safe dataguard support bug

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#2043]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

terraform version: 1.5.4
oci provider version: 5.28.0

### Affected Resource(s)

oci_data_safe_target_database

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Expected Behavior

1. data safe should register the target database both in primary mode and in standby mode
2. data safe should detect the autonomous database primary/standby status change during failover and failback, then update the target database connection status according.

### Actual Behavior

As per release notes, as of version 5.25.0, data safe should support data guard. however, with an autonomous database with cross region dataguard, the data safe target database resource fails to create registration on the standby database. Also after registering the standby database by failing over the primary to standby node, then upon failback to primary, the registered target database connection to the origin primary database node fails with "username/password incorrect" error.
Could you please elaborate what this data safe support for active data guard means as stated in release notes for version 5.25.0?

### Steps to Reproduce

1. have an autonomous database with primary node and cross-region standby node
2. use data_safe_target_database resource to create connection to both primary and standby node, primary will succeed and standby will fail
3. failover and failback autonomous database primary and standby a few times and wait enough time in between, verify target database connection status, both connections to primary and standby would fail, either with username/password incorrect error, or cannot connect to database error.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by psomashe** [comment]
Thank you for reporting the issue. 
Data Safe does provide support active data guard enabled databases of DBCS, ExaCC and On-premises database types. It does not provide support for other database types like Autonomous Database.

**Comment by sagarp337** [comment]
Response from service team -
Data Safe does provide support active data guard enabled databases of DBCS, ExaCC and On-premises database types. It does not provide support for other database types like Autonomous Database.
