### ISSUE TITLE
compartment dependent resources fail to deploy in montreal on first run

### ISSUE THREAD

**Issue by luckeyca** [oracle/terraform-provider-oci#2065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.5.4
on linux_amd64
+ provider registry.terraform.io/oracle/oci v5.33.0

### Affected Resource(s)

oci_identity_compartment

### Terraform Configuration Files

```hcl
provider "oci" {
  region = "ca-toronto-1"
}

provider "oci" {
  alias  = "montreal"
  region = "ca-montreal-1"
}

resource "oci_identity_compartment" "this" {
  compartment_id = "ocid1.compartment.oc1..xxxxxxxxx"
  description    = "test compartment"
  name           = "test-compartment"
  enable_delete  = true
}

resource "oci_logging_log_group" "this" {
  provider       = oci.montreal
  compartment_id = oci_identity_compartment.this.id
  display_name   = "test-log-group"
  description    = "test log group"
}
```

### Debug Output

```
$ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # oci_identity_compartment.this will be created
  + resource "oci_identity_compartment" "this" {
      + compartment_id = "ocid1.compartment.oc1..xxxxxxxx"
      + defined_tags   = (known after apply)
      + description    = "test compartment"
      + enable_delete  = true
      + freeform_tags  = (known after apply)
      + id             = (known after apply)
      + inactive_state = (known after apply)
      + is_accessible  = (known after apply)
      + name           = "test-compartment"
      + state          = (known after apply)
      + time_created   = (known after apply)
    }

  # oci_logging_log_group.this will be created
  + resource "oci_logging_log_group" "this" {
      + compartment_id     = (known after apply)
      + defined_tags       = (known after apply)
      + description        = "test log group"
      + display_name       = "test-log-group"
      + freeform_tags      = (known after apply)
      + id                 = (known after apply)
      + state              = (known after apply)
      + time_created       = (known after apply)
      + time_last_modified = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
oci_identity_compartment.this: Creating...
oci_identity_compartment.this: Creation complete after 9s [id=ocid1.compartment.oc1..aaaaaaaa44cdwx23n6xozuoosqg27vuht6mxvl73ccdis3elpew6fhvecfwq]
oci_logging_log_group.this: Creating...
╷
│ Error: 404-NotAuthorizedOrNotFound, Authorization failed or requested resource not found.
│ Suggestion: Either the resource has been deleted or service Logging Log Group need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/logging_log_group
│ API Reference: https://docs.oracle.com/iaas/api/#/en/logging-management/20200531/LogGroup/CreateLogGroup
│ Request Target: POST https://logging.ca-montreal-1.oci.oraclecloud.com/20200531/logGroups
│ Provider version: 5.33.0, released on 2024-03-13.
│ Service: Logging Log Group
│ Operation Name: CreateLogGroup
│ OPC request ID: edc66fd79dea5c7edd000c26f11f1dd3/5D222215EC374ACC8476380C447FBF83/50463A329CFCEA0F802B965F8816F8DB
│
│
│   with oci_logging_log_group.this,
│   on main.tf line 20, in resource "oci_logging_log_group" "this":
│   20: resource "oci_logging_log_group" "this" {
│
╵
$ terraform apply -auto-approve
oci_identity_compartment.this: Refreshing state... [id=ocid1.compartment.oc1..xxxxxx]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # oci_logging_log_group.this will be created
  + resource "oci_logging_log_group" "this" {
      + compartment_id     = "ocid1.compartment.oc1..xxxxxxxx"
      + defined_tags       = (known after apply)
      + description        = "test log group"
      + display_name       = "test-log-group"
      + freeform_tags      = (known after apply)
      + id                 = (known after apply)
      + state              = (known after apply)
      + time_created       = (known after apply)
      + time_last_modified = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
oci_logging_log_group.this: Creating...
oci_logging_log_group.this: Creation complete after 0s [id=ocid1.loggroup.oc1.ca-montreal-1.amaaaaaa5xeuumqaf4vkot27lw3bhezflaok4um7kog4nnfzebxxdjpbxcgq]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
### Expected Behavior

the compartment should be created first and then log group should be created in montreal region.

### Actual Behavior

the compartment was created successfully, but log group deployment to montreal fails on the first run, but deployed fine by IMMEDIATELY(use command history by pressing upper arrow key on the keyword which minimize the delay to 1-2 seconds) re-run the same terraform apply command. This problem does NOT happen with toronto region.

I have re-created the same issue with multiple other resources that have dependencies on compartment, such as vcn and drg.
Also add explicit depends_on argument doesn't help with the issue.

the two workarounds are: 

1. re-run even IMMEDIATELY without any pause in between using command line history
2. use null resource or time_sleep resource to add as little as ONE second sleeper delay.

### Steps to Reproduce

1. use the terraform code example above, for the child resource depends on compartment sources, I have tested log group, vcn and drg, but suspect it would apply to all the children resource types that have dependencies on compartment
2. terraform apply -auto-approve
3. it should fails to deploy child resource, log group in this case, in montreal region on the first run
4. re-run terraform apply -auto-approve immediately using command history. deployment will succeed.
5. remove or comment out the provider alias argument from the child resource which will deploy the resource in toronto region. This will NOT have the problem described above.

### Important Factoids

only happens to region specific resource deployed to Montreal region that has dependency on compartment creation which is not region specific.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by aabulbul** [comment]
Please allow sometime between creation and reading for compartments by using [time_sleep](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) terraform resource utility, for upto a minute:

```
resource "oci_identity_compartment" "this" {
  # Usual arguments
}

resource "time_sleep" "wait_1_minute" {
  depends_on = [oci_identity_compartment.this]

  create_duration = "1m"
}

# This block  will fetch the compartment (at least) 1 minute after oci_identity_compartment.network
resource "oci_logging_log_group" "this" {
  compartment_id = oci_identity_compartment.this.id
  # Other arguments
}
```

**Comment by luckeyca** [comment]
Hi @aabulbul, I have been using the time_sleep already before reporting this problem. time_sleep does work as a workaround. However, as terraform best practice, time_sleep should only be used as last resort and as a workaround. Hence I reported this issue so that you can fix the problem from the root.

**Comment by aabulbul** [comment]
@luckeyca : This is the behavior of compartments by design and an expected behavior.

**Comment by luckeyca** [comment]
Hi @aabulbul, I respectfully disagree that this should be a designed behavior, but something should be handled by developement.
As per terraform, see article here: https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep, time_sleep resource is largely designed as a workaround, NOT a solution for other resources that don't handle their time dependencies well. Please forward this article to your development and have them fix the issue.

**Comment by aabulbul** [comment]
@luckeyca . Compartments are special kind of resources used for managing OCI resources under them. Keeping this in mind and the underlying architecture to best support OCI resources, its own lifecycle and IAM authorization, we went with this design where they cannot be immediately read after creation. Thus, this isn't a bug but a behavior by design.

**Comment by becky-intelletive** [comment]
Is there an OCI CLI command that could check whether the compartment is available?

**Comment by becky-intelletive** [comment]
Using time_sleep is less than ideal.

Consider a terraform projects that creates 3 nested compartments then manages resources inside of them.

Whenever the compartments are created, the 1min `time_sleep` is necessary after creation of each compartment.

Whenever the compartments are updated or left alone, the `time_sleep` _runs anyway_, increasing the length of the Terraform job by 3m unnecessarily.

Now multiply that by 50 clients, each with 3 sets of nested compartments, all managed by the same Terraform project. Suddenly that's 150m added - that's _two and a half hours_.

It doesn't scale.

**Comment by luckeyca** [comment]
not just less than ideal, this, among other thing, breaks the fundamental principle of being terraform as declarative programming language as compared to imperative programming. Given the replication is expected, it's provider developer, in this case Oracle's responsibility to handle the delay using their backend APIs instead of asking client to do unreliable workaround like time_sleep. I am escalating this
