### ISSUE TITLE
Terraform import Error: "can not marshal to path in request for field NetworkLoadBalancerId. Due to can not marshal a nil pointer"

### ISSUE THREAD

**Issue by RyanMarkoff-eaton** [oracle/terraform-provider-oci#2066]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform 1.3 and provider 5.9.0

### Affected Resource(s)

"oci_network_load_balancer_backend_set", and "oci_network_load_balancer_network_load_balancer"

### Terraform Configuration Files
This terraform code was generated from Oracle's CD3 utility here: [(https://github.com/oracle-devrel/cd3-automation-toolkit)](https://github.com/oracle-devrel/cd3-automation-toolkit) and has occurred with the Load Balancer and Network Load Balancer resource types in my environment. 

### Expected Behavior
Terraform import using an existing OCI resource using its ocid as instructed here: [(https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/load_balancer_backend#import)]

### Actual Behavior

Terraform imports fail and report the error "can not marshal to path in request for field NetworkLoadBalancerId. Due to can not marshal a nil pointer". Note that this issue has also been seen with the other OCI Load Balancer. 

### Steps to Reproduce
Just running this import statement below fails, and variants of which also failed similar to the other github issue linked below. 
1. `terraform import module.nlb-backends[\"oci-lb-resource\"].oci_network_load_balancer_backend.backend 'NetworkLoadBalancerId/ocid1.networkloadbalancer.details.withheld/backend-sets/<load_bal>/backends'`

### References
This appears to be a similar bug as this reported issue: [https://github.com/oracle/terraform-provider-oci/issues/1726](https://github.com/oracle/terraform-provider-oci/issues/1726)

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by aseerapu** [comment]
> _terraform import module.nlb-backends[\"oci-lb-resource\"].oci_network_load_balancer_backend.backend 'NetworkLoadBalancerId/ocid1.networkloadbalancer.details.withheld/backend-sets/<load_bal>/backends'

What are you providing <load_bal> value ? this is supposed to be backen set name.

**Comment by aseerapu** [comment]
> terraform import module.nlb-backends["oci-lb-resource"].oci_network_load_balancer_backend.backend 'NetworkLoadBalancerId/ocid1.networkloadbalancer.details.withheld/backend-sets/<load_bal>/backends'

What are you providing <load_bal> value ? this is supposed to be backend set name.

**Comment by RyanMarkoff-eaton** [comment]
> > terraform import module.nlb-backends["oci-lb-resource"].oci_network_load_balancer_backend.backend 'NetworkLoadBalancerId/ocid1.networkloadbalancer.details.withheld/backend-sets/<load_bal>/backends'
> 
> What are you providing <load_bal> value ? this is supposed to be backend set name.

I was using the backend set name, it was just placeholder value.

**Comment by aseerapu** [comment]
Can you please try this way? https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/network_load_balancer_backend

> $ terraform import module.nlb-backends["oci-lb-resource"].oci_network_load_balancer_backend.backend "networkLoadBalancers/{networkLoadBalancerId}/backendSets/{backendSetName}/backends/{backendName}"

**Comment by RyanMarkoff-eaton** [comment]
> Can you please try this way? https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/network_load_balancer_backend
> 
> > $ terraform import module.nlb-backends["oci-lb-resource"].oci_network_load_balancer_backend.backend "networkLoadBalancers/{networkLoadBalancerId}/backendSets/{backendSetName}/backends/{backendName}"

The next time I import one I'll try that and reply back. Thanks.

**Comment by aseerapu** [comment]
Sure, Please re open the issue if the issue still persists.

**Comment by aseerapu** [comment]
is it ok to resolve this ticket now and re open this if the issue still persists ?

**Comment by aseerapu** [comment]
https://docs.oracle.com/en-us/iaas/Content/NetworkLoadBalancer/BackendSets/list-backend-set.htm#top
```

1. Open the navigation menu, click Networking, and then click Load balancers. Click Network load balancer. The Network load balancers page appears.
2. Select the Compartment from the list. All network load balancers in that compartment are listed in tabular form.
3. Select a State from the list to limit the network load balancers displayed to that state.
4. Select the network load balancer containing the backend sets that you want to list. The network load balancer's Details page appears.
5. Click Backend sets under Resources. The Backend sets list appears. All backend sets are listed in tabular form.
```

**Comment by aseerapu** [comment]
Please provide name while creating backend 
https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/network_load_balancer_backend
if name is not provided then by default name will be set based on the ipaddress and port with format as "ipaddress:port"
