### ISSUE TITLE
Unable to update ExaCS VM Cluster Data Safe target (Related to #1853)

### ISSUE THREAD

**Issue by davcosentino** [oracle/terraform-provider-oci#2097]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform version: 1.7.4
Provider version: 5.38.0, released on 2024-04-17

### Affected Resource(s)

affected_resources = oci_data_safe_target_database

### Terraform Configuration Files

```hcl
resource "oci_data_safe_target_database" "test_target_database" {
    #Required
    compartment_id = var.compartment_id
    database_details {
        #Required
        database_type = var.target_database_database_details_database_type
        infrastructure_type = var.target_database_database_details_infrastructure_type

        #Optional
        autonomous_database_id = oci_database_autonomous_database.test_autonomous_database.id
        db_system_id = oci_database_db_system.test_db_system.id
        instance_id = oci_core_instance.test_instance.id
        ip_addresses = var.target_database_database_details_ip_addresses
        listener_port = var.target_database_database_details_listener_port
        service_name = oci_core_service.test_service.name
        vm_cluster_id = oci_database_vm_cluster.test_vm_cluster.id
    }

    #Optional
    connection_option {
        #Required
        connection_type = var.target_database_connection_option_connection_type

        #Optional
        datasafe_private_endpoint_id = oci_dataflow_private_endpoint.test_private_endpoint.id
        on_prem_connector_id = oci_data_safe_on_prem_connector.test_on_prem_connector.id
    }
    credentials {
        #Required
        password = var.target_database_credentials_password
        user_name = oci_identity_user.test_user.name
    }
    defined_tags = {"Operations.CostCenter"= "42"}
    description = var.target_database_description
    display_name = var.target_database_display_name
    freeform_tags = {"Department"= "Finance"}
    tls_config {
        #Required
        status = var.target_database_tls_config_status

        #Optional
        certificate_store_type = var.target_database_tls_config_certificate_store_type
        key_store_content = var.target_database_tls_config_key_store_content
        store_password = var.target_database_tls_config_store_password
        trust_store_content = var.target_database_tls_config_trust_store_content
    }
}
```

### Expected Behavior

With infrastructure_type=ORACLE_CLOUD and database_type=DATABASE_CLOUD_SERVICE, I should be able to update (change password) an ExaCS VM Cluster Data Safe target by setting vm_cluster_id=\<VM Cluster OCID\>.

### Actual Behavior

When I try to update (change password) ExaCS VM Cluster Data Safe target by setting infrastructure_type=ORACLE_CLOUD, database_type=DATABASE_CLOUD_SERVICE and vm_cluster_id=\<VM Cluster OCID\>, I get the following error: **400-InvalidParameter, The cloud database system id cannot be an empty string.**

### Steps to Reproduce

1. `terraform apply`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.
