### ISSUE TITLE
data source in oci_network_load_balancer_network_load_balancers should have attribute reference items before accessing any attributes internal to network_load_balancer_collection

### ISSUE THREAD

**Issue by hjain28** [oracle/terraform-provider-oci#2105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

data "oci_network_load_balancer_network_load_balancers" "name" {
  #Required
  compartment_id = abc
  display_name = "xyz"
  state = "ACTIVE"
}

for ip address to refer it should be 
data.oci_network_load_balancer_network_load_balancers.network_load_balancers_ips.network_load_balancer_collection[0].items[*].ip_addresses

rather than 
data.oci_network_load_balancer_network_load_balancers.network_load_balancers_ips.network_load_balancer_collection[0].ip_addresses

items attribute was missing 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by aseerapu** [comment]
@hjain28 ,
I want to understand the concern here:
1) `data.oci_network_load_balancer_network_load_balancers.network_load_balancers_ips.network_load_balancer_collection[0].ip_addresses` is this working and you are suggesting that structure is incorrect?  why do you think that structure is incorrect?
2)  `data.oci_network_load_balancer_network_load_balancers.network_load_balancers_ips.network_load_balancer_collection[0].ip_addresses` with this ip address fetch is failing?
