### ISSUE TITLE
Cannot enable IPSec over FastConnect

### ISSUE THREAD

**Issue by bogdan-m-darie** [oracle/terraform-provider-oci#2126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
$ terraform -v
Terraform v1.8.3
on linux_amd64
```
### Affected Resource(s)
```oci_core_cpe```
### Terraform Configuration Files
```
resource "oci_core_cpe" "this" {
  compartment_id      = var.compartment_id
  ip_address          = var.ip_address
  cpe_device_shape_id = var.cpe_device_shape_id
  defined_tags        = var.defined_tags
  display_name        = var.display_name
  freeform_tags       = var.freeform_tags
  is_private          = var.is_private
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
There should be an argument to enable IPSec over FastConnect.
### Actual Behavior
IPSec over FastConnect cannot be enabled using Terraform

### Steps to Reproduce

1. `terraform apply`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by bogdan-m-darie** [comment]
"is_private" is the required variable in the "oci_core_cpe" resource for enablement. This is the equivalent of the "Allow IPSec over FastConnect" checkbox for the CPE in the OCI web console.
