### ISSUE TITLE
TF plan showing recreate cluster is needed when a new subnet id is added to output variables

### ISSUE THREAD

**Issue by putharekulu** [oracle/terraform-provider-oci#2146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform 0.13.5 (Used with OCI Shepherd)
OCI provider 5.45.0

### Affected Resource(s)

oci_containerengine_cluster, oci_containerengine_node_pool

### Terraform Configuration Files

```hcl
resource "oci_containerengine_cluster" "cluster" {

  compartment_id       = var.compartment_id
  kubernetes_version = var.controlplane_kubernetes_version
  name               = var.name
  vcn_id             = var.service_vcn_id
  type                 = var.cluster_type

  endpoint_config {
    is_public_ip_enabled = true
    subnet_id            = var.k8s_endpoint_subnet_id
  }

  kms_key_id = var.encrypt_etcd ? var.kms_key_id : null

  options {

    add_ons {
      is_kubernetes_dashboard_enabled = var.is_kubernetes_dashboard_enabled
      is_tiller_enabled               = false
    }

    kubernetes_network_config {
      pods_cidr     = var.pods_cidr
      services_cidr = var.services_cidr
    }

    service_lb_subnet_ids = [var.service_lb_subnet_id]
  }
}

network module

// Test
resource "oci_core_subnet" "test_subnet" {
  cidr_block = 10.10.200.0/24
  compartment_id = var.compartment_id
  vcn_id = oci_core_vcn.service_vcn.id
  prohibit_public_ip_on_vnic = true
  display_name = "test_${oci_core_vcn.service_vcn.display_name}"
  dns_label = "justatest"
}

output "just_a_test" {
  value = oci_core_subnet.test_subnet.id
}
```

### Expected Behavior

With adding a new subnet and output the subnet ID, no changes should be shown in terraform plan for OKE module.

### Actual Behavior

Just add the subnet code and the terraform plan shows just creating of the subnet which is correct.
When I add an output variable to get the id of the new subnet, TF plan shows terminating and rebuilding the oke cluster. Plan shows this change

```
~ endpoint_config { 
            is_public_ip_enabled = true 
          - nsg_ids              = [] -> null 
          ~ subnet_id            = "ocid1.subnet.oc1.iad.xxxxxxxx -> (known after apply) # forces replacement 
        } 
```

### Steps to Reproduce

terraform plan by adding new subnet and output variable

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by putharekulu** [comment]
Can we have any update on this? Thanks

**Comment by joekr** [comment]
Currently updating the subnet id for endpoint_config is now allowed. We've taken a note an will explore this as a possible future feature request.

**Comment by putharekulu** [comment]
I am not updating the subnet id for endpoint_config.....

We migrated to VCN native and added the endpoint_config couple of months ago and the migration is successful. 
Added a new subnet, route tables etc for a new requirement and it is successfully created.
When I try to add  the following output variable and then try to do a terraform plan, that is when the endpoint_config shows as forcing replacement and terraform plan shows deleting and recreating the cluster.

 output "just_a_test" {
  value = oci_core_subnet.test_subnet.id
}

**Comment by XinruXiao-9** [comment]
Hi @putharekulu, could you please check how do you set up var.k8s_endpoint_subnet_id? It could be because you added a new subnet and due to some code setting up, this variable got changed to the newly added subnet.

**Comment by putharekulu** [comment]
@XinruXiao-9 I don't see any issues when a new subnet is added. The issue pops up when an output variable is added.

The following is the code for getting the var.k8s_endpoint_subnet_id

```
subnet_cidrs:
      service:
        newbits: 8
        netnum: 0
      service_lb:
        newbits: 8
        netnum: 2
      service_lb_private:
        newbits: 8
        netnum: 3
      scan:
        newbits: 12
        netnum: 96
      k8s_endpoint:
        newbits: 14
        netnum: 544

// Setting subnet CIDR ranges
  service_subnet_cidr = cidrsubnet(
    var.service_vcn_cidr,
    var.subnet_cidr_map.service.newbits,
    var.subnet_cidr_map.service.netnum
  )
  lb_service_subnet_cidr = cidrsubnet(
    var.service_vcn_cidr,
    var.subnet_cidr_map.service_lb.newbits,
    var.subnet_cidr_map.service_lb.netnum
  )
  lb_service_private_subnet_cidr = cidrsubnet(
    var.service_vcn_cidr,
    var.subnet_cidr_map.service_lb_private.newbits,
    var.subnet_cidr_map.service_lb_private.netnum
  )
  scan_platform_subnet_cidr = cidrsubnet(
    var.service_vcn_cidr,
    var.subnet_cidr_map.scan.newbits,
    var.subnet_cidr_map.scan.netnum
  )
  k8s_endpoint_subnet_cidr = cidrsubnet(
    var.service_vcn_cidr,
    var.subnet_cidr_map.k8s_endpoint.newbits,
    var.subnet_cidr_map.k8s_endpoint.netnum
  )

// Subnet for kubernetes cluster endpoint.
resource "oci_core_subnet" "k8s_endpoint_subnet" {
  cidr_block = local.k8s_endpoint_subnet_cidr
  compartment_id = var.compartment_id
  vcn_id = oci_core_vcn.service_vcn.id
  prohibit_public_ip_on_vnic = false
  route_table_id = oci_core_route_table.k8s_endpoint_subnet_route_table.id
  security_list_ids = [oci_core_security_list.k8s_endpoint_subnet_security_list.id]
  display_name = "k8s_endpoint_${oci_core_vcn.service_vcn.display_name}"
  dns_label = "k8sendpoint"
}

output "k8s_endpoint_subnet" {
  value = try(oci_core_subnet.k8s_endpoint_subnet.id, "")
}

```

**Comment by XinruXiao-9** [comment]
HI @putharekulu , I am not able to repro the issue in my end with simply adding a new subnet and its output to the vcn. Things works well in my end.

can you also show up how you are setting the var.k8s_endpoint_subnet_id? The above code shows how you configured "k8s_endpoint_subnet" but not how you set up the variable of k8s_endpoint_subnet_id.

**Comment by putharekulu** [comment]
@XinruXiao-9 Thanks for looking into this. 

I am passing it to oke module as module
`module "oke_cluster_controlplane" {
  for_each = try(module.config.config.oke, {})
  source   = "./modules/oke"

  name                            = each.value.name
  service_vcn_id                  = module.controlplane_network[each.value.network_module_key].service_vcn
  service_lb_subnet_id            = module.controlplane_network[each.value.network_module_key].service_lb_subnet_id
  service_np_subnet_id            = module.controlplane_network[each.value.network_module_key].service_subnet_id
  compartment_id                  = data.oci_identity_compartments.tier3_compartment[each.value.compartment].compartments.0.id
  pods_cidr                       = each.value.pods_cidr
  services_cidr                   = each.value.services_cidr
  boot_volume_size                = each.value.boot_volume_size
  nodepool_size                   = each.value.nodepool_size
  image_id                        = local.image_map[module.config.config.default_image_type]
  hostclass                       = module.config.config.hostclass
  node_shape                      = each.value.node_shape
  controlplane_kubernetes_version = each.value.kubernetes_version
  memory_in_gbs                   = each.value.memory_in_gbs
  ocpus                           = each.value.ocpus
  is_kubernetes_dashboard_enabled = each.value.dashboard_enabled
  kms_key_id                      = module.vault[each.value.vault_module_key].vault_key_ocid
  nodepools                       = each.value.nodepools
  cluster_type                    = try(each.value.cluster_type, "")
  image_map                       = local.image_map
  cloud_init_file                 = try(each.value.cloud_init_file, "cloud-init.yaml")
  **k8s_endpoint_subnet_id          = try(module.controlplane_network[each.value.network_module_key].k8s_endpoint_subnet, ""**)`

**Comment by XinruXiao-9** [comment]
Hi @putharekulu, is controlplane_network the module you created the subnet? How do you configure each.value.network_module_key? Also can you maybe just output the k8s_endpoint_subnet_id and do terraform output to check that k8s_endpoint_subnet_id is not changed.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by Maxrovr** [comment]
Closing ticket as the reporter is unresponsive
