### ISSUE TITLE
Start versioning the provider binary releases to work w/ Terraform v 0.10.0

### ISSUE THREAD

**Issue by tehmaspc** [oracle/terraform-provider-oci#217]
### Terraform Version

v 0.10.0

In order to get Terraform v 0.10.0 to find the baremetal provider - a version suffix is required on the binary file (apart from installing the binary into the correct plugin dir).

This issue is to raise the need to append the version of the BMC TF provider to the binary files such that the current release looks like this:

terraform.d/plugins/linux_amd64/**terraform-provider-baremetal_v1.0.16**

For more details:
* https://www.terraform.io/upgrade-guides/0-10.html#third-party-provider-plugins
* https://github.com/hashicorp/terraform/issues/15705#issuecomment-320801813

Cheers,
Tehmasp

**Comment by codycushing** [comment]
Thanks for the details. We will likely introduce this with the other pre v.10 incompatible change of removing other provider code from the repo.

**Comment by josephholsten** [comment]
related: just updating the terraform dependency, similar to https://github.com/terraform-providers/terraform-provider-ultradns/pull/3
