### ISSUE TITLE
Broken formatting in docs page of oci_core_instance_configuration

### ISSUE THREAD

**Issue by idkman23** [oracle/terraform-provider-oci#2176]
https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance_configuration
The formatting seems to be broken after [`percentage_of_cores_enabled`](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_instance_configuration#percentage_of_cores_enabled) resulting in a giant wall of text and repeating text.

<img width="1288" alt="image" src="https://github.com/user-attachments/assets/829f9f37-c8ba-4a08-b5a6-68d43e2fc98e">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by AravindOracle** [comment]
This is resolved. Please close it.
