### ISSUE TITLE
API Gateway fails if certificate_id is not provided though it is an optional parameter

### ISSUE THREAD

**Issue by jeliker1** [oracle/terraform-provider-oci#2216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v1.7.4
on darwin_arm64
+ provider registry.terraform.io/oracle/oci v6.13.0

### Affected Resource(s)
affected_resources = oci_apigateway_gateway

### Terraform Configuration Files

```hcl
resource "oci_apigateway_gateway" "api1" {
  #Required
  compartment_id = var.compartment_id
  endpoint_type  = "PRIVATE"
  subnet_id      = var.subnet_id

  display_name = "API1"
}
```

### Debug Output
```hcl
Error: 400-MissingParameter, Missing certificateId
│ Suggestion: Please retry or contact support for help with service: Apigateway Gateway
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/apigateway_gateway 
│ API Reference:  
│ Request Target: POST https://apigateway.us-langley-1.oci.oraclegovcloud.com/20190501/gateways 
│ Provider version: 6.13.0, released on 2024-10-12.  
│ Service: Apigateway Gateway 
│ Operation Name: CreateGateway 
│ OPC request ID: ea0332b0063a90f210845ce0332b04c7/2D178B464DCF74F2106B11878C9215F1/C1A8FFB44DC843E250E63117548CF23F 
```

### Expected Behavior
API Gateway should successfully create without certificate_id value (which is optional)

### Actual Behavior
API Gateway DOES NOT successfully create without certificate_id value (which is optional)

### Steps to Reproduce

1. `terraform apply`

### References
* [CreateGatewayDetails](https://docs.oracle.com/en-us/iaas/api/#/en/api-gateway/20190501/datatypes/CreateGatewayDetails)
   Note `certificateId, Required: no`

**Comment by jeliker1** [comment]
Thinking this could be specific to FedRAMP regions but don't find that documented anywhere. Help!

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by stefanklas** [comment]
API Gateway service is only supporting default certificates in OC1 realms. 

Therefore for DRCC and FedRAMP, customers are required to provide their own custom certificate.

Documentation for this can be found here: https://docs.oracle.com/en-us/iaas/Content/APIGateway/Tasks/apigatewaysettingupcustomdomainscerts.htm

**Comment by jeliker1** [comment]
Thank you for your comments @stefanklas. Though I agree the behavior is as you say (default certificate only works for OC1 but no error if we provide a certificate), the documentation page you shared doesn't make that statement anywhere as far as I can see. I reviewed before opening this bug and also again after you shared the page and don't see that expectation. I am trusting your authority when you say it absolutely is not supported outside of OC1 realm since, as I say, I don't see that spelled out.

The closest is the page suggesting that default certificate only apply to private or non-production. Generally for private we prefer default certificate if only because we then do not have to maintain the certificate renewal!

Can you update the documentation page or otherwise request for that update for that documentation then we can close this ticket as "resolved"?

**Comment by stefanklas** [comment]
Absolutely! I will file an internal ticket to update the documentation to make this clearer. Will update here once this has been published.

**Comment by stefanklas** [comment]
Documentation has not been updated. Closing this ticket.

**Comment by jeliker1** [comment]
That's wonderful! I see the changes and the constraint is very clear now. Thank you.
