### ISSUE TITLE
facing issue with lbr backend set with session persistent

### ISSUE THREAD

**Issue by jmajumde** [oracle/terraform-provider-oci#226]
### Terraform Version

<details>
# Run this command to get the terraform version:
$ terraform -v
Terraform v0.9.4

</details>

### Baremetal Provider Version
Terraform Provider : v1.0.16
<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-baremetal
2017/08/15 20:21:12 [INFO] terraform-provider-baremetal v1.0.16
This binary is a plugin.
</details>

### Description:
While we are creating lbaas backend sets with session persistent flag enabled then looks like the lbaas session persistent does not honored. Though there is no error while creating lbaas backends but unless we login to web console and do a dummy submit for lbaas backendset, application does not work to handle the persistent request.

But, as a w/r the same backendset creation if I do with ruby-sdk apis or direct lbaas rest call this behavior does not happen. 

### Terraform Plan

<details>
This issue is not related to any TF plan execution failures. TF plan execution for lbaas always succeeds

</details>

**Comment by codycushing** [comment]
To clarify, you are saying the property may be defined and changed in your plan but does not change the state of the resource, and you verify this by checking the same resource in the console?

**Comment by jmajumde** [comment]
The state of the resource is also good if you go and check in BM UI console. But the problem is any application which relies session persistent does not work unless from console we do a re-submit of the lbaas backendset even the creation of lbaas backendset is all good from TF

Where as if I create the lbaas backendset with ruby sdk or direct rest API call then thats not the case. Our application works perfectly fine as the session persistent  flag takes in effect for lbaas

**Comment by briangustafson** [comment]
I tried to repro using a modification of the lb_full.tf example, and session persistence worked correctly for me. See the modifications that I used at https://github.com/oracle/terraform-provider-baremetal/commit/28b02a17c737e5d5f781f084382dfbc673d54b00. When you go to the LB public IP, then it should stick to whichever backend it receives first. Is this different from what you were trying?
