### ISSUE TITLE
policy format change in API? causes terraform to rebuild policies

### ISSUE THREAD

**Issue by PeterJamesHarrison** [oracle/terraform-provider-oci#230]
### Terraform Version
Terraform v0.9.11
### terraform-provider-baremetal Version
terraform-provider-baremetal_amd64-1.0.16

I noticed that the policy language format changed every so slightly.  What this actually meant is that I had to update the format of all my policies in Terraform to match the new format.  So as not to cause on going policies updates on every change.

Generally the changes were:
1) if the “where” clause was added it needed an extra space in front of it.
2) if you had a list then there would need to have an extra space after a “{“ and an extra space before an “}” and within the list a “,” needed a space either side.
3) Outside of a list if using a RegEx then you would need to a space either side of the “=“
In any case the handling of the “=“ was different within a list or outside a list.

Below you can see the force changes needed from the Terraform output.

~ baremetal_identity_policy.XXX-NetSec-Admin
    statements.0: "allow group XXX-NetSec-Admins to manage security-lists in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-NetSec-Admins to manage security-lists in tenancy where target.compartment.name=/XXX-*/"
    statements.1: "allow group XXX-NetSec-Admins to manage internet-gateways in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-NetSec-Admins to manage internet-gateways in tenancy where target.compartment.name=/XXX-*/"
    statements.2: "allow group XXX-NetSec-Admins to manage cpes in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-NetSec-Admins to manage cpes in tenancy where target.compartment.name=/XXX-*/"
    statements.3: "allow group XXX-NetSec-Admins to manage ipsec-connections in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-NetSec-Admins to manage ipsec-connections in tenancy where target.compartment.name=/XXX-*/"
    statements.4: "allow group XXX-NetSec-Admins to use virtual-network-family in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-NetSec-Admins to use virtual-network-family in tenancy where target.compartment.name=/XXX-*/"

~ baremetal_identity_policy.XXX-Network-Admin
    statements.0:  "allow group XXX-Network-Admins to manage vcns in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage vcns in tenancy where target.compartment.name=/XXX-*/"
    statements.1:  "allow group XXX-Network-Admins to manage subnets in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage subnets in tenancy where target.compartment.name=/XXX-*/"
    statements.10: "allow group XXX-Network-Admins to manage vnic-attachments in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage vnic-attachments in tenancy where target.compartment.name=/XXX-*/"
    statements.11: "allow group XXX-Network-Admins to manage load-balancers in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage load-balancers in tenancy where target.compartment.name=/XXX-*/"
    statements.15: "allow group XXX-Network-Admins to use virtual-network-family in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to use virtual-network-family in tenancy where target.compartment.name=/XXX-*/"
    statements.2:  "allow group XXX-Network-Admins to manage route-tables in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage route-tables in tenancy where target.compartment.name=/XXX-*/"
    statements.3:  "allow group XXX-Network-Admins to manage dhcp-options in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage dhcp-options in tenancy where target.compartment.name=/XXX-*/"
    statements.4:  "allow group XXX-Network-Admins to manage drgs in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage drgs in tenancy where target.compartment.name=/XXX-*/"
    statements.5:  "allow group XXX-Network-Admins to manage cross-connects in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage cross-connects in tenancy where target.compartment.name=/XXX-*/"
    statements.6:  "allow group XXX-Network-Admins to manage cross-connect-groups in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage cross-connect-groups in tenancy where target.compartment.name=/XXX-*/"
    statements.7:  "allow group XXX-Network-Admins to manage virtual-circuits in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage virtual-circuits in tenancy where target.compartment.name=/XXX-*/"
    statements.8:  "allow group XXX-Network-Admins to manage private-ips in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage private-ips in tenancy where target.compartment.name=/XXX-*/"
    statements.9:  "allow group XXX-Network-Admins to manage vnics in tenancy  where target.compartment.name = /XXX-*/" => "allow group XXX-Network-Admins to manage vnics in tenancy where target.compartment.name=/XXX-*/"

~ baremetal_identity_policy.XXX-Sys-Admin
    statements.0: "allow group XXX-Sys-Admins to manage instance-family in tenancy  where all { target.compartment.name=/XXX-*/ , target.compartment.name!=/XXX-Networks/ , target.compartment.name!=/XXX-SUB-*/ }" => "allow group XXX-Sys-Admins to manage instance-family in tenancy where all {target.compartment.name=/XXX-*/,target.compartment.name!=/XXX-Networks/,target.compartment.name!=/XXX-SUB-*/}"
    statements.1: "allow group XXX-Sys-Admins to manage object-family in tenancy  where all { target.compartment.name=/XXX-*/ , target.compartment.name!=/XXX-Networks/ , target.compartment.name!=/XXX-SUB-*/ }" => "allow group XXX-Sys-Admins to manage object-family in tenancy where all {target.compartment.name=/XXX-*/,target.compartment.name!=/XXX-Networks/,target.compartment.name!=/XXX-SUB-*/}"
    statements.2: "allow group XXX-Sys-Admins to manage volume-family in tenancy  where all { target.compartment.name=/XXX-*/ , target.compartment.name!=/XXX-Networks/ , target.compartment.name!=/XXX-SUB-*/ }" => "allow group XXX-Sys-Admins to manage volume-family in tenancy where all {target.compartment.name=/XXX-*/,target.compartment.name!=/XXX-Networks/,target.compartment.name!=/XXX-SUB-*/}"
    statements.3: "allow group XXX-Sys-Admins to use load-balancers in tenancy  where all { target.compartment.name=/XXX-*/ , target.compartment.name!=/XXX-Networks/ , target.compartment.name!=/XXX-SUB-*/ }" => "allow group XXX-Sys-Admins to use load-balancers in tenancy where all {target.compartment.name=/XXX-*/,target.compartment.name!=/XXX-Networks/,target.compartment.name!=/XXX-SUB-*/}"
    statements.4: "allow group XXX-Sys-Admins to use subnets in tenancy  where all { target.compartment.name=/XXX-*/ , target.compartment.name!=/XXX-Networks/ , target.compartment.name!=/XXX-SUB-*/ }" => "allow group XXX-Sys-Admins to use subnets in tenancy where all {target.compartment.name=/XXX-*/,target.compartment.name!=/XXX-Networks/,target.compartment.name!=/XXX-SUB-*/}"
    statements.5: "allow group XXX-Sys-Admins to use private-ips in tenancy  where all { target.compartment.name=/XXX-*/ , target.compartment.name!=/XXX-Networks/ , target.compartment.name!=/XXX-SUB-*/ }" => "allow group XXX-Sys-Admins to use private-ips in tenancy where all {target.compartment.name=/XXX-*/,target.compartment.name!=/XXX-Networks/,target.compartment.name!=/XXX-SUB-*/}"
    statements.6: "allow group XXX-Sys-Admins to use vnics in tenancy  where all { target.compartment.name=/XXX-*/ , target.compartment.name!=/XXX-Networks/ , target.compartment.name!=/XXX-SUB-*/ }" => "allow group XXX-Sys-Admins to use vnics in tenancy where all {target.compartment.name=/XXX-*/,target.compartment.name!=/XXX-Networks/,target.compartment.name!=/XXX-SUB-*/}"
    statements.7: "allow group XXX-Sys-Admins to use vnic-attachments in tenancy  where all { target.compartment.name=/XXX-*/ , target.compartment.name!=/XXX-Networks/ , target.compartment.name!=/XXX-SUB-*/ }" => "allow group XXX-Sys-Admins to use vnic-attachments in tenancy where all {target.compartment.name=/XXX-*/,target.compartment.name!=/XXX-Networks/,target.compartment.name!=/XXX-SUB-*/}"

**Comment by codycushing** [comment]
Thanks for the detailed account. There will be an api fix forthcoming that presents the string back to the user exactly as inputed.

**Comment by codycushing** [comment]
Fixed in v2.0.2
