### ISSUE TITLE
Private IP as route table target type

### ISSUE THREAD

**Issue by AudreyBramy** [oracle/terraform-provider-oci#235]
### Terraform Version
10.4.0

### Baremetal Provider Version
v1.0.18

### Description:
It is now allowed in baremetal (through the interface) to use a private ip as route table target type. 

The terraform baremetal documentation only refers to a _network_entity_id_ : 
```

resource "baremetal_core_route_table" "t" {
    compartment_id = "compartment_id"
    display_name = "display_name"
    route_rules {
        cidr_block = "cidr_block"
        network_entity_id = "network_entity_id"
    }
    route_rules {
        cidr_block = "cidr_block"
        network_entity_id = "network_entity_id"
    }
    vcn_id = "vcn_id"
}
```

Is it possible to use a private IP? 
If not, have you planed to add the functionality soon?

**Comment by briangustafson** [comment]
The network_entity_id should accept a private IP address OCID - see https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/RouteRule/. However, we do not yet have support in the provider for creating private IPs or setting the skipSourceDestCheck property on a VNIC. Those are features that we're planning to add in the near future.

**Comment by AudreyBramy** [comment]
Thanks for your answer.

Have you already scheduled a date in your roadmap for these features?

Audrey Bramy

**Comment by briangustafson** [comment]
Hi Audrey - I can't give a firm date at the moment, but we'll let you know when we have more info.

**Comment by briangustafson** [comment]
Hi Audrey - We do have private IPs and the VNIC skipSourceDestCheck property in the latest release. We're working on an example or private IP routing, but you should be set to try this out.

**Comment by alaincampos** [comment]
> The network_entity_id should accept a private IP address OCID - see https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/RouteRule/. However, we do not yet have support in the provider for creating private IPs or setting the skipSourceDestCheck property on a VNIC. Those are features that we're planning to add in the near future.

Follow up to this... has this been implemented in the Terraform OCI provider?  Thanks!
