### ISSUE TITLE
Support compartment renaming

### ISSUE THREAD

**Issue by PeterJamesHarrison** [oracle/terraform-provider-oci#250]
API now supports renaming of compartment name and description.  
https://docs.us-phoenix-1.oraclecloud.com/api/#/en/identity/20160918/requests/UpdateCompartmentDetails
https://docs.us-phoenix-1.oraclecloud.com/api/#/en/identity/20160918/Compartment/UpdateCompartment

Request to support the same via Terraform

**Comment by codycushing** [comment]
implemented by #272

**Comment by codycushing** [comment]
Supported in v2.0.2

**Comment by codycushing** [comment]
Supported in v2.0.2
