### ISSUE TITLE
DBAAS forced destroy when issuing target command 

### ISSUE THREAD

**Issue by ttdeangelo** [oracle/terraform-provider-oci#254]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.9.11

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:
 plugin: /app/bmcs/terraform/providers/terraform-provider-baremetal_amd64$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
Include a description with repro steps, expected result and actual result
The following was run
terraform apply -var-file=args.tfvars -target dns_a_record_set.test-arecord
### Terraform Plan

A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>data "template_file" "userdata" {

  #######################################
  # Data source: Userdata: First boot script
  #######################################

  template = "${file(var.bootstrap_common)}"

  vars {
        yum_packages = "${var.yum_packages}"
        yum_server = "${var.yum_servers[var.region]}"
        ol6_repo_rpm = "${var.ol6_repo_rpms[var.region]}"
        ol7_repo_rpm = "${var.ol7_repo_rpms[var.region]}"
        chef_server_fqdn01 = "${var.chef_server_fqdn01}"
        chef_server_ip01 = "${var.chef_server_ip01}"
        appowner = "${var.appowner}"
        mntpoints = "${var.mntpoints}"
        executor  = "${var.user_ocid}"
        iscsi_ipport  = "${var.iscsi_ipport}"
        fs_type  = "${var.fs_type}"
        ntp_ips = "${var.ntp_ips}"
        dsk_meta = "${var.dsk_meta}"
        iptables_state = "${var.iptables_state}"
       }
}

data "template_file" "os_harden" {

  #######################################
  # Data source: Harden OS
  #######################################

  template = "${file(var.harden)}"

}

#Section: ----------------- 2017/07/31 02:32:22: Action: create, User: terrafor, Range: gcce1t-gcce1t ---

**Comment by ttdeangelo** [comment]
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x240aec7]
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: goroutine 123 [running]:
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: github.com/hashicorp/terraform/vendor/github.com/miekg/dns.(*Msg).Insert(0xc4209617e0, 0xc4209616c0, 0x1, 0x1)
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/miekg/dns/update.go:71 +0x87
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: github.com/hashicorp/terraform/builtin/providers/dns.resourceDnsARecordSetUpdate(0xc4200ee700, 0x4639400, 0xc420870870, 0x2, 0x2)
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/dns/resource_dns_a_record_set.go:144 +0x903
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: github.com/hashicorp/terraform/builtin/providers/dns.resourceDnsARecordSetCreate(0xc4200ee700, 0x4639400, 0xc420870870, 0x0, 0x0)
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/dns/resource_dns_a_record_set.go:58 +0x2f8
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4204435c0, 0xc4208629b0, 0xc420950be0, 0x4639400, 0xc420870870, 0x1, 0x28, 0xc42094cb10)
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x48d
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4202e5ce0, 0xc420862960, 0xc4208629b0, 0xc420950be0, 0x7f8f2804c960, 0x0, 0x0)
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420883be0, 0xc420950520, 0xc42088b2b0, 0x0, 0x0)
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: reflect.Value.call(0xc4202ae420, 0xc4205c61e8, 0x13, 0x5548023, 0x4, 0xc4206e1f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: reflect.Value.Call(0xc4202ae420, 0xc4205c61e8, 0x13, 0xc42058bf20, 0x3, 0x3, 0x0, 0x0, 0xc420336e40)
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: net/rpc.(*service).call(0xc4208b43c0, 0xc4208b4380, 0xc4208807a8, 0xc4201e8b80, 0xc420888800, 0x463b340, 0xc420950520, 0x16, 0x463b380, 0xc42088b2b0, ...)
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: created by net/rpc.(*Server).ServeCodec
2017/09/18 20:27:49 [DEBUG] plugin: terraform0911: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/09/18 20:27:49 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/18 20:27:49 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/09/18 20:27:49 [DEBUG] root: eval: *terraform.EvalIf
2017/09/18 20:27:49 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/18 20:27:49 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/09/18 20:27:49 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/09/18 20:27:49 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* dns_a_record_set.git00000776-arecord: unexpected EOF
2017/09/18 20:27:49 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* dns_a_record_set.git00000776-arecord: unexpected EOF
2017/09/18 20:27:49 [TRACE] [walkApply] Exiting eval tree: dns_a_record_set.git00000776-arecord
2017/09/18 20:27:49 [DEBUG] dag/walk: upstream errored, not walking "provider.dns (close)"
2017/09/18 20:27:49 [DEBUG] plugin: /app/bmcs/terraform/bin/terraform0911: plugin process exited
2017/09/18 20:27:49 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/09/18 20:27:49 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/09/18 20:27:49 [TRACE] Preserving existing state lineage "3d688c4a-60ce-4ebd-b337-dbc71f6f3fb9"
2017/09/18 20:27:49 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/09/18 20:27:49 [WARN] plugin: error closing client during Kill: connection is shut down
2017/09/18 20:27:49 [WARN] plugin: error closing client during Kill: unexpected EOF
2017/09/18 20:27:49 [DEBUG] plugin: /app/bmcs/terraform/providers/terraform-provider-baremetal_amd64: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by codycushing** [comment]
Hello, there isn't enough information here to help you troubleshoot, and what information there is indicates your problem is in the oci provider. 

Please include all your plan files. 
Please add a meaningful description that gives a better picture of your repro steps and original conditions. 
Please look at the error message: “unexpected EOF” typically means your plan file is not being parsed correctly.
Please look at the stack trace: the error is coming from this package "github.com/hashicorp/terraform/vendor/github.com/miekg/dns" (not the oci provider)

**Comment by codycushing** [comment]
Closing due to no follow up

**Comment by ttdeangelo** [comment]
I will update the plan details, as I previously removed due to confidentiality.

**Comment by ttdeangelo** [comment]
All ocids have been removed.
-/+ baremetal_database_db_system.test1
    availability_domain:                 "HnEM:US-ASHBURN-AD-1" => "HnEM:US-ASHBURN-AD-1"
    compartment_id:                      "" => ""
    cpu_core_count:                      "36" => "36"
    data_storage_percentage:             "80" => "<computed>"
    database_edition:                    "ENTERPRISE_EDITION_EXTREME_PERFORMANCE" => "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"
    db_home.#:                           "1" => "1"
    db_home.0.database.#:                "1" => "1"
    db_home.0.database.0.admin_password: "<sensitive>" => "<sensitive>" (attribute changed)
    db_home.0.database.0.db_name:        "test1" => "test1"
    db_home.0.db_version:                "12.1.0.2" => "12.1.0.2"
    db_home.0.display_name:              "dbaas-cngcce1t" => "dbaas-test1"
    disk_redundancy:                     "HIGH" => "HIGH"
    display_name:                        "test1" => "test1"
    domain:                              "test.com" => "test.com"
    hostname:                            "test0000001" => "test0000001"
    lifecycle_details:                   "" => "<computed>"
    listener_port:                       "1521" => "<computed>"
    scan_dns_record_id:                  "" => "<computed>"
    scan_ip_ids.#:                       "0" => "<computed>"
    shape:                               "BM.HighIO1.36" => "BM.HighIO1.36"
    ssh_public_keys.#:                   "1" => "1"
    ssh_public_keys.0:                   "" => "" (forces new resource)
    state:                               "AVAILABLE" => "<computed>"
    subnet_id:                           "" => ""
    time_created:                        "2017-08-03 17:27:19.452 +0000 UTC" => "<computed>"
    version:                             "12.2.0.1.0" => "<computed>"
    vip_ids.#:                           "0" => "<computed>"

-/+ baremetal_database_db_system.test2
    availability_domain:                 "HnEM:US-ASHBURN-AD-1" => "HnEM:US-ASHBURN-AD-1"
    compartment_id:                      "" => ""
    cpu_core_count:                      "8" => "8"
    data_storage_percentage:             "80" => "<computed>"
    database_edition:                    "ENTERPRISE_EDITION_HIGH_PERFORMANCE" => "ENTERPRISE_EDITION_HIGH_PERFORMANCE"
    db_home.#:                           "1" => "1"
    db_home.0.database.#:                "1" => "1"
    db_home.0.database.0.admin_password: "<sensitive>" => "<sensitive>" (attribute changed)
    db_home.0.database.0.db_name:        "" => ""
    db_home.0.db_version:                "12.1.0.2" => "12.1.0.2"
    db_home.0.display_name:              "dbaas-test0000002" => "dbaas-test0000002"
    disk_redundancy:                     "NORMAL" => "NORMAL"
    display_name:                        "test2" => "test2"
    domain:                              "test.com" => "test.com"
    hostname:                            "" test0000002=> "test0000002"
    lifecycle_details:                   "" => "<computed>"
    listener_port:                       "1521" => "<computed>"
    scan_dns_record_id:                  "" => "<computed>"
    scan_ip_ids.#:                       "0" => "<computed>"
    shape:                               "BM.HighIO1.36" => "BM.HighIO1.36"
    ssh_public_keys.#:                   "1" => "1"
    ssh_public_keys.0:                   "" => "" (forces new resource)
    state:                               "AVAILABLE" => "<computed>"
    subnet_id:                           "" => ""
    time_created:                        "2017-09-18 22:26:02.191 +0000 UTC" => "<computed>"
    version:                             "12.1.2.10.2" => "<computed>"
    vip_ids.#:                           "0" => "<computed>"

~ data.baremetal_core_vnic.test001-vnic0
    availability_domain: "" => "<computed>"
    compartment_id:      "" => "<computed>"
    display_name:        "" => "<computed>"
    hostname_label:      "" => "<computed>"
    private_ip_address:  "" => "<computed>"
    public_ip_address:   "" => "<computed>"
    state:               "" => "<computed>"
    subnet_id:           "" => "<computed>"
    vnic_id:             "" => "${data.baremetal_database_db_nodes.test1-db_nodes.db_nodes.0.vnic_id}"

<= data.baremetal_database_db_nodes.test1-db_nodes
    compartment_id: ""
    db_nodes.#:     "<computed>"
    db_system_id:   "${baremetal_database_db_system.test1.id}"
    limit:          "1"

<= data.baremetal_database_db_nodes.test2-db_nodes
    compartment_id: ""
    db_nodes.#:     "<computed>"
    db_system_id:   "${baremetal_database_db_system.test2.id}"
    limit:          "1"

+ dns_a_record_set.-arecord
    addresses.#: "<computed>"
    name:        ""
    ttl:         "10800"
    zone:        "."

+ dns_cname_record.
    cname: ""
    name:  "db-ash-1"
    ttl:   "10800"
    zone:  ""

+ dns_ptr_record.
    name: "${format(\"%[2]s.%[1]s\",\n   element(split(\".\", \"${element(dns_a_record_set.arecord.addresses,1)}\"),2),\n element(split(\".\", \"${element(dns_a_record_set.arecord.addresses,1)}\"),3 ))\n            }"
    ptr:  ""
    ttl:  "10800"
    zone: ""
    
    ssh-rsa 


Plan: 8 to add, 0 to change, 2 to destroy.
 terraform apply -var-file=args.tfvars -target dns_a_record_set.-arecord
baremetal_database_db_system.test1: Refreshing state... (ID: )
data.baremetal_database_db_nodes.test1-db_nodes: Refreshing state...
baremetal_database_db_system.test1: Destroying... (ID: )
baremetal_database_db_system.test1: Destruction complete

**Comment by briangustafson** [comment]
Hi - This still is not very clear to me from the data provided. However, I agree with @codycushing that the crash is coming from the DNS provider, specifically when creating a dns_a_record_set. I would suggest examining the input to that resource, looking at the code for that resource.
