### ISSUE TITLE
Loadbalancer and Security lists

### ISSUE THREAD

**Issue by AudreyBramy** [oracle/terraform-provider-oci#266]
### Terraform Version
0.10.4

### Description:
Regarding the following example : 
https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/load_balancer/lb_full/lb_full.tf

It seems that we have to open loadbalancer ports for all sources (0.0.0.0/0) to allow ingress traffic from the loadbalancer to an instance.  

It is possible to restrict access for the loadbalancer only?

Thanks.

**Comment by briangustafson** [comment]
Yes, this can be done. To avoid restricting internet traffic as well, you will want to create two new subnets just for the LB, and then add ingress security list rules for the CIDR range of those two subnets to the subnets containing the backend instances. 

Let me know if that works for your scenario and properly addresses the question.
