### ISSUE TITLE
Issue with Linux provider using oci_identity_users{} - works on Windows provider

### ISSUE THREAD

**Issue by richlewis469** [oracle/terraform-provider-oci#277]
### Terraform Version

<details>
# Run this command to get the terraform version:
$ terraform -v
Terraform v0.10.6
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:
$ \<path-to-plugin\>/terraform-provider-oci
2017/09/29 16:12:38 [INFO] terraform-provider-oci 2.0.1
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
</details>

### Description:
Include a description with repro steps, expected result and actual result

Executing Terraform oci_identity_users{} on Windows Provider returns correct result, executing on Linux causes a SIGSEGV and crashes Terraform.

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.
See Attachments

[oci_identity_users-crash.tar.gz](https://github.com/oracle/terraform-provider-oci/files/1344616/oci_identity_users-crash.tar.gz)

[crash.log](https://github.com/oracle/terraform-provider-oci/files/1344622/crash.log)

![windows capture](https://user-images.githubusercontent.com/8545361/31019931-f7130502-a4f6-11e7-95bc-b7dd6decb331.JPG)

[linux-capture.txt](https://github.com/oracle/terraform-provider-oci/files/1344626/linux-capture.txt)

</details>

Signed-off-by: Rich Lewis <rich.lewis@oracle.com>

**Comment by codycushing** [comment]
Just to rule out the obvious here, which plugin binaries are you using per os/arch?

**Comment by richlewis469** [comment]
Windows/amd64 - Terraform v0.10.6
Windows/amd64 - terraform-provider-oci_v2.0.0

Linux/amd64 - Terraform v0.10.6
Linux/amd64 - terraform-provider-oci 2.0.0

I can provide the test case as a Vagrant automated image if that would help.

**Comment by briangustafson** [comment]
I tried running the plan on the latest OCI Oracle Linux 7.4 image, and it works there. So it would be helpful if you could provide the specific OS or image that is used.

**Comment by codycushing** [comment]
Hi there, if you can repro this with build v2.0.2 running in debug mode and provide the output it will help us investigate. Be sure to cleanse any sensitive data present in the output.

Example debug command:
$ `DEBUG=true TF_LOG=DEBUG terraform apply`

**Comment by richlewis469** [comment]
OK, performed more debuging. Pinned issue down to the way Windows uses TYPE to pull values from fingerprint file versus Linux using CAT. Used direct value instead of reading from file in the environment variables, and it worked correctly. Closing Issue, as OS Specific Behavior.
