### ISSUE TITLE
dns_label must be lowercase

### ISSUE THREAD

**Issue by alapidas** [oracle/terraform-provider-oci#279]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.10.6
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
2017/09/29 21:34:38 [INFO] terraform-provider-baremetal v1.0.18
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
</details>

### Description:
Include a description with repro steps, expected result and actual result

Make a VCN and a subnet that contains a DNS label with an uppercase letter in it.  Initially it works fine, but if you run `terraform plan` again, it marks the subent as changed because the dns_label in OCI is now all lowercase (the server side is lowercasing it) but your local data has an upperacse letter in it.

This should either error out in the first planning stage (before the infra has ever been provisioned) or it should never error out.

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

resource "baremetal_core_subnet" "BastionSubnet" {
    availability_domain = "US-ASHBURN-AD-1"
    cidr_block = "10.10.0.0/16"
    display_name = "theDisplayname"
    dns_label = "myName"
    compartment_id = "blah"
    vcn_id = "SomeVCN"
    route_table_id = "someRouteTable"
    security_list_ids = ["someSecList"]
    dhcp_options_id = "theDHCPOptions"
}

Note the camelcase dns_label above
</details>

**Comment by briangustafson** [comment]
Thanks for reporting this - we're looking into a solution.

**Comment by briangustafson** [comment]
Addressed with https://github.com/oracle/terraform-provider-oci/pull/285 - will be in the next release.

**Comment by codycushing** [comment]
Fixed in v2.0.2
