### ISSUE TITLE
compartment_id should not be required field for creating policies

### ISSUE THREAD

**Issue by devcamcar** [oracle/terraform-provider-oci#280]
### Terraform Version

Terraform v0.10.6

### OCI Provider Version

terraform-provider-oci 2.0.1

### Description:

I have a use case where I need to apply a group policy for an entire tenancy, and not a specific compartment.  Currently the OCI Provider requires compartment_ocid and won't allow tenant wide policies to be created.

### Terraform Plan

    variable "tenancy_ocid" {}
    variable "user_ocid" {}
    variable "fingerprint" {}
    variable "private_key_path" {}
    variable "compartment_ocid" {}
    variable "region" {}

    provider "oci" {
      tenancy_ocid = "${var.tenancy_ocid}"
      user_ocid = "${var.user_ocid}"
      fingerprint = "${var.fingerprint}"
      private_key_path = "${var.private_key_path}"    
      region = "${var.region}"
    }

    resource "oci_identity_compartment" "t" {
      name = "test-compartment"
      description = "automated test compartment"
    }

    resource "oci_identity_group" "t" {
      name = "-tf-group"
      description = "automated test group"
    }

    resource "oci_identity_policy" "p" {
      name = "-tf-policy"
      description = "automated test policy"
      statements = ["Allow group ${oci_identity_group.t.name} to read instances in tenancy"] 
    }

**Comment by codycushing** [comment]
If you want a policy to exist outside of a specific compartment (in the root compartment) then you can pass the tenancy ocid as the compartment id param.
https://docs.us-phoenix-1.oraclecloud.com/api/#/en/identity/20160918/requests/CreatePolicyDetails

**Comment by devcamcar** [comment]
That worked, thanks!
