### ISSUE TITLE
Unable to set output variable in Terraform module

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-oci#288]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.10.7

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

2017/10/05 17:35:17 [INFO] terraform-provider-oci 2.0.1
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

### Description:
I've a module for creating IAM resources in Oracle baremetal/OCI . I do set a temporary password for the users I add to the tenancy. For some reason I am unable to propagate password to through an output variable to the module . 

Tree :
  .
├── bmc_provider.tf
├── iam_main.tf
├── terraform.tfstate
├── tr_iam
│   ├── create_user_group.tf
│   └── variable.tf

### Terraform Plan

**iam_main.tf :**

variable "CN_AdminGroupName" {
  description = "CN Admin Group "
  type = "string"
  default = "CN_AdminGroup_tst"
}

module "tf_iam_cn_grp" {
  source                = "./tr_iam"
  enable_flag           = true
  tenancy_ocid          = "${var.tenancy_ocid}"
  user_ocid             = "${var.user_ocid}"
  fingerprint           = "${var.fingerprint}"
  private_key_path      = "${var.private_key_path}"
  compartment_ocid      = "${var.compartment_ocid}"
  usr_list              = ["abc123@oracle.com","pqr123@oracle.com"]
  grp_list              = "${var.CN_AdminGroupName}"
  policy_name           = "CN_AdminPolicy"
  policy_stmnts         = ["Allow group ${var.CN_AdminGroupName} to manage compartments in tenancy where target.compartment.name=/CN_*/""]

**output "UIPassword" {
  sensitive = false
  value = ["${module.tf_iam_cn_grp.UserUIPassword}"]
}**

**create_user_group.tf**

resource "oci_identity_user" "UsrCreate" {
    count = "${length(var.usr_list) * var.enable_flag}"
    name = "${element(var.usr_list,count.index)}"
    description = "Terraform: CN user managed with TF"
    lifecycle {
              ignore_changes = []
             }

}

resource "oci_identity_group" "GrpCreate" {
    count =  "${var.enable_flag}"
    name = "${var.grp_list}"
    description = "Terraform: CN Group managed with TF"
    lifecycle {
               ignore_changes = []
              }
}
resource "oci_identity_ui_password" "tf_password" {
  count = "${length(var.usr_list) * var.enable_flag}"
  user_id = "${element(oci_identity_user.UsrCreate.*.id,count.index)}"
}

output "UserUIPassword" {
  sensitive = false
  value = ["${oci_identity_ui_password.tf_password.password}"]
}
resource "oci_identity_user_group_membership" "assgn" {
                compartment_id = "${var.compartment_ocid}"
                group_id = "${oci_identity_group.GrpCreate.id}"
                count = "${length(var.usr_list) * var.enable_flag}"
                user_id = "${element(oci_identity_user.UsrCreate.*.id,count.index)}"
                lifecycle {
                    ignore_changes = []
                }
                }
resource "oci_identity_policy" "iam_oci_policy_creation" {
    depends_on            = ["oci_identity_group.GrpCreate"]
    count = "${var.enable_flag}"
    name = "${var.policy_name}"
    description = "TF managed CN policy"
    compartment_id = "${var.compartment_ocid}"
    statements = "${var.policy_stmnts}"
  }

**terraform plan**
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.tf_iam_cn_grp.oci_identity_group.GrpCreate
      id:              <computed>
      compartment_id:  <computed>
      description:     "Terraform: CN Group managed with TF"
      inactive_state:  <computed>
      name:            "CN_AdminGroup_tst"
      state:           <computed>
      time_created:    <computed>
      time_modified:   <computed>

  + module.tf_iam_cn_grp.oci_identity_policy.iam_oci_policy_creation
      id:              <computed>
      compartment_id:  "ocid1.tenancy.oc1..aaaaaaaazqe56p5uw4ri7hzvmblb6jzwiuw6mdt7xgllx4vug3ttbyjtjuxq"
      description:     "TF managed CN policy"
      inactive_state:  <computed>
      name:            "CN_AdminPolicy"
      state:           <computed>
      statements.#:    "12"
      statements.0:    "Allow group CN_AdminGroup_tst to manage compartments in tenancy where target.compartment.name=/CN_*/"
      statements.1:    "Allow group CN_AdminGroup_tst to manage users in tenancy"
      statements.10:   "Allow group CN_AdminGroup_tst to manage policies in tenancy where target.compartment.name=/CN_*/"
      statements.11:   "Allow group CN_AdminGroup_tst to manage load-balancer in tenancy where target.compartment.name=/CN_*/"
      statements.2:    "Allow group CN_AdminGroup_tst to manage groups in tenancy where any {request.permission='GROUP_INSPECT', request.permission='GROUP_READ', request.permission='GROUP_CREATE'}"
      statements.3:    "Allow group CN_AdminGroup_tst to use groups in tenancy where target.group.name=/CN_*/"
      statements.4:    "Allow group CN_AdminGroup_tst to inspect compartments in tenancy where target.compartment.name=/CN_*/"
      statements.5:    "Allow group CN_AdminGroup_tst to manage virtual-network-family in tenancy where target.compartment.name=/CN_*/"
      statements.6:    "Allow group CN_AdminGroup_tst to manage instance-family in tenancy where target.compartment.name=/CN_*/"
      statements.7:    "Allow group CN_AdminGroup_tst to manage volume-family in tenancy where target.compartment.name=/CN_*/"
      statements.8:    "Allow group CN_AdminGroup_tst to manage database-family in tenancy where target.compartment.name=/CN_*/"
      statements.9:    "Allow group CN_AdminGroup_tst to manage object-family in tenancy where target.compartment.name=/CN_*/"
      time_created:    <computed>
      time_modified:   <computed>
      version_date:    <computed>

  + module.tf_iam_cn_grp.oci_identity_ui_password.tf_password[0]
      id:              <computed>
      inactive_status: <computed>
      password:        <computed>
      state:           <computed>
      time_created:    <computed>
      user_id:         "${element(oci_identity_user.UsrCreate.*.id,count.index)}"

  + module.tf_iam_cn_grp.oci_identity_ui_password.tf_password[1]
      id:              <computed>
      inactive_status: <computed>
      password:        <computed>
      state:           <computed>
      time_created:    <computed>
      user_id:         "${element(oci_identity_user.UsrCreate.*.id,count.index)}"

  + module.tf_iam_cn_grp.oci_identity_user.UsrCreate[0]
      id:              <computed>
      compartment_id:  <computed>
      description:     "Terraform: CN user managed with TF"
      inactive_state:  <computed>
      name:            "abc123@oracle.com"
      state:           <computed>
      time_created:    <computed>
      time_modified:   <computed>

  + module.tf_iam_cn_grp.oci_identity_user.UsrCreate[1]
      id:              <computed>
      compartment_id:  <computed>
      description:     "Terraform: CN user managed with TF"
      inactive_state:  <computed>
      name:            "pqr123@oracle.com"
      state:           <computed>
      time_created:    <computed>
      time_modified:   <computed>

  + module.tf_iam_cn_grp.oci_identity_user_group_membership.assgn[0]
      id:              <computed>
      compartment_id:  "ocid1.tenancy.oc1..aaaaaaaazqe56p5uw4ri7hzvmblb6jzwiuw6mdt7xgllx4vug3ttbyjtjuxq"
      group_id:        "${oci_identity_group.GrpCreate.id}"
      inactive_state:  <computed>
      state:           <computed>
      time_created:    <computed>
      user_id:         "${element(oci_identity_user.UsrCreate.*.id,count.index)}"

  + module.tf_iam_cn_grp.oci_identity_user_group_membership.assgn[1]
      id:              <computed>
      compartment_id:  "ocid1.tenancy.oc1..aaaaaaaazqe56p5uw4ri7hzvmblb6jzwiuw6mdt7xgllx4vug3ttbyjtjuxq"
      group_id:        "${oci_identity_group.GrpCreate.id}"
      inactive_state:  <computed>
      state:           <computed>
      time_created:    <computed>
      user_id:         "${element(oci_identity_user.UsrCreate.*.id,count.index)}"

Plan: 8 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

**Comment by briangustafson** [comment]
I think I see the issue - in the module, you need to add a ".*" to the output so that it looks like:

output "UserUIPassword" {
    sensitive = false
    value = ["${oci_identity_ui_password.tf_password.*.password}"]
}

I gave this a quick try and it works for me. Note that it does write the password to the state file, just FYI.

I'm closing this, but please reopen if this doesn't work for you.

**Comment by rahulviswam17** [comment]
Thank you that worked for me.

**Comment by rahulviswam17** [comment]
I've a follow up question on this, is there a way I can print the results as a map . So that when i provision a bunch of users I can easily understand which password belongs to which user. Tried the below but doesnt look neat. Any suggestions would be great :


**RESOURCE**
output "UserUIPassword" {
  sensitive = false
  value = ["${oci_identity_user.UsrCreate.*.name}","${oci_identity_ui_password.tf_password.*.password}"]

}


**OUTPUT**


Outputs:

UIPassword = [
    abc07@oracle.com,
    pqr07@oracle.com,
    .8f+3VuD[cTsd[9zPl;;,
    _LbD(D6kPi7k>+3uPsV{
]
 

**REQUIRED OUTPUT**
UIPassword = [
    abc07@oracle.com : .8f+3VuD[cTsd[9zPl 
    pqr07@oracle.com : _LbD(D6kPi7k>+3uPsV{
   
]

**Comment by briangustafson** [comment]
Good question - if referencing a specific resource, you can do something like:
output "UserUIPassword" {
sensitive = false
value = ["Name: ${oci_identity_user.UsrCreate.0.name}, Password: ${oci_identity_ui_password.tf_password.0.password}"]
}
However, I'm not sure how to get that working for an arbitrary count. (Apparently you can't use the "count" variable in output.)

**Comment by rahulviswam17** [comment]
Hi Brian ,
Thats true, count variable is not available in output. Any means to write these output to a file ? or is the best solution to have a separate script to read statefile?
