### ISSUE TITLE
How to parametrize the configuration?

### ISSUE THREAD

**Issue by kocic11** [oracle/terraform-provider-oci#290]
### Terraform Version

Terraform v0.10.7
### OCI Provider Version

terraform-provider-oci 2.0.1

### Description:
Let's say I want to create two compute instances from the same set of the configuration files. I can copy all the files from terraform-provider-oci/docs/examples/compute/instance to terraform-provider-oci/docs/examples/compute/instance_2 and replace all references to TFInstance with TFInstance2. However, it is error prone and against DRY principle. 

Instead, can I make the instance name a variable and have a single set of parametrized configuration files?

I tried using locals, but had mixed results.

**Comment by MarcinZablocki** [comment]
I'd suggest using modules  in this case. 

https://www.terraform.io/docs/modules/usage.html


e.g: 

instances/compute/main.tf: 

resource "oci_core_instance" "TFInstanceCompute" {
  count               = "${var.count}"
  availability_domain = "${var.availability_domain}"
  compartment_id      = "${var.compartment_ocid}"
  display_name        = "${var.label_prefix}${var.display_name}-${count.index}"
  hostname_label      = "${var.hostname_label}-${count.index}"
  image               = "${lookup(data.oci_core_images.ImageOCID.images[0], "id")}"
  shape               = "${var.shape}"
  subnet_id           = "${var.subnet_id}"

  metadata {
    roles               = "compute"
    ssh_authorized_keys = "${var.ssh_public_key_openssh}"
#    user_data           = "${base64encode(data.template_file.compute-bootstrap.rendered)}"
  }
}

compute.tf:

module "instances-compute" {
  source                 = "instances/compute"
  count                  = "${var.computeCount}"
  availability_domain    = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
  compartment_ocid       = "${var.compartment_ocid}"
  display_name           = "compute-ad1"
  domain_name            = "${var.domain_name}"
  hostname_label         = "compute-ad1"
  instance_os_ver        = "${var.instance_os_ver}"
  label_prefix           = "${var.label_prefix}"
  shape                  = "${var.computeShape}"
  ssh_public_key_openssh = "${module.tls.ssh_public_key_openssh}"
  subnet_id              = "${module.subnet-compute-ad1.id}"
  tenancy_ocid           = "${var.compartment_ocid}"
}

**Comment by kocic11** [comment]
@MarcinZablocki 
Not sure if or how the modules would help.

Following your example, main.tf will always create an instance with the name "TFInstanceCompute". What I would like to have is something like this:

resource "oci_core_instance" "${var.InstanceName}" {

**Comment by briangustafson** [comment]
If you us count, as in Marcin's example, then you can reference individual instances by appending a number, such as ${oci_core_instance.TFInstanceCompute.5}. That's true with or without modules. If using modules (with or without count), then you can instantiate multiple instances as shown at https://www.terraform.io/docs/modules/usage.html#multiple-instances-of-a-module.

Do those options not work for your use case?

**Comment by lucassrg** [comment]
@kocic11, It really depends on your use case. If you have a cluster and you want to manage 2 identical instances from the same terraform template file, you can use `count` variables to specify the number of nodes you want to create on that particular resource. But then you have to use interpolation syntax to manage the `index` name/number of your resource to better identify them and also avoid naming conflict. 

On the other hand, you can use Terraform [variable files](https://www.terraform.io/docs/configuration/variables.html) to specify the values of the input variables for each environment that you have.  In fact, the variable file is always a good practice and you can specify an input variable to set the number of clusters for each different environment that you have. For example, you can set the count variable to 2 on your dev environment and 10 on production.

For example, if you want to create your resources on dev environment you can have a `development.tfvars` file, then the usage is simple, you just need to refer to it on your terraform calls:
`terraform plan -var-file=development.tfvars`
`terraform apply -var-file=development.tfvars`
`terraform destroy -var-file=development.tfvars`

By default, terraform looks for `terraform.tfvars`, so if you have that file on your project folder, it automatically will be loaded without having to specify the -var-file parameter.

**Comment by kocic11** [comment]
@lukassrg

It is not just the name that needs to be changed. For example, once the compute instance is created, it may be referenced by other resources. In the example below, the name of the compute instance is TFInstance:

resource "oci_core_volume_attachment" "TFBlock0Attach" {
    attachment_type = "iscsi"
    compartment_id = "${var.compartment_ocid}"
    instance_id = "${oci_core_instance.TFInstance.id}"
    volume_id = "${oci_core_volume.TFBlock0.id}"
}

What I was thinking of doing was something like this (which doesn’t work):

instance_id = "${oci_core_instance.${var.InstanceName}.id}"

This way I could use the same file (in this case block.tf) regardless of the instance name.

Regards,
Aleksandar

**Comment by lucassrg** [comment]
@kocic11 

You have to use [format](https://www.terraform.io/docs/configuration/interpolation.html#format-format-args-) function to specify the name the way that you want:

```
instance_id = ${format("oci_core_instance.%s.id", ${var.InstanceName})}"

```

I do have a [post](https://medium.com/@lucas_srg/how-to-onboard-a-new-customer-on-oracle-bare-metal-cloud-service-with-terraform-b716bed10146) on medium with some sample code using format/interpolation/count variables. It's related to IAM, but you can apply on your use case.

**Comment by kocic11** [comment]
@lucassrg 

This is not going to work because it is interpolated as a string. For example, terraform plan shows it as:

instance_id:                  "oci_core_instance.TFInstance2.id"

Instead, it should be:

instance_id:                  "${oci_core_instance.TFInstance2.id}"

Regards,
Aleksandar

**Comment by lucassrg** [comment]
@kocic11 ,
The answer for what you are looking for is the`count` meta-parameters. On your answer to @MarcinZablocki , you said:

>@MarcinZablocki
>Not sure if or how the modules would help.
>
>Following your example, main.tf will always create an instance with the name "TFInstanceCompute". What I would like to have is something like this:
>
>resource "oci_core_instance" "${var.InstanceName}" {

This is not true, `TFInstanceCompute` is not the `instance name` but this is the [resource identifier](https://www.terraform.io/docs/configuration/resources.html) for the `oci_core_instance resource type` - this is internal to Terraform as part of its resource definition.

The `instance name` (actually display_name) is part of the configuration of that `oci_core_instance` resource and is defined as an attribute you set within the resource block (the {}). If you want to create 2 instances based on the same configuration template, you just specify a `count` parameter as I previously explained. 
```
variable "number_of_instances" {}


resource "oci_core_instance" "my-instances" {
   count       = "${var.number_of_instances}"
   availability_domain = "${lookup(data.oci_identity_availability_domains.ads.availability_domains[var.availability_domain - 1],"name")}"
  compartment_id      = "${var.compartment_ocid}"
  display_name = "${format("TFInstanceName%03d", count.index + 1)}
  image               = "${lookup(data.oci_core_images.base-image.images[0], "id")}"
  shape               = "${var.instance_shape}"
...
```
You can see the output of my sample code [here](https://gist.github.com/lucassrg/40989d20034134356d586108064e93ff). Each instance has its own individual `id (ocid)` completely managed by Terraform.

Hope that it clarifies.
Lucas

**Comment by tehmaspc** [comment]
@lucassrg is right; you cannot parameterize the resource name - use `count` or create a module and call that module twice w/ diff resource names. HCL is still limited in it's abilities.

**Comment by kohashim** [comment]
It's been for a while since the last suggestion was made.  Closing for now.  Reopen if necessary.
