### ISSUE TITLE
oci-tool fails when migrating plan with empty directory

### ISSUE THREAD

**Issue by briangustafson** [oracle/terraform-provider-oci#292]
Using the oci-tool to migrate a directory that contains an empty directory will fail when trying to validate the backup:

$ oci-tool  migrate -dir=myplan/
Migrating plan directory...
Creating backup... myplan --> myplan.backup
Copying myplan --> myplan.backup
Copying myplan/multi_vnic.tf --> myplan.backup/multi_vnic.tf, 3416 bytes
panic: Error backing up directory before migration
 Backup corrupt

goroutine 1 [running]:
main.main()
	/oci-tool/main.go:94 +0x3c5

The workaround for now is simply to delete the empty directory.

**Comment by codycushing** [comment]
Available in v2.0.2 release as oci-tool.zip
