### ISSUE TITLE
how to configure a backend for remote statefile

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-oci#293]
### Terraform Version
For eg: I tried configuring a backed S3 , but its erroring out despite of giving valid region . I guess I am missing some concept here.
<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.10.7

### OCI Provider Version
./terraform-provider-oci_v2.0.1
2017/10/07 23:59:10 [INFO] terraform-provider-oci 2.0.1
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

</details>

### Description:
Error while trying to configure S3 backend for Terraform remote statefile :

**terraform init**
Downloading modules...

Initializing the backend...

**Error configuring the backend "s3": Not a valid region: us-phoenix-1**

Please update the configuration in your Terraform files to fix this error
then run this command again.

### TF file :

provider "oci" {
  region = "us-phoenix-1"
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
}

terraform {
  backend "s3" {
    bucket = "my-tfstates"
    key    = "terraform.tfstate"
    region = "us-phoenix-1"
  }
}

**Comment by briangustafson** [comment]
I assume that you're trying to use S3 as the backend, not OCI, correct? In that case you need to use an AWS region, see for example https://www.terraform.io/docs/backends/types/s3.html. OCI is not currently supported as a backend.

**Comment by rahulviswam17** [comment]
@briangustafson : Based on your statement, there's no way we can use the remote_statefile management we can achieve in OCI ?

**Comment by briangustafson** [comment]
@rahulviswam17 Correct, that is not currently supported, but is being tracked in our backlog. Are you blocked on this, or is there a particular scenario that requires this? If so, let us know, that will help to prioritize.
