### ISSUE TITLE
Support for Database Sevice on VMs

### ISSUE THREAD

**Issue by swmuruga** [oracle/terraform-provider-oci#294]
### Terraform Version

0.10.7

### OCI Provider Version

der-oci_v2.0.0

### Description:
Need support for provisioning Databases on Virtual Machines (VMs). Tried to use the same tf file for the baremetal, by adding a key "initial_data_storage_size_in_gb" which errored out in the terraform plan

### Terraform Plan

1 error(s) occurred:

* oci_database_db_system.TFDBNode: : invalid or unknown key: initial_data_storage_size_in_gb

**Comment by briangustafson** [comment]
We're planning to add support for this in the near future. Thanks for bringing it up, as that helps us to prioritize. We'll let you know when this is available.

**Comment by briangustafson** [comment]
This has been released in v2.0.3. See the example at https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/db_systems/DBSystem.tf#L26 (and note that the param is data_storage_size_in_gb, not initial_data_storage_size_in_gb).
