### ISSUE TITLE
Creating identity objects using non-home region

### ISSUE THREAD

**Issue by alapidas** [oracle/terraform-provider-oci#296]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
```
✔ ~/infra/terraform/backup [develop|✚ 3…7]
14:56 $ tf -v
Terraform v0.10.6

Your version of Terraform is out of date! The latest version
is 0.10.7. You can update by downloading from www.terraform.io/downloads.html
```

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

```
✔ ~/infra/terraform/backup [develop|✚ 3…7]
14:43 $ ~/.terraform.d/plugins/darwin_amd64/terraform-provider-baremetal_v1.0.18
2017/10/09 14:54:06 [INFO] terraform-provider-baremetal v1.0.18
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

</details>

### Description:
Include a description with repro steps, expected result and actual result

When I try an create identity objects in Ashburn I get errors because it's not the home region for that tenancy.  As an isolated thing, this makes sense, but what if I want to make identity objects _and_ compute objects?  I found this https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/iam/ad_multi_region/ad_multi_region.tf which is nice if you know in advance what your home region will be, but if you don't then it would be nice if your requests could be auto-delegated to the right region.  A caveat to this would be that after creating identity objects, you need to wait for them to replicate over to the non-home region to use them.

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by codycushing** [comment]
https://github.com/oracle/terraform-oci-cf-install/issues/5

**Comment by codycushing** [comment]
Tenancy and Region data sources will be released soon with an example of how to auto route identity resource calls to the home region

**Comment by codycushing** [comment]
A way to do this is now supported in v2.1.9. 
See this file for an example: https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/concepts/identity_home_resolution/main.tf

**Comment by jayakrishnanl** [comment]
The above link no longer works. Do you have an example on how to tackle this?

**Comment by jayakrishnanl** [comment]
Correct link is here:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/concepts/identity_home_resolution/main.tf

Creating a provider with home region, set an alias for it and refer it on the IAM resources did the trick.

**Comment by ankeetj** [comment]
We are facing similar issue in java OCI SDK .  

`Please go to your home region IAD to execute CREATE, UPDATE and DELETE operations.`

How can I create user in non home region ?

**Comment by majidkhan591** [comment]
similar issue.

Error: Service error:NotAllowed. Please go to your home region jed to execute CREATE, UPDATE and DELETE operations.. http status code: 403. Opc request id: f022dbab29a907ac248861f64d0283b7/13C085A2F9771D08012756C95694D558/0D1577C426750F7C74EC7A2D85565537

  on module/tag/main.tf line 12, in resource "oci_identity_tag_namespace" "creat_tag_namespace":
  12: resource "oci_identity_tag_namespace" "creat_tag_namespace" {

**Comment by majidkhan591** [comment]
Ok the workaround is provided in this link:

https://github.com/oracle-terraform-modules/terraform-oci-iam/issues/14

followed the same link

This is my configuration:
main.tf
provider oci {
  tenancy_ocid         = var.tenancy_ocid
  user_ocid            = var.user_ocid
  fingerprint          = var.api_fingerprint
  private_key_path     = var.api_private_key_path
  region               = var.region
  disable_auto_retries = false
}

provider oci {
  alias             = "home"
  region            = lookup(data.oci_identity_regions.home-region.regions[0], "name")
  tenancy_ocid      = var.tenancy_ocid
  user_ocid         = var.user_ocid
  fingerprint       = var.api_fingerprint
  private_key_path  = var.api_private_key_path
}

data oci_identity_tenancy tenancy {
  tenancy_id = var.tenancy_ocid
}

data oci_identity_regions home-region {
  filter {
    name = "key"
    values = [data.oci_identity_tenancy.tenancy.home_region_key]
  }
}

module "create_tags" {
  providers = {
    oci = oci.home
  }

 ## some of the variables I placed here for the following source
  source      = "./module/tag"

}
