### ISSUE TITLE
Issue with new block device setting size_in_gbs

### ISSUE THREAD

**Issue by rishiraaz** [oracle/terraform-provider-oci#297]
[root@]# terraform -v
Terraform v0.10.7

[root@]# .terraform.d/plugins/linux_amd64/terraform-provider-oci_v2.0.0
2017/10/10 04:46:26 [INFO] terraform-provider-oci v2.0.0
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

[root@]# terraform plan
1 error(s) occurred:

* oci_core_volume.TFBlock0: : invalid or unknown key: size_in_gbs

**Comment by codycushing** [comment]
Adding in 2.0.2 release

**Comment by rishiraaz** [comment]
thanks
