### ISSUE TITLE
oci-tool does not fully migrate some lines with multiple baremetal references

### ISSUE THREAD

**Issue by briangustafson** [oracle/terraform-provider-oci#298]
For example, the following line has 2 baremetal resource references and 2 baremetal data source references:

statements = ["Allow group ${baremetal_identity_group.t.name} to read instances in compartment ${baremetal_identity_compartment.t.name}", "Allow group "${lookup(data.baremetal_identity_group.groups[0], "id")}" to read instances in compartment "${lookup(data.baremetal_identity_compartment.compartments[0], "id")}"]

The tool will currently only convert 1 of each to oci:

statements = ["Allow group ${oci_identity_group.t.name} to read instances in compartment ${baremetal_identity_compartment.t.name}", "Allow group "${lookup(data.oci_identity_group.groups[0], "id")}" to read instances in compartment "${lookup(data.baremetal_identity_compartment.compartments[0], "id")}"]

**Comment by briangustafson** [comment]
This is fixed in master, https://github.com/oracle/terraform-provider-oci/pull/283, and will be in the next release of the oci-tool.

**Comment by codycushing** [comment]
Available in v2.0.2 release as oci-tool.zip
