### ISSUE TITLE
oci_identity_availability_domains does not support splat syntax

### ISSUE THREAD

**Issue by lhdomenech** [oracle/terraform-provider-oci#300]
### Terraform Version
0.10.7
### OCI Provider Version
terraform-provider-oci 2.0.1

### Description:
oci_identity_availability_domains does not work with splat syntax. 

For example using:
```
"${lookup(data.oci_identity_availability_domains.ADs.availability_domains.*.name, count.index)}"
```

produces the error:
```
* oci_core_subnet.test[1]: At column 3, line 1: lookup: argument 1 should be type map, got type string in:

${lookup(data.oci_identity_availability_domains.ADs.availability_domains.*.name, count.index)}
```

This prevent its usage with count. When used with splay syntax, it should be a list but it is of type string instead.

### Terraform Plan

```
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "private_key_password" {}
variable "compartment_ocid" {}

provider "oci" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  private_key_password = "${var.private_key_password}"
  region = "${var.region}"
}

data "oci_identity_availability_domains" "ADs" {
  compartment_id = "${var.compartment_ocid}"
}

resource "oci_core_virtual_network" "test" {
  compartment_id = "${var.compartment_ocid}"

  cidr_block = "10.0.0.0/16"
  display_name = "test"
}

resource "oci_core_subnet" "test" {
  count = 2

  compartment_id = "${var.compartment_ocid}"

  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains.*.name, count.index)}"
  route_table_id = "${oci_core_virtual_network.test.default_route_table_id}"
  security_list_ids = ["${oci_core_virtual_network.test.default_security_list_id}"]
  vcn_id = "${oci_core_virtual_network.test.id}"
  dhcp_options_id = "${oci_core_virtual_network.test.default_dhcp_options_id}"

  display_name = "test"
  cidr_block = "${cidrsubnet("10.0.0.0/16", 8, count.index)}"
}
```

plan results:
```
Error running plan: 1 error(s) occurred:

* oci_core_subnet.test: 2 error(s) occurred:

* oci_core_subnet.test[0]: At column 3, line 1: lookup: argument 1 should be type map, got type string in:

${lookup(data.oci_identity_availability_domains.ADs.availability_domains.*.name, count.index)}
* oci_core_subnet.test[1]: At column 3, line 1: lookup: argument 1 should be type map, got type string in:

${lookup(data.oci_identity_availability_domains.ADs.availability_domains.*.name, count.index)}
```

**Comment by alapidas** [comment]
The same behavior can be seen with compartments datasource.  In my particular use case, I want to make a map of compartment OCID to name via zipmap, but since splat doesn't work, I can't do it.

**Comment by parweza** [comment]
As per Terraformer documentation https://www.terraform.io/docs/configuration/interpolation.html#attributes-of-a-data-source 
Splat syntax works listing attributes of data source .
_"The syntax is data.TYPE.NAME.ATTRIBUTE. For example. ${data.aws_ami.ubuntu.id} will interpolate the id attribute from the aws_ami data source named ubuntu. If the data source has a count attribute set, you can access individual attributes with a zero-based index, such as ${data.aws_subnet.example.0.cidr_block}. You can also use the splat syntax to get a list of all the attributes: ${data.aws_subnet.example.*.cidr_block}."_
 
The above code is trying to apply splat syntax on attribute itself (which is a list). So one possible way would be : 
availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[count.index],"name")}"

**Comment by lhdomenech** [comment]
That works, thanks.
