### ISSUE TITLE
tfstate file contains database admin password in clear text

### ISSUE THREAD

**Issue by ttsharma** [oracle/terraform-provider-oci#302]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.9.9

### OCI Provider Version

Terraform Provider : v1.0.16
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

2017/10/11 04:10:28 [INFO] terraform-provider-baremetal v1.0.16

### Description:
Created a dbsystem using a terraform provider. The tfstate file contains admin password in clear text after the dbsystem is created successfully.
I am not writing password in my plan file as can be noticed in the example that I have provided below. I am using a variable to define the password value to which is provided at runtime.

Kindly suggest a way to suppress this or we should have a fix to not print password in clear text in the state file.

### Terraform Plan
Sample plan file
[oracle@ecsorchvm tarundbsystem]$ cat dbsystem.tf
{
  "resource": {
    "baremetal_database_db_system": {
      "tarundbsystem": {
        "availability_domain": "CQIl:US-ASHBURN-AD-1",
        "compartment_id": "ocid1.compartment.oc1..aaaaaaaamzfaycvu6wtvcr7rdeq7xkzfpt5krvt6drb3ly52vjd4wcywtaqa",
        "cpu_core_count": "8",
        "database_edition": "ENTERPRISE_EDITION",
        "disk_redundancy": "HIGH",
        "shape": "BM.HighIO1.36",
        "subnet_id": "ocid1.subnet.oc1.iad.aaaaaaaagdno4waazr42v3bpwlmjexozes5baasxyfftrw5jlxkcor26qjuq",
        "ssh_public_keys": [
          "${file(\"/u01/install/APPS/.ssh/id_rsa.pub\")}"
        ],
        "display_name": "tarundbsystem",
        "hostname": "tarundbsystem",
        "domain": "ecsclientsubnet.ebsecstesting.oraclevcn.com",
        "db_home": {
          "db_version": "11.2.0.4",
          "display_name": "tarundbsystem-dbhome01",
          "database": {
            "admin_password": "${var.dbsystem_admin_password}",
            "db_name": "prod"
          }
        }
      }
    }
  }
}

### Terraform state file content
Excerpts from state file
         "type": "baremetal_database_db_system",
                    "depends_on": [],
                    "primary": {
                        "id": "ocid1.dbsystem.oc1.phx.abyhqljs2hj3yswnj2d7wddwhbb3hrifwymfufsf4thkykmg4ahk36ytzkqa",
                        "attributes": {
                            "availability_domain": "XDaU:PHX-AD-1",
                            "compartment_id": "ocid1.compartment.oc1..aaaaaaaar6ntzjiyl7oif4hn55op6rscni4djidim2y4iju4xa6xseizdvga",
                            "cpu_core_count": "2",
                            "data_storage_percentage": "80",
                            "database_edition": "ENTERPRISE_EDITION_HIGH_PERFORMANCE",
                            "db_home.#": "1",
                            "db_home.0.database.#": "1",
                            "db_home.0.database.0.admin_password": "WElcome123##",
                            "db_home.0.database.0.character_set": "",
                            "db_home.0.database.0.db_name": "nobydb1",
                            "db_home.0.database.0.db_workload": "",
                            "db_home.0.database.0.ncharacter_set": "",
                            "db_home.0.database.0.pdb_name": "",
                            "db_home.0.db_version": "11.2.0.4",
                            "db_home.0.display_name": "nobydb-dbhome01",
                            "disk_redundancy": "HIGH",
                            "display_name": "nobydb",
                            "domain": "dbad1.myvcn.oraclevcn.com",
                            "hostname": "nobydb",
 ½                          "id": "ocid1.dbsystem.oc1.phx.abyhqljs2hj3yswnj2d7wddwhbb3hrifwymfufsf4thkykmg4ahk36ytzkqa",
                            "lifecycle_details": "",
                            "listener_port": "1521",
                            "scan_dns_record_id": "",
                            "scan_ip_ids.#": "0",
                            "shape": "BM.HighIO1.36",
                            "ssh_public_keys.#": "1",

**Comment by codycushing** [comment]
This is expected behavior from Terraform. Typically users secure sensitive data in their statefiles using a secure backend. We might be able prevent this value from being stored but it requires some investigation and backwards compatibility testing.

**Comment by codycushing** [comment]
The recommendation for this is to use a secure backend for storing your statefiles. An example of how to set that up is here: https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/terraformUsingObjectStore.htm
