### ISSUE TITLE
"<" and ">" stored as \u003c and  u003e respectively in the statefile 

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-oci#307]
### Terraform Version

# Run this command to get the terraform version:

$ terraform -v

Terraform v0.10.7

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
./terraform-provider-oci_v2.0.1
2017/10/11 12:08:10 [INFO] terraform-provider-oci 2.0.1
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

### Description:
"<" and ">" stored as \u003c and  u003e respectively in the statefile where in on the console its printed as it is. 

### Terraform Plan

<details>

**maint.tf**
module "tf_iam_cn_grp" {
  source                = "./tr_iam"
  enable_flag           = true
  tenancy_ocid          = "${var.tenancy_ocid}"
  user_ocid             = "${var.user_ocid}"
  fingerprint           = "${var.fingerprint}"
  private_key_path      = "${var.private_key_path}"
  compartment_ocid      = "${var.compartment_ocid}"
  usr_list              = ["abc1@oracle.com","abc2@oracle.com","abc3@oracle.com","abc4@oracle.com","abc5@oracle.com"]
  grp_list              = "${var.CN_AdminGroupName}"
  policy_name           = "CN_AdminPolicy"
  policy_stmnts         = ["Allow group ${var.CN_AdminGroupName} to manage compartments in tenancy where target.compartment.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to manage users in tenancy","Allow group ${var.CN_AdminGroupName} to manage groups in tenancy where any {request.permission='GROUP_INSPECT', request.permission='GROUP_READ', request.permission='GROUP_CREATE'}","Allow group ${var.CN_AdminGroupName} to use groups in tenancy where target.group.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to inspect compartments in tenancy where target.compartment.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to manage virtual-network-family in tenancy where target.compartment.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to manage instance-family in tenancy where target.compartment.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to manage volume-family in tenancy where target.compartment.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to manage database-family in tenancy where target.compartment.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to manage object-family in tenancy where target.compartment.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to manage policies in tenancy where target.compartment.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to manage load-balancer in tenancy where target.compartment.name=/CN_*/","Allow group ${var.CN_AdminGroupName} to read audit-events in tenancy where target.compartment.name=/CN_*/"]

**create_user_group.tf**

resource "oci_identity_user" "UsrCreate" {
    count = "${length(var.usr_list) * var.enable_flag}"
    name = "${element(var.usr_list,count.index)}"
    description = "Terraform: CN user managed with TF"
    lifecycle {
              ignore_changes = []
             }

}

resource "oci_identity_group" "GrpCreate" {
    count =  "${var.enable_flag}"
    name = "${var.grp_list}"
    description = "Terraform: CN Group managed with TF"
    lifecycle {
               ignore_changes = []
              }

}

resource "oci_identity_ui_password" "tf_password" {
  count = "${length(var.usr_list) * var.enable_flag}"
  user_id = "${element(oci_identity_user.UsrCreate.*.id,count.index)}"
}

output "UserUIPassword" {

  sensitive = false
  value = ["${oci_identity_user.UsrCreate.*.name}","${oci_identity_ui_password.tf_password.*.password}"]
 }

resource "oci_identity_user_group_membership" "assgn" {
                compartment_id = "${var.compartment_ocid}"
                group_id = "${oci_identity_group.GrpCreate.id}"
                count = "${length(var.usr_list) * var.enable_flag}"
                user_id = "${element(oci_identity_user.UsrCreate.*.id,count.index)}"
                lifecycle {
                    ignore_changes = []
                }
                }

resource "oci_identity_policy" "iam_oci_policy_creation" {
    depends_on            = ["oci_identity_group.GrpCreate"]
    count = "${var.enable_flag}"
    name = "${var.policy_name}"
    description = "TF managed CN policy"
    compartment_id = "${var.compartment_ocid}"
    statements = "${var.policy_stmnts}"
  }

</details>

**Comment by codycushing** [comment]
Can you please explain the problem you are experiencing because of this?

**Comment by codycushing** [comment]
It's not clear what the issue is here.
