### ISSUE TITLE
Skip Source/Destination Check

### ISSUE THREAD

**Issue by RiaanRossouw** [oracle/terraform-provider-oci#315]
Terraform v0.10.7
OCI 2.0.1

### Description:
Adding Skip Source/Destination Check crash terraform.  Without below code in instance resource it works fine.

resource "oci_core_instance" "usas-qlut-gw01" {
[..]
    shape = "${var.BastionShape}"
    subnet_id = "${oci_core_subnet.Qa-bastion01-AD1.id}"
    create_vnic_details {
      skip_source_dest_check = true
    }
[..]
}

### Terraform Plan

  + oci_core_instance.usas-qlut-gw01
      id:                                           <computed>
      availability_domain:                          "Qufz:PHX-AD-1"
      compartment_id:                               "ocid1.compartment.oc1..aaaaaaaami6grl55ip2e4vesu5peoc4siddesb4557pazu7w4qktedlm24oa"
      create_vnic_details.%:                        "1"
      create_vnic_details.skip_source_dest_check:   "1"
      display_name:                                 "usas-qlut-gw01"
      hostname_label:                               <computed>
      image:                                        "ocid1.image.oc1.phx.aaaaaaaa3g2xpzlbrrdknqcjtzv2tvxcofjc55vdcmpxdlbohmtt7encpana"
      metadata.%:                                   "2"
[..]
      private_ip:                                   <computed>
      public_ip:                                    <computed>
      region:                                       <computed>
      shape:                                        "VM.Standard1.1"
      state:                                        <computed>
      subnet_id:                                    "${oci_core_subnet.Qa-bastion01-AD1.id}"
      time_created:                                 <computed>

### Terraform apply
Error applying plan:
1 error(s) occurred:
* oci_core_instance.usas-qlut-gw01: 1 error(s) occurred:
* oci_core_instance.usas-qlut-gw01: unexpected EOF

**Comment by RiaanRossouw** [comment]
[crash.log](https://github.com/oracle/terraform-provider-oci/files/1382799/crash.log)

**Comment by briangustafson** [comment]
You should be able to fix this by adding subnet_id to create_vnic_details:

    shape = "${var.BastionShape}"
    subnet_id = "${oci_core_subnet.Qa-bastion01-AD1.id}"
    create_vnic_details {
      skip_source_dest_check = true
      subnet_id = "${oci_core_subnet.Qa-bastion01-AD1.id}"
    }

subnet_id is a required parameter in create_vnic_details, but was not being enforced in 2.0.1. This is now enforced in 2.0.2. (I'll note that the duplicated subnet_id is something that we're planning to address soon. Once you add it to create_vnic_details you can remove it from the instance, but for now that requires a destroy and recreate. So for now you can avoid that by just having subnet_id in both places.)

**Comment by RiaanRossouw** [comment]
Thanks Brian! That worked for me.
