### ISSUE TITLE
resource oci_core_volume size_in_gbs key

### ISSUE THREAD

**Issue by RiaanRossouw** [oracle/terraform-provider-oci#318]
### Terraform Version
Terraform v0.10.7

### OCI Provider Version
2017/10/19 07:56:38 [INFO] terraform-provider-oci 2.0.1

### Description:
example docs show size_in_gbs for creating block volumes but it only works with size_in_mbs

### Terraform Plan
rrosso@rrosso-VirtualBox:/media/sf_KESTE/AgencyMatrix/src/terraform-Production/main$ tf plan
1 error(s) occurred:
* oci_core_volume.t: : invalid or unknown key: size_in_gbs

**Comment by RiaanRossouw** [comment]
I just noticed this bug fix in 2.0.2 https://github.com/oracle/terraform-provider-oci/issues/297

Any idea when 2.0.2 is coming because I can't get 2.0.1 size_in_mbs to work either and I can't go back to 2.0.0 because it does not have skip_dest_source.  This is getting urgent for a production deployment.

**Comment by briangustafson** [comment]
2.0.2 was released last week - see https://github.com/oracle/terraform-provider-oci/releases. Please give it a try.

**Comment by RiaanRossouw** [comment]
Thanks I tried 2.0.2 and maybe I am losing my mind but it appears to work fine with apply but there is nothing in the console afterwards....

oci_core_volume.kvm-disk01: Creating...
  availability_domain: "" => "BDQS:US-ASHBURN-AD-1"
  compartment_id:      "" => "ocid1.tenancy.oc1..aaaaaaaaqgtun34nh3djsbx7oi23amylou7elkyws4yrnyrv3e35uoua7jwa"
  display_name:        "" => "kvm-disk01"
  size_in_gbs:         "" => "2000"
  size_in_mbs:         "" => "<computed>"
  state:               "" => "<computed>"
  time_created:        "" => "<computed>"
oci_core_volume.kvm-disk01: Still creating... (10s elapsed)
oci_core_volume.kvm-disk01: Creation complete after 14s (ID: ocid1.volume.oc1.iad.abuwcljtsnieipldxe...6w5zysxrez4osxtqdpdiyxi4hbfm4arquiksua)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

**Comment by RiaanRossouw** [comment]
Brian can you confirm this is not a serious regression...

I tried in another tenancy and the same thing happened terraform is all happy but the console does not show this block volume.  I can even destroy it from terraform again.  

variable "DBSize" {
  default = "50" // size in GBs, min: 50, max 16384
}
resource "oci_core_volume" "t" {
  availability_domain = "${data.oci_identity_availability_domains.ADs.availability_domains.0.name}"
  compartment_id = "${var.tenancy_ocid}"
  display_name = "-tf-volume"
  size_in_gbs = "${var.DBSize}"
}

oci_core_volume.t: Creating...
  availability_domain: "" => "Qufz:PHX-AD-1"
  compartment_id:      "" => "ocid1.tenancy.oc1..aaaaaaaaw4a2agyum2bsnk6hfvgrvefkiqpghnr6jggyzvvt3f4yrsbkeibq"
  display_name:        "" => "-tf-volume"
  size_in_gbs:         "" => "50"
  size_in_mbs:         "" => "<computed>"
  state:               "" => "<computed>"
  time_created:        "" => "<computed>"
oci_core_volume.t: Still creating... (10s elapsed)
oci_core_volume.t: Creation complete after 14s (ID: ocid1.volume.oc1.phx.abyhqljt2tx2ny2nw2...jxsb62nfgnmxammdt7o4jp4kbulgj4gxvwegqq)

**Comment by parweza** [comment]
@RiaanRossouw 
I was able to create the volume with above mentioned config. Can you please confirm if you have selected right compartment and region in the console?

Thanks.

**Comment by RiaanRossouw** [comment]
Thanks I just noticed that also.  It is probably a mistake here that tripped me up!
https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/storage/block/block.tf

**Comment by codycushing** [comment]
That is not a mistake, this example shows how to use the block volume resource, not manage compartments--it uses the root compartment (tenancy) to minimize example scope. 

size_in_mbs should have worked for you in 2.0.1, what error did you receive?

**Comment by RiaanRossouw** [comment]
Both are working for me now with 2.0.2 thanks.  I probably fat fingered the zeros with size_in_mbs before.
