### ISSUE TITLE
Default Route Table/Default Security List objects are always created and there's no way to update them

### ISSUE THREAD

**Issue by lucassrg** [oracle/terraform-provider-oci#322]
### Terraform Version

<details>
Terraform v0.10.6
</details>

### OCI Provider Version

<details>
terraform-provider-oci 2.0.2
</details>

### Description:
Running either the [vcn_full](https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/networking/vcn_full/vcn_full.tf) example or the [template file](https://gist.github.com/lucassrg/9b97fb224cb4882d7db6b04a5b048ea8) I created, the `Default Security List for <vcn>` or `Default Route Table for <vcn>` objects are *always* created and there's no way to remove them. You can just read these objects since they are available as [data sources](https://github.com/oracle/terraform-provider-oci/blob/7be1a4d5a8cc7895f742e3cfae5db3f07d081204/docs/datasources/core/virtual_networks.md).

Having these objects created by default seems to be a default behavior from OCI since these objects are also created via OCI Console. However, through the UI, there's a possibility to modify them, and I could not find a way to do it via Terraform, which lead us to have always 2 security lists created in case you need to specify any additional security rule not available in the default security list. The same applies for the Route table resource.

**Comment by briangustafson** [comment]
The creation of those default resources happens at the service level when creating a VCN, and this is not something that can currently be disabled. You bring up a good point that there is no good way to modify these default resources from Terraform. This is something that we are tracking and will be looking into.

**Comment by alexng-canuck** [comment]
The fix for this has been merged. Please see https://github.com/oracle/terraform-provider-oci/blob/master/docs/Managing%20Default%20Resources.md for details on how to configure default VCN resources in Terraform.
