### ISSUE TITLE
Can we use Consul as a backend for OCI Terraform

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-oci#324]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.10.7
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

2017/10/23 10:16:14 [INFO] terraform-provider-oci 2.0.1
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

</details>

### Description:
Can I use Consul as a backend for managing OCI terraform remote statefile ?

terraform {
  backend "consul" {
    address = "<consul_host>:<port>"
    path    = "terraform/stor_remote_statefile"
    scheme  = "https"
  }
}
### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by briangustafson** [comment]
This is not something that we've explicitly tested, but generally the OCI provider should work with any backend. The OCI provider doesn't do anything special regarding statefile management.
