### ISSUE TITLE
Support Block Volume Fast Clones

### ISSUE THREAD

**Issue by philskents** [oracle/terraform-provider-oci#327]
How do we reproduce the functionality described in this article with the terraform OCI provider?

https://blogs.oracle.com/cloud-infrastructure/cloud-wars%3a-arrival-of-block-volume-clones

**Comment by briangustafson** [comment]
Support for cloning will be available in the provider in the near future.

**Comment by briangustafson** [comment]
This is now available in 2.0.4.

**Comment by saifkhan179** [comment]
Can we clone Block volumes through terraform in OCI ?
