### ISSUE TITLE
invalid or unknown key: initial_data_storage_size_in_gb with the latest v2.0.3 plugin

### ISSUE THREAD

**Issue by swmuruga** [oracle/terraform-provider-oci#336]
### Terraform Version

Terraform v0.10.6

### OCI Provider Version
-rwxr-xr-x. 1 opc opc 19078698 Oct 27 15:07 terraform-provider-oci_v2.0.3

### Description:
Trying to launch a VM based Database System with the latest OCI plugin and it failed with " invalid or unknown key: initial_data_storage_size_in_gb"

### Terraform Plan

resource "oci_database_db_system" "VMDB" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
  compartment_id = "${var.compartment_ocid}"
  cpu_core_count = "${var.CPUCoreCount}"
  database_edition = "${var.DBEdition}"
  db_home {
    database {
      "admin_password" = "${var.DBAdminPassword}"
      "db_name" = "${var.DBName}"
      "character_set" = "${var.CharacterSet}"
      "ncharacter_set" = "${var.NCharacterSet}"
      "db_workload" = "${var.DBWorkload}"
      "pdb_name" = "${var.PDBName}"
    }
    db_version = "${var.DBVersion}"
    display_name = "${var.DBDisplayName}"
  }
  disk_redundancy = "${var.DBDiskRedundancy}"
  shape = "${var.DBNodeShape}"
  subnet_id = "${var.SubnetOCID}"
  ssh_public_keys = ["${var.ssh_public_key}"]
  display_name = "${var.DBNodeDisplayName}"
  domain = "${var.DBNodeDomainName}"
  hostname = "${var.DBNodeHostName}"
  data_storage_percentage = "40"
  initial_data_storage_size_in_gb = "${var.InitialDataStorageSizeInGB}"
  license_model = "${var.LicenseModel}"
  node_count = "${var.NodeCount}"

**Comment by swmuruga** [comment]
after changing the key from "initial_data_storage_size_in_gb" to "data_storage_size_in_gb", we are able to launch the database. The example needs to be updated accordingly.

**Comment by briangustafson** [comment]
Thanks for reporting this - I have a fix for the example and docs out for review at https://github.com/oracle/terraform-provider-oci/pull/337.
