### ISSUE TITLE
Unable to specify source ports in security list rules

### ISSUE THREAD

**Issue by darkfibre** [oracle/terraform-provider-oci#338]
### Terraform Version
Terraform v0.10.7

### OCI Provider Version
terraform-provider-oci_v2.0.3

### Description:
Both ingress and egress security list rules assume the ports specified in "tcp_options" or "udp_options" are destination ports. There are situations where source ports must be specified, stateless rules in particular need to match the source port in order to permit return traffic.

You can manually fix the rule using the OCI web interface, but subsequent terraform runs will revert the change.

**Comment by briangustafson** [comment]
Thanks for reporting, we'll be looking into this.

**Comment by briangustafson** [comment]
This has been fixed in release 2.0.5. Please give it a try.
