### ISSUE TITLE
oci_core_images returns incompatible GPU image as the first available Oracle Linux 7.4

### ISSUE THREAD

**Issue by jlamillan** [oracle/terraform-provider-oci#345]
### Description:

It looks like oci_core_images is now returning a GPU image as the first image in the list, which will cause an error _unless_ the user is using the BM.GPU2.2 shape.

IMO, this is a problem since a lot of the example code sets up their oci_core_images data source like:

```
data "oci_core_images" "ImageOCID" {
  compartment_id           = "${var.compartment_ocid}"
  operating_system         = "${var.os}"
  operating_system_version = "${var.version}"
}
```

and use it like:

```
resource "oci_core_instance" "TFInstance" {
  ...
  image               = "${lookup(data.oci_core_images.ImageOCID.images[0], "id")}"
  shape               = ANY SHAPE BESIDES BM.GPU2.2
  ...
}
```

However, when `var.os=Oracle Linux` and `var.version=7.4` and you try and create an instance, you'll get an error:

### Terraform Plan

<details>
```
* oci_core_instance.TFInstanceK8sMaster: Status: 400; Code: InvalidParameter; OPC Request ID: /XXXXX; Message: Shape VM.Standard1.8 is not valid for image ocid1.image.oc1.iad.aaaaaaaaflaxipg2k4l7mjudowij5vic76jjnqgzktw46pga4knjpqcrxw6a.
```
</details>

-----

Assuming the image ordering for Oracle Linux 7.4 is here to stay, users would be better off passing the image name in directly in the data source like so:

```
data "baremetal_core_images" "ImageOCID" {
    compartment_id = "${var.compartment_ocid}"
    display_name = "Oracle-Linux-7.4-2017.08.25-0"
}
```

**Comment by briangustafson** [comment]
Thanks for reporting. As mentioned in #342, we're looking into the right long term fix for specifying images. For now, I believe that your suggestion of switching the examples to filter on display_name is a good one.

**Comment by tomzepf-oracle** [comment]
This has just broken quite a bit of our terraform, and a number of examples in the docs/examples directory.

**Comment by briangustafson** [comment]
I've merged a change to update the examples to filter on display_name, as suggested by @jlamillan. Each example also includes the following note: "This technique is for example purposes only. The results of oci_core_images may change over time for Oracle-provided images, so the only sure way to get the correct OCID is to supply it directly."

We're looking into the correct long term solution to this problem.

**Comment by briangustafson** [comment]
A long-term solution to this issue is being tracked with #352.
