### ISSUE TITLE
Results of oci_core_images will change over time for Oracle-provided images

### ISSUE THREAD

**Issue by briangustafson** [oracle/terraform-provider-oci#352]
The data source "oci_core_images" is backed by the ListImages API, which returns both user-created and Oracle-provided images. However, the Oracle-provided images will change over time, with new images being added and old ones removed. That means that relying on this to get the OCID of an Oracle-provided image is likely to eventually break. However, hard-coding OCIDs is also problematic: the Oracle-provided images have different OCIDs for each region, which means that hard-coding an OCID will limit the config to a single region.

Currently, most of the examples in this provider filter images on display_name with the following note:

    # Gets the OCID of the image. This technique is for example purposes only. The results of oci_core_images may
    # change over time for Oracle-provided images, so the only sure way to get the correct OCID is to supply it directly.
    data "oci_core_images" "image-list" {
        compartment_id = "${var.compartment_ocid}"
        display_name = "Oracle-Linux-7.4-2017.10.25-0"
    }

This issue is tracking a better solution to this problem. (See related issues #342 and #345.)

Note that filters may also be used on oci_core_images, but that too will likely break with time for Oracle-provided images.

**Comment by kohashim** [comment]
I think hard-coding OCIDs is a valid option here.  In fact, I believe most of users are hard-coding OCIDs for images for their production systems, rather than picking up a random image from ListImages API.  Thus the current examples with the data source "oci_core_images" show a technique which is not quite useful for actual use cases.

A map variable can be used for choosing a right OCID for each region.  The examples would need to be updated when a new region is added or the image needs to be updated for reasons such as a security update.

**Comment by briangustafson** [comment]
Agree - using image OCIDs directly should be the standard approach for production use cases, and as you mention this could be selected from a map variable based on region. We'll update the docs and examples to reflect this.

**Comment by briangustafson** [comment]
Most of the examples now reference the image OCID directly using a map variable - see for example https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/compute/private_ip/private_ip.tf#L66 .

**Comment by parweza** [comment]
we are still using datasource in following:
docs/solutions/glusterfs/compute.tf
docs/solutions/omc_monitored_server/chef_stage_and_monitor_instance/main.tf
docs/solutions/omc_monitored_server/stage_and_monitor_instance/main.tf
docs/solutions/omc_monitored_server/stage_server/main.tf

**Comment by rohanbhattacharjee** [comment]
The last few examples called out here has been fixed - https://github.com/oracle/terraform-provider-oci/commit/2cf466d69fba146751fd1460f5c70b61075cb256#diff-f0a2b658e73fad9bc7cf9b65b32ebfef

**Comment by keithhopkins-gpc** [comment]
The following examples are still using datasource:
/docs/examples/compute/image/compute.tf

**Comment by codingarchitect** [comment]
Hi,
Can we have a solution like follows:
- to use latest on first run and
- pin it to to that id on subsequent runs -
Some other tools use something called a lock file. Till some thing of that sort is available in terraform everything else is a compromise.
I do not know if this is feasible at the terraform oci provider or needs to be done at terraform level.
But it would be better than hardcoding ids

Thanks & Regards,
Sendhil
