### ISSUE TITLE
Maximum number of objects in a security rule?

### ISSUE THREAD

**Issue by philskents** [oracle/terraform-provider-oci#356]
### Terraform Version

0.10.7

### OCI Provider Version

2.0.1

### Description:
I get the error "Message: The requested ingress security rule count '61' is invalid for this request type." when creating longer security rules

**Comment by kohashim** [comment]
According to https://docs.us-phoenix-1.oraclecloud.com/Content/General/Concepts/servicelimits.htm (expand "Networking Limits"/"Security List Limits"), a security list can have at most 50 ingress rules by default.

You can request a service limit increase via My Oracle Support.  See the same doc above and find the section "Requesting a Service Limit Increase".

**Comment by kohashim** [comment]
Closing for now.  Reopen if you have any further questions.  Thanks.
