### ISSUE TITLE
Multiple route rules

### ISSUE THREAD

**Issue by RiaanRossouw** [oracle/terraform-provider-oci#357]
### Terraform Version
0.10.7
### OCI Provider Version
2.0.4

### Description:
Multiple route rules in route table

Can't add multiple route rules.  Expect it should work like security lists using square brackets but not working.  Can someone confirm this is a bug or just my mistake.

resource "oci_core_route_table" "NAT" {
    compartment_id = "${var.compartment_ocid}"
    vcn_id = "${oci_core_virtual_network.NonProd-VCN.id}"
    display_name = "NAT"
    route_rules [{
        cidr_block = "0.0.0.0/0"
        network_entity_id = "ocid1.privateip.blah"
    },{
        cidr_block = "192.168.150.0/24"
        network_entity_id = "ocid1.drg.blah"
    }]
}

**Comment by kohashim** [comment]
Did 'terraform init' succeed?  '=' is missing after 'route_rules'.

**Comment by RiaanRossouw** [comment]
My bad.  It was working with one rule for plan and apply.  I must have dropped the "=" when I made it a list with square brackets.  And of course assumed it is barfing on multiple items and not syntax.

I run clean now with two rules.

No changes. Infrastructure is up-to-date.
