### ISSUE TITLE
Example for iscsiattach.sh is in nfs directory vs. block directory

### ISSUE THREAD

**Issue by nelsonse** [oracle/terraform-provider-oci#363]
Example showing how to scan for all iscsi block targets is currently in the NFS examples and belongs in the block examples:

https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/storage/nfs/userdata/iscsiattach.sh

should be:
https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/storage/block/userdata/iscsiattach.sh

**Comment by parweza** [comment]
After looking into the code I think you have the script placed correctly. The script is used for connecting block volume not for creating one. 
In addition to that [nfs-bootstrap](https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/storage/nfs/userdata/nfs-bootstrap#L10) directly refers to this scrip t. Restructure will break this script for clients using old version. 
Please let me know your thoughts.
