### ISSUE TITLE
Cannot create new secondary vNIC on existing instance after deletion of original

### ISSUE THREAD

**Issue by nelsonse** [oracle/terraform-provider-oci#365]
### Terraform Version

Terraform v0.10.8

### OCI Provider Version

v2.0.3

### Description:
After initially creating an instance with a secondary vNIC, delete the vNIC only using --target=<vnic>, then create a new one using any method.  Terraform does not simply create a new vNIC but wants to re-create the entire environment.  This occurs whether you perform a targeted apply or generic apply.

### Terraform Plan

[kvm.tar.txt](https://github.com/oracle/terraform-provider-oci/files/1481032/kvm.tar.txt)

tarball with all .tf files, current .tfstate after deletion, and backup tfstate prior to deletion

**Comment by rcohenma** [comment]
I can't reproduce this issue.

I have a instance and a vnicAttachment  in my config.
I can create them with no problem.
I then use a target delete on the vnicAttachment
~/terraform destroy -target=oci_core_vnic_attachment.SecondaryVnicAttachment

I then do a ~/terraform plan
showing only the SecondaryVnicAttachment would be created.

I then did a ~/terraform apply
Only the SecondaryVnicAttachment got recreated.

When you say "delete the vNIC only using --target=",
do you mean the oci_core_vnic_attachment as my command shows above?

**Comment by rcohenma** [comment]
can you send the ~/terraform plan output after you do the targeted deletion of the vnic attachment?

**Comment by nelsonse** [comment]
If you change the vcn/subnet combination used from the original secondary vNIC creation to a different one, what happens then...

**Comment by rcohenma** [comment]
subnet_id is not an updatable value of vnic_attachment. A change of subnet_id will force a new vnic_attachment. the existing one will be destroyed and a new one will be created with the updated values.

**Comment by nelsonse** [comment]
I cannot seem to repo at this time.  Go ahead and close this issue.
