### ISSUE TITLE
Chef provisioner with Volume attach resource problem

### ISSUE THREAD

**Issue by herasimau** [oracle/terraform-provider-oci#372]
### Terraform Version
v.0.10.8

### OCI Provider Version
v2.0.4

### Description:
In the same terraform project where exists creation of instance with chef provisioner and volume attach resource, i have this error when provisioner installs chef client : 

```
null_resource.chef (chef): Thank you for installing Chef!
null_resource.chef (chef): rm: cannot remove /tmp/install.sh.11347': No such file or directory
null_resource.chef (chef): Cleanup user key...

Error: Error applying plan:
1 error(s) occurred:
null_resource.chef: 1 error(s) occurred:
Command "sudo bash ./install.sh -v \"\"" exited with non-zero exit status: 1
```
Volume resource depends on chef provisoner.

### Terraform Plan

[chef-node.zip](https://github.com/oracle/terraform-provider-oci/files/1514679/chef-node.zip)

A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

**Comment by briangustafson** [comment]
I see that you're using the image "Oracle-Linux-6.9-2017.10.25-0", and I'm able to reproduce the same error when running the solution at https://github.com/oracle/terraform-provider-oci/tree/master/docs/solutions/chef with that image. However, if I use "Oracle-Linux-7.4-2017.10.25-0" then it succeeds. 

I'm not yet sure why the 6.9 image is failing, but would it be an acceptable workaround to use 7.4 for now?

**Comment by herasimau** [comment]
Unfortunately no, another workaround that i can suggest is to install chef-client in separate remote-exec provisioner, example :
```
  provisioner "remote-exec"{

    connection {
      host = "${oci_core_instance.LiferayInstance.public_ip}"
      type = "ssh"
      user = "opc"
      private_key = "${var.ssh_private_key}"
      timeout = "10m"
    }
    inline = ["sudo mkdir /home/opc/download/",
      "sudo chown -R opc:opc /home/opc/download/",
      "curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -d /home/opc/download/ && rm install.sh"]

  }
```

  and in chef provisioner you need to skip install with this flag

`skip_install = true`

**Comment by parweza** [comment]
Hi,
I was able able to reproduce the issue up until yesterday. Now I am not . This may be related to  chef releasing new version (not sure) https://downloads.chef.io/chef/13.6.4.

Can you please confirm if you are still facing the issue?

Thanks,
Parwez

**Comment by briangustafson** [comment]
Closing, but please let us know if you continue to see this issue.
