### ISSUE TITLE
Read UI Password vs Create/Reset UI Password

### ISSUE THREAD

**Issue by markpinkston** [oracle/terraform-provider-oci#381]
I have a general question about resource "oci_identity_ui_password".  I'm passing an initial list of users as a variable and then iterating on that list to do various functions, including print the initial password.  If I update my list of users by adding one to the list, my code runs "oci_identity_ui_password" all over again for all created users.  This ends up resetting the existing users' passwords to a new one-time password.  Is there any ability to simple read a UI password or run a conditional to prevent "oci_identity_ui_password" from being run on existing users, and only to run on new users?

**Comment by rohanbhattacharjee** [comment]
Hi @markpinkston,

For the first part of your question, regarding whether we could simply read the UI password for an existing user, the answer is, unfortunately, no.

The API reference for the `UIPassword` is available here - https://docs.us-phoenix-1.oraclecloud.com/api/#/en/identity/20160918/UIPassword/. This `UIPassword` resource does not have a `GET` operation available for it.

Regarding the second part of your question about preventing `oci_identity_ui_password` from being run for existing users, it would help if we can see your terraform configuration files (`*.tf`) and the terraform state file (`*.tfstate`).

It seems (looking at our code), when we create this `UIPassword` resource, we do save information in the `tfstate` file. Hence if you were to run the `terraform plan/apply` for users for whom the `UIPassword` resource were already created, terraform should automatically skip invoking the resource-creation call. Hence, if we could access your terraform config and state files, it would help us make progress on that front.

**Comment by markpinkston** [comment]
Okay, I had to redact and reduce the code to the simplest version, which I will include here.  Basically, you create a list of users, pass that list to Create User, and iterate through the list using UI password to list the initial credentials.  But if I add another user to the list, UI password is run again for ALL users.  Is there a way to prevent this?

variables.txt: original
variables2.txt: add "user3"
user.txt: create users and run UI password then output user/pass

[variables.txt](https://github.com/oracle/terraform-provider-oci/files/1553398/variables.txt)
[variables2.txt](https://github.com/oracle/terraform-provider-oci/files/1553399/variables2.txt)
[user.txt](https://github.com/oracle/terraform-provider-oci/files/1553400/user.txt)



[terraform plan and apply add user3.txt](https://github.com/oracle/terraform-provider-oci/files/1553387/terraform.plan.and.apply.add.user3.txt)
[terraform plan and apply create user1 user2.txt](https://github.com/oracle/terraform-provider-oci/files/1553388/terraform.plan.and.apply.create.user1.user2.txt)

**Comment by briangustafson** [comment]
Closing, but please reopen if this approach does not work for you.
