### ISSUE TITLE
remote state in OCI object storage

### ISSUE THREAD

**Issue by dzejar** [oracle/terraform-provider-oci#384]
Hi, is there already a way how to store remote state in the OCI storage? It seems that OCI already has [S3 compatibility storage](https://docs.us-phoenix-1.oraclecloud.com/api/#/en/s3objectstorage/20160918/) for some time, but the native [terraform s3 backend](https://www.terraform.io/docs/backends/types/s3.html) seems to have no option to configure different API endpoint and use OCI one instead of AWS S3. Does anybody know about a hack for this? Or is there (planned?) some support for this feature in OCI terraform provider?

**Comment by sanketdjain** [comment]
@rohanbhattacharjee Can you provide an example with `PAR` and `http` backend ?

**Comment by sn-narang** [comment]
Hi @dzejar 

You can store remote state in OCI by creating a pre-authenticated request. 

You can refer this wiki page for detailed steps - [](https://github.com/oracle/terraform-provider-oci/wiki/Using-Oracle-Object-Storage-to-store-Terraform-state-files)

Please let us know if you have any additional feedback. We are also planning more native support for this feature and will keep you updated.

**Comment by sn-narang** [comment]
Hi @sanketdjain 

An example with PAR and http backend is published on this wiki - [https://github.com/oracle/terraform-provider-oci/wiki/Using-Oracle-Object-Storage-to-store-Terraform-state-files](https://github.com/oracle/terraform-provider-oci/wiki/Using-Oracle-Object-Storage-to-store-Terraform-state-files)

Please let us know if you have any additional feedback

**Comment by br0ziliy** [comment]
@sanketdjain @dzejar 
With the latest Terraform and OCI provider, following S3 backend configuration works for storing state file in OCI Object Storage (note that `bucket` and `key` config parameters need special attention):

```
terraform {
   backend "s3" {
       endpoint = "compat.objectstorage.us-phoenix-1.oraclecloud.com" # This will be always the same
       region = "us-phoenix-1" # or us-ashburn-1
       bucket = "[YOUR_TENANT_NAME]" # Put the tenant name here
       key = "tfstate/mystate" # This should contain "[OCI_BUCKET_NAME]/[OBJECT_NAME]"
       access_key = "[OCID of Amazon S3 compat key]" 
       secret_key =  "[base64-encoded secret key from OCI WebUI]"
       # All S3-specific validations are skipped:
       skip_region_validation = true
       skip_credentials_validation = true 
       skip_get_ec2_platforms = true
       skip_requesting_account_id = true
       skip_metadata_api_check = true
   }
}
```

There will be no locking available with this configuration.
@sn-narang mind adding this as a separate Wiki page?

**Comment by sn-narang** [comment]
@dzejar Support for locking of state files is on our roadmap and we are currently prioritizing it. I will keep you posted on this. Is this currently a blocker for you ?

**Comment by sn-narang** [comment]
@br0ziliy I am making a note of this. Will add it to the wiki. Thank you so much !

**Comment by dzejar** [comment]
@sn-narang Not a big blocker currently, but would be very nice to have soon, as more people are going to use it in my team.

**Comment by tama1214** [comment]
@sn-narang  Did you manage to solve the problem with  state locking  in OCI Object Storage?

**Comment by chrishiner** [comment]
Any more updates on this? It seems dumb to me to have to use another cloud provider for state/locking for our terraform configs for OCI instead of using OCI Object Storage.

**Comment by gibsster** [comment]
> @sn-narang, Did OCI manage to solve the problem with state locking in OCI Object Storage? This is a hot topic for our company - we are actively using OСI resources, and the lack of this useful feature is a bit disappointing. Thanks.

do you know if it's already possible to lock the state file in OCI using S3-Compatible Backend?

**Comment by gibsster** [comment]
@tama1214 do you know if it's already possible to lock the state file in OCI using S3-Compatible Backend?

**Comment by tama1214** [comment]
@gibsster , yes it is possible to use OCI Object storage using S3-Compatible Backend. Backend config below:

'''
terraform {
   backend "s3" {
     bucket   = "<my-bucket-name>"   # your bucket name
     key      = "terraform.tfstate"            # your terraform tfstate file name
     region   = "<region>"                     # OCI bucket  region
     endpoint = "<your_endpoint>"      # Example: https://<tenant_name>.compat.objectstorage.us-ashburn-1.oraclecloud.com
     skip_region_validation      = true
     skip_credentials_validation = true
     skip_requesting_account_id  = true
     skip_get_ec2_platforms      = true
     skip_metadata_api_check     = true
     force_path_style            = true
   }
 }
'''

**Comment by rodrigc** [comment]
@gibsster @tama1214 @dzejar @chrishiner @br0ziliy I filed a Support Request ticket with Oracle Cloud.
Oracle aknowledged that the Terraform provider for Oracle storage does not currently support tfstate locking.

I pointed out to Oracle that competing clouds support this feature:

* AWS, https://developer.hashicorp.com/terraform/language/settings/backends/s3
* Azure, https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli#4-understand-state-locking and https://developer.hashicorp.com/terraform/language/settings/backends/azurerm
* Google, https://developer.hashicorp.com/terraform/language/settings/backends/gcs



Oracle created an Enhancement Request **R2-37831**
to add tfstate locking to the Terraform provider for Oracle storage.
Oracle did not confirm a timeline as to when tfstate locking will be added to the Oracle Terraform provider.

If you want to check on the status of this Enhancement Request  **R2-37831**, you will need to submit
a support ticket at https://support.oracle.com
