### ISSUE TITLE
iam policy resource compartment change didn't take

### ISSUE THREAD

**Issue by nshttpd** [oracle/terraform-provider-oci#386]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

```
Terraform v0.11.1
+ provider.oci v2.0.4
```
</details>

### Description:

should a `compartment_id` change to a policy require ForceNew? 

https://github.com/oracle/terraform-provider-oci/blob/master/provider/identity_policy_resource.go#L34

Did an apply and created a policy within a compartment and realized it was the incorrect one. Updated the `compartment_id` and ran another apply. Terraform and the provider reported that it was just a modification and went about doing it's work. The policy itself though when looking through the Console UI never moved compartments.

**Comment by rohanbhattacharjee** [comment]
Hi @nshttpd,

This looks like a bug. I will log a JIRA for it and address this ASAP.

Thanks for reporting this.

**Comment by rohanbhattacharjee** [comment]
#389 addresses this bug. Thanks for reporting this.

**Comment by rohanbhattacharjee** [comment]
This should be fixed with the release that we did last week - https://github.com/oracle/terraform-provider-oci/releases/tag/v2.0.5
