### ISSUE TITLE
Add support for resource tagging

### ISSUE THREAD

**Issue by jhorwit2** [oracle/terraform-provider-oci#400]
https://docs.us-phoenix-1.oraclecloud.com/Content/General/Concepts/resourcetags.htm

**Comment by br0ziliy** [comment]
Hi guys, is this somewhere on the roadmap?

**Comment by abdul-git** [comment]
Hello - I would also like update on this...when tagging will be available with Terraform?

**Comment by mies** [comment]
any update on this?

**Comment by boatrig** [comment]
Does this enhancement request include the ability to create Defined tags Name Spaces using Terraform?

**Comment by ljsmith93** [comment]
This would be really useful...

**Comment by jhorwit2** [comment]
@anandhmahal any eta on this feature? I notice it's in progress, but don't see any PR.

**Comment by keithhopkins-gpc** [comment]
+1 on needing this feature.  We use tags for chargeback.

**Comment by codycushing** [comment]
Support for tagging resources and filtering by tags has been added in release 2.1.13
