### ISSUE TITLE
Enhancement Request - VCN Peering Resource

### ISSUE THREAD

**Issue by jobmiller** [oracle/terraform-provider-oci#404]
Please add a VCN Peering Resource to enable initiation of peering requests.

**Comment by cgong-github** [comment]
Any update on this enhancement?

**Comment by ora1521** [comment]
LPGs and VCN Peering seems to be one of the most significant components in modern OCI architecture. Do you have any details when this feature will be available?

**Comment by jjwarzecha** [comment]
With an inter-region peering announced - [remoteVCNpeering](https://docs.us-phoenix-1.oraclecloud.com/Content/Network/Tasks/remoteVCNpeering.htm) - it is a must. 
Please add a higher priority to this feature :-)

**Comment by codycushing** [comment]
Remote Peering available in release v2.1.8
