### ISSUE TITLE
Enhancement Request - Filter support for VCN and DB System

### ISSUE THREAD

**Issue by sanketdjain** [oracle/terraform-provider-oci#408]
### Terraform Version
Terraform v0.11.1

    provider.null v1.0.0
    provider.oci v2.0.5
    provider.template v1.0.0

### OCI Provider Version

    oci_v2.0.5 
    2018/01/05 09:35:28 [INFO] terraform-provider-oci 2.0.5

### Description:
Currently, the VCN and DB System data sources do not support filtering on name. It is would be very convenient if we can allow filter attribute on these data sources.

VCNs can be created with duplicate names, but this can be very confusing. For test deployments, it is okay to share an existing VCN, and a lookup on the VCN data source with filter on the name.

### Terraform Plan

N/A as this is enhancement request.

**Comment by alexng-canuck** [comment]
Thanks @sanketdjain for the suggestion. We will look into this.

I believe filter by name is currently supported for VCN data sources at least.

For example:
`data "oci_core_virtual_networks" "vcn" {
	compartment_id = "${data.oci_identity_compartments.compartment.compartments.0.id}"
	filter {
		name = "display_name"
		values = [ "my_vcn_name" ]
	}
}`

Is this what you're looking for?

**Comment by rcohenma** [comment]
Looks like we are missing the filtering logic in the DBSystem data_source. We will add it soon.

**Comment by rohanbhattacharjee** [comment]
Hi @sanketdjain ,

Please try out the new filters (includes VCNs and DBaas) that have been released as part of https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.0-beta. Obviously, it will also be available when the v2.1.0 is released.

Thanks
Rohan

**Comment by michaelhart** [comment]
Just a follow up: v.2.1.0 has been released, which adds additional filter options for all data sources.

Details here: https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.0
