### ISSUE TITLE
Enhancement Request - Backend creation with all load balancers to which backend set is registered

### ISSUE THREAD

**Issue by sanketdjain** [oracle/terraform-provider-oci#409]
### Terraform Version
Terraform v0.11.1

    provider.null v1.0.0
    provider.oci v2.0.5
    provider.template v1.0.0

### OCI Provider Version

    oci_v2.0.5
    2018/01/05 09:35:28 [INFO] terraform-provider-oci 2.0.5

### Description:
For creating a complete load balancer system, we require the following:

- load balancer
- listener
- backendset
- backends
- compute instances

Each of the above can be more than one resource using "count" in the resource.

Consider creating 2 Load Balancers:
- When creating 2 load balancers, we need to register the backendset to each load balancer. This can be accomplished using the count on backendset resource.
- But when creating backends for one or more compute instances, we need to register the backend with each backend set, for each load balancer. This is a m*n iteration, where m=number of load balancers, and n=number of compute instances.

Terraform cannot handle double iteration easily, it only handle flat iterations using count. This can be done for the first time by using a count of <m*n> for the backend resource, but future additional of load balancers or resources will cause deletion+creation of resources.

### Terraform Plan

Instead of Terraform Plan, I am including below the Terraform resource definitions to support the above desription. As this is enhancement request, the below information should be more useful than a Terraform Plan:

```
// Load Balancers
resource "oci_load_balancer" "lb" {
  count          = "${var.lb_count}"
  shape          = "${var.lb_shape}"
  compartment_id = "${oci_identity_compartment.comp.id}"
  subnet_ids     = [
    "${element(oci_core_subnet.sub_lb.*.id, count.index)}",
    "${element(oci_core_subnet.sub_lb.*.id, count.index+1)}"
  ]
  display_name   = "${format("%s-%s","lb", "${count.index}")}"
}

// SSL Certificate
resource "oci_load_balancer_certificate" "cert_lb" {
  count              =  "${var.lb_count}"
  load_balancer_id = "${element(oci_load_balancer.lb.*.id, count.index)}"
  certificate_name   = "${format("%s-%s","cert_lb", "${count.index}")}"
  ca_certificate     = "${file("${var.tls_path}/ca_cert.crt")}"
  public_certificate = "${file("${var.tls_path}/cert.crt")}"
  private_key        = "${file("${var.tls_path}/cert.key")}"
}

// HTTP Listener
resource "oci_load_balancer_listener" "lis_https" {
  count                    = "${var.lb_count}"
  load_balancer_id         = "${element(oci_load_balancer.lb.*.id, count.index)}"
  name                     = "${format("%s-%s","list-https", "${count.index}")}"
  default_backend_set_name = "${element(oci_load_balancer_backendset.bes_wls.*.id, count.index)}"
  port                     = "443"
  protocol                 = "HTTP"

  ssl_configuration {
    certificate_name        = "${element(oci_load_balancer_certificate.cert_lb.*.certificate_name, count.index)}"
    verify_peer_certificate = false
  }
}

// HTTP Backend Set
resource "oci_load_balancer_backendset" "bes_wls" {
  count          = "${var.lb_count}"
  name           = "${format("%s-%s","bes-wls", "${count.index}")}"
  load_balancer_id = "${element(oci_load_balancer.lb.*.id, count.index)}"
  policy           = "ROUND_ROBIN"

  health_checker {
    port     = "${local.wls_health_port}"
    protocol = "HTTP"
    response_body_regex = ".*"
    url_path = "/"
  }
}

// Backends
resource "oci_load_balancer_backend" "be_wls" {
  count            = "${var.wls_count * var.lb_count}"
  load_balancer_id = "${element(oci_load_balancer.lb.*.id, count.index % var.lb_count)}"
  backendset_name  = "${element(oci_load_balancer_backendset.bes_wls.*.id, count.index % var.lb_count)}"
  ip_address       = "${element(oci_core_instance.serv_wls.*.private_ip, count.index / var.lb_count)}"
  port             = "${local.wls_broker_port}"
  backup           = false
  drain            = false
  offline          = false
  weight           = 1
}
```

The most interesting part is the backend creation as "be_wls" resource above. The above definition will cause deletion+creation of all backends when either the number of load balancer (var.lb_count) changes or the number of compute instances (serv_wls) changes.

Adding new computes is more common operation. So in order to mitigate the issue when new compute instances are added, I included ignore_changes in lifecycle on the backend resource.

```
// Backends, allowing addition of new Computes without deletion of resources
resource "oci_load_balancer_backend" "be_wls" {
  count            = "${var.wls_count * var.lb_count}"
  load_balancer_id = "${element(oci_load_balancer.lb.*.id, count.index % var.lb_count)}"
  backendset_name  = "${element(oci_load_balancer_backendset.bes_wls.*.id, count.index % var.lb_count)}"
  ip_address       = "${element(oci_core_instance.serv_wls.*.private_ip, count.index / var.lb_count)}"
  port             = "${local.wls_broker_port}"
  backup           = false
  drain            = false
  offline          = false
  weight           = 1

  lifecycle {
    ignore_changes = ["count"]
  }
}
```
But when adding new load balancer, we cannot avoid deletion+creation of backend resources.

**Comment by sanketdjain** [comment]
One question that came to mind while encountering the above limitation on backend creation is whether we need multiple Load Balancers in OCI. If I understand correctly, load balancer itself is a highly available OCI system, which is registered across 2 subnets in 2 different Availability domains for high availability. Do users need multiple load balancers for more scalability and high availability across all 3 availability domains in OCI  ?

Currently we are creating 3 load balancers for scalability with round-robin subnets across 3 availability domains.

**Comment by kohashim** [comment]
Closing for now.  Feel free to reopen if necessary.  Thanks.
