### ISSUE TITLE
Compute resources depending on custom image get destroyed+created on every apply

### ISSUE THREAD

**Issue by sanketdjain** [oracle/terraform-provider-oci#410]
### Terraform Version

Terraform v0.11.1

    provider.null v1.0.0
    provider.oci v2.0.5
    provider.template v1.0.0

### OCI Provider Version

    oci_v2.0.5 
    2018/01/05 09:35:28 [INFO] terraform-provider-oci 2.0.5

### Description:

In Terraform, I created a instance, ran an install script and created a custom image from the instance.

**image.tf**
```
resource "oci_core_instance" "serv_img_inst" {
  count = "${var.create_image}"
  compartment_id = "${oci_identity_compartment.comp.id}"
  display_name = "img-1"
  hostname_label = "img1"
  image = "${lookup(data.oci_core_images.img_oel7.images[0], "id")}"
  shape = "${lookup(var.serv_shape_map, "img")}"
  subnet_id = "${element(oci_core_subnet.sub_app.*.id, count.index)}"
  availability_domain = "${element(oci_core_subnet.sub_app.*.availability_domain, count.index)}"
  extended_metadata {
    ssh_authorized_keys = "${file(var.ssh_public_key_path)}"
  }

  provisioner "remote-exec" {
    inline = "${data.template_file.serv_image.rendered}"

    connection {
      type = "ssh"
      host = "${self.public_ip}"
      user = "${var.remote_user}"
      private_key = "${file(var.ssh_private_key_path)}"
    }
  }

  timeouts {
    create ="30m"
  }
}

resource "oci_core_image" "serv_image" {
  count = "${var.create_image}"
  compartment_id = "${oci_identity_compartment.comp_images.id}"
  display_name = "${var.image_name}"
  instance_id = "${element(oci_core_instance.serv_img_inst.*.id, count.index)}"

  depends_on = ["oci_core_instance.serv_img_inst"]

  timeouts {
    create = "60m"
  }
}

```

Creation of the image above is optional using a variable "var.create_image" as seen above. The compute instances are created using the image id obtained from a data source lookup using the name of the custom image (either created above, or already existing in OCI Compartment).

**datasources.tf**
```
/* OEL7 Image */
data "oci_core_images" "img_oel7" {
  compartment_id = "${oci_identity_compartment.comp_images.id}"
  display_name = "${var.oel7_image}"
}

/* Server Image */
data "oci_core_images" "img" {
  compartment_id = "${oci_identity_compartment.comp_images.id}"
  display_name = "${var.image_name}"

  // Wait on custom image to be created, if {var.create_image} == 1
  depends_on = ["oci_core_image.serv_image"]
}

```

**compute.tf**
```
resource "oci_core_instance" "serv_wls" {
  count = "${var.wls_count}"
  compartment_id = "${oci_identity_compartment.comp.id}"
  display_name = "wls-${count.index+1}"
  hostname_label = "wls-${count.index+1}"
  image = "${lookup(data.oci_core_images.img.images[0], "id")}"
  shape = "${lookup(var.serv_shape_map, "wls")}"
  subnet_id = "${element(oci_core_subnet.sub_app.*.id, count.index)}"
  availability_domain = "${element(oci_core_subnet.sub_app.*.availability_domain, count.index)}"
  extended_metadata {
    ssh_authorized_keys = "${file(var.ssh_public_key_path)}"
    tags = "group:wls"
  }

  provisioner "remote-exec" {
    inline = "${data.template_file.serv_init.rendered}"

    connection {
      type = "ssh"
      host = "${self.public_ip}"
      user = "${var.remote_user}"
      private_key = "${file(var.ssh_private_key_path)}"
    }
  }

  timeouts {
    create ="${var.create_timeout}"
  }
}

```

With the above Terraform code, the compute instance gets deleted+created on every Terraform Apply, because of the **image** attribute being detected as a "computed" value. I specify var.create_image=1 always, still Terraform detects that the resource has to be re-created, even though the image id is the same.

### Workaround

I used ignore_changes on "image" attribute to avoid re-creation of the compute resources. But this also means that when the image has actually changed, the compute resournces will not get re-created.

```
resource "oci_core_instance" "serv_wls" {
  count = "${var.wls_count}"
  compartment_id = "${oci_identity_compartment.comp.id}"
  display_name = "wls-${count.index+1}"
  hostname_label = "wls-${count.index+1}"
  image = "${lookup(data.oci_core_images.img.images[0], "id")}"
  shape = "${lookup(var.serv_shape_map, "wls")}"
  subnet_id = "${element(oci_core_subnet.sub_app.*.id, count.index)}"
  availability_domain = "${element(oci_core_subnet.sub_app.*.availability_domain, count.index)}"
  extended_metadata {
    ssh_authorized_keys = "${file(var.ssh_public_key_path)}"
    tags = "group:wls"
  }

  // TEMPORARY WORKAROUND
  lifecycle {
    ignore_changes = ["image"]
  }

  provisioner "remote-exec" {
    inline = "${data.template_file.serv_init.rendered}"

    connection {
      type = "ssh"
      host = "${self.public_ip}"
      user = "${var.remote_user}"
      private_key = "${file(var.ssh_private_key_path)}"
    }
  }

  timeouts {
    create ="${var.create_timeout}"
  }
}

```

### Terraform Plan

See test case above in description with Terraform description.

**Comment by alexng-canuck** [comment]
Investigating this.

**Comment by alexng-canuck** [comment]
@sanketdjain The culprit appears to be this part of the custom image's data source config:

```
  // Wait on custom image to be created, if {var.create_image} == 1
  depends_on = ["oci_core_image.serv_image"]
```

If you remove this part, it no longer tries to create a new instance. 

Need to further investigate why Terraform has this behavior, but I believe Terraform treats this dependency as a hint that the custom image may change and would force the instance to also be created again.
image to depend on a new value.

**Comment by sanketdjain** [comment]
@alexng-canuck  Thanks for looking into this. If I remove the depends_on, is it guaranteed that the Compute instance creation will wait for the image creation to be completed ?

**Comment by alexng-canuck** [comment]
@sanketdjain . Sorry for the late response.

Instead of passing the custom image as a datasource to the Compute instance, could you pass it using "oci_core_image.serv_image.id" instead? Terraform would make sure the custom image is created before the Compute instance is created, since there's a clear dependency.

**Comment by sanketdjain** [comment]
@alexng-canuck
I wanted a way to conditionally create image if it does not exist. So the image id comes from the data source or the image resource. I cannot just use from the image resource as var.create_image may be 0 when image already exists.

**Comment by alexng-canuck** [comment]
@sanketdjain This appears to be a known limitation in Terraform. When a data source has a "depends_on" it will always trigger a refresh in the datasource, and that's what's causing the image of the custom instance to be recomputed. (See https://github.com/hashicorp/terraform/issues/11806)

A workaround that I tried successfully was to remove the `depends_on` attribute and create an implicit dependency like this:

```
data "oci_core_images" "img" {
  compartment_id = "${oci_identity_compartment.comp_images.id}"
  
  //REPLACE THIS: display_name = "${var.image_name}"
  display_name = "${var.create_image == 0 ? var.image_name : oci_core_image.serv_image.display_name}"

  //REMOVE THIS: depends_on = ["oci_core_image.serv_image"]
}
```

When `create_image` is 1, the data source will wait on the custom image creation to finish before resolving the display name. When `create_image` is 0, the `image_name` is used directly to find the custom image and there's no dependency.
