### ISSUE TITLE
Need to support datasource filters based on tags

### ISSUE THREAD

**Issue by nelsonse** [oracle/terraform-provider-oci#418]
### Terraform Version

0.10.x, 0.11.x
### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

2.0.5

### Description:
Terraform datasource can be filtered on metadata currently.  With the release of resource tagging, it would be useful to select resources based on tags.

**Comment by alexng-canuck** [comment]
The general idea of support for resource tags will be resolved as part #400 and should be resolved as part of resolving that issue.

@nelsonse if there's anything else I'm missing please let me know. Otherwise, I'll close this as a duplicate of #400 .

**Comment by alexng-canuck** [comment]
Closing this issue, please reopen if you feel this wouldn't be adequately covered by #400
