### ISSUE TITLE
Crash in oci_database_db_nodes datasource for listing nodes in DB Systems

### ISSUE THREAD

**Issue by sanketdjain** [oracle/terraform-provider-oci#419]
### Terraform Version

Terraform v0.11.1

    provider.null v1.0.0
    provider.oci v2.0.5
    provider.template v1.0.0

### OCI Provider Version

    oci_v2.0.5 
    2018/01/05 09:35:28 [INFO] terraform-provider-oci 2.0.5

### Description:

I am trying to list the DB System resources provisioned in a compartment, and also list the DB Nodes for each DB System. I am interested in obtaining the IP addresses of each node in the DB Systems in the compartment. The below datasources.tf causes a crash of Terraform. I have tried it repeatedly and it is consistently crashing. This is a critical issue to use DB System resource in our automation workflow. Please advise if there are any workarounds for this issue.

**datasources.tf**

```
data "oci_database_db_systems" "serv_exa" {
  compartment_id = "${var.comp_id}"
  limit = 10
}

data "oci_database_db_nodes" "nodes_exa" {
  count = "${length(data.oci_database_db_systems.serv_exa.db_systems)}"
  compartment_id = "${var.comp_id}"
  db_system_id = "${data.oci_database_db_systems.serv_exa.db_systems[count.index]}"
}
```

### Terraform Plan

Terraform plan and apply are both crashing, so cannot provide the plan file. There are no resources being provisioned, only data source lookup of existing resources.

crash.log is attached: [crash.log](https://github.com/oracle/terraform-provider-oci/files/1620009/crash.log)

**Comment by alexng-canuck** [comment]
Taking a look.

**Comment by alexng-canuck** [comment]
One thing I noticed, is that db_system_id is set to 
```db_system_id = "${data.oci_database_db_systems.serv_exa.db_systems[count.index]}"```

Which would give you the entire db_system object. Perhaps try again with the "id" field added to the end.

```db_system_id = "${data.oci_database_db_systems.serv_exa.db_systems[count.index].id}"```

**Comment by sanketdjain** [comment]
@alexng-canuck  I tried your suggestion, but Terraform is not able to parse this syntax:

```
db_system_id = "${data.oci_database_db_systems.serv_exa.db_systems[count.index].id}"
```

```
$ terraform plan

Error: Failed to load root config module: Error loading /home/oracle/artifacts/scripts/terraform/datasources.tf: Error reading config for oci_database_db_nodes[nodes_exa]: parse error at 1:64: expected "}" but found "."
```


Since db_systems is a list of maps, I changed to use the following and it seems to work fine.

** Working solution **
```
db_system_id = "${lookup(data.oci_database_db_systems.serv_exa.db_systems[count.index], "id")}"
```


Anyways, thanks for taking a look quickly. I understand it was error in my TF code, but it would be good to report a compile error rather than a crash in Terraform Plan for a type-mismatch. Please feel free to close the issue if you don't think this is possible to avoid.

**Comment by alexng-canuck** [comment]
@sanketdjain 
Sorry, the syntax in my original response was incorrect. Glad to see you found the correct syntax.

I agree that having Terraform panic is probably not a good idea. There are known issues with type mismatch that Terraform has addressed in the past (https://github.com/hashicorp/terraform/issues/2649). We should forward this feedback to them.

For now, I will close this issue.
