### ISSUE TITLE
Renaming Object store bucket name in existing deployment is failing

### ISSUE THREAD

**Issue by sanketdjain** [oracle/terraform-provider-oci#424]
### Terraform Version

Terraform v0.11.1

    provider.null v1.0.0
    provider.oci v2.0.5
    provider.template v1.0.0

### OCI Provider Version

    oci_v2.0.5 
    2018/01/05 09:35:28 [INFO] terraform-provider-oci 2.0.5

### Description:

1. Create a bucket in Terraform
2. Update the bucket name and apply again.

Terraform detects that the bucket name has changed, and it tries to **update** the resource. However, I don't think renaming buckets is supported in OCI and Terraform keeps trying again continuously. Eventually it fails with timeout.

I think OCI Plugin should detect it as a delete + create, if renaming is not supported, and the bucket is empty.

### Test Case:

```
// Backup buckets for CTRL
resource "oci_objectstorage_bucket" "bt_bkp_ctrl" {
  count = "${local.create_bucket ? var.ctrl_count : 0}"
  compartment_id = "${oci_identity_compartment.comp_backups.id}"
  name = "backup_${replace(element(oci_core_instance.serv_ctrl.*.hostname_label, count.index), "-", "")}"
  access_type = "ObjectRead"
  namespace = "${data.oci_objectstorage_namespace.nmsp.namespace}"
}
```

### Terraform Plan

Terraform will perform the following actions:

$ terraform plan
```
 <= data.oci_core_images.img
      id:             <computed>
      compartment_id: "ocid1.compartment.oc1..aaaaaaaanw5tvfobn7gujvbgkrcwlstuoczledvjcj6s3zchdp6burchb2fq"
      display_name:   "adwc_base_img"
      images.#:       <computed>

  ~ oci_objectstorage_bucket.bt_bkp_ctrl
      name:           "BACKUP_CTRL1" => "backup_ctrl1"

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by kohashim** [comment]
Thank you for the report.  Confirmed the issue by reproducing.  A fix is now under review.

**Comment by codycushing** [comment]
Fixed in https://github.com/oracle/terraform-provider-oci/releases/tag/2.0.7
