### ISSUE TITLE
Add support for load balancer idleTimeout configuration

### ISSUE THREAD

**Issue by sanketdjain** [oracle/terraform-provider-oci#425]
### Terraform Version

Terraform v0.11.1

    provider.null v1.0.0
    provider.oci v2.0.5
    provider.template v1.0.0

### OCI Provider Version

    oci_v2.0.5 
    2018/01/05 09:35:28 [INFO] terraform-provider-oci 2.0.5

### Description:

The OCI REST API supports load balancer timeout configuration. The Terraform plugin does not support it. This is very critical for our implementation. Please support this enhancement:

https://docs.us-phoenix-1.oraclecloud.com/api/#/en/loadbalancer/20170115/requests/ConnectionConfiguration

### Terraform Plan

This is enhancement request

**Comment by rcohenma** [comment]
This was added in version 2.1.2

https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.2
