### ISSUE TITLE
Import of Load balancer resource is not supported

### ISSUE THREAD

**Issue by sanketdjain** [oracle/terraform-provider-oci#429]
### Terraform Version

Terraform v0.11.1

    provider.null v1.0.0
    provider.oci v2.0.5
    provider.template v1.0.0

### OCI Provider Version

    oci_v2.0.5 
    2018/01/05 09:35:28 [INFO] terraform-provider-oci 2.0.5

### Description:
We have an existing load balancer that is already hooked up to a DNS. It should be possible to import the load balancer in different environments created through Terraform.

However, attempting to import the load balancer resource in Terraform reports an error that it not yet supported.

Load balancer is a critical resource which impact on the connections from users. So we don't want to destroy the load balancer ever. Also, creating a private load balancer for each environment is not worth it for test-dev purposes. So the ability to import existing load balancer would be very useful enhancement.

### Test case
```
$ terraform import oci_load_balancer.lb  1
oci_load_balancer.lb: Importing from ID "1"...
Error importing: 1 error(s) occurred:

* oci_load_balancer.lb (import id: 1): import oci_load_balancer.lb (id: 1): resource oci_load_balancer doesn't support import
```

**Comment by rcohenma** [comment]
oci_load_balancer resource imports has been fixed in release 2.1.6
