### ISSUE TITLE
failed oci_load_balancer_listener creation has successful state.

### ISSUE THREAD

**Issue by nshttpd** [oracle/terraform-provider-oci#430]
### Terraform Version
```
Terraform v0.11.1
+ provider.oci v2.0.6
```
### Description:

attempting to create a oci_load_balancer_listener, oci_load_balancer_backend(s), oci_load_balancer_backendset. The backend and backendset were successful, but the  listener failed with :

```
Error: Error applying plan:

1 error(s) occurred:

* oci_load_balancer_listener.em_secure_upload: 1 error(s) occurred:

* oci_load_balancer_listener.em_secure_upload: Resource creation failed, state FAILED
```
In the state file it's stored with the FAILED state in there :

```
                "oci_load_balancer_listener.em_secure_upload": {
                    "type": "oci_load_balancer_listener",
                    "depends_on": [
                        "data.terraform_remote_state.shared"
                    ],
                    "primary": {
                        "id": "ocid1.loadbalancerworkrequest.oc1.phx.ninja",
                        "attributes": {
                            "default_backend_set_name": "secure-backend",
                            "id": "ocid1.loadbalancerworkrequest.oc1.phx.ninja",
                            "load_balancer_id": "ocid1.loadbalancer.oc1.phx.lbinphx",
                            "name": secure-upload",
                            "port": "4888",
                            "protocol": "TCP",
                            "state": "FAILED"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.oci"
                },
```

I would think that a FAILED work request shouldn't be stored as a successful state modification. If one `taints` the item to try and get it to be created :

```
Error: Error applying plan:

1 error(s) occurred:

* oci_load_balancer_listener.em_secure_upload (destroy): 1 error(s) occurred:

* oci_load_balancer_listener.em_secure_upload: unexpected state 'FAILED', wanted target 'SUCCEEDED_WORK_REQUEST, SUCCEEDED'. last error: %!s(<nil>)
```

I've had to manually edit the .tfstate file and remove the FAILED item to get attempt the apply again.

**Comment by kohashim** [comment]
Thank you for the report.  This is a known issue originally reported at https://github.com/oracle/terraform-provider-oci/issues/414.  We are investigating.  Thank you for your patience.

**Comment by kohashim** [comment]
A mitigation has been made and landed in the master branch: https://github.com/oracle/terraform-provider-oci/commit/66f10652d0e7835f5027afa008ac5cdf59cfbf85, which removes at least the necessity of removing the failed resources from the state file when destroying.  The next release will include this fix.  Otherwise you can clone the master branch to try it out.

The ideal solution is still to retry on the failure of a work request in a load balancer resource, which is in our backlog.

**Comment by nshttpd** [comment]
Just built from Master and tested this out since I had a backend set work request fail on creation. It worked as expected to properly handle FAILED states.

**Comment by kohashim** [comment]
Glad to hear.  Closing.

**Comment by codycushing** [comment]
Fixed in https://github.com/oracle/terraform-provider-oci/releases/tag/2.0.7
