### ISSUE TITLE
How to create an instance with a network in a different compartment?

### ISSUE THREAD

**Issue by gcstang** [oracle/terraform-provider-oci#431]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.10.8
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
v2.0.6
</details>

### Description:
I'm trying to create an Instance that uses a Network in a different compartment via Terraform.

Availability Domain is already selected i.e. AD-1
Instance would be created in Compartment X
Existing VCN is in Compartment Y
In the browser there is an option to see the Compartment Selections

> If the image, Virtual Cloud Network, or Subnet is in a different Compartment than the Instance, click here to enable Compartment selection for those resources.

Once that is clicked I can select a Compartment Y for Virtual Cloud Network Compartment and then the Virtual Cloud Network. 
Once those are selected I can select a Subnet Compartment in Compartment X
And finally I can select a subnet.

How can this be accomplished with the terraform-provider-oci ?

**Comment by kohashim** [comment]
Assuming Compartment X and Y are under a same tenancy, you can simply specify the ID of Compartment Y and the ID of your desired subnet under Compartment Y such as:
```
resource "oci_core_instance" "Instance" {
    availability_domain = "${var.AD1}"
    compartment_id = "${var.OcidOfCompartmentY}"
    display_name = "instance"
    hostname_label = "instance"
    image = "${var.OcidOfInstanceImage}"
    shape = "VM.Standard1.1"
    create_vnic_details {
        subnet_id = "${var.OcidOfSubnetUnderCompartmentY}"
        assign_public_ip = "false"
    },
}
```
