### ISSUE TITLE
Add support for Path Routes resource in load balancer

### ISSUE THREAD

**Issue by sanketdjain** [oracle/terraform-provider-oci#434]
### Terraform Version
Terraform v0.11.1

    provider.null v1.0.0
    provider.oci v2.0.5
    provider.template v1.0.0

### OCI Provider Version

    oci_v2.0.5 
    2018/01/05 09:35:28 [INFO] terraform-provider-oci 2.0.5

### Description:

The OCI Console supports Path Routes in Load Balancer. But there is no resource for Path Route in  Load balancer. The ability to specify path routes helps in redirecting the requests to appropriate backend sets based on the REST URL format of the application, and avoids using separate ports for each backend set.

### Terraform Plan

This is an enhancement request.

**Comment by rcohenma** [comment]
Support for path routes was added in release 2.1.2
https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.2
