### ISSUE TITLE
Location of plugin on windows

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#435]
### Terraform Version

Terraform v0.11.1

### Description:
The current documentation recommends to install the plugin in %APPDATA%/terraform.d/plugins/.

This should be %APPDATA%/Roaming/terraform.d/plugins/

**Comment by jbolla** [comment]
By default %APPDATA% should already refer to the Roaming directory:
%UserProfile%/AppData/Roaming

You can check whether this is the case on your system by entering the following at a cmd prompt:
echo %APPDATA%

**Comment by hyder** [comment]
Thanks
