### ISSUE TITLE
Add support for reserved public ips

### ISSUE THREAD

**Issue by jhorwit2** [oracle/terraform-provider-oci#438]
https://docs.us-phoenix-1.oraclecloud.com/Content/Network/Tasks/managingpublicIPs.htm

**Comment by rcohenma** [comment]
We have a plan to reach feature parity with the services. We'll make note of this request and try to prioritize the public_ip resource.

**Comment by dmutreja** [comment]
+1 on the need for this.

**Comment by juanbecerra** [comment]
+1

**Comment by juanbecerra** [comment]
I can see the latest version of the provider 2.1.4 - 2018-04-09 has added support for reserved public IPs, is there an example on how to attach public IPs to Load Balancers?

**Comment by juanbecerra** [comment]
https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/networking/public_ip/public_ip.tf

**Comment by juanbecerra** [comment]
https://github.com/oracle/terraform-provider-oci/blob/master/docs/core/public_ips.md

**Comment by anandhmahal** [comment]
Public IP is supported from v2.1.4

**Comment by samjeckert** [comment]
Hi, I don't actually see a solution for attaching a public IP to a load balancer. As far as I can see it seems that the only examples require the public IP's to attach to instances. This would be very helpful!

**Comment by jhorwit2** [comment]
That's not supported yet in oci @samjeckert

**Comment by kvinodhbabu** [comment]
Hi, Seems we dont have support yet to attach a public IP which is already RESERVED to a compute instance using Terraform only way is to create along with script where we have the compute and attach the public ip which gets destroy once we issue "terraform destroy".
