### ISSUE TITLE
Add support for new OCI storage type - File Systems (aka File Storage Service)

### ISSUE THREAD

**Issue by jlamillan** [oracle/terraform-provider-oci#440]
Oracle [recently announced](https://blogs.oracle.com/cloud-infrastructure/introducing-oracle-cloud-infrastructure-file-storage-service) the public availability of Oracle Cloud Infrastructure File Storage Service (FSS) in all OCI regions. Here is the [File Storage Service API](https://docs.us-phoenix-1.oraclecloud.com/api/#/en/filestorage/20171215/).

**Comment by rcohenma** [comment]
We have a plan to reach feature parity with the services. We'll make note of this request and try to prioritize FSS

**Comment by alexng-canuck** [comment]
We have added support for the File Storage Service in the latest Terraform provider release. See https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.2

Let us know if this addresses your request and if you have more feedback for supporting File Storage Services.

**Comment by jlamillan** [comment]
Yes it does, thanks.
