### ISSUE TITLE
Load Balancer back end set healthcheck config state not managed

### ISSUE THREAD

**Issue by darkfibre** [oracle/terraform-provider-oci#441]
### Terraform Version

<details>

Terraform v0.11.2

</details>

### OCI Provider Version

<details>
v2.0.6
</details>

### Description:
OCI provider does not recognize when Load Balancer backend set healthcheck configuration changes. Doesn't seem to track it in the state file.

1. Create a simple load balancer with a single backend set and listener via terraform
2. Manually change any of the health_checker attributes via the OCI Web Interface (port, or interval_ms)
3. Run 'terraform plan', it will report "No changes. Infrastructure is up-to-date."

### Terraform Plan

<details>

```
resource "oci_load_balancer" "lb1" {
  shape          = "100Mbps"
  compartment_id = "${var.compartment_ocid}"
  subnet_ids     = [ "${var.subnet}" ]
  display_name = "my-loadbalancer"
  is_private = true
}

resource "oci_load_balancer_backendset" "lb-bes1" {
  name             = "lb-bes1"
  load_balancer_id = "${oci_load_balancer.lb1.id}"
  policy           = "ROUND_ROBIN"

  health_checker { port = "80" protocol = "HTTP" interval_ms = "2000" response_body_regex = ".*" url_path = "/" }
}

resource "oci_load_balancer_listener" "lb-listener1" {
  load_balancer_id         = "${oci_load_balancer.lb1.id}"
  name                     = "http"
  default_backend_set_name = "${oci_load_balancer_backendset.lb-bes1.id}"
  port                     = 80
  protocol                 = "HTTP"
}

resource "oci_load_balancer_backend" "lb-be1" {
  load_balancer_id = "${oci_load_balancer.lb1.id}"
  backendset_name  = "${oci_load_balancer_backendset.lb-bes1.id}"
  ip_address       = "10.x.x.x"
  port             = 80
}
```

</details>

**Comment by rcohenma** [comment]
I can't reproduce this.
I can see the healthchecker attributes in the state file 
And an update occurs when i update the port.

**Comment by darkfibre** [comment]
Hmm. You change the port of the healthcheck in the UI, and then when you re-run terraform it correctly reverts the change?

**Comment by rcohenma** [comment]
Oh i missed that you were making the change in the UI instead of the terraform config. This is a known issue that is on our backlog. We have issues importing backend sets and retrieving changes made to backend sets outside of the terraform plan. You should manage the backend sets exclusively through the terraform config until we get around to fixing this.

**Comment by rcohenma** [comment]
I tried with the latest version of the provider and this seems to be resolved.

1. I created a load balancer with a backend set and a backend (with healthchecker Port 80)
2. I used the UI to change the port of the backend set to 88
3. I ran terraform plan, and saw an update from 88 => 80
4. Ran apply and the update was successful

Feel free to reopen if you are still having issues.
