### ISSUE TITLE
DRG Datasource List not documented

### ISSUE THREAD

**Issue by tjkervin** [oracle/terraform-provider-oci#442]
### Terraform Version

Not a terraform related issue

### OCI Provider Version

Latest Source

### Description:
The drg documentation is missing the list attribute (drgs). This should be added so that it's clear how to leverage the datasource. 

### Terraform Plan

N/A

**Comment by rcohenma** [comment]
https://github.com/oracle/terraform-provider-oci/blob/master/docs/datasources/core/drgs.md

**Comment by tjkervin** [comment]
Yes, this is the documentation for it, but you are missing the list attribute (drgs) from this document. It's not clear in the document what you are actually supposed to use to access the list. Have a look at the documentation for virtual networks:

https://github.com/oracle/terraform-provider-oci/blob/master/docs/datasources/core/virtual_networks.md

There is an attribute reference for virtual_networks, which returns the list of virtual networks. It's not documented in the drgs documentation what this list element is. 

Please reopen this issue.

**Comment by rcohenma** [comment]
Oh I see.
it is "drgs"
We will fix this soon
Thanks for bringing this up

**Comment by anandhmahal** [comment]
Reopening to fix the doc

**Comment by parweza** [comment]
fixed in https://github.com/oracle/terraform-provider-oci/pull/459
