### ISSUE TITLE
Export dns_labels

### ISSUE THREAD

**Issue by mccoold** [oracle/terraform-provider-oci#445]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.11.1

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

2.05

### Description:
Please add dns_label to the vcn and subnet data attributes so they can be pulled back programmatically. The oci_database_db_system requires that the domain name match the subnet and it would be nice to pull them from a datasource.  The datasources.md file does not list it as an attribute.

### Terraform Plan

data "oci_core_subnet" "subnetList" {
	 compartment_id = "${var.compartment_ocid}"
     availability_domain = "${lookup(data.oci_identity_availability_domains.ads.availability_domains[var.ad - 1],"name")}"
     vcn_id = "${var.vcnocid}"
}

resource "null_resource" "subnets" {
  count = "${length(data.oci_core_images.subnetList.subnets)}"
  triggers = {
    names = "${lookup(data.oci_core_images.subnetList.subnets[count.index],"display_name")}"
    dns_label = "${lookup(data.oci_core_images.subnetList.subnets[count.index],"dns_label")}"
    ids = "${lookup(data.data.oci_core_images.subnetList.subnets[count.index],"id")}"
  }
}

**Comment by AlaaShaker** [comment]
@mccoold I believe `dns_label` is available for both Subnets & VCNs data sources, perhaps the docs just didn't mention it. I have just verified that with the OCI Provider v2.0.7 using the config you supplied (I assume the `data.oci_core.images.subnetList` was a typo?). 

Have you considered upgrading your OCI Provider to a later version & trying again? This field is supported in our latest [2.1.0-beta](https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.0-beta) release. Here are the updated docs: [Subnets](https://github.com/oracle/terraform-provider-oci/blob/v2.1.0-beta/docs/core/subnets.md) & [VCNs](https://github.com/oracle/terraform-provider-oci/blob/v2.1.0-beta/docs/core/vcns.md).

I'm going to close this issue as a no-repro for now. If upgrading the provider doesn't resolve the issue, please reopen it & I'd be more than happy to investigate further.
