### ISSUE TITLE
Load Balancer Certificate Resource does not mark keys and passphrases as sensitive

### ISSUE THREAD

**Issue by tjkervin** [oracle/terraform-provider-oci#447]
### Terraform Version

<details>
Terraform v0.11.2

</details>

### OCI Provider Version

<details>
v2.0.5
</details>

### Description:
Currently, the Load Balancer Certificate resource does not mark the private key and passphrase as sensitive, so these values are spit out to the console. This request would for these to be included as sensitive values so they do not display to the console.

**Comment by alexng-canuck** [comment]
@tjkervin Thanks for the feedback. I have shared this with the team and it has been added to our backlog.

**Comment by alexng-canuck** [comment]
Hello @tjkervin,

This has been fixed in the latest Terraform OCI provider release: https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.2

Let us know if this addresses your concerns.

Thanks,
Alex

**Comment by tjkervin** [comment]
Yup,

That's the fix I had implemented in our local instance.  Thank you.
