### ISSUE TITLE
File System Creation

### ISSUE THREAD

**Issue by RiaanRossouw** [oracle/terraform-provider-oci#451]
### Terraform Version

<details>
Terraform v0.11.2
provider.oci v2.0.6
</details>

### Description:
Sorry if I missed it but I can''t find any resource for the new File System (NFS) services.  Do they exist or planned?

**Comment by RiaanRossouw** [comment]
Just noticed alreadsy open ticket...
Add support for new OCI storage type - File Systems (aka File Storage Service) #440

**Comment by rohanbhattacharjee** [comment]
We don't support NFS as yet.

There are plans to support it in the (near-term) future. But we don't have a firm date as yet that I can tell you.
