### ISSUE TITLE
Solaris build?

### ISSUE THREAD

**Issue by nagulako** [oracle/terraform-provider-oci#453]
### Terraform Version

<details>
Looking for a built provider for Solaris.  I see different OS's around - but not Solaris.
Thanks

# Run this command to get the terraform version:

$ terraform -v

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
Include a description with repro steps, expected result and actual result

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by codycushing** [comment]
Thanks for the request, we will include Solaris builds starting with the next release. You can create your own solaris build in the meantime by cloning the project and running:
with just golang 1.9 installed:
`env GOOS=solaris GOARCH=amd64 go build -o terraform-provider-oci`

or with the gox tool (`go get github.com/mitchellh/gox`):
`gox --osarch="solaris/amd64"`
