### ISSUE TITLE
TCP Timeout connecting to iaas.us-ashburn-1.oraclecloud.com via Proxy

### ISSUE THREAD

**Issue by jimmycal** [oracle/terraform-provider-oci#456]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.11.3

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:
2018/02/15 21:27:15 [INFO] terraform-provider-oci 2.0.7

</details>

### Description:
We are running a development server within a private subnet in OCI VCN.  The private subnet is connected back to the customer's corporate network via VPN.   We have configured the http_proxy, and https_proxy to point back to the customers on-premises proxy server.  We have validated the proxy configuration works through testing with our CLI.

When running terraform apply we see the following timeout at the proxy - 

[opc@terraform vcn]$ export TF_LOG=DEBUG
[opc@terraform vcn]$ terraform apply
2018/02/15 16:08:00 [INFO] Terraform version: 0.11.3  3802b14260603f90c7a1faf55994dcc8933e2069
2018/02/15 16:08:00 [INFO] Go runtime version: go1.9.1
2018/02/15 16:08:00 [INFO] CLI args: []string{"/usr/local/bin/terraform", "apply"}
2018/02/15 16:08:00 [DEBUG] Attempting to open CLI config file: /home/opc/.terraformrc
2018/02/15 16:08:00 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/02/15 16:08:00 [INFO] CLI command args: []string{"apply"}
2018/02/15 16:08:00 [INFO] command: empty terraform config, returning nil
2018/02/15 16:08:00 [DEBUG] command: no data state file found for backend config
2018/02/15 16:08:00 [DEBUG] New state was assigned lineage "4c538c88-706b-4533-9fbc-a5c54477e9c2"
2018/02/15 16:08:00 [INFO] command: backend initialized: <nil>
2018/02/15 16:08:00 [DEBUG] checking for provider in "."
2018/02/15 16:08:00 [DEBUG] checking for provider in "/usr/local/bin"
2018/02/15 16:08:00 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2018/02/15 16:08:00 [DEBUG] checking for provider in "/home/opc/.terraform.d/plugins"
2018/02/15 16:08:00 [DEBUG] checking for provider in "/home/opc/.terraform.d/plugins/linux_amd64"
2018/02/15 16:08:00 [DEBUG] found provider "terraform-provider-oci_v2.0.7"
2018/02/15 16:08:00 [DEBUG] found valid plugin: "oci", "2.0.7", "/home/opc/.terraform.d/plugins/linux_amd64/terraform-provider-oci_v2.0.7"
2018/02/15 16:08:00 [DEBUG] checking for provisioner in "."
2018/02/15 16:08:00 [DEBUG] checking for provisioner in "/usr/local/bin"
2018/02/15 16:08:00 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2018/02/15 16:08:00 [DEBUG] checking for provisioner in "/home/opc/.terraform.d/plugins"
2018/02/15 16:08:00 [DEBUG] checking for provisioner in "/home/opc/.terraform.d/plugins/linux_amd64"
2018/02/15 16:08:00 [INFO] command: backend <nil> is not enhanced, wrapping in local
2018/02/15 16:08:00 [INFO] backend/local: starting Apply operation
2018/02/15 16:08:00 [INFO] terraform: building graph: GraphTypeInput
2018/02/15 16:08:00 [DEBUG] Resource state not found for "oci_core_virtual_network.vcn1": oci_core_virtual_network.vcn1
2018/02/15 16:08:00 [TRACE] Graph after step *terraform.AttachStateTransformer:

oci_core_virtual_network.vcn1 - *terraform.NodeAbstractResource
2018/02/15 16:08:00 [DEBUG] resource oci_core_virtual_network.vcn1 using provider provider.oci
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.tenancy_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.user_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.fingerprint" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.private_key_path" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.compartment_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.region" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "provider.oci" references: [var.tenancy_ocid var.user_ocid var.fingerprint var.private_key_path var.region]
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "oci_core_virtual_network.vcn1" references: [var.compartment_ocid]
2018/02/15 16:08:00 [DEBUG] Starting graph walk: walkInput
2018-02-15T16:08:00.728Z [DEBUG] plugin: starting plugin: path=/home/opc/.terraform.d/plugins/linux_amd64/terraform-provider-oci_v2.0.7 args=[/home/opc/.terraform.d/plugins/linux_amd64/terraform-provider-oci_v2.0.7]
2018-02-15T16:08:00.728Z [DEBUG] plugin: waiting for RPC address: path=/home/opc/.terraform.d/plugins/linux_amd64/terraform-provider-oci_v2.0.7
2018-02-15T16:08:00.734Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: 2018/02/15 16:08:00 [INFO] terraform-provider-oci 2.0.7
2018-02-15T16:08:00.735Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: 2018/02/15 16:08:00 [DEBUG] plugin: plugin address: unix /tmp/plugin220224846
2018/02/15 16:08:00 [INFO] terraform: building graph: GraphTypeValidate
2018/02/15 16:08:00 [DEBUG] Resource state not found for "oci_core_virtual_network.vcn1": oci_core_virtual_network.vcn1
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.fingerprint" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.private_key_path" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.compartment_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.region" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "provider.oci" references: [var.user_ocid var.fingerprint var.private_key_path var.region var.tenancy_ocid]
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "oci_core_virtual_network.vcn1" references: [var.compartment_ocid]
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.tenancy_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.user_ocid" references: []
2018/02/15 16:08:00 [DEBUG] Starting graph walk: walkValidate
2018/02/15 16:08:00 [DEBUG] Resource state not found for "oci_core_virtual_network.vcn1": oci_core_virtual_network.vcn1
2018/02/15 16:08:00 [TRACE] Graph after step *terraform.AttachStateTransformer:

oci_core_virtual_network.vcn1 - *terraform.NodeValidatableResourceInstance
2018/02/15 16:08:00 [TRACE] Graph after step *terraform.TargetsTransformer:

oci_core_virtual_network.vcn1 - *terraform.NodeValidatableResourceInstance
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "oci_core_virtual_network.vcn1" references: []
2018/02/15 16:08:00 [TRACE] Graph after step *terraform.ReferenceTransformer:

oci_core_virtual_network.vcn1 - *terraform.NodeValidatableResourceInstance
2018/02/15 16:08:00 [TRACE] Graph after step *terraform.RootTransformer:

oci_core_virtual_network.vcn1 - *terraform.NodeValidatableResourceInstance
2018/02/15 16:08:00 [TRACE] dag/walk: added new vertex: "oci_core_virtual_network.vcn1"
2018/02/15 16:08:00 [INFO] backend/local: apply calling Refresh
2018/02/15 16:08:00 [INFO] terraform: building graph: GraphTypeRefresh
2018/02/15 16:08:00 [TRACE] No managed resources in state during refresh, skipping managed resource transformer
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.fingerprint" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.private_key_path" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.compartment_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.region" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.tenancy_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.user_ocid" references: []
2018/02/15 16:08:00 [TRACE] Graph after step *terraform.ReferenceTransformer:

var.compartment_ocid - *terraform.NodeRootVariable
var.fingerprint - *terraform.NodeRootVariable
var.private_key_path - *terraform.NodeRootVariable
var.region - *terraform.NodeRootVariable
var.tenancy_ocid - *terraform.NodeRootVariable
var.user_ocid - *terraform.NodeRootVariable
2018/02/15 16:08:00 [TRACE] Graph after step *terraform.TargetsTransformer:

var.compartment_ocid - *terraform.NodeRootVariable
var.fingerprint - *terraform.NodeRootVariable
var.private_key_path - *terraform.NodeRootVariable
var.region - *terraform.NodeRootVariable
var.tenancy_ocid - *terraform.NodeRootVariable
var.user_ocid - *terraform.NodeRootVariable
2018/02/15 16:08:00 [INFO] backend/local: apply calling Plan
2018/02/15 16:08:00 [INFO] terraform: building graph: GraphTypePlan
2018/02/15 16:08:00 [DEBUG] Resource state not found for "oci_core_virtual_network.vcn1": oci_core_virtual_network.vcn1
2018/02/15 16:08:00 [TRACE] Graph after step *terraform.AttachStateTransformer:

oci_core_virtual_network.vcn1 - *terraform.NodePlannableResource
2018/02/15 16:08:00 [DEBUG] resource oci_core_virtual_network.vcn1 using provider provider.oci
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "provider.oci" references: [var.user_ocid var.fingerprint var.private_key_path var.region var.tenancy_ocid]
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "oci_core_virtual_network.vcn1" references: [var.compartment_ocid]
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.tenancy_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.user_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.fingerprint" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.private_key_path" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.compartment_ocid" references: []
2018/02/15 16:08:00 [DEBUG] ReferenceTransformer: "var.region" references: []
2018/02/15 16:08:00 [DEBUG] Resource state not found for "oci_core_virtual_network.vcn1": oci_core_virtual_network.vcn1
2018/02/15 16:08:00 [TRACE] Graph after step *terraform.AttachStateTransformer:

oci_core_virtual_network.vcn1 - *terraform.NodePlannableResourceInstance

2018/02/15 16:08:00 [DEBUG] command: asking for input: "Do you want to perform these actions?"
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + oci_core_virtual_network.vcn1
      id:                       <computed>
      cidr_block:               "10.0.0.0/16"
      compartment_id:           "ocid1.tenancy.oc1..aaaaaaaab6ggo3q7dhmo5erjdw3n4qrrrx3qo2rso6gc6kvnowro3g64y5vq"
      default_dhcp_options_id:  <computed>
      default_route_table_id:   <computed>
      default_security_list_id: <computed>
      display_name:             "vcn1"
      dns_label:                "vcn1"
      state:                    <computed>
      time_created:             <computed>

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

2018/02/15 16:08:03 [INFO] terraform: building graph: GraphTypeApply
royTainted:false, Meta:map[string]interface {}(nil)}
2018/02/15 16:08:03 [DEBUG] Resource state not found for "oci_core_virtual_network.vcn1": oci_core_virtual_network.vcn1
2018/02/15 16:08:03 [TRACE] Graph after step *terraform.AttachStateTransformer:

oci_core_virtual_network.vcn1 - *terraform.NodeApplyableResource
2018/02/15 16:08:03 [DEBUG] resource oci_core_virtual_network.vcn1 using provider provider.oci
2018/02/15 16:08:03 [DEBUG] ReferenceTransformer: "var.user_ocid" references: []
2018/02/15 16:08:03 [DEBUG] ReferenceTransformer: "var.fingerprint" references: []
2018/02/15 16:08:03 [DEBUG] ReferenceTransformer: "var.private_key_path" references: []
2018/02/15 16:08:03 [DEBUG] ReferenceTransformer: "var.compartment_ocid" references: []
2018/02/15 16:08:03 [DEBUG] ReferenceTransformer: "var.region" references: []
2018/02/15 16:08:03 [DEBUG] ReferenceTransformer: "oci_core_virtual_network.vcn1" references: [var.compartment_ocid]
2018/02/15 16:08:03 [DEBUG] ReferenceTransformer: "provider.oci" references: [var.tenancy_ocid var.user_ocid var.fingerprint var.private_key_path var.region]
2018/02/15 16:08:03 [DEBUG] ReferenceTransformer: "var.tenancy_ocid" references: []
oci_core_virtual_network.vcn1: Creating...
  cidr_block:               "" => "10.0.0.0/16"
  compartment_id:           "" => "ocid1.tenancy.oc1..aaaaaaaab6ggo3q7dhmo5erjdw3n4qrrrx3qo2rso6gc6kvnowro3g64y5vq"
  default_dhcp_options_id:  "" => "<computed>"
  default_route_table_id:   "" => "<computed>"
  default_security_list_id: "" => "<computed>"
  display_name:             "" => "vcn1"
  dns_label:                "" => "vcn1"
  state:                    "" => "<computed>"
  time_created:             "" => "<computed>"
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: 2018/02/15 16:08:03 [DEBUG] HTTP Request: POST /20160918/vcns?compartmentId=ocid1.tenancy.oc1..aaaaaaaab6ggo3q7dhmo5erjdw3n4qrrrx3qo2rso6gc6kvnowro3g64y5vq HTTP/1.1
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: Host: iaas.us-ashburn-1.oraclecloud.com
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: User-Agent: Oracle-GoSDK/20160918 (go/go1.9.2; linux/amd64; terraform/0.9.4-dev) Oracle-TerraformProvider/2.0.7
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: Content-Length: 164
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: Accept: */*
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: Authorization: Signature version="1",headers="date (request-target) host content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaaab6ggo3q7dhmo5erjdw3n4qrrrx3qo2rso6gc6kvnowro3g64y5vq/ocid1.user.oc1..aaaaaaaamkujtqcabylijagicrrlcayikwhdsd5merz7qx2ksrjw2i64gkja/73:03:6b:f0:42:a8:85:53:ff:d7:d0:8d:ff:c3:1c:d4",algorithm="rsa-sha256",signature="j5Do4Htx7+dly3PZhMNiA9guvkr9pzDMECvAd5EXpF8bgbOgGOf4y/ZM8kJxXkO0sqVWw8eT7lEI2Sps4j3axZAu1X+0AQdJlEMMe58KQlq0vTZHQJG5l95FZDbS3AC9TQHxAb6tGjZCWE+MdwLD720xeruMshcg10VkpUsuznrcBv9xIOEer0Ky328tkVZCuQ+xuE4KmBAPVvhXHby6KEtU7jipmXAMS54Foy1SlEXMxtYLdZfCqINy/50tOrYHwJBn7Qw2dbOsw4AgGzH/ghTW2ON41tz975R+AEvwNs/rCcDrZqPBTfR5rQSsqBzjptAXvO2OKPR3rkIrCJzH7Q=="
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: Content-Type: application/json
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: Date: Thu, 15 Feb 2018 16:08:03 GMT
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: X-Content-Sha256: GIZA6AQ9BfbDUWbqI87+tXMAdHImCmVkV/U0MQ0WfYg=
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: opc-retry-token: g0lisvmp3Tv9hqY9KxujsvJ4oVXrlc
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: Accept-Encoding: gzip
2018-02-15T16:08:03.855Z [DEBUG] plugin.terraform-provider-oci_v2.0.7:
oci_core_virtual_network.vcn1: Still creating... (10s elapsed)
2018-02-15T16:08:13.857Z [DEBUG] plugin.terraform-provider-oci_v2.0.7: 2018/02/15 16:08:13 [WARN] Could not get HTTP Response, error: &url.Error{Op:"Post", URL:"https://iaas.us-ashburn-1.oraclecloud.com/20160918/vcns?compartmentId=ocid1.tenancy.oc1..aaaaaaaab6ggo3q7dhmo5erjdw3n4qrrrx3qo2rso6gc6kvnowro3g64y5vq", Err:(*net.OpError)(0xc4203f2a00)}
2018/02/15 16:08:13 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* oci_core_virtual_network.vcn1: Post https://iaas.us-ashburn-1.oraclecloud.com/20160918/vcns?compartmentId=ocid1.tenancy.oc1..aaaaaaaab6ggo3q7dhmo5erjdw3n4qrrrx3qo2rso6gc6kvnowro3g64y5vq: dial tcp: lookup iaas.us-ashburn-1.oraclecloud.com on 48.152.32.5:53: read udp 48.152.32.52:55675->48.152.32.5:53: i/o timeout
2018/02/15 16:08:13 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* oci_core_virtual_network.vcn1: Post https://iaas.us-ashburn-1.oraclecloud.com/20160918/vcns?compartmentId=ocid1.tenancy.oc1..aaaaaaaab6ggo3q7dhmo5erjdw3n4qrrrx3qo2rso6gc6kvnowro3g64y5vq: dial tcp: lookup iaas.us-ashburn-1.oraclecloud.com on 48.152.32.5:53: read udp 48.152.32.52:55675->48.152.32.5:53: i/o timeout
2018/02/15 16:08:13 [TRACE] [walkApply] Exiting eval tree: oci_core_virtual_network.vcn1

2018/02/15 16:08:13 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

1 error(s) occurred:

* oci_core_virtual_network.vcn1: 1 error(s) occurred:

2018-02-15T16:08:13.862Z [DEBUG] plugin: plugin process exited: path=/home/opc/.terraform.d/plugins/linux_amd64/terraform-provider-oci_v2.0.7
* oci_core_virtual_network.vcn1: Post https://iaas.us-ashburn-1.oraclecloud.com/20160918/vcns?compartmentId=ocid1.tenancy.oc1..aaaaaaaab6ggo3q7dhmo5erjdw3n4qrrrx3qo2rso6gc6kvnowro3g64y5vq: dial tcp: lookup iaas.us-ashburn-1.oraclecloud.com on 48.152.32.5:53: read udp 48.152.32.52:55675->48.152.32.5:53: i/o timeout

This run it appeared that the DNS resolution was the issue, so we added to our local /etc/hosts file
129.213.2.143 iaas.us-ashburn-1.oraclecloud.com, which changed the error to a a socket timeout at that address.  

We are running the  VCN.tf example. 

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {
	default = "ocid1.compartment.oc1..aaaaaaaapj7xxlndxbcrmhw6cftylvdndmyetzmz2aanqy5vk3gciiro5hpa"
}
variable "region" {
	default = "us-ashburn-1"
}

provider "oci" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region = "${var.region}"
}

resource "oci_core_virtual_network" "vcn1" {
  cidr_block = "10.0.0.0/16"
  dns_label = "vcn1"
  compartment_id = "${var.compartment_ocid}"
  display_name = "vcn1"
}

### Terraform Plan

<details>

</details>

**Comment by parweza** [comment]
Looks like 
Were you able to ping 129.213.2.143 from the host you are running the terraform?
Can you also run traceroute for 129.213.2.143?

**Comment by rohanbhattacharjee** [comment]
We are closing this issue since there has been no response from the customer for several days. Please reopen if necessary.

**Comment by jimmycal** [comment]
Sorry for the delay, a took a bit to get back in front of our customer....ping fails with no response, and traceroute does not return any details, see the screenshots.   The CLI works correctly on this same instance.  Attached is the bash_profile configuration as well.  
![image001](https://user-images.githubusercontent.com/1430096/37736350-12bec56c-2d27-11e8-8a03-689cd0b25b2b.png)
![image002](https://user-images.githubusercontent.com/1430096/37736351-12cda15e-2d27-11e8-9f28-386779fa56f6.png)
![image004](https://user-images.githubusercontent.com/1430096/37736352-12dc2364-2d27-11e8-9e6c-5862349b914a.png)

**Comment by rohanbhattacharjee** [comment]
Reopening this issue since @jimmycal has an update from the customer.

**Comment by alexng-canuck** [comment]
Hello @jimmycal ,
I noticed that this was observed with Terraform provider v2.0.7. That version has an issue with setting proxies on the HTTP client.

The issue has since been fixed. Can you verify whether it still repros with the latest Terraform provider (v2.1.1). You can find the release here: https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.1

Let us know if you're still having problems with the latest version.

**Comment by jimmycal** [comment]
Validating with the customer on Friday....thank you for the update!

**Comment by alexng-canuck** [comment]
Hi @jimmycal I will close this issue since I haven't heard back from you. 

The latest version of the provider should fix this issue. If this issue still happens with the latest version of the provider, please reopen the issue and let us know.

Thanks!

**Comment by dariagrudzien** [comment]
@alexng-canuck I actually have the same problem in a different region, using provider v3.36.0 I have no proxy setup. Do you have any tips on how to try and debug this?
