### ISSUE TITLE
Add support for creating an instance from a pre-created boot volume

### ISSUE THREAD

**Issue by virtualorg1** [oracle/terraform-provider-oci#457]
### Terraform Version

Terraform v0.11.3

### OCI Provider Version

provider.oci v2.0.7

### Description:
Need to add the functionality to create instances using a pre-created boot volume.

In the opc provider, when creating an instance using opc_compute_instance, you can attach any pre-created storage including boot volumes thus:

  storage {
		index = 1
                volume = "BootVolumeName"
  }
  storage {
		index = 2
                volume = "SecondVolumeName"
  }
  storage {
		index = 3
                volume = "ThirdVolumeName"
  }
  boot_order = [ 1 ]

This doesn't seem to be available in oci provider so it is not possible to create an instance with a pre-created boot volume. This is needed.

**Comment by parweza** [comment]
OCI terraform plugin currently only supports imageId  which has been deprecated in favor of InstanceSourceDetails https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/requests/LaunchInstanceDetails . 
Adding backlog item to support LaunchInstanceDetails

**Comment by virtualorg1** [comment]
Related to this, is there a way to detach a boot volume so the instance can be destroyed and the boot volume attached to another newly created instance (once the 'InstanceSourceDetails' functionality identified in this issue is added)? At the moment, if you destroy the instance with Terraform, it destroys the boot volume, which is not always what you want.

**Comment by briangustafson** [comment]
That's a good call out - as part of that work to support boot volume specification when launching an instance, the provider should also expose the "preserverBootVolume" option for use during delete (https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/Instance/TerminateInstance). I'll note, however, that the simplest approach of adding a "preserver_boot_volume" parameter on the instance resource would leave users with dangling boot volume resources after destroy that are not managed by Terraform.

**Comment by alexng-canuck** [comment]
Hi @virtualorg1 

We added this functionality in the latest Terraform OCI provider release: https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.5
 
We introduced some new properties for the Instance resource, to enable the Instance resizing scenario:
- A “preserve_boot_volume” property for saving the attached boot volume
- A computed “boot_volume_id” property for getting the ID of the attached boot volume
- A “source_details” flag for specifying the ID of the preserved boot volume when you need to launch a new instance
 
For more details, refer to this doc: https://github.com/oracle/terraform-provider-oci/blob/master/docs/core/instances.md
