### ISSUE TITLE
DHCP changes displayed in terraform plan when nothing changed in any of the TF files?

### ISSUE THREAD

**Issue by FettBoba** [oracle/terraform-provider-oci#458]
### Terraform Version

<details>
Terraform v0.11.0
</details>

### OCI Provider Version

<details>
terraform-provider-oci 2.0.4
</details>

### Description:
DHCP changes displayed in terraform plan when nothing changed in any of the TF files?
 
I run the initial apply … done successfully.
Don’t change anything – run TF plan later again and get:
 
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
 
Terraform will perform the following actions:
 
  ~ oci_core_dhcp_options.DHCPoptions
      options.#:                       "2" => "1"
      options.1.search_domain_names.#: "1" => "0"
      options.1.search_domain_names.0: "glusterdemo.oraclevcn.com" => ""
      options.1.type:                  "SearchDomain" => ""
 
Plan: 0 to add, 1 to change, 0 to destroy.
 
In my netwok.tf file I have:
 
resource "oci_core_dhcp_options" "DHCPoptions" {
    compartment_id = "${var.compartment_ocid}"
    vcn_id = "${oci_core_virtual_network.VCN_GlusterDemo.id}"
    display_name = "DHCPoptions"
 
    options {
      type = "DomainNameServer"
      server_type = "VcnLocalPlusInternet"
    }
}
 
And of course in each Subnet resource:
 
  dhcp_options_id = "${oci_core_dhcp_options.DHCPoptions.id}"

**Comment by parweza** [comment]
looks like create dhcp options by default creates a search domain based upon the VCN and that search domain is not honored during update.
