### ISSUE TITLE
Invalid VNIC creation parameter

### ISSUE THREAD

**Issue by cslist** [oracle/terraform-provider-oci#460]
### Terraform Version

$ terraform -v
[root@tfserver:Primary_Region/us-phoenix-1] -> terraform -v
Terraform v0.11.3
+ provider.oci (unversioned)
+ provider.template v1.0.0

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

[root@tfserver:Primary_Region/us-phoenix-1] -> /bin/terraform-provider-oci
2018/02/22 00:55:22 [INFO] terraform-provider-oci 0.0.0
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

### Description:
Getting "Invalid VNIC creation paramters" error while creating a compute instance

data "template_file" "cloud-config" {
  template = <<YAML
#cloud-config
runcmd:
 - yum update -y >> /tmp/yum.log
YAML
}

resource "oci_core_instance" "LinuxInstance" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
  compartment_id = "${var.compartment_ocid}"
  display_name = "server1"
  hostname_label = "server1"
  image = "${lookup(var.LinuxImageOCID, var.region)}"
  shape = "${var.InstanceShape}"
  subnet_id = "${oci_core_subnet.SubnetProd.id}"

  create_vnic_details {
    display_name = "server1vnic"
    subnet_id = "${oci_core_subnet.SubnetProd.id}"
  },

  metadata {
    ssh_authorized_keys = "${var.ssh_public_key}"
    user_data = "${base64encode(data.template_file.cloud-config.rendered)}"
  }

  timeouts {
    create = "60m"
  }
}
=====
terraform apply -- resulting in following error

Error: Error applying plan:

1 error(s) occurred:

* oci_core_instance.LinuxInstance: 1 error(s) occurred:

* oci_core_instance.LinuxInstance: Status: 400; Code: InvalidParameter; OPC Request ID: /E99E07EF93AD811ACE5B4336C8449461/2C1017D9F2556F545FFFD8DDDE6C2D89; Message: Invalid VNIC creation parameters
========
tried wihtout create_vnic_details -- gives the same error! 

### Terraform Plan

<details>
  + oci_core_instance.LinuxInstance
      id:                                           <computed>
      availability_domain:                          "XXX"
      compartment_id:                               "XXX"
      create_vnic_details.#:                        "1"
      create_vnic_details.0.assign_public_ip:       "true"
      create_vnic_details.0.display_name:           "server1vnic"
      create_vnic_details.0.hostname_label:         <computed>
      create_vnic_details.0.private_ip:             <computed>
      create_vnic_details.0.skip_source_dest_check: "false"
      create_vnic_details.0.subnet_id:              "XXX"
      display_name:                                 "server1"
      hostname_label:                               "server1"
      image:                                        "XXX"
      metadata.%:                                   "2"
      metadata.ssh_authorized_keys:                 "XXX"
      metadata.user_data:                           "XXX"
      private_ip:                                   <computed>
      public_ip:                                    <computed>
      region:                                       <computed>
      shape:                                        "VM.Standard1.2"
      state:                                        <computed>
      subnet_id:                                    "XXX"
      time_created:                                 <computed>

  + oci_core_volume_attachment.Server1Block0Attach
      id:                                           <computed>
      attachment_type:                              "iscsi"
      availability_domain:                          <computed>
      chap_secret:                                  <computed>
      chap_username:                                <computed>
      compartment_id:                               "XXX"
      display_name:                                 <computed>
      instance_id:                                  "${oci_core_instance.LinuxInstance.id}"
      ipv4:                                         <computed>
      iqn:                                          <computed>
      port:                                         <computed>
      state:                                        <computed>
      time_created:                                 <computed>
      volume_id:                                    "XXX"

Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

</details>

**Comment by briangustafson** [comment]
Is this by any chance using a private subnet (prohibit_public_ip_on_vnic=true)? If so, then you will need to set assign_public_ip=false in create_vnic_details. Let me know if that is not the issue.

**Comment by cslist** [comment]
No, that's not the case. The subnet is allowed for public segment (Subnet Access: Public Subnet). 
I just tried setting assign_public_ip=false but still gives the same error. :-(

**Comment by cslist** [comment]
Interesting! I had to remove hostname_label parameter from the instance block and then it worked! Is this a bug?

resource "oci_core_instance" "LinuxInstance" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
  compartment_id = "${var.compartment_ocid}"
  display_name = "server1"
  #hostname_label = "server1"
  image = "${lookup(var.LinuxImageOCID, var.region)}"
  shape = "${var.InstanceShape}"
  #subnet_id = "${oci_core_subnet.SubnetProd.id}"

  create_vnic_details {
    display_name = "server1vnic"
    subnet_id = "${oci_core_subnet.SubnetProd.id}"
  },

  metadata {
    ssh_authorized_keys = "${var.ssh_public_key}"
    user_data = "${base64encode(data.template_file.cloud-config.rendered)}"
  }

  timeouts {
    create = "60m"
  }
}

**Comment by bjamb** [comment]
The mentioned workaround did not help us while we tried the same for building the consecutive servers. It errors with same message. Message: Invalid VNIC creation parameters.

resource "oci_core_instance" "server2" {
availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
compartment_id = "${var.compartment_ocid}"
display_name = "server2"
#hostname_label = "server2"
image = "${lookup(var.LinuxImageOCID, var.region)}"
shape = "${var.InstanceShape}"
#subnet_id = "${oci_core_subnet.SubnetQA.id}"

create_vnic_details {
display_name = "server2vnic"
subnet_id = "${oci_core_subnet.SubnetQA.id}"
},

**Comment by briangustafson** [comment]
@bjamb - Have you tried setting "assign_public_ip=false"? I've found 3 parameters in launch instance that can cause this error: 
- assign_public_ip must be set to false if the subnet has "prohibit_public_ip_on_vnic=true".
- hostname_label can only be set if the subnet has a "dns_label".
- private_ip, if specified, must be in the valid range.

If any of those are incorrect, then you'll get the "Invalid VNIC creation parameters" error. Let me know if none of that works.

We'll investigate whether a more specific and helpful error message can be given instead.

**Comment by rohanbhattacharjee** [comment]
We are closing this issue for because we have provided the details for why the error could be happening.

Internally, we are exploring options on whether the error message can be made more helpful.
