### ISSUE TITLE
Beta Release 2.1.0-beta - 2018-02-08 Issues

### ISSUE THREAD

**Issue by gcstang** [oracle/terraform-provider-oci#462]
2.1.0-beta

Release Notes
OCI Terraform Provider now uses the official Go SDK

1. The link to the "official Go SDK" doesn't exist 404 (https://github.com/oracle/oci-go-sdk)
    Where can I find the Go SDK?
2. The docs link goes to an old version 2.0.6

**Comment by rohanbhattacharjee** [comment]
Hi @gcstang -

1. The "official Go SDK" repo is currently a private repository under the Oracle organization. The link is valid, but some people may not have access to it at this time. We should have a solution to this in the next several days.

2. Thanks for pointing this out. Fixed the link.

**Comment by rohanbhattacharjee** [comment]
Hi Gil,
The official Go SDK repo is private to Oracle - hence the link may seem broken to some people without access to it.
It is one of the significant new changes to the OCI Terraform Provider. Hence we wanted to include that information in the release notes.
However, we are still working out the best way to provide more information about the new Go SDK. We should have more information in the next several days.
ThanksRohan
		
		

		Get Outlook for iOS
	





On Tue, Feb 27, 2018 at 6:26 AM -0800, "Gil" <notifications@github.com> wrote:












2.1.0-beta


Release Notes

OCI Terraform Provider now uses the official Go SDK

The link to the "official Go SDK" doesn't exist 404 (https://github.com/oracle/oci-go-sdk)

Where can I find the Go SDK?
The docs link goes to an old version 2.0.6
