### ISSUE TITLE
Consider releasing 32 and 64bit binaries as separate downloads

### ISSUE THREAD

**Issue by jhorwit2** [oracle/terraform-provider-oci#463]
Currently binaries for different archs of the same os are shipped in the same tar. This increases the download time and isn't a common pattern for shipping binaries. It also means you can't one line download the binary with `wget | tar` which is possible if it was an arch per tar.

**Comment by rohanbhattacharjee** [comment]
Hi @jhorwit2,

We had a quick discussion about this within our team.

Given that the size of the zips is currently fairly small (10-20 MBs) and we have quite a long backlog to take care of in the team, we don't think will have a realistic chance to get to this.

In the future, if the zip sizes increase substantially, we will definitely consider following this approach.

Please re-open the issue if you have more questions.

Thanks
Rohan

**Comment by AlaaShaker** [comment]
@jhorwit2 This has been fixed as part of #471. Please let us know if that isn't sufficient to enable your one-line download use case.
