### ISSUE TITLE
Remote Peering

### ISSUE THREAD

**Issue by RiaanRossouw** [oracle/terraform-provider-oci#468]
Hi all,  Any plans to support remote peering in the plugin?

https://docs.us-phoenix-1.oraclecloud.com/Content/Network/Tasks/remoteVCNpeering.htm

**Comment by AlaaShaker** [comment]
Yes, it's definitely high on our priority list (esp. as we focus on achieving parity with the services). 

I will close this issue as a dupe of #404 - you can follow that issue instead. Please feel free to reopen this issue if you think the other one doesn't adequately address your concern.
