### ISSUE TITLE
Feature Request: Add support for "Amazon S3 Compatibility API Keys"

### ISSUE THREAD

**Issue by rgmccaw** [oracle/terraform-provider-oci#472]
### Terraform Version

Terraform v0.11.3

### OCI Provider Version

terraform-provider-oci 2.0.7

### Description:

Add support for "Amazon S3 Compatibility API Keys".

In the UI and documentation these are called "[Amazon S3 Compatibility API Keys](https://docs.us-phoenix-1.oraclecloud.com/Content/Object/Tasks/s3compatibleapi.htm)"
and in the SDKs and API they are called "[CustomerSecretKey](https://docs.us-phoenix-1.oraclecloud.com/api/#/en/identity/20160918/CustomerSecretKey/)"

**Comment by AlaaShaker** [comment]
Thanks for the feature request. This will be supported once we achieve parity with the service, which our next big focus. I'll make an internal note of your request to help prioritize this work.

**Comment by alexng-canuck** [comment]
Hi @rgmccaw ,

Customer secret keys are now supported in the latest releases, starting since version 2.1.9: https://github.com/oracle/terraform-provider-oci/releases

Let us know if this addresses your original request.

Thanks,
Alex

**Comment by rgmccaw** [comment]
@alexng-canuck 👍
