### ISSUE TITLE
Service error:NotAuthenticated. 

### ISSUE THREAD

**Issue by sreehacs** [oracle/terraform-provider-oci#474]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.11.3
+ provider.oci v2.1.0-beta

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
* provider.oci: version = "~> 2.1"

</details>

### Description:
Include a description with repro steps, expected result and actual result

### Terraform Plan

<details>
provider "oci" {
  tenancy_ocid = "<tenancy_ocid>"
  user_ocid = "<user_ocid>"
  fingerprint = "<fingerprint>"
  private_key = "${file("~/.oci/oci_api_key.pem")}"
  region = "us-ashburn-1"
}

resource "oci_identity_compartment" "compartment1" {
  name = "TerraformTestCompartment"
  description = "Terraform Test Compartment"
}

When applying above plan getting below error:

Error: Error applying plan:

1 error(s) occurred:

* oci_identity_compartment.compartment1: 1 error(s) occurred:

* oci_identity_compartment.compartment1: Service error:NotAuthenticated. Date 'Sun, 11 Mar 2018 16:32:46 UTC' is not within allowed clock skew. Current 'Sun, 11 Mar 2018 16:39:04 UTC', valid datetime range: ['Sun, 11 Mar 2018 16:34:04 UTC', 'Sun, 11 Mar 2018 16:44:05 UTC']. http status code: 401

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

</details>

**Comment by michaelhart** [comment]
@sreehacs, it looks like your system's time was slightly behind.

> HTTP status code 401 (NotAuthenticated) is returned if the client's clock is skewed more than 5 minutes from the server's.

https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/usingapi.htm#Maximum

Can you try synchronizing your system's clock to within 5 minutes of the server time? You can determine that by running: `curl -s --head https://iaas.us-ashburn-1.oraclecloud.com | grep Date`
