### ISSUE TITLE
Add Boot volume size

### ISSUE THREAD

**Issue by herasimau** [oracle/terraform-provider-oci#475]
It's possible to add boot volume size on instance creation?

https://docs.us-phoenix-1.oraclecloud.com/Content/Block/Concepts/bootvolumes.htm?Highlight=boot%20volume%20size

**Comment by anandhmahal** [comment]
This feature is now supported with v2.1.6

**Comment by vidhyasriramulu** [comment]
Tried v2.1.6 for boot volume creation and attachment . Got 

Error: oci_core_boot_volume_attachments.TFBlock0Attach: Provider doesn't support resource: oci_core_boot_volume_attachments
Error: oci_core_boot_volumes.TFBlock0: Provider doesn't support resource: oci_core_boot_volumes

my .terraformrc points to the "terraform-provider-oci_v2.1.16" 

any help ?

**Comment by alexng-canuck** [comment]
@vidhyasriramulu Boot volumes and boot volume attachments are currently supported as datasources. A forthcoming release will allow creation of boot volumes and attachments as floating resources.

If you need to attach an existing boot volume to an instance, you can specify it during creation of the instance using the `source_details` of an instance.

Can you share more details about the scenario you're trying to accomplish?

**Comment by vidhyasriramulu** [comment]
we are trying to create an instance and attach a boot volume to expand the disk space of '/' . 

Below is the code that errors out . 
resource "oci_core_boot_volumes" "TFBlock0" {
  availability_domain = "${var.ad}"
  compartment_id = "${var.compartment_ocid}"
  display_name = "2TB NFS"
  size_in_gbs = "${var.2TB}"
}

resource "oci_core_boot_volume_attachments" "TFBlock0Attach" {
    compartment_id = "${var.compartment_ocid}"
    instance_id = "${oci_core_instance.onebox-instance.id}"
    volume_id = "${oci_core_boot_volumes.TFBlock0.id}"
}

we currently have 50G as default, and would like to extend it to 250GB . (as below) through terraform . 
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            6.9G   12K  6.9G   1% /dev
tmpfs           1.4G  340K  1.4G   1% /run
/dev/sda1       148G  1.2G  141G   1% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup


 Appreciate if you can share the snippet of code using  source_details .

**Comment by alexng-canuck** [comment]
When you create an instance you can specify the size of a boot volume that gets created with it.

```
resource "oci_core_instance" "TFInstance" {
...
  source_details {
    source_type = "image"
    source_id = "${var.InstanceImageOCID[var.region]}"

    # Apply this to set the size of the boot volume that's created for this instance.
    # Otherwise, the default boot volume size of the image is used.
    # This should only be specified when source_type is set to "image".
    boot_volume_size_in_gbs = "250"
  }
...
}
```

**Comment by vidhyasriramulu** [comment]
@alexng-canuck Thanks for the sample. Now am able to attach boot volume during instance creation .
