### ISSUE TITLE
Provider Review

### ISSUE THREAD

**Issue by mbfrahry** [oracle/terraform-provider-oci#476]
Hello all!

My name is Matthew and I'm a member of the Terraform team over at Hashicorp. I've been looking over the provider recently and it's in a good spot but there is some feedback I have that I'd like to get addressed before we move it into the terraform-provider organization. 

I also want to throw this [guide](https://www.terraform.io/guides/writing-custom-terraform-providers.html) in as reading material when going back over the provider with my feedback. Most of my points can be tied back to this guide and it'll be helpful when reviewing others contributions to the provider.

This issue will serve as a checklist for tracking each point of feedback. I'm reviewing this off [981dad7](https://github.com/oracle/terraform-provider-oci/commit/981dad7c9ade9388510a08085c54e01d8b13a26d). The main focus of this initial review will be to get the schema right as well. Any major changes to the schema when we get it under terraform-providers could result in painful migrations that we want to mitigate as much as we can here.

- [ ] The [crud folder](https://github.com/oracle/terraform-provider-oci/tree/7e6c8c2ec3d1e8cf81be74c0382450f7c5219624/crud) has features that are outside the scope of Terraform, mainly the polling for when a resource is in a desired state (created, deleted, etc). 
This functionality should be moved into the sdk. When Terraform calls the sdk to create a resource, a ready to go resource or an error should be returned. When Terraform calls the sdk to destroy a resource, it should return nil, a 404 error (which is also good since that means it was deleted), or an error saying that the resource couldn’t be deleted. Doing this will also make each resource/datasource file more readable. I've rewritten the [cpe resource](https://gist.github.com/mbfrahry/946c4b9fe9d8bb103647f68b9b1820d8) as an example for what each resource will look like once you move the crud package out of Terraform. 

- [ ] Removing the crud package will also force you to rewrite the tests. Things were mostly good with the tests but there are somethings that are missed so I rewrote the [cpe resource test](https://gist.github.com/mbfrahry/f501addc28d403c76371fa5bd27ec577) as a guide to follow. The main pieces missing were [testAccPreCheck](https://gist.github.com/mbfrahry/f501addc28d403c76371fa5bd27ec577) to make sure that the client will be setup correctly when running the tests, [CheckDestroy](https://gist.github.com/mbfrahry/f501addc28d403c76371fa5bd27ec577) to confirm that the resource was destroyed correctly, and [check exists](https://gist.github.com/mbfrahry/f501addc28d403c76371fa5bd27ec577). The other pieces were more for consistency and readability.

- [ ] Additionally, every resource that supports import needs a separate import test. The tests currently have it all wrapped as one but it's better for readability if they are in their own file. I've added an example for how it should look [here](https://gist.github.com/mbfrahry/501e64b865e85f1cd3eb9ab0ae4afe27)
For consistency with other providers, you should rename the [provider folder](https://github.com/oracle/terraform-provider-oci/tree/master/provider) to `oci`

- [ ] There are a couple of [areas](https://github.com/oracle/terraform-provider-oci/blob/master/provider/core_security_list_resource.go#L32) where I want to confirm that a `TypeList` is the right approach used instead of a `TypeSet`. A `TypeList` is used when ordering matters and vice versa when using a `TypeSet`. I'm wondering, for the example I linked, if the API returns egress security rules (and everywhere else a `TypeList` is used) in the same order that you sent it and if not than it needs to be a `TypeSet` so it won't cause diffs in Terraform's state in every subsequent apply.

- [ ] There are some attributes in each of the resources that don't make the most of sense to track in Terraform [time_created](https://github.com/oracle/terraform-provider-oci/blob/master/provider/core_cpe_resource.go#L50), [state](https://github.com/oracle/terraform-provider-oci/blob/master/provider/core_drg_resource.go), etc. They could change on every apply or don’t provide relevant data to the user. 

- [ ] `id` is set in every resource schema and doesn't need to be. Terraform takes care of this for you so it can be removed from the schema. It can be set after the creation of a resource through `d.SetId(resource.ID)` and retrieved through d.Id()
- [ ] It looks like there are a few [places](https://github.com/oracle/terraform-provider-oci/blob/master/provider/core_security_list_resource.go#L74) where you pass -1 to the sdk. The comment says it's because Terraform is passing 0 to the sdk but it looks like the sdk is sending that field name and maybe the api is defaulting that value for you. You should be able to add [here](https://github.com/oracle/oci-go-sdk/blob/master/core/icmp_options.go#L28) `mandatory:"false" json:"code,omitempty"`. `omitempty` will prevent the sdk from sending the `code` field to the API when it is an empty value. You can do this for every non mandatory field. 

- [ ] Each resource/datasource in [provider.go](https://github.com/oracle/terraform-provider-oci/tree/master/provider) is named backwards. They should follow the format of `resource_core_cpe.go` and the corresponding test `resource_core_cpe_test.go`. 

- [ ] The docs folder will need to be renamed `website` and will take  quite a bit of refactoring to integrate with our website. My suggestion would be to look at the way we did it with the [OCI Classic Provider](https://github.com/terraform-providers/terraform-provider-opc/tree/master/website). [opc.erb](https://github.com/terraform-providers/terraform-provider-opc/blob/master/website/opc.erb) is how sidebar will look. Inside [website/docs](https://github.com/terraform-providers/terraform-provider-opc/tree/master/website/docs) you'll find [index.html](https://github.com/terraform-providers/terraform-provider-opc/blob/master/website/docs/index.html.markdown) which details how to setup and test the provider. This folder also contains the `d` and `r` folder which contains the documentation for datasources and resources respectively. 

We can update this comment as things are completed and I'll open subsequent comments if I have any more pieces of feedback. Please feel free to reach out with any other comments or questions as well.

**Comment by alexng-canuck** [comment]
Closing this issue since we have addressed them in the latest release (v2.2.0) or gotten agreement from @mbfrahry that it's not necessary.
