### ISSUE TITLE
Error in "oci_core_instances" datasource for listing Core Instances filtering the state

### ISSUE THREAD

**Issue by rrcastro** [oracle/terraform-provider-oci#478]
### Terraform Version

<details>
Terraform v0.10.8
</details>

### OCI Provider Version

<details>
2018/03/13 14:09:52 [INFO] terraform-provider-oci 0.0.0

</details>
<p>2.1.0 - 2018-03-08: <a href="https://github.com/oracle/terraform-provider-oci/releases/download/v2.1.0/linux_amd64.tar.gz"> linux_amd64.tar.gz  </a></p></p>

### Description:

I am trying to list the Core Instances resources provisioned in a compartment, filtering the state.

In documentation ( <a href="https://github.com/oracle/terraform-provider-oci/blob/master/docs/core/instances.md">link</a> ), the state field can be a filter.

The below datasources.tf causes a error of Terraform.

_**Error: data.oci_core_instances.clone_instance: : invalid or unknown key: state**_

<p><strong>datasources.tf</strong></p>
<pre><code>data "oci_identity_availability_domains" "ADs" {
        #Required
        compartment_id = "${var.tenancy_ocid}"
}
data "oci_core_instances" "clone_instance" {
        #Required
        compartment_id = "${var.compartment_ocid}"
        #Optional
        availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[var.AD - 1],"name")}"
        display_name = "${var.instance_display_name}"
        state = "${var.instance_state}"
}
</code></pre>

### Terraform Plan

<details>
Error in Terraform plan, so cannot provide the plan file. 
</details>
<p>Error: data.oci_core_instances.clone_instance: : invalid or unknown key: state</p>

**Comment by rrcastro** [comment]
A possible workround:
<p><strong>datasources_workround.tf</strong></p>
<pre><code>data "oci_identity_availability_domains" "ADs" {
        #Required
        compartment_id = "${var.tenancy_ocid}"
}
data "oci_core_instances" "clone_instance" {
        #Required
        compartment_id = "${var.compartment_ocid}"
        #Optional
        availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[var.AD - 1],"name")}"
        display_name = "${var.instance_display_name}"
        filter {
                name = "state"
                values = ["${var.instance_state}"]
        }
}
</code></pre>

**Comment by michaelhart** [comment]
This issue should be resolved with release v2.1.1:
https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.1

If you are still experiencing any issues after updating to the latest version, please reopen this ticket and let us know.

Thanks,
Michael

**Comment by saifkhan179** [comment]
There is no documentation on creating a clone volume or attaching one. Can anyone please point me to any docs available ?
