### ISSUE TITLE
Improve Gluster example -

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/terraform-provider-oci#483]
Update the Gluster example;
1. Allow a variable number of instances
2. Support iSCSI attached remote block volumes
3. Support dual AD deployments
    * Document the performance implications
4. Support existing VCNs
5. Enable the host firewall (!!)
6. Newer OL image
7. Support VMs

**Comment by alexng-canuck** [comment]
@craigcarl-oracle ; we're in the middle of moving all the solutions from this repo over to https://github.com/oracle/terraform-examples/tree/master/examples/oci

This issue can now be tracked here: https://github.com/oracle/terraform-examples/issues/23

Closing this one.
