### ISSUE TITLE
add support for virtual hostname in oci_load_balancer_listener

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#486]
### Terraform Version

v0.11.2

### OCI Provider Version
v2.0.6

### Description:
A virtual hostname can be assigned to a load balancer listener as documented in https://docs.us-phoenix-1.oraclecloud.com/Content/Balance/Tasks/managingrequest.htm#vhost

### Terraform Plan

This is an enhancement request

**Comment by alexng-canuck** [comment]
Thanks for the feedback. I will add this to our backlog to help us prioritize this for upcoming releases of the provider.

**Comment by tondacrha** [comment]
Hi @alexng-canuck. Is there a date set for the upcoming release with the virtual hostname support?

**Comment by cslist** [comment]
Would you be able to expedite this one? THis is a key requirement for our implementation and not able to automate the process with terraform.

**Comment by parweza** [comment]
Requested feature has been added in [v2.1.7](https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.7). Please use the latest version of oci provider.
Resolving the issue now, please reopen if you have any questions.
