### ISSUE TITLE
Need the functionality to change the shape of the instance without destroying the boot volume.

### ISSUE THREAD

**Issue by neerkuma** [oracle/terraform-provider-oci#488]
### Terraform Version

Terraform Version
Terraform v0.11.3

OCI Provider Version
provider.oci v2.0.7
### Description:

When shape of instacne is change it force the new resource while destroying it should preserve the boot disk and use it while creating the new instance.

### Terraform Plan

</details>

**Comment by alexng-canuck** [comment]
Thanks for the feedback! I will share this request with the team and we will investigate this.

**Comment by alexng-canuck** [comment]
@neerkuma 
This is addressed in the latest Terraform OCI provider release: https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.5
 
We introduced some new properties for the Instance resource, to enable the Instance resizing scenario:

- A “preserve_boot_volume” property for saving the attached boot volume
- A computed “boot_volume_id” property for getting the ID of the attached boot volume
- A “source_details” flag for specifying the ID of the preserved boot volume when you need to launch a new instance
 
For more details, refer to this doc: https://github.com/oracle/terraform-provider-oci/blob/master/docs/core/instances.md
 
We’d love to hear your feedback.
