### ISSUE TITLE
provider.oci: can not create client, bad configuration: did not find a proper configuration for private key 

### ISSUE THREAD

**Issue by mbenolie** [oracle/terraform-provider-oci#491]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

<Terraform v0.11.5

/details>

/details>

### OCI Provider Version
+ provider.oci v2.1.1

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
Error when running  terraform plan. Already looked at issue #427 but it does not solve my problem. Is there a way to see what is the real error with the private key.
### Terraform Plan
* provider.oci: can not create client, bad configuration: did not find a proper configuration for private key

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by alexng-canuck** [comment]
Hello @mbenolie ,

Can you share how your private keys are specified in the provider config? (You can remove any sensitive values from your example).

A few reasons why this error might occur:
- Not specifying either a `private_key` or `private_key_path` in the config
- Specifying a `private_key_path` that's not a valid path to a private key file
- Not specifying a `private_key_password` for a private key that's encrypted
- Specifying an incorrect `private_key_password` for an encrypted private key

**Comment by mbenolie** [comment]
Hi Alex, 

 

provider "oci" {

    tenancy_ocid = "${var.tenancy_ocid}"

    user_ocid = "${var.user_ocid}"

    fingerprint = "${var.fingerprint}"

    private_key_path = "${var.private_key_path}"

    private_key_password="${var.private_key_password}"

    region = "${var.region}"

 

Rgds,

Michel

**Comment by alexng-canuck** [comment]
@mbenolie, have you verified that the cause isn't one of the following reasons?

- Specifying a `private_key_path` that's not a path to a valid private key file
- Specifying an incorrect `private_key_password` for an encrypted private key

**Comment by alexng-canuck** [comment]
@mbenolie Can you also confirm that the `var.private_key_path` and `var.private_key_password` are set? This is usually done in a .tfvar file or in your environment using `TF_VAR_{variable_name}`.

**Comment by mbenolie** [comment]
Hi Alex, 

I Regeenrated the keys without a passphrase and that took care of the problem.

Thanks
Michel
