### ISSUE TITLE
Need attribute for custom boot vol size in oci_core_instance

### ISSUE THREAD

**Issue by revnav** [oracle/terraform-provider-oci#492]
### Terraform Version

Terraform v0.11.3

### OCI Provider Version

provider.oci v2.1.0-beta

### Description:
Oracle introduced custom boot volume size feature few weeks ago. (https://docs.us-phoenix-1.oraclecloud.com/Content/Block/Concepts/bootvolumes.htm#Custom )

However I don't see an attribute for it in terraform provider for OCI yet : https://github.com/oracle/terraform-provider-oci/blob/master/docs/core/instances.md
Any idea when this would be available in terraform provider?

**Comment by alexng-canuck** [comment]
Thanks for the feedback @revnav . This item is in our backlog and being tracked in issue #475. I will share this feedback with the team and we will look at prioritizing this for an upcoming release.

If your request isn't addressed by #475, please let us know. Thanks!

**Comment by revnav** [comment]
Thanks, yes this is duplicate of #475.
