### ISSUE TITLE
Confusing document on installing terraform-provider-oci on Windows

### ISSUE THREAD

**Issue by scottz1** [oracle/terraform-provider-oci#497]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
Include a description with repro steps, expected result and actual result

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by scottz1** [comment]
I was getting an error running terraform init. It couldn't find the provider. The error is that I put the provider under appdata, but it REALLY needs to be under %appdata% which resolves to appdata/roaming.

**Comment by anandhmahal** [comment]
The README document is updated to reflect that `%APPDATA` is a system path.  Resolving this for now.
