### ISSUE TITLE
Add support for File Storage Service (NFS)

### ISSUE THREAD

**Issue by juanbecerra** [oracle/terraform-provider-oci#499]
Hi,

Is there a way to provision NFS file systems and mounts for the File Storage Service? We are automating an implementation that requires a shared drive and need to use the new service rather than manually configuring NFS in an instance.

**Comment by alexng-canuck** [comment]
Hi @juanbecerra ,

The File Storage Services are now supported in the latest Terraform release. See https://github.com/oracle/terraform-provider-oci/tree/master/docs/file_storage for more info.

For an example of how these resources are configured, you can also refer to this: https://github.com/oracle/terraform-provider-oci/tree/master/docs/examples/storage/fss

The latest releases are here: https://github.com/oracle/terraform-provider-oci/releases

Let us know if this addresses your scenario.

**Comment by juanbecerra** [comment]
Thanks Alex, 
That worked !!!

**Comment by ora1521** [comment]
Is there any option to obtain the IP address and then mount it in compute resource within some post provisioning inline (remote exec)?

**Comment by rohanbhattacharjee** [comment]
We released the updated examples here - https://github.com/oracle/terraform-provider-oci/tree/master/docs/examples/storage/fss

It now shows how to mount an FSS on a particular instance.

**Comment by juanbecerra** [comment]
Thanks Rohan,

One question I have is on running the "remote-exec" I am working on a large implementation and some of the instances (in particular the ones that need the shared drive) and in private subnets which are accessed via a bastion instance. is there a way to run "remote-exec" via a bastion server and if not what other way we can use to mount those drives given that they require information from the provisioning that I cannot pass on the instance metadata?

Regards,
Juan

**Comment by rohanbhattacharjee** [comment]
Hi Juan,
 
Looking at the Terraform documentation, there may be a native way to connect to your instance via a bastion host - https://www.terraform.io/docs/provisioners/connection.html.

In the last section they describe connecting via a bastion host as an intermediate hop.
 
So, if I had to guess, your remote-exec configuration would remain the same, except that the `connection` section would have some of those `bastion_host` and other bastion-auth related fields added to it.

Something like the following -

```
resource "null_resource" "mount_fss_on_instance" {
  depends_on = ["oci_core_instance.my_instance",
                "oci_file_storage_export.my_export_fs1_mt1"]
  provisioner "remote-exec" {
    connection {
      agent = false
      timeout = "30m"
      host = "${oci_core_instance.my_instance.public_ip}"
      user = "opc"
      private_key = "${file(var.ssh_private_key)}"

      bastion_host        = "${var.bastion_ip}"
      bastion_user        = "opc"
      bastion_private_key = "${file(var.ssh_private_key)}"
    }
    inline = [
      "sudo yum -y install nfs-utils > nfs-utils-install.log",
      "sudo mkdir -p /mnt/myfsspaths/fs1/path1",
      "sudo mount ${local.mount_target_1_ip_address}:${var.export_path_fs1_mt1} /mnt${var.export_path_fs1_mt1}",
    ]
  }
}
```

 
Thanks
Rohan
