### ISSUE TITLE
Unable to run terraform commands for oci

### ISSUE THREAD

**Issue by narengol** [oracle/terraform-provider-oci#501]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
[root@bfda56bf60f2 terraform]# ./terraform version
Terraform v0.11.5
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
1. Followed the steps mentioned in readme https://github.com/oracle/terraform-provider-oci
2. Placed plugins in terraform.d/plugins/linux_amd64/
[root@bfda56bf60f2 terraform]# ls terraform.d/plugins/linux_amd64/
terraform-provider-aws_v1.13.0_x4  terraform-provider-oci
[root@bfda56bf60f2 terraform]# ls terraform.d/plugins/linux_amd64/terraform-provider-oci/
CHANGELOG.md  CONTRIBUTING.md  crud  docs  LICENSE.md  main.go  Makefile  provider  README.md  scripts  tools  vendor  wercker.yml
[root@bfda56bf60f2 terraform]#

3. Unable to execute terraform init with sample oci plan, getting the below.

Provider "oci" not available for installation.
A provider named "oci" could not be found in the official repository.
This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by scross01** [comment]
Try the following:

- Download the latest version of the provider from https://github.com/oracle/terraform-provider-oci/releases

- Uncompress the download and copy the provider executable to `~/.terraform.d/plugins/`

    ```
    $ ls ~/.terraform.d/plugins/
    terraform-provider-oci_v2.1.4
    ```
- You can remove any `oci` entries from the `~/.terraformrc` file.  The `.terraformrc` config is only required if you have installed the plugin in a non-standard location

**Comment by narengol** [comment]
Thankyou, it worked.
