### ISSUE TITLE
Data reading from shell script.

### ISSUE THREAD

**Issue by Gopi1995krishna** [oracle/terraform-provider-oci#502]
Hi,

I created an instance in oci using terraform and i executed a shell script there.

How can I use output of shell script i executed in newly created instance as a variable in terraform.

Could you please share me any example of this.

Thanks

**Comment by rcohenma** [comment]
Hello,

I'm not sure this is possible.

executing scripts is done through terraform's remote-exec 
https://www.terraform.io/docs/provisioners/remote-exec.html

Terraform doesn't seem to have support for what you are suggesting

You could try using local-exec and write a script that gets data from the instance using ssh and scp 
https://www.terraform.io/docs/provisioners/local-exec.html

**Comment by hyder** [comment]
You can try writing the output of the shell script to a file, then get the file, as @rcohenma mentions, and then pass it as a variable. You'll need to introduce a delay to detect when the file has been written to do that. See (https://github.com/hashicorp/terraform/issues/4668) for example of using a delay with null_resource

**Comment by anandhmahal** [comment]
@Gopi1995krishna - Does the recommendation provided by @hyder helps address your concern?

**Comment by anandhmahal** [comment]
@Gopi1995krishna I am closing this issue.  In case you still need help, please reopen and will look into it again
