### ISSUE TITLE
Enhance arguments to data sources by adding tags

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#503]
### Terraform Version

v0.11.2

### OCI Provider Version
v2.0.6

### Description:
When defining resources, we can use tags and associate them with resources. Later, we want to be able to list resources based on tags. However, for data sources, we can't use tags at the moment.

e.g. I define a few computes: mysql, nginx, redis where I can associate tags with them.

resource "oci_core_instance" "redis" {
  .....
   count = "${var.rediscount}"
  extended_metadata {
    tags                = "group:redis"
  }
}

resource "oci_core_instance" "nginx" {
  .....
   count = "${var.nginxcount}" 
  extended_metadata {
    tags                = "group:nginx"
  }
}
etc...

Let's say I now want to be able to obtain a list of vnic attachments but just for the redis or nginx instances. At the moment, vnic_attachment only allows these 4 arguments:

availability_domain - (Optional) The name of the Availability Domain. Example: Uocm:PHX-AD-1
compartment_id - (Required) The OCID of the compartment.
instance_id - (Optional) The OCID of the instance.
vnic_id - (Optional) The OCID of the VNIC.

If I don't pass the instance_id as argument, I will get the vnic attachments for all instances in this compartment whereas I want to filter the resources based on certain criteria. Note I use vnic_attachments here as example. It would be good to have this for other types of resources too.

### Terraform Plan

This is an enhancement request

**Comment by rcohenma** [comment]
Oracle OCI supports tagging. https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/taggingoverview.htm

Our terraform provider doesn't currently support tagging. We have a plan to reach feature parity with the services. We will make note of this request and try to prioritize tagging.

**Comment by boatrig** [comment]
@rcohenma 
I'm hoping you can expand upon your answer.  We are wanting to create Defined tagged Named Spaces using terraform.  Does the terraform plugin currently support creating the Named Spaces?

If not, is there an enhancement request tracking number for it?

**Comment by meghshi** [comment]
+1 for this enhancement.  We are waiting for it too.

**Comment by mmorianos** [comment]
+1

**Comment by jjwarzecha** [comment]
+1

**Comment by llBIKSll** [comment]
+1

**Comment by svilmune** [comment]
+1

**Comment by codycushing** [comment]
Support for tagging resources and filtering by tags has been added in release 2.1.13
