### ISSUE TITLE
Local Peering Gateways - cant create 2 at the same time.

### ISSUE THREAD

**Issue by nagulako** [oracle/terraform-provider-oci#506]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
[root@ocs-work terraform_files]# terraform -v
Terraform v0.11.5
+ provider.oci v2.1.5

</details>

### OCI Provider Version

<details>

+ provider.oci v2.1.5

</details>

### Description:
When you try to create two local peering gateways - terraform doesn't know how to process them.  It will throw a Cycle error.  I'm not sure if there is anyway to handle this  - other than put in the OCID?
### Terraform Plan
[root@ocs-work terraform_files]# terraform plan

Error: Error asking for user input: 1 error(s) occurred:

* Cycle: oci_core_local_peering_gateway.lpg-sabre, oci_core_local_peering_gateway.lpg-ocs

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.
resource "oci_core_virtual_network" "vcn01" {
        cidr_block = "10.89.0.0/16"
        compartment_id = "${var.ntk_compartment_ocid}"

        display_name = "VCN01"
        dns_label = "vcn01"
}
resource "oci_core_virtual_network" "VCN-OCS" {
    cidr_block = "10.26.6.0/24"
    compartment_id = "${var.compartment_ocid}"
    display_name = "VCN-OCS1"

}

resource "oci_core_local_peering_gateway" "lpg-ocs" {
        #Required
        compartment_id = "${var.compartment_ocid}"
        vcn_id = "${oci_core_virtual_network.VCN-OCS.id}"

        #Optional
        peer_id = "${oci_core_local_peering_gateway.lpg-1.id}"
}

resource "oci_core_local_peering_gateway" "lpg-1" {
        #Required
        compartment_id = "${var.ntk_compartment_ocid}"
        vcn_id = "${oci_core_virtual_network.vcn01.id}"

        #Optional
        peer_id = "${oci_core_local_peering_gateway.lpg-ocs.id}"
}

</details>

**Comment by rcohenma** [comment]
You should not have a peer_id on both resources.
in Local Peering Gateways (LPG) we have a concept of requestor LPG and acceptor LPG
You should only have a peer_id field in the requestor LPG
See the following documentation for more detail:
https://docs.us-phoenix-1.oraclecloud.com/Content/Network/Tasks/localVCNpeering.htm
https://github.com/oracle/terraform-provider-oci/blob/master/docs/core/local_peering_gateways.md
https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/networking/local_vcn_peering/local_vcn_peering.tf
