### ISSUE TITLE
Local Peering Gateways - Doc bug

### ISSUE THREAD

**Issue by nagulako** [oracle/terraform-provider-oci#507]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.11.5

</details>

### OCI Provider Version
provider.oci v2.1.5
<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
Include a description with repro steps, expected result and actual result

The example provided doesn't have "peer.id" and instead stops at "peer"

resource "oci_core_local_peering_gateway" "test_local_peering_gateway" {
	#Required
	compartment_id = "${var.compartment_id}"
	vcn_id = "${oci_core_vcn.test_vcn.id}"

	#Optional
	display_name = "${var.local_peering_gateway_display_name}"
	peer_id = "${oci_core_local_peering_gateway.test_local_peering_gateway2}" <--- Should be ".id" 
}
</details>

**Comment by briangustafson** [comment]
Fixed with PR #513.
