### ISSUE TITLE
Deleting the oci_core_instance also deletes oci_core_images created using the instance

### ISSUE THREAD

**Issue by bitsarvi** [oracle/terraform-provider-oci#509]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.11.7
+ provider.oci v2.1.4
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
2018/04/18 04:17:51 [INFO] terraform-provider-oci 2.1.4

</details>

### Description:
Include a description with repro steps, expected result and actual result
* Created an OCI Linux 7.4 instance
* Created an image based on the above instance.
* Unable to destroy just the instance using `terraform destroy -target=`. This ends up destroying the image too
* I'm able to destroy just the instance from the console. 
* I'm able to destroy just the image using `terraform destroy -target=`
```
$ cat resources.tf
variable "oracle_tenancy_ocid" {}
variable "oracle_user_ocid" {}
variable "oracle_fingerprint" {}
variable "oracle_private_key_path" {}
variable oracle_region {}
variable compartment_id {}
variable subnet_id {}

variable "base_image" {
    type = "map"
    default = {
        // See https://docs.us-phoenix-1.oraclecloud.com/Content/Resources/Assets/OracleProvidedImageOCIDs.pdf
        // Oracle-provided image "Oracle-Linux-7.4-2018.02.21-1"
        us-phoenix-1 = "ocid1.image.oc1.phx.aaaaaaaaupbfz5f5hdvejulmalhyb6goieolullgkpumorbvxlwkaowglslq"
        us-ashburn-1 = "ocid1.image.oc1.iad.aaaaaaaajlw3xfie2t5t52uegyhiq2npx7bqyu4uvi2zyu3w3mqayc2bxmaa"
        eu-frankfurt-1 = "ocid1.image.oc1.eu-frankfurt1.aaaaaaaa7d3fsb6272srnftyi4dphdgfjf6gurxqhmv6ileds7ba3m2gltxq"
        uk-london-1 = "ocid1.image.oc1.uk-london1.aaaaaaaaa6h6gj6v4n56mqrbgnosskq63blyv2752g36zerymy63cfkojiiq"
    }
}

resource "oci_core_instance" "base_instance" {
    availability_domain = "BnQb:PHX-AD-1"
    compartment_id      = "${var.compartment_id}"
    display_name        = "foobar"
    shape               = "VM.DenseIO1.4"
    create_vnic_details {
        subnet_id           = "${var.subnet_id}"
    }
    image = "${var.base_image[var.oracle_region]}"
}

resource "oci_core_image" "release_image" {
    depends_on = [ "oci_core_instance.base_instance" ]

    #Required
    compartment_id = "${var.compartment_id}"
    instance_id = "${oci_core_instance.base_instance.id}"
}

$ terraform apply -auto-approve
(output omitted)
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

$ terraform state list
oci_core_image.release_image
oci_core_instance.base_instance

$ terraform plan -target=oci_core_instance.base_instance -destroy
(output omitted)
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - oci_core_image.release_image

  - oci_core_instance.base_instance


Plan: 0 to add, 0 to change, 2 to destroy.

$ terraform plan -target=oci_core_image.release_image -destroy
(output omitted)
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - oci_core_image.release_image


Plan: 0 to add, 0 to change, 1 to destroy.


```

*Expected result*: `terraform destroy -target=oci_core_instance.base_instance` **should not destroy** `oci_core_image.release_image`

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

See `resources.tf` above
</details>

**Comment by codycushing** [comment]
Hello, when you use Terraforms interpolation syntax to point the image resources `instance_id` field to the instance resource, it creates a dependency, so Terraform behaves as expected when it determines the image must be deleted before the image can be deleted. To avoid this behavior, prior to delete, you can replace the interpolation string `"${oci_core_instance.base_instance.id}"` in the image resource with the actual instance OCID literal. You will also need to remove the `depends_on` from the image resource (which wasn't actually required in the first place due to the interpolation string).
