### ISSUE TITLE
terraform init downloads null provider.

### ISSUE THREAD

**Issue by ttsharma** [oracle/terraform-provider-oci#510]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.10.8

### OCI Provider Version

2018/04/23 21:51:43 [INFO] terraform-provider-oci 2.0.7

### Description:
When I execute terraform init it downloads terraform-provider-null_v1.0.0_x4 under the .terraform/plugins.

I do not want that to happen because I may not have internet connectivity always.

I do not want any downloads to happen on the fly.

If I use -plugin-dir flag then it fails as below:
===============================
$ terraform init -plugin-dir=/scratch/user2/terraform-work/linux_386

Initializing provider plugins...

Missing required providers.

The following provider constraints are not met by the currently-installed
provider plugins:

* null (any version)

Terraform can automatically download and install plugins to meet the given
constraints, but this step was skipped due to the use of -get-plugins=false
and/or -plugin-dir on the command line.

If automatic installation is not possible or desirable in your environment,
you may manually install plugins by downloading a suitable distribution package
and placing the plugin's executable file in one of the directories given in
by -plugin-dir on the command line, or in the following directory if custom
plugin directories are not set:
    terraform.d/plugins/linux_386
===============================

Below o/p shows Downloading plugin for provider "null"
===============================

$ terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "null" (1.0.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.null: version = "~> 1.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
===============================

Content of provider.tf is as below:
===============================
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "private_key_password" {}
variable "compartment_ocid" {}
variable "region" {}

provider "oci" {
  region = "${var.region}"
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  private_key_password = "${var.private_key_password}"
}
===============================

**Comment by rohanbhattacharjee** [comment]
I believe if you reference the `null_resource` in your terraform configuration files, then Terraform does not really have an option but to download it (unless, you have it already downloaded).

Typically, `null_resource` usage happens when running `remote-exec` etc. as you see in this example - https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/storage/fss/instance.tf#L17

So, if you do not have internet connectivity, then either you could pre-download the null_resource, or you could remove any references to it from your configuration.

**Comment by codycushing** [comment]
The above statement is correct, by design, Terraform will automatically download officially supported providers based on reference. You can pre-populate these if you so chose or not use them.
