### ISSUE TITLE
oci_database_db_system forces new resource with change to cpu_core_count

### ISSUE THREAD

**Issue by drauba** [oracle/terraform-provider-oci#517]
### Terraform Version
Terraform v0.11.7

### OCI Provider Version
terraform-provider-oci 2.1.5

### Description:
Changing cpu_core_count on a database system forces a new resource. This action can be completed with the oci cli without recreating the database system. 

### Terraform Plan
Feature request. 
</details>

**Comment by parweza** [comment]
Thanks for the feedback. I have added this to our backlog to help us prioritize this for upcoming releases of the provider.

**Comment by drauba** [comment]
Would the change be as simple as updating this piece of code from database_db_system_resource.go?

`			"cpu_core_count": {
				Type:     schema.TypeInt,
				Required: true,
				ForceNew: true, // todo: remove when update is supported
			}`

**Comment by codycushing** [comment]
Hello, this has been addressed in release 2.1.13
