### ISSUE TITLE
Support Remote Peering Connection for VCN Remote Peering

### ISSUE THREAD

**Issue by cgong-github** [oracle/terraform-provider-oci#521]
It is great to support VCN local peering with the latest OCI Terraform provider.  

Could we add support for Remote Peering too?

**Comment by parweza** [comment]
Thanks for your feed. I have added this in our backlog items to help us prioritize this for upcoming releases of the provider.

**Comment by anandhmahal** [comment]
Duplicate of #404

**Comment by codycushing** [comment]
Available in release v2.1.8
