### ISSUE TITLE
docs for oci_identity_availability_domains as data show compartment_id = tenency_id

### ISSUE THREAD

**Issue by sochoa** [oracle/terraform-provider-oci#522]
This is a documentation bug across the github repository.  The `oci_identity_availability_domains` data examples show `compartment_id = "${var.tenency_id}"`.  It _should_ be `compartment_id = "${var.compartment_id}"`.

**Comment by jhorwit2** [comment]
@sochoa You can use the tenancy ID or a compartment id there. The tenancy is just the root compartment, which is why it works. 

From the docs [here])(https://docs.us-phoenix-1.oraclecloud.com/api/#/en/identity/20160918/AvailabilityDomain/ListAvailabilityDomains): 

> Lists the Availability Domains in your tenancy. Specify the OCID of either the tenancy or another of your compartments as the value for the compartment ID (remember that the tenancy is simply the root compartment).

**Comment by briangustafson** [comment]
@jhorwit2 is correct. Closing
