### ISSUE TITLE
Add ability to manage container service with Terraform

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#525]
Terraform Version
v0.11.7

OCI Provider Version
v2.1.7

Description:
Add ability to manage container service and related resources that can be created with Terraform on a par with other resources such as vcns, instances etc

This is an enhancement request

**Comment by briangustafson** [comment]
This is being tracked in our backlog. Thanks for bringing this up, since requests such as this help us to prioritize.

**Comment by eginez** [comment]
Support has been added in the latest release of the provider
