### ISSUE TITLE
Defining the Backup policy of a block volume w/ terraform

### ISSUE THREAD

**Issue by samjeckert** [oracle/terraform-provider-oci#527]
Is it possible to set this with Terraform configs? I do not see an option to do this. I know I can do it manually via Console but i'd like to be able to define block volumes with a policy set. 

Thanks!

**Comment by kohashim** [comment]
Volume backup policy is not supported yet, but is in our roadmap.  Thanks.

**Comment by codycushing** [comment]
Support for setting volume backup policies has been added in release 2.1.13
