### ISSUE TITLE
The provider should have an instance metadata datasource -

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/terraform-provider-oci#530]
With support for Instance Principals running Terraform on OCI instances will become more common. Instance metadata (`curl -L http://169.254.169.254/opc/v1/instance/`) can contain data that is useful as a data source.  We should treat instance metadata as a first class datasource.

A new metadata key, `regionName` will ship soon, this will enable us to set "${var.region}" from the metadata, this means we can build region independent TF configurations using Instance Principals. 

WRT implementation; additional keys will be added over time, if possible the datasource should support arbitrary keys so the provider doesn't need to be updated to support them. Maybe something like - 
`data "oci_core_instance_metadata" "something_new" {
  awesome_new_thing = "${oci_core_instance_metadata.something_new}"
}`

to access `http://169.254.169.254/opc/v1/instance/something_new`

We would also need to support arbitrarily deep keys, something like -
`data "oci_core_instance_metadata" "instance_public_keys" {
  instance_keys = "${oci_core_instance_metadata.metadata.ssh_authorized_keys}"
}`

**Comment by craigcarl-oracle** [comment]
I needed the functionality, I wrote it as a external datasource. It's grungy but working -

The external script - 
```
#!/usr/bin/python
import sys
import json
import requests 

r = requests.get('http://169.254.169.254/opc/v1/instance/')
ud = r.json()

# Everything returned to TF needs to be a string so we convert timeCreated.
ud["timeCreated"] = str(ud["timeCreated"])

# I need the API endpoint so I convert from the metadata. 
# Only need to do this in PHX and IAD.
if ud["region"] == 'phx':
	ud["region"] = 'us-phoenix-1'
elif (ud["region"] == 'iad'):
	ud["region"] = 'us-ashburn-1'

# TF can't handle nested JSON, metadata is nested. 
# I don't need it so I delete it. Alternatively you could flatten it. 
ud.pop('metadata', None)
json.dump(ud, sys.stdout)
```

main.tf
```
data "external" "userdata" {
  program = ["python", "get_userdata.py"]
}

output "local_image" {
  value = "${data.external.userdata.result.image}"
}

output "local_availability_domain" {
  value = "${data.external.userdata.result.availabilityDomain}"
}

output "local_shape" {
  value = "${data.external.userdata.result.shape}"
}

output "local_region" {
  value = "${data.external.userdata.result.region}"
}
```
Results - 
```
data.external.userdata: Refreshing state...
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
local_availability_domain = Uocm:PHX-AD-1
local_image = ocid1.image.oc1.phx.aaaaaaaaeq3jmnrt3tfytoxn47muky2suiykdcor2dp7jthmqslwwjssahzc
local_region = us-phoenix-1
local_shape = VM.Standard2.1
```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
