### ISSUE TITLE
Support for Dynamic Groups

### ISSUE THREAD

**Issue by gregoryguillou** [oracle/terraform-provider-oci#532]
### Terraform Version

0.11.7

### OCI Provider Version

2.1.8

### Description:

I did not find any way to manage or access "Dynamic Groups" from the OCI terraform provider. My understanding is that it is the way to go to grant permissions to scripts or programs running on a given instance, like accessing a bucket. Is there a way to create such a resource from this provider or is there a better way? Thank you.

### Terraform Plan

<details>
N/A
</details>

**Comment by kohashim** [comment]
Currently OCI terraform provider doesn't support Dynamic Groups yet.  It is is our roadmap.  Thanks.

**Comment by gregoryguillou** [comment]
Thank you

**Comment by alexng-canuck** [comment]
Hi @gregoryguillou 

Dynamic groups is now supported in the latest release: https://github.com/oracle/terraform-provider-oci/releases/tag/v2.1.10

Please let us know if this addresses your original request for being able to manage them in Terraform.

Thanks,
Alex

**Comment by gregoryguillou** [comment]
Awesome. I'll test it. Thank you

**Comment by gregoryguillou** [comment]
I've tested with the 2.1.10 provider, imported my resource (i.e. the dynamic group) and referenced by interpolating its name from a policy. It works fine for me. Thank you.
