### ISSUE TITLE
module loosing provider information

### ISSUE THREAD

**Issue by RomeshSharma** [oracle/terraform-provider-oci#533]
Terraform v0.11.7
+ provider.oci v2.1.8

### Description:
I am calling a module from parent configuration file and inside the module its loosing provider information. My environment file has already got TF variables exported and below output confirms that.

env|grep TF_VAR
TF_VAR_tenancy_ocid=ocid1.tenancy.XXX
TF_VAR_region=us-ashburn-1
TF_VAR_fingerprint=XXX
TF_VAR_private_key_path=XXXX
TF_VAR_user_ocid=ocid1.userXXX

### Terraform Plan
terraform plan
provider.oci.region
  (Required) The region for API connections (e.g. us-ashburn-1).

  Enter a value: us-ashburn-1

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error: Error refreshing state: 1 error(s) occurred:

* provider.oci: when auth is set to 'ApiKey', tenancy_ocid, user_ocid, and fingerprint are required

### parent file looks as under:
provider "oci" {
  region = "us-ashburn-1"
  alias = "us-ashburn-1"
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  disable_auto_retries = "true"
  version = "~> 2.1"
}

module "vcn_iad" {
  source                = "../modules/vcn_mod"
  vcn_cidr              = "${var.vcn_cidr}"
  vcn_compartment_id    = "${var.compartment_id}"
  vcn_display_name      = "XXX-vcn"
  vcn_dns_label         = "XXX"
//  provider_alias        = "iad"
//  provider              = "oci.iad"
  vcn_target_region     = "us-ashburn-1"
  providers =  {
          "oci"         = "oci.us-ashburn-1"
  }
}

And the module main.tf looks as under:

resource "oci_core_vcn" "vcn" {
//  provider      = "oci.${var.vcn_target_region}"
  cidr_block     = "${var.vcn_cidr}"
  compartment_id = "${var.vcn_compartment_id}"
  display_name   = "${var.vcn_display_name}"
  dns_label      = "${var.vcn_dns_label}"
}

**Comment by RomeshSharma** [comment]
Terraform init works well but when I say terraform validate it complains abt Region though its already set in the parent as above.

terraform init
Initializing modules...
- module.vcn_phx
- module.vcn_iad
- module.vcn_fra

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.oci: version = "~> 2.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

terraform validate

Error: provider.oci: "region": required field is not set

**Comment by briangustafson** [comment]
Are you sure that you don't have a provider block somewhere else in your config? (I noticed that your output for "terraform plan" starts with "provider.oci.region", but from my own experimentation it looks like if the provider has an alias then that output should be "provider.oci.myalias.region".)

**Comment by RomeshSharma** [comment]
Thanks Brian. There are multiple providers in the parent but each correspond to a different region. Here is how the parent (caller) looks like and the objective is to get the module called for different regions

provider "oci" {
  region = "us-ashburn-1"
  alias = "us-ashburn-1"
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  disable_auto_retries = "true"
  version = "~> 2.1"
}

provider "oci" {
  region = "eu-frankfurt-1"
  alias = "eu-frankfurt-1"
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  disable_auto_retries = "true"
  version = "~> 2.1"
}

provider "oci" {
  region = "us-phoenix-1"
  alias = "us-phoenix-1"
  tenancy_ocid = "${var.tenancy_ocid}"                                                                                                                                                               
  user_ocid = "${var.user_ocid}"                                                                                                                                                                     
  fingerprint = "${var.fingerprint}"                                                                                                                                                                 
  private_key_path = "${var.private_key_path}"                                                                                                                                                       
  disable_auto_retries = "true"                                                                                                                                                                      
  version = "~> 2.1"                                                                                                                                                                                 
}

module "vcn_phx" {
  source                = "../modules/vcn_mod"
  vcn_cidr              = "${var.vcn_cidr}"
  vcn_compartment_id    = "${var.compartment_id}"
  vcn_display_name      = "APICSPODAUTO-vcn"
  vcn_dns_label         = "APICSPODAUTO"  
//  provider_alias        = "phx"
//  provider              = "oci.phx"
  vcn_target_region     = "us-phoenix-1"
  providers =  {
          oci         = "oci.us-phoenix-1"
  }
}

module "vcn_iad" {
  source                = "../modules/vcn_mod"
  vcn_cidr              = "${var.vcn_cidr}"
  vcn_compartment_id    = "${var.compartment_id}"
  vcn_display_name      = "APICSPODAUTO-vcn"
  vcn_dns_label         = "APICSPODAUTO"
//  provider_alias        = "iad"
//  provider              = "oci.iad"
  vcn_target_region     = "us-ashburn-1"
  providers =  {
          oci         = "oci.us-ashburn-1"
  }
}

module "vcn_fra" {
  source                = "../modules/vcn_mod"
  vcn_cidr              = "${var.vcn_cidr}"
  vcn_compartment_id    = "${var.compartment_id}"
  vcn_display_name      = "APICSPODAUTO-vcn"
  vcn_dns_label         = "APICSPODAUTO"
//  provider_alias        = "fra"
//  provider              = "oci.fra"
  vcn_target_region     = "eu-frankfurt-1"
  providers =  {
          oci         = "oci.eu-frankfurt-1"
  }
}

**Comment by alexng-canuck** [comment]
Followed up offline with @RomeshSharma .

This issue was a config issue; wherein a datasource in the root config was relying on a default provider; but didn't specify one. After explicitly specifying a provider to the datasource; the issue is no longer seen.
