### ISSUE TITLE
Support for retrieving image list of different Operating Systems

### ISSUE THREAD

**Issue by elwyne-mabanglo** [oracle/terraform-provider-oci#535]
### Terraform Version

<details>

provider.null v1.0.0
provider.oci v2.1.9

</details>

### OCI Provider Version

<details>

OCI 2.1.9

</details>

### Description:
I did not find a way to retrieve a image list of Windows Server 2008 but was able to retrieve Windows Server 2012 by setting operating_system to just "Windows"

### Terraform Plan

<details>

`data "oci_core_images" "list_images" {
  compartment_id = "${var.compartment_ocid}"
  shape = "VM.Standard1.2"
  operating_system = "Windows 2008"
}`

</details>

**Comment by alexng-canuck** [comment]
Hi @elwyne-mabanglo 

There are multiple ways you can do this.

If you know the exact version of Windows that you want, you could do something like this:

```
data "oci_core_images" "list_images" {
        compartment_id = "${var.compartment_ocid}"
        shape = "VM.Standard1.2"
        operating_system = "Windows"
        operating_system_version = "Server 2008 R2"
}
```

If you don't know the exact version that you want, you could use filtering to help you explore. Like this:

```
data "oci_core_images" "list_images" {
        compartment_id = "${var.compartment_ocid}"
        shape = "VM.Standard1.2"
        operating_system = "Windows"

        filter = {
                name = "operating_system_version"
                values = ["2008"]
                regex = true
        }
}
```

**Comment by alexng-canuck** [comment]
Hi @elwyne-mabanglo , does this address your question?

**Comment by elwyne-mabanglo** [comment]
@alexng-canuck Yes this answer my question thank you!

**Comment by elwyne-mabanglo** [comment]
@alexng-canuck Yes this answer my question thank you!
