### ISSUE TITLE
Error on Init

### ISSUE THREAD

**Issue by cpruvost** [oracle/terraform-provider-oci#536]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.11.7

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:
2018/05/25 16:34:36 [INFO] terraform-provider-oci 2.1.10
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

$ \<path-to-plugin\>/terraform-provider-oci

</details>
C:\Users\chris\AppData\Roaming\terraform.d\plugins
terraform-provider-oci_v2.1.10.exe

### Description:
Include a description with repro steps, expected result and actual result

### terraform init

<details>
failed to read provider plugin C:\Users\chris\AppData\Roaming\terraform.d\plugins\terraform-provider-oci_v2.0.6.exe: open C:\Users\chris\AppData\Roaming\terraform.d\plugins\terraform-provider-oci_v2.0.6.exe: The system cannot find the file specified.

So I do not understand why terraform tried to load the old oci plugins

**Comment by alexng-canuck** [comment]
Hello @cpruvost

Can you check whether you have a `%APPDATA%/terraform.rc` file? And if so, does that file have a configuration like this?

```
providers {
  oci = "%appdata%/terraform.d/plugins/terraform-provider-oci_v2.0.6.exe"
}
```

If this setting exists, then it will override the plugin that Terraform uses during `init` command.

**Comment by cpruvost** [comment]
yes perfect ..ty very much..it runs now.
