### ISSUE TITLE
how to create instance when image and VCN are in different compartment

### ISSUE THREAD

**Issue by ttsharma** [oracle/terraform-provider-oci#537]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.9.9

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

linux_386/terraform-provider-oci_v2.0.7

### Description:
How do I create a tf plan for create an instance when image and network are in different compartments
The create instance tf example has just one placeholder for compartment_id which should be that of instance, where do I mention the compartment id of VCN / Subnet?

I can do this from console.

### Terraform Plan

NA
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

NA

**Comment by alexng-canuck** [comment]
Hi @ttsharma 

When you create an instance, you only need to specify the ID for the subnet. This ID can be for any subnet in any compartment within your tenancy. The compartment id is not necessary, because it is only needed when creating the subnet.

The above also is true for images.

So the example with subnet and instance in different compartments would look like this:

```
variable subnet_compartment_id = {}

variable instance_compartment_id = {}

resource "oci_core_subnet" "ExampleSubnet" {
  compartment_id = "${var.subnet_compartment_id}"
  vcn_id = "${oci_core_virtual_network.ExampleVCN.id}"
  route_table_id = "${oci_core_route_table.ExampleRT.id}"
  dhcp_options_id = "${oci_core_virtual_network.ExampleVCN.default_dhcp_options_id}"
}

resource "oci_core_instance" "TFInstance" {
  compartment_id = "${var.instance_compartment_id}"
  display_name = "TFInstance${count.index}"
  shape = "${var.InstanceShape}"

  create_vnic_details {
    subnet_id = "${oci_core_subnet.ExampleSubnet.id}"
    display_name = "primaryvnic"
    assign_public_ip = true
    hostname_label = "tfexampleinstance${count.index}"
  }
}
```
