### ISSUE TITLE
Terraform stuck in waiting data.oci_objectstorage_objects

### ISSUE THREAD

**Issue by pblahaorcl** [oracle/terraform-provider-oci#544]
### Terraform Version

# Run this command to get the terraform version:

$ terraform -v

bash-4.2# terraform -v
2018/06/15 13:00:26 [INFO] Terraform version: 0.11.7  
2018/06/15 13:00:26 [INFO] Go runtime version: go1.9beta2
2018/06/15 13:00:26 [INFO] CLI args: []string{"/usr/bin/terraform", "-v"}
2018/06/15 13:00:26 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2018/06/15 13:00:26 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/06/15 13:00:26 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.11.7
2018/06/15 13:00:26 [DEBUG] checking for provider in "."
2018/06/15 13:00:26 [DEBUG] checking for provider in "/usr/bin"
2018/06/15 13:00:26 [DEBUG] found provider "terraform-provider-oci_v2.1.12"
2018/06/15 13:00:26 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2018/06/15 13:00:26 [DEBUG] checking for provider in "/root/.terraform.d/plugins"
2018/06/15 13:00:26 [DEBUG] found valid plugin: "oci", "2.1.12", "/usr/bin/terraform-provider-oci_v2.1.12"
2018/06/15 13:00:26 [DEBUG] plugin: waiting for all plugin processes to complete...
+ provider.oci v2.1.12

### Description:
Include a description with repro steps, expected result and actual result

### Terraform Plan

<details>
resource "oci_objectstorage_namespace_metadata" "namespace-metadata1" {
  namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
  default_s3compartment_id = "${oci_identity_compartment.Build.id}"
  default_swift_compartment_id = "${oci_identity_compartment.Build.id}"
}

resource "oci_objectstorage_bucket" "bucket1" {
  compartment_id = "${oci_identity_compartment.Build.id}"
  namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
  name = "bdsql-bucket"
  access_type = "NoPublicAccess"
}

resource "oci_objectstorage_object" "object1" {
  namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
  bucket = "${oci_objectstorage_bucket.bucket1.name}"
  object = "config.json"
  content_language = "en-US"
  content_type = "application/json"
  content = "${file("config.json")}"
}

resource "oci_objectstorage_preauthrequest" "bucket-par" {
  namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
  bucket = "${oci_objectstorage_bucket.bucket1.name}"
  name = "parOnBucket"
  access_type = "AnyObjectWrite" //Other configurations accepted are ObjectWrite, ObjectReadWrite
  time_expires = "2020-12-10T23:00:00Z"
}

resource "oci_objectstorage_preauthrequest" "object-par" {
  namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
  bucket = "${oci_objectstorage_bucket.bucket1.name}"
  object = "${oci_objectstorage_object.object1.object}"
  name = "object-par"
  access_type = "ObjectRead" // ObjectRead, ObjectWrite, ObjectReadWrite, AnyObjectWrite
  time_expires = "2020-12-29T23:00:00Z"
}

data "oci_objectstorage_namespace" "ns" {
}

data oci_objectstorage_namespace_metadata namespace-metadata1 {
  namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
}

data "oci_objectstorage_bucket_summaries" "buckets1" {
  compartment_id = "${oci_identity_compartment.Build.id}"
  namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
  filter {
    name = "name"
    values = ["${oci_objectstorage_bucket.bucket1.name}"]
  }
}

data "oci_objectstorage_object_head" "object-head1" {
  namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
  bucket = "${oci_objectstorage_bucket.bucket1.name}"
  object = "${oci_objectstorage_object.object1.object}"
}

data "oci_objectstorage_objects" "objects1" {
  namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
  bucket = "${oci_objectstorage_bucket.bucket1.name}"
}

output namespace {
  value = "${data.oci_objectstorage_namespace.ns.namespace}"
}

output namespace-metadata {
  value = <<EOF
  namespace = ${data.oci_objectstorage_namespace_metadata.namespace-metadata1.namespace}
  default_s3compartment_id = ${data.oci_objectstorage_namespace_metadata.namespace-metadata1.default_s3compartment_id}
  default_swift_compartment_id = ${data.oci_objectstorage_namespace_metadata.namespace-metadata1.default_swift_compartment_id}
EOF
}

output buckets {
  value = "${data.oci_objectstorage_bucket_summaries.buckets1.bucket_summaries}"
}

output object-head-data {
  value = <<EOF
  object = ${data.oci_objectstorage_object_head.object-head1.object}
  content-length = ${data.oci_objectstorage_object_head.object-head1.content-length}
  content-type = ${data.oci_objectstorage_object_head.object-head1.content-type}
EOF
}

output objects {
  value = "${data.oci_objectstorage_objects.objects1.objects}"
}

output "par_request_url" {
  value = "https://objectstorage.${var.region}.oraclecloud.com${oci_objectstorage_preauthrequest.object-par.access_uri}"
}
</details>

Running terraform plan with above file but terraform is stuck:

2018/06/15 12:57:31 [TRACE] [walkRefresh] Exiting eval tree: output.EtcdPublicIPs
2018/06/15 12:57:34 [TRACE] dag/walk: vertex "output.objects", waiting for: "data.oci_objectstorage_objects.objects1"
2018/06/15 12:57:34 [TRACE] dag/walk: vertex "output.object-head-data", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:36 [TRACE] dag/walk: vertex "root", waiting for: "output.object-head-data"
2018/06/15 12:57:36 [TRACE] dag/walk: vertex "provider.oci (close)", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:39 [TRACE] dag/walk: vertex "output.objects", waiting for: "data.oci_objectstorage_objects.objects1"
2018/06/15 12:57:39 [TRACE] dag/walk: vertex "output.object-head-data", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:41 [TRACE] dag/walk: vertex "provider.oci (close)", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:41 [TRACE] dag/walk: vertex "root", waiting for: "output.object-head-data"
2018/06/15 12:57:44 [TRACE] dag/walk: vertex "output.object-head-data", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:44 [TRACE] dag/walk: vertex "output.objects", waiting for: "data.oci_objectstorage_objects.objects1"
2018/06/15 12:57:46 [TRACE] dag/walk: vertex "provider.oci (close)", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:46 [TRACE] dag/walk: vertex "root", waiting for: "output.object-head-data"
2018/06/15 12:57:49 [TRACE] dag/walk: vertex "output.objects", waiting for: "data.oci_objectstorage_objects.objects1"
2018/06/15 12:57:49 [TRACE] dag/walk: vertex "output.object-head-data", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:51 [TRACE] dag/walk: vertex "root", waiting for: "output.object-head-data"
2018/06/15 12:57:51 [TRACE] dag/walk: vertex "provider.oci (close)", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:54 [TRACE] dag/walk: vertex "output.object-head-data", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:54 [TRACE] dag/walk: vertex "output.objects", waiting for: "data.oci_objectstorage_objects.objects1"
2018/06/15 12:57:56 [TRACE] dag/walk: vertex "root", waiting for: "output.object-head-data"
2018/06/15 12:57:56 [TRACE] dag/walk: vertex "provider.oci (close)", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:57:59 [TRACE] dag/walk: vertex "output.objects", waiting for: "data.oci_objectstorage_objects.objects1"
2018/06/15 12:57:59 [TRACE] dag/walk: vertex "output.object-head-data", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:58:01 [TRACE] dag/walk: vertex "provider.oci (close)", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:58:01 [TRACE] dag/walk: vertex "root", waiting for: "output.object-head-data"
2018/06/15 12:58:04 [TRACE] dag/walk: vertex "output.object-head-data", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:58:04 [TRACE] dag/walk: vertex "output.objects", waiting for: "data.oci_objectstorage_objects.objects1"
2018/06/15 12:58:06 [TRACE] dag/walk: vertex "root", waiting for: "output.object-head-data"
2018/06/15 12:58:06 [TRACE] dag/walk: vertex "provider.oci (close)", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:58:09 [TRACE] dag/walk: vertex "output.object-head-data", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:58:09 [TRACE] dag/walk: vertex "output.objects", waiting for: "data.oci_objectstorage_objects.objects1"
2018/06/15 12:58:11 [TRACE] dag/walk: vertex "root", waiting for: "output.object-head-data"
2018/06/15 12:58:11 [TRACE] dag/walk: vertex "provider.oci (close)", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:58:14 [TRACE] dag/walk: vertex "output.object-head-data", waiting for: "data.oci_objectstorage_object_head.object-head1"
2018/06/15 12:58:14 [TRACE] dag/walk: vertex "output.objects", waiting for: "data.oci_objectstorage_objects.objects1"
2018/06/15 12:58:16 [TRACE] dag/walk: vertex "root", waiting for: "output.object-head-data"
2018/06/15 12:58:16 [TRACE] dag/walk: vertex "provider.oci (close)", waiting for: "data.oci_objectstorage_object_head.object-head1"
^CInterrupt received.

It seems the issue is in data for data.oci_objectstorage_object_head and data.oci_objectstorage_objects for case when the object doesn't exist yet. 
I removed data/output and then was able to run terraform plan sucesfully.

**Comment by alexng-canuck** [comment]
Hi @pblahaorcl ,

For the data sources that are waiting on results from resources; can you try adding the `depends_on` attribute? This ensures that the resource is created before the data source queries the results.

For example:
```
data "oci_objectstorage_objects" "objects1" {
depends_on = ["oci_objectstorage_bucket.bucket1", "oci_objectstorage_object.object1"]
namespace = "${data.oci_objectstorage_namespace.ns.namespace}"
bucket = "${oci_objectstorage_bucket.bucket1.name}"
}
```

A possible reason you have seen it stuck waiting on data sources is because the bucket might not exist yet; and so it was spinning waiting for it to be created. Adding the `depends_on` helps address this.

**Comment by pblahaorcl** [comment]
Hi @alexng-canuck, 
adding dependency resolved the issue.

Thanks,

Petr
