### ISSUE TITLE
Support for Service Gateway

### ISSUE THREAD

**Issue by skripted** [oracle/terraform-provider-oci#546]
Do we have support for the following? 

1. Service Gateway
2. Updating boot volume backup policy
3. Creating Volume groups and setting backup policy ?

**Comment by codycushing** [comment]
Hello, version 2.1.13 of the provider adds support for 2) and 3).

Service Gateways will be supported soon.

**Comment by rcohenma** [comment]
Hello, version 2.1.15 of the provider adds support for Service Gateways
