### ISSUE TITLE
Intermittent issue attaching multiple volumes to instance

### ISSUE THREAD

**Issue by rajesh-chawla** [oracle/terraform-provider-oci#547]
### Terraform Version

Terraform v0.11.7
+ provider.oci v2.1.12
+ provider.template v1.0.0

### OCI Provider Version

2018/06/23 11:23:37 [INFO] terraform-provider-oci 2.1.12

### Description:
Use case: To create a RAID configured volumes for multiple instances in OCI. To do this, I want to attach multiple volumes to an instance in terraform.
 
Issue: When execute terraform apply, I *sometimes* get the error below. If I add the option '-parallelism=1', I get no error. The occasional error causes issues for automating tests.

Error: Error applying plan:

1 error(s) occurred:
* oci_core_volume_attachment.linux_blocks_attach[1]: 1 error(s) occurred:
* oci_core_volume_attachment.linux_blocks_attach.1: Service error:Conflict. Volume ocid1.volume.oc1.iad.abuwcljsjnavdtcv3sfbs4aiu6bxcfakbrx24m4wyyvk6yntkpvkxgwdfhqq currently attached. http status code: 409

### Terraform Plan

A self contained .tf file that has a repro is attached.

[vm.tf.zip](https://github.com/oracle/terraform-provider-oci/files/2130088/vm.tf.zip)

**Comment by parweza** [comment]
Thanks for the detailed tf file. I was able to reproduce the issue with provided config. The initial investigation point to server side issue. I have filed an issue on the service owner and following up  with them. Will keep you posted on the progress.

**Comment by alexng-canuck** [comment]
Hi @rajesh-chawla , 

In the meantime; you can ensure that retries are enabled. This will help ensure that if Terraform encountered a 409 from the service; that it will try attaching it again for some time until it succeeds.

You can do this by removing the `disable_auto_retries` attribute from the `provider` block of your config (or setting this attribute to "false").

**Comment by rajesh-chawla** [comment]
After removing 'disable_auto_retries' from the provider, I had 10 successful runs of creating and destroying resources from terraform and terratest.

**Comment by alexng-canuck** [comment]
Thanks for getting back to us. I will close this issue then. Let us know if you see this issue again.
