### ISSUE TITLE
Add support for tagging load balancer resources

### ISSUE THREAD

**Issue by jhorwit2** [oracle/terraform-provider-oci#549]
https://docs.cloud.oracle.com/iaas/releasenotes/changes/9ced7d70-005a-4aa1-a47a-213dd8d2dcad/

**Comment by parweza** [comment]
Thanks for the feedback. I have added this to our backlog to help us prioritize this for upcoming releases of the provider.

**Comment by rcohenma** [comment]
support for tagging in the load balancer service was added in v2.2.0
https://github.com/oracle/terraform-provider-oci/releases/tag/v2.2.0
