### ISSUE TITLE
terraform panic when data.oci_core_subnets receives unexpected argument

### ISSUE THREAD

**Issue by keithhopkins-gpc** [oracle/terraform-provider-oci#550]
### Terraform Version

Terraform v0.11.7
+ provider.oci v2.1.13

### OCI Provider Version

2018/07/06 16:31:01 [INFO] terraform-provider-oci 2.1.13
This binary is a plugin....

### Description:
* module.services-subnet.data.oci_core_subnets.services_subnet[0]: unexpected EOF
* module.services-subnet.data.oci_core_subnets.services_subnet[1]: unexpected EOF

2018/07/06 16:27:08 [ERROR] root.services-subnet: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2018/07/06 16:27:08 [ERROR] root.services-subnet: eval: *terraform.EvalSequence, err: unexpected EOF
2018/07/06 16:27:08 [TRACE] [walkRefresh] Exiting eval tree: module.services-subnet.data.oci_core_subnets.services_subnet[0]
2018/07/06 16:27:08 [ERROR] root.services-subnet: eval: *terraform.EvalReadDataDiff, err: unexpected EOF
2018/07/06 16:27:08 [ERROR] root.services-subnet: eval: *terraform.EvalSequence, err: unexpected EOF
2018/07/06 16:27:08 [TRACE] [walkRefresh] Exiting eval tree: module.services-subnet.data.oci_core_subnets.services_subnet[1]
2018/07/06 16:27:08 [TRACE] dag/walk: upstream errored, not walking "root"
2018/07/06 16:27:08 [TRACE] dag/walk: upstream errored, not walking "module.services-subnet.output.modules_subnets"
2018/07/06 16:27:08 [TRACE] dag/walk: upstream errored, not walking "provider.oci (close)"
2018/07/06 16:27:08 [TRACE] dag/walk: upstream errored, not walking "root"

panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
Changed 
from:
vcn_id         = "${lookup(data.oci_core_vcns.core.virtual_networks,"id")}"
to
vcn_id = "${data.oci_core_vcns.core.virtual_networks}"
in following code snippet, because terraform complained it was getting a list, but expecting a map.

By commenting out the 'data "oci_core_subnets" "services_subnet"' section below, and an "output" section displaying that data item, the full code/plan will apply.

### Terraform Plan

in a module's data.tf:
```
data "oci_identity_availability_domains" "core" {
  #Required
  compartment_id = "${var.tenancy_ocid}"
}
data "oci_core_vcns" "core" {
  #Required
  compartment_id = "${var.compartment_id}"
  #Optional
  display_name = "${local.prefix}-vcn"
  # state = "${var.vcn_state}"
}
data "oci_core_subnets" "services_subnet" {
  count = 2
  #Required
  compartment_id = "${var.compartment_id}"
  # vcn_id         = "${lookup(data.oci_core_vcns.core.virtual_networks,"id")}"
  vcn_id = "${data.oci_core_vcns.core.virtual_networks}"
  #Optional
  display_name = "${local.prefix}-services_subnet${count.index}"
}
```

**Comment by parweza** [comment]
virtual_networks  is  List of VCN Resource https://github.com/oracle/terraform-provider-oci/blob/master/provider/core_vcns_data_source.go#L41.

To access id of a particular VCN you need to first you need to access that vcn. for example if you want to get id of the first VCN returned by data source 
```hcl
data "oci_core_subnets" "services_subnet" {
  count = 2
  #Required
  compartment_id = "${var.compartment_id}"
   vcn_id         = "${lookup(data.oci_core_vcns.core.virtual_networks[0],"id")}"
  # vcn_id = "${data.oci_core_vcns.core.virtual_networks}"
  #Optional
  display_name = "${local.prefix}-services_subnet${count.index}"
}
```
