### ISSUE TITLE
oci_core_instance.TFInstance: Service error:InvalidParameter. Invalid format for ssh public key. http status code: 400

### ISSUE THREAD

**Issue by saiindian2** [oracle/terraform-provider-oci#554]
### Terraform Version

v0.11.7

### OCI Provider Version

provider.oci v2.1.12.

### Description:
I tried to run the terraform files present in examples ->compute -> Instance.
I have configured api keys successfully.

I generated ssh keys using puttygen as I am working on windows 10 laptop

In the variables.tf file,
I have updated the ssh keys variables as below 

variable "ssh_public_key" { default = "D:\terraform\terraform-provider-oci\docs\examples\compute\instance\oci.pub" }
variable "ssh_private_key" { default = "D:\terraform\terraform-provider-oci\docs\examples\compute\instance\oci.ppk" }

when I did terraform apply , I am facing below error

Error: Error applying plan:

1 error(s) occurred:

    oci_core_instance.TFInstance: 1 error(s) occurred:

    oci_core_instance.TFInstance: Service error:InvalidParameter. Invalid format for ssh public key. http status code: 400

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Note: with the same public key I am able to create instance using the OCI console.

### Terraform Plan

variable "tenancy_ocid" { }
variable "user_ocid" {  }
variable "fingerprint" { }
variable "private_key_path" {  }
variable "region" { default = "us-ashburn-1" }

variable "compartment_ocid" {  }
variable "ssh_public_key" { default =  "D:\\terraform\\terraform-provider-oci\\docs\\examples\\compute\\instance\\oci-public.pub" }
#variable "ssh_private_key" { default =  "D:\\terraform\\terraform-provider-oci\\docs\\examples\\compute\\instance\\oci.ppk" }

# Defines the number of instances to deploy
variable "NumInstances" {
    default = "1"
}

# Defines the number of volumes to create and attach to each instance
# NOTE: Changing this value after applying it could result in re-attaching existing volumes to different instances.
# This is a result of using 'count' variables to specify the volume and instance IDs for the volume attachment resource.
variable "NumIscsiVolumesPerInstance" {
    default = "2"
}

variable "NumParavirtualizedVolumesPerInstance" {
    default = "2"
}

# Choose an Availability Domain
variable "AD" {
    default = "1"
}

variable "InstanceShape" {
    default = "VM.Standard1.2"
}

variable "InstanceImageOCID" {
   # type = "map"
    default = {
        // See https://docs.us-phoenix-1.oraclecloud.com/images/
        // Oracle-provided image "Oracle-Linux-7.4-2018.02.21-1"
       # us-phoenix-1 = "ocid1.image.oc1.phx.aaaaaaaaupbfz5f5hdvejulmalhyb6goieolullgkpumorbvxlwkaowglslq"
        us-ashburn-1 = "ocid1.image.oc1.iad.aaaaaaaajlw3xfie2t5t52uegyhiq2npx7bqyu4uvi2zyu3w3mqayc2bxmaa"
       # eu-frankfurt-1 = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa7d3fsb6272srnftyi4dphdgfjf6gurxqhmv6ileds7ba3m2gltxq"
        #uk-london-1 = "ocid1.image.oc1.uk-london-1.aaaaaaaaa6h6gj6v4n56mqrbgnosskq63blyv2752g36zerymy63cfkojiiq"
    }
}

variable "DBSize" {
    default = "50" // size in GBs
}

variable "BootStrapFile" {
    default = "./userdata/bootstrap"
}

**Comment by Gestas** [comment]
@saiindian2 Did you use the process described [here](https://docs.cloud.oracle.com/iaas/Content/GSG/Tasks/creatingkeys.htm) to create your key? Specifically step 5 in "Creating an SSH Key Pair on Windows Using PuTTY Key Generator". You can't use the "Save public key" button, you need to use the text above.

**Comment by codycushing** [comment]
Hello, it looks like you may be passing _the path_ of your key to a field which is expecting the actual key file **contents**. If you look in that example's `env-vars` file, you will see the entry for `ssh_public_key` demonstrating how you can include the key's contents: 
```export TF_VAR_ssh_public_key=$(cat <path to public key>)```

**Comment by saiindian2** [comment]
Thank you, I am actually working on these examples on a windows machine. 
Appreciate if there are instructions with respect to OS for beginners so that they are kept aware of the changes.
