### ISSUE TITLE
provider.oci: fork/exec ~/.terraform.d/plugins/terraform-provider-oci_v2.1.13: exec format error

### ISSUE THREAD

**Issue by kjm0001** [oracle/terraform-provider-oci#556]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

```Terraform v0.11.7```

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

```+ provider.oci v2.1.13```
</details>

### Description:
Include a description with repro steps, expected result and actual result
Trying to use the db_systems in the examples directory. I updated the env-vars. The terraform plan fails on the var.subnet_ocid. In my env-vars I have this, although this var name doesn't seem to match the rest of the tf files. 
```
##Specific to this example
### Choose a subnet that exists in the AD and compartment you are launching the instance in
export TF_VAR_SubnetOCID="ocid1.subnet.oc1.iad.aaaaaaaauuwngq6li4k2xermjqopo47i5ehw6fcqt3osuuy5goumvnd63xeq"

I performed a terraform init

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.oci: version = "~> 2.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

### Terraform Plan

I attempted the terraform plan and it failed exec format error on  var.subnet_ocid. 

<details>

```terraform plan

var.subnet_ocid
  Enter a value: ocid1.subnet.oc1.iad.aaaaaaaauuwngq6li4k2xermjqopo47i5ehw6fcqt3osuuy5goumvnd63xeq

Error: Error asking for user input: 1 error(s) occurred:

* provider.oci: fork/exec ~/.terraform.d/plugins/terraform-provider-oci_v2.1.13: exec format error
```
</details>

**Comment by kjm0001** [comment]
I decided to use another linux variant and was able to get past this issue. I also changed the subnet var in the env-vars to match the var.subnet_ocid as well.

**Comment by codycushing** [comment]
For our info, which provider binary were you trying to use on which linux OS?
