### ISSUE TITLE
In Provider version 2.1.14, updates to a Route Table's Route Rules (when they contain a rule that includes a Service Gateway ID) fail with a 400 service error code

### ISSUE THREAD

**Issue by codycushing** [oracle/terraform-provider-oci#558]
### Terraform Version

<details>
any
</details>

### OCI Provider Version

<details>
2.1.14
</details>

### Description:
This bug was discovered shortly after the release of v2.1.14. A fix is available in v2.1.15, see the [releases page](https://github.com/oracle/terraform-provider-oci/releases) for the [latest build](https://github.com/oracle/terraform-provider-oci/releases/latest)

**Comment by alexng-canuck** [comment]
@codycushing closing this as it seems to have been fixed.
