### ISSUE TITLE
Add a custom destroy provider

### ISSUE THREAD

**Issue by hyder** [oracle/terraform-provider-oci#568]
### Terraform Version

0.11.7

### OCI Provider Version

2.1.16

</details>

### Description:
When working with OKE, an OCI Load Balancer may sometimes be created by K8s. However, tfstate is unaware of it. As such, running a destroy will fail.

### Terraform Plan

<details>
1 way to handle this would be to add a custom destroy provider that would allow running a either a local or remote exec and run a script that would issue the command to destroy the LB, perhaps through the oci-cli.

This would also help in other clean up tasks e.g. orphaned mount targets.
</details>

**Comment by codycushing** [comment]
Interesting idea, can you explain how supporting this through Terraform as a provider would be an improvement over say a script or util for the same? The workflow of changing your plan to enable such a mechanism seems less fluid than simply invoking a tool without altering your configuration files.

**Comment by parweza** [comment]
Hi @hyder,
Terraform already provides hooks through provisioners to  run script locally and/or remotely before destroying any resource.  You can achieve what you are asking  by running delete script as mentioned above and add implicit dependency on vcn resource that you created.

```hcl 
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}

provider "oci" {
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region           = "${var.region}"
}

resource "oci_core_virtual_network" "vcn1" {
  cidr_block     = "10.0.0.0/16"
  dns_label      = "vcn1"
  compartment_id = "${var.compartment_ocid}"
  display_name   = "vcn1"

}

resource "null_resource" "destroy_hook" {
  depends_on = ["oci_core_virtual_network.vcn1"]
  provisioner "local-exec" {
    command = "echo 'privisonar called'"
    when = "destroy"
  }
}
```

**Comment by hyder** [comment]
My delete script needs to run as a remote-exec. So that wouldn't work.

**Comment by parweza** [comment]
@hyder I have given local exec as an example and you can use any provisionor you want   including remote exec remote-exec

**Comment by hyder** [comment]
Ok let me try this. Can you please keep it open?

**Comment by parweza** [comment]
@hyder Can you please confirm if that answers your question and we can close this issue?
