### ISSUE TITLE
OCI Provider Service Error:NotAuthenticated

### ISSUE THREAD

**Issue by geeshans** [oracle/terraform-provider-oci#571]
### Terraform Version

```
terraform -v
Terraform v0.11.7
+ provider.oci v2.1.3

```

### Terraform Configuration Files

```
# Gets a list of Availability Domains

data "oci_identity_availability_domains" "ADs" {
  compartment_id = "${var.tenancy_ocid}"
}

```

### Debug Output

https://gist.github.com/geeshans/c5231c1f6b6f98d99c3046652ab71583

### Expected Behavior

Terraform to apply successfully
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
### Additional Context

I have already double checked the 
  tenancy_ocid 
  user_ocid 
  fingerprint 
  private_key_path
  region

**Comment by jbolla** [comment]
Can you check whether your system's clock is in sync? The observed behavior can result from a difference of over five minutes between the clocks on your system and on the service.

https://docs.cloud.oracle.com/iaas/Content/API/Concepts/usingapi.htm#Maximum

**Comment by geeshans** [comment]
Apparently `private_key_password` was also set but not being passed to the oci provider. Passing this with the other variables sorted this issue. Would be nice if the the error message or the trace logs was more informative.  
Thanks for your time! Cheers!
