### ISSUE TITLE
Listing IP addresses of Multiple DBS, if count = n.

### ISSUE THREAD

**Issue by nirmalpathak** [oracle/terraform-provider-oci#572]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.11.7
+ provider.null v1.0.0
+ provider.oci v2.1.15
+ provider.template v1.0.0
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
provider.oci v2.1.15

</details>

### Description:

I am able to get the output of IP of DBS RAC, if count=1 from present DB System example but it doesn't work if I have DB count greater than 1 in DBS resource, e.g.

**Reproduce Steps:**
Add count variable in resource "oci_database_db_system" & set its value greater than 1.

```
resource "oci_database_db_system" "dbs" {
 count               = "2"
..
}
```

**Expected Results**
```
DBSHostnames = [
    dbs1,
    dbs2
]
DBSPrivateIPs = [
    172.16.0.2
    172.16.0.5
]
```

**Actual Results**
```
DBSHostnames = [
    dbs1,
    dbs2
]
DBSPrivateIPs = [
    172.16.0.2
]
```

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

  ~ module.create_db.data.oci_core_vnic.DBNodeVnic
      id:                                      "" => <computed>
      availability_domain:                     "" => <computed>
      compartment_id:                          "" => <computed>
      display_name:                            "" => <computed>
      freeform_tags.%:                         "" => <computed>
      hostname_label:                          "" => <computed>
      is_primary:                              "" => <computed>
      mac_address:                             "" => <computed>
      private_ip_address:                      "" => <computed>
      public_ip_address:                       "" => <computed>
      skip_source_dest_check:                  "" => <computed>
      state:                                   "" => <computed>
      subnet_id:                               "" => <computed>
      time_created:                            "" => <computed>
      vnic_id:                                 "" => "${element(data.oci_database_db_node.DBNodeDetails.*.vnic_id, count.index)}"

  ~ module.create_db.data.oci_database_db_node.DBNodeDetails
      id:                                      "" => <computed>
      backup_vnic_id:                          "" => <computed>
      db_node_id:                              "" => "${lookup(data.oci_database_db_nodes.DBNodeList.db_nodes[count.index], \"id\")}"
      db_system_id:                            "" => <computed>
      hostname:                                "" => <computed>
      software_storage_size_in_gb:             "" => <computed>
      state:                                   "" => <computed>
      time_created:                            "" => <computed>
      vnic_id:                                 "" => <computed>

 <= module.create_db.data.oci_database_db_nodes.DBNodeList
      id:                                      <computed>
      compartment_id:                          "ocid1.compartment.oc1..aaaaaaaagwemgjhjgb5g4jye2p7gahc2i3zqrspakh743wnstldn36bx3u7a"
      db_nodes.#:                              <computed>
      db_system_id:                            "${element(oci_database_db_system.jdedb.*.id, count.index)}"

  + module.create_db.null_resource.remote-exec
      id:                                      <computed>

  + module.create_db.oci_database_db_system.jdedb[0]
      id:                                      <computed>
      availability_domain:                     "IAUF:PHX-AD-3"
      backup_subnet_id:                        <computed>
      cluster_name:                            <computed>
      compartment_id:                          "ocid1.compartment.oc1..aaaaaaaagwemgjhjgb5g4jye2p7gahc2i3zqrspakh743wnstldn36bx3u7a"
      cpu_core_count:                          "4"
      data_storage_percentage:                 <computed>
      data_storage_size_in_gb:                 "256"
      database_edition:                        "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"
      db_home.#:                               "1"
      db_home.0.database.#:                    "1"
      db_home.0.database.0.admin_password:     <sensitive>
      db_home.0.database.0.character_set:      "AL32UTF8"
      db_home.0.database.0.db_backup_config.#: <computed>
      db_home.0.database.0.db_name:            "JDECDB"
      db_home.0.database.0.db_workload:        "OLTP"
      db_home.0.database.0.ncharacter_set:     "AL16UTF16"
      db_home.0.database.0.pdb_name:           "JDEDB"
      db_home.0.db_version:                    "12.1.0.2"
      db_home.0.display_name:                  "JDECDB"
      disk_redundancy:                         "NORMAL"
      display_name:                            "npjdedbpho1"
      domain:                                  <computed>
      freeform_tags.%:                         <computed>
      hostname:                                "npjdedbpho1"
      last_patch_history_entry_id:             <computed>
      license_model:                           "LICENSE_INCLUDED"
      lifecycle_details:                       <computed>
      listener_port:                           <computed>
      node_count:                              "2"
      reco_storage_size_in_gb:                 <computed>
      scan_dns_record_id:                      <computed>
      scan_ip_ids.#:                           <computed>
      shape:                                   "VM.Standard1.2"
      source:                                  <computed>
      ssh_public_keys.#:                       "1"
      ssh_public_keys.0:                       "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7CT9SgWXjy0spFsLHEewgAnn1KHahXhxtaPJMocBtVH6QpiHgIzOtWOROKwcKDwiPDU4SU8x4cZJwwc5/x+XLO3h7ZhGh+VmXNbzakammCxMSlZAKwWvUdVcFFT0OhOwSr43gYz2Z3Q1MWBJHsOONRg9IyXmrSZQz51rB+PUuhYyvD24DqCmFjuTX1b8e/plhaBUZl6JmQ71CgZi6219+CRPOTa+OmhdzCIB4ORkLvRc3wlcKqkJPupur5M2C8onZgGD3WQc3EnEtHdYn+vKnE48cZsKBn9dH63W8jrMQXjNJ7K7R8Iz/RJl1VrVzWH5+z58AeSRV+TXDwqgTo1Vh ndpathak@ndpathak-mac"
      state:                                   <computed>
      subnet_id:                               "ocid1.subnet.oc1.phx.aaaaaaaaeexqxt3szy2twsqxkaezmgrjb6p3gkkkl4sov6ngqahbhq35k22q"
      time_created:                            <computed>
      version:                                 <computed>
      vip_ids.#:                               <computed>

  + module.create_db.oci_database_db_system.jdedb[1]
      id:                                      <computed>
      availability_domain:                     "IAUF:PHX-AD-3"
      backup_subnet_id:                        <computed>
      cluster_name:                            <computed>
      compartment_id:                          "ocid1.compartment.oc1..aaaaaaaagwemgjhjgb5g4jye2p7gahc2i3zqrspakh743wnstldn36bx3u7a"
      cpu_core_count:                          "4"
      data_storage_percentage:                 <computed>
      data_storage_size_in_gb:                 "256"
      database_edition:                        "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"
      db_home.#:                               "1"
      db_home.0.database.#:                    "1"
      db_home.0.database.0.admin_password:     <sensitive>
      db_home.0.database.0.character_set:      "AL32UTF8"
      db_home.0.database.0.db_backup_config.#: <computed>
      db_home.0.database.0.db_name:            "JDECDB"
      db_home.0.database.0.db_workload:        "OLTP"
      db_home.0.database.0.ncharacter_set:     "AL16UTF16"
      db_home.0.database.0.pdb_name:           "JDEDB"
      db_home.0.db_version:                    "12.1.0.2"
      db_home.0.display_name:                  "JDECDB"
      disk_redundancy:                         "NORMAL"
      display_name:                            "npjdedbpho2"
      domain:                                  <computed>
      freeform_tags.%:                         <computed>
      hostname:                                "npjdedbpho2"
      last_patch_history_entry_id:             <computed>
      license_model:                           "LICENSE_INCLUDED"
      lifecycle_details:                       <computed>
      listener_port:                           <computed>
      node_count:                              "2"
      reco_storage_size_in_gb:                 <computed>
      scan_dns_record_id:                      <computed>
      scan_ip_ids.#:                           <computed>
      shape:                                   "VM.Standard1.2"
      source:                                  <computed>
      ssh_public_keys.#:                       "1"
      ssh_public_keys.0:                       "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7CT9SgWXjy0spFsLHEewgAnn1KHahXhxtaPJMocBtVH6QpiHgIzOtWOROKwcKDwiPDU4SU8x4cZJwwc5/x+XLO3h7ZhGh+VmXNbzakammCxMSlZAKwWvUdVcFFT0OhOwSr43gYz2Z3Q1MWBJHsOONRg9IyXmrSZQz51rB+PUuhYyvD24DqCmFjuTX1b8e/plhaBUZl6JmQ71CgZi6219+CRPOTa+OmhdzCIB4ORkLvRc3wlcKqkJPupur5M2C8onZgGD3WQc3EnEtHdYn+vKnE48cZsKBn9dH63W8jrMQXjNJ7K7R8Iz/RJl1VrVzWH5+z58AeSRV+TXDwqgTo1Vh ndpathak@ndpathak-mac"
      state:                                   <computed>
      subnet_id:                               "ocid1.subnet.oc1.phx.aaaaaaaaeexqxt3szy2twsqxkaezmgrjb6p3gkkkl4sov6ngqahbhq35k22q"
      time_created:                            <computed>
      version:                                 <computed>
      vip_ids.#:                               <computed>

Plan: 3 to add, 2 to change, 0 to destroy.

------------------------------------------------------------------------

</details>

**Comment by rcohenma** [comment]
Sorry it took so long for us to respond.

You didn't include your tf config so i can't talk about the specific code you are using.

I tried doing it myself though and unfortunately due to current limitations of terraform i don't think it is possible to use count in this case.

You can use count for db_system resource but i don't think you can use count to get the IPs.

To get the IPs requires listing the db_nodes by db_system_id to get the vnic_id 
you would then use the vnic datasource to get the IPs

The problem is adding the count to db_nodes datasource creates an array of maps that includes an array of maps. 
As far as I know Terraform has limitations that don't allow you to access the vnic_id inside this complex structure.
element() does not allow you to access an element in an array of complex structures
lookup() does not allow you to get an value for a key in a map if that map is not a flat map
you cannot use consecutive [] to access elements from arrays and maps
https://github.com/hashicorp/terraform/issues/8047

They say they are working on it but for now you will need to have one db_nodes datasource per db_system you have.
