### ISSUE TITLE
deprecated cidr_block -- what version will eliminate support?

### ISSUE THREAD

**Issue by MarkPinkston-OTA** [oracle/terraform-provider-oci#575]
I just have a question on versioning, maybe I'm not looking in the right places.

1) We are getting the deprecation messages for cidr_block in favor of destination, what version of the provider will prevent those commands from being run?  We want to be aware of how much time we have to make changes to our current code without fearing it simply won't run.

2) Would it be okay to give the version a specific resource is introduced in?  That way if we need a specific resource, we can quickly determine which version is required?

**Comment by jbolla** [comment]
1. We have not yet determined the precise version of the provider that will discontinue support for cidr_block.
2. The changelog at [../blob/master/CHANGELOG.md](../blob/master/CHANGELOG.md) contains a record of the changes introduced with each version. Does it contain the information you are seeking?

**Comment by MarkPinkston-OTA** [comment]
Hi Jason,

Thanks for the quick response.  As for #2, it is true you can reverse through the CHANGELOG, but it would be nice to see it under each specific resource when I look at the docs folder.  Like a field at the top or bottom that simply says "Initial supported version = v2.1.13".  So for example on terraform-provider-oci/docs/core/security_lists.md right underneath the header "oci_core_security_list" you could put initial supported version.  Also, if necessary you could put final supported version if it is changed.

On #1, is there a list of any/all deprecated values?  Is cidr_block the only one we are likely to see warnings on?

**Comment by rcohenma** [comment]
Thank you for your suggestion.

We expect that when people upgrade the version of the terraform provider because they need a new feature they will always upgrade to the latest version available.
