### ISSUE TITLE
oci_database_db_system.database does not use display_name

### ISSUE THREAD

**Issue by richardson-marc** [oracle/terraform-provider-oci#580]
### Terraform Version

 v0.11.7

</details>

### OCI Provider Version

terraform-provider-oci_v2.2.1

</details>

### Description:
build a terraform file with the display_name set.  Observe that terraform plan and terraform apply both use a computed value

### Terraform Plan

<details>
resource "oci_database_db_system" "database" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
  compartment_id   = "${var.compartment_ocid}"
  cpu_core_count   = "${var.db_cores}"
  database_edition = "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"
  db_home {
    database {
      "admin_password" = "${var.db_password}"
      "db_name"       = "int1"
      "character_set" = "AL32UTF8"
      "db_workload"   = "DSS"
    }
    db_version   = "18.2.0.0"
     display_name = "${var.display_name}"
  }
  data_storage_percentage = 40
  license_model           = "LICENSE_INCLUDED"
  disk_redundancy         = "NORMAL"
  shape                   = "${var.db_shape}"

    subnet_id               = "${oci_core_subnet.db.id}"
  ssh_public_keys = ["${var.bastion_public_key}"]
  #  cluster_name    = "cluster"
  hostname = "hostname"
  node_count = 1

terraform plan/apply:
 + oci_database_db_system.database
      id:                                       <computed>
      availability_domain:                      "vins:US-ASHBURN-AD-1"
      backup_subnet_id:                         <computed>
      cluster_name:                             <computed>
      compartment_id:                           "<compartment OCID>"
      cpu_core_count:                           "2"
      data_storage_percentage:                  "40"
      data_storage_size_in_gb:                  <computed>
      database_edition:                         "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"
      db_home.#:                                "1"
      db_home.0.database.#:                     "1"
      db_home.0.database.0.admin_password:      <sensitive>
      db_home.0.database.0.backup_id:           <computed>
      db_home.0.database.0.backup_tde_password: <computed>
      db_home.0.database.0.character_set:       "AL32UTF8"
      db_home.0.database.0.db_backup_config.#:  <computed>
      db_home.0.database.0.db_name:             "int1"
      db_home.0.database.0.db_workload:         "DSS"
      db_home.0.database.0.ncharacter_set:      <computed>
      db_home.0.database.0.pdb_name:            <computed>
      db_home.0.db_version:                     "18.2.0.0"
      db_home.0.display_name:                   "db41-ad1-i01"
      disk_redundancy:                          "NORMAL"
     display_name:                             <computed>

</details>

This seems to be the relevant code in the provider.  The documentation suggest that display_name can be set by the user, but that is not the case.
https://github.com/oracle/terraform-provider-oci/blob/master/provider/database_db_system_resource.go#L165

**Comment by rcohenma** [comment]
Tried to reproduce it but couldn't.

Looking at your config file it looks like you are getting the correct display_name in the plan output

 db_home.0.display_name: "db41-ad1-i01"

You should note that there are 2 display names in this resource

one is set at the top level (it doesn't seem like you are setting that one) which is the display_name of the db_system

The other one is the display_name of the db_home inside the db_home object. This is the one you are setting.

You could move your display_name line outside of the db_home object and into the db_system resource to solve  your issue.

Let me know if this addresses your issue

**Comment by richardson-marc** [comment]
updated as suggested terraform plan now shows this:

display_name:                             "dbsystem201808<somedigits>" => "my-db-name"

So I believe apply should delete the DB resource and create it with the expected name.  Testing now, will verify in the AM.  Thank you for your help!

**Comment by richardson-marc** [comment]
this worked, thank you!
