### ISSUE TITLE
Database creation with container for backup is failing

### ISSUE THREAD

**Issue by Shasthri** [oracle/terraform-provider-oci#583]
### Terraform Version
Terraform v0.11.8

### OCI Provider Version
terraform-provider-oraclepaas_v1.3.0_x4

### Description:
Creating Database classic along with the storage container classic for backup failed with the below error.

------------------------------------
Aug 29, 2018 6:03:49 AM UTC	Failed to configure Oracle Database Server...[ SCRIPT execution errors in [129.157.177.156]: * getaddrinfo(3) failed for idcs-************.storage.oraclecloud.com:443 * Couldn't resolve host 'idcs-************.storage.oraclecloud.com' * Closing connection #0 ERROR : Connectivity problem with OSS server. ERROR : Assistant bkup has failed, please check ocde logfile /var/opt/oracle/log/ORCL/ocde/ocde_2018-08-29_05:48:25.log INFO: Total time taken by ocde is 882 seconds #### Completed OCDE with errors, please check logs #### = 300 nls_language = "AMERICAN" ]
-----------------------------------

### Terraform Plan

Below are the file contents that was used.

--main.tf --
variable user {}
variable password {}
variable domain {}

provider "oraclepaas" {
  user              = "${var.user}"
  password          = "${var.password}"
  identity_domain   = "${var.domain}"
  database_endpoint = "https://dbaas.oraclecloud.com"
}

resource "oraclepaas_database_service_instance" "database" {
  name              = "my-terraformed-database1"
  description       = "Created by Terraform"
  shape             = "oc1m"
  subscription_type = "HOURLY" // HOURLY MONTHLY
  ssh_public_key = "${file("publicKey")}"
  notification_email = "${var.user}"

  edition = "EE" // SE EE EE_HP EE_EP
  version = "18.0.0.0" // 18.0.0.0 or 12.2.0.1 or 12.1.0.2 or 11.2.0.4

  bring_your_own_license   = false // Bring Your Own License (BYOL) is supported only with Universal Credits account.
  high_performance_storage = false // High Performance Storage is only supported for CLOUD_CREDIT service entitlement

  database_configuration {
    admin_password     = "Pa55_Word"
    backup_destination = "BOTH"
    sid                = "ORCL"
    usable_storage     = 25
    is_rac             = false
  }

  backups {
    cloud_storage_container = "storage-idcs-************/my-terraformed-database-backup"
    create_if_missing       = true
  }
}
----------------

terraform.tfvars

user="cloud.admin"
password="*************"
domain="idcs-****************"
database_endpoint="https://dbaas.oraclecloud.com"
java_endpoint="https://jaas.oraclecloud.com"

Note: Actual values of the identity domain has been masked.

As the error says, it is creating the storage end point URL with the values provided in the "backups" section. 

Actual storage REST endpoint we can see in console is : https://gse00015502.us.storage.oraclecloud.com/v1/Storage-gse00015502

Terraform created URL as seen in error is : idcs-************.storage.oraclecloud.com

So we can see there is mismatch between the actual REST endpoint and the terraform created one.

Further we tried to give the below value in the "backups" section -

  backups {
    cloud_storage_container = "storage-gse00015502.us/my-terraformed-database-backup"
    create_if_missing       = true
  }

It gave the below error -
Unable to connect to Oracle Cloud Storage Container [storage-gse00015502.us/my-terraformed-database-backup]. Verify Cloud Storage Username and/or Password and try again.

Tried also with the below value (Added "." after "us")-
cloud_storage_container = "storage-gse00015502.us./my-terraformed-database-backup"

Fails with the error (it adds "." to form the endpoint)-

getaddrinfo(3) failed for gse00015502.us..storage.oraclecloud.com:443 * Couldn't resolve host 'gse00015502.us..storage.oraclecloud.com' * Closing connection #0 ERROR : Connectivity problem with OSS server. ERROR : Assistant bkup has failed, please check ocde logfile /var/opt/oracle/log/ORCL/ocde/ocde_2018-08-29_11:56:30.log INFO: Total time taken by ocde is 861 seconds #### Completed OCDE with errors,

Please let us know your thoughts/suggestions on this.

**Comment by ravitandonrt** [comment]
@Shasthri Sorry for the delayed response. This repository/issues is for the OCI terraform provider. Your resource and provider is for OraclePaas and you need to file your issue here: https://github.com/terraform-providers/terraform-provider-oraclepaas

I will be closing this issue.
