### ISSUE TITLE
File System Services - After creation of multiple FSS, the display_names of all of the FSS are marked as needing updating 

### ISSUE THREAD

**Issue by NullARC** [oracle/terraform-provider-oci#587]
### Terraform Version
[jsaleh@linuxadmin(ENV=Infra - Region=us-ashburn-1) fss]$terraform -version
Terraform v0.11.7
+ provider.oci v2.2.2

### OCI Provider Version
[jsaleh@linuxadmin(ENV=Infra - Region=us-ashburn-1) fss]$terraform -version
Terraform v0.11.7
+ provider.oci v2.2.2

### Description:
1) Create Terraform files for Mount targets (2 - one in each AD)
2) Create Terraform files for FSS - one file with all required resources for file system services that use created mount target
3) Test files using 'terraform plan'
4) Build service using 'terraform apply'
5) Verify service build using 'terraform plan'
 - expect to see all services up to date 
 - actual result - each new FSS needs to have the 'display_name' updated as it shows the current 'display_name' is one from another FSS that was just created.

NOTE: Captured TF trace files for each step. TF trace files uploaded

### Terraform Plan

Output from 2nd 'terraform plan' command. Full log of command log uploaded

saleh@linuxadmin(ENV=Infra - Region=us-ashburn-1) fss]$tf plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.oci_identity_availability_domains.ADs: Refreshing state...
oci_file_storage_file_system.informatica_share: Refreshing state... (ID: ocid1.filesystem.oc1.iad.aaaaaaaaaaaael43nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_mount_target.ASHOC1MT01-FSS-MT1: Refreshing state... (ID: ocid1.mounttarget.oc1.iad.aaaaaa4np2smsiy4nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_file_system.ebs_japrd_fs_ne: Refreshing state... (ID: ocid1.filesystem.oc1.iad.aaaaaaaaaaaael47nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_mount_target.ASHOC2MT01-FSS-MT1: Refreshing state... (ID: ocid1.mounttarget.oc1.iad.aaaaaa4np2snoafznfqwillqojxwiotjmfsc2ylefuzaaaaa)
oci_file_storage_file_system.ebs_japrd_fs2: Refreshing state... (ID: ocid1.filesystem.oc1.iad.aaaaaaaaaaaael46nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_file_system.ebs_demantra_apps: Refreshing state... (ID: ocid1.filesystem.oc1.iad.aaaaaaaaaaaael44nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_file_system.prd_stage2: Refreshing state... (ID: ocid1.filesystem.oc1.iad.aaaaaaaaaaaael36nfqwillqojxwiotjmfsc2ylefuzaaaaa)
oci_file_storage_file_system.ebs_japrd_fs1: Refreshing state... (ID: ocid1.filesystem.oc1.iad.aaaaaaaaaaaael5anfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_file_system.prd_stage1: Refreshing state... (ID: ocid1.filesystem.oc1.iad.aaaaaaaaaaaael45nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export_set.prd_stage2-FSS-MT1-ES1: Refreshing state... (ID: ocid1.exportset.oc1.iad.aaaaaa4np2snoafynfqwillqojxwiotjmfsc2ylefuzaaaaa)
oci_file_storage_export_set.fs2-FSS-MT1-ES1: Refreshing state... (ID: ocid1.exportset.oc1.iad.aaaaaa4np2smsiy3nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export_set.fs1-FSS-MT1-ES1: Refreshing state... (ID: ocid1.exportset.oc1.iad.aaaaaa4np2smsiy3nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export_set.fs_ne-FSS-MT1-ES1: Refreshing state... (ID: ocid1.exportset.oc1.iad.aaaaaa4np2smsiy3nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export_set.ebs_demantra_apps-FSS-MT1-ES1: Refreshing state... (ID: ocid1.exportset.oc1.iad.aaaaaa4np2smsiy3nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export_set.prd_stage1-FSS-MT1-ES1: Refreshing state... (ID: ocid1.exportset.oc1.iad.aaaaaa4np2smsiy3nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export_set.informatica-FSS-MT1-ES1: Refreshing state... (ID: ocid1.exportset.oc1.iad.aaaaaa4np2smsiy3nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export.prd_stage2-FSS-MT1-FS1: Refreshing state... (ID: ocid1.export.oc1.iad.aaaaaby27vez3bk2nfqwillqojxwiotjmfsc2ylefuzaaaaa)
oci_file_storage_export.informatica-FSS-MT1-FS1: Refreshing state... (ID: ocid1.export.oc1.iad.aaaaaby27vey7iu5nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export.fs1-FSS-MT1-FS1: Refreshing state... (ID: ocid1.export.oc1.iad.aaaaaby27vey7ipfnfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export.fs_ne-FSS-MT1-FS1: Refreshing state... (ID: ocid1.export.oc1.iad.aaaaaby27vey7iu7nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export.fs2-FSS-MT1-FS1: Refreshing state... (ID: ocid1.export.oc1.iad.aaaaaa4np2smsik2nfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export.ebs_demantra_apps-FSS-MT1-FS1: Refreshing state... (ID: ocid1.export.oc1.iad.aaaaaby27vey7iphnfqwillqojxwiotjmfsc2ylefuzqaaaa)
oci_file_storage_export.prd_stage1-FSS1-MT1-FS1: Refreshing state... (ID: ocid1.export.oc1.iad.aaaaaa4np2smsiy6nfqwillqojxwiotjmfsc2ylefuzqaaaa)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ oci_file_storage_export_set.ebs_demantra_apps-FSS-MT1-ES1
      display_name: "fs_ne-FSS-MT1-ES1" => "ebs_demantra_apps-FSS-MT1-ES1"

  ~ oci_file_storage_export_set.fs1-FSS-MT1-ES1
      display_name: "fs_ne-FSS-MT1-ES1" => "fs1-FSS-MT1-ES1"

  ~ oci_file_storage_export_set.fs2-FSS-MT1-ES1
      display_name: "fs_ne-FSS-MT1-ES1" => "fs2-FSS-MT1-ES1"

  ~ oci_file_storage_export_set.informatica-FSS-MT1-ES1
      display_name: "fs_ne-FSS-MT1-ES1" => "informatica-FSS-MT1-ES1"

  ~ oci_file_storage_export_set.prd_stage1-FSS-MT1-ES1
      display_name: "fs_ne-FSS-MT1-ES1" => "prd_stage1-FSS-MT1-ES1"

Plan: 0 to add, 5 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

[TF-FSS-Bug-Capture-4Sep18.txt](https://github.com/oracle/terraform-provider-oci/files/2351000/TF-FSS-Bug-Capture-4Sep18.txt)
[TF_FSS_1st_PLAN.log](https://github.com/oracle/terraform-provider-oci/files/2351003/TF_FSS_1st_PLAN.log)
[TF_FSS_1st_APPLY.log](https://github.com/oracle/terraform-provider-oci/files/2351004/TF_FSS_1st_APPLY.log)
[TF_FSS_2nd_PLAN.log](https://github.com/oracle/terraform-provider-oci/files/2351005/TF_FSS_2nd_PLAN.log)

**Comment by ravitandonrt** [comment]
This is a documentation issue. The File Storage Export Sets are created and destroyed implicitly as part of creating Mount Targets. They are modeled and exposed as a resource as they support Update and Get operations.

If you look at the provider source code, it uses Mount Target id to get the Export Set details.

What happened in this case is that multiple Export Sets were created in Terraform Config pointing to same Mount Target (as evident in the OCID of each export set), hence each of those Export Sets were overwriting each other and hence, resulting in a diff on each plan execution.

To remediate this, one should only create a single Export Set per mount target and use that for each export.

References:

- https://github.com/oracle/terraform-provider-oci/blob/master/provider/file_storage_export_set_resource.go#L120
- https://docs.cloud.oracle.com/iaas/api/#/en/filestorage/20171215/ExportSet/
- https://docs.cloud.oracle.com/iaas/Content/File/Tasks/managingmounttargets.htm
