### ISSUE TITLE
need to remove one }

### ISSUE THREAD

**Issue by OracleDaran** [oracle/terraform-provider-oci#592]
https://github.com/oracle/terraform-provider-oci/blob/804c91d78cd1d0c75b7105560110cf3122261f38/docs/examples/networking/subnet/subnet.tf#L35

**Comment by ravitandonrt** [comment]
Thanks for reporting @OracleDaran , will get it fixed.

**Comment by OracleDaran** [comment]
> Thanks for reporting @OracleDaran, just confirmed with @alexng-canuck, his next changes will address this.

Thanks!
