### ISSUE TITLE
Improvement needed: extract all IP addresses of all instances in instance pool

### ISSUE THREAD

**Issue by paulkut** [oracle/terraform-provider-oci#671]
### Terraform Version

<details>
0.11.10
</details>

### OCI Provider Version

<details>
3.10.0
</details>

### Description
Some way needed to extract list of IP Addresses of the instances in the instance pool.

Hi,

As for today, we could extract instance ip address only via OCI_CORE_VNIC command that requires to specify exact vnic_id we are looking for. When deploying instance pools we have no way to get all ip addresses of pool instances at once. OCI_CORE_VNIC command is unable to accept list of IDs, OCI_CORE_INSTANCE_POOL_INSTANCES has no such information. From my point of view, ideally the last command should return IP addresses with corresponding host names as well.

Best regards,
Paul.

**Comment by bowfeng** [comment]
@paulkut Thanks for your feedback.
There is a way to get back IP address through ` data "oci_core_instance"`.
below is tf snippet to get back ip address. let's assume you already have instance pool resource.

 data "oci_core_instance_pool_instances" "TFInstancePoolInstanceDatasources" {
  compartment_id   = "${var.compartment_ocid}"
  instance_pool_id = "${oci_core_instance_pool.TFInstancePool.id}"
}

data "oci_core_instance" "instanceInthePool" {
  instance_id = "${data.oci_core_instance_pool_instances.TFInstancePoolInstanceDatasources.instances.0.id}"
}

output ip_address {
  value = "${data.oci_core_instance.singleInstance.public_ip}"
}

**Comment by kilokahn** [comment]
@paulkut - does the workaround mentioned by @bowfeng work for you? Thanks!

**Comment by paulkut** [comment]
Not really. To get ALL IP addresses you have to iterate over all instances. Working example is following:

```
data "oci_core_instance_pool_instances" "instances" {
  compartment_id = "${var.compartment_ocid}"
  instance_pool_id = "${oci_core_instance_pool.instance_pool.id}"
}
data "oci_core_instance" "instance" {
  count = 5  #count of instances, may be replaces to variable
  instance_id = "${lookup(data.oci_core_instance_pool_instances.instances.instances[count.index], "id")}"
}
output "Pooled instances private IPs" { value = [ "${data.oci_core_instance.instance.*.private_ip}" ] }
```

**Comment by kilokahn** [comment]
@paulkut - thanks for the quick response. So, you are suggesting that the workaround does the job while being inefficient and inelegant?

**Comment by paulkut** [comment]
Yes. I think that it should be more straighforward way as far as actually list of IP addresses is the most important output from Instance Pool object. So as a best solution - oci_core_instance_pool object should have IP addresses as an output.

**Comment by kilokahn** [comment]
Thanks @paulkut! We will add this to the enhancement queue. If there are more customers interested in this, they can 👍 this comment.

**Comment by bnestelroad** [comment]
This is the very close to the exact issue I'm experiencing right now.  I'll take this one step further and say why I need a list of private ip's.  I am attempting to add instance pool instances to multiple load balancer backendsets.  I can add the instance pool instances to the first BES via `oci_core_instance_pool.load_balancers`, but adding to the anything else requires me to use `oci_load_balancer_backend` which then requires the instance pool instance IP address to make the connection.

**Comment by dragon299** [comment]
I am also interested in such a feature. I would like to generate an ansible-inventory file from terraform

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
