### ISSUE TITLE
bm provider: issue with creating route table without route rule

### ISSUE THREAD

**Issue by ttsharma** [oracle/terraform-provider-oci#68]
Want to create a route table with 0 route rule.

Such a route table can come handy to attach to a subnet which I am not sure if I want to open to public internet or not.

baremetal_core_route_table does not allow me to create such a route table, I can create one from console though.

In case I define route table as:
resource "baremetal_core_route_table" "tts_tf_apps_routetable" {
    compartment_id = "${var.compartment_ocid}"
    vcn_id = "${baremetal_core_virtual_network.tts_tf_vcn.id}"
    display_name = "tts_tf_routetable"
}

It errors:
  * baremetal_core_route_table.tts_tf_apps_routetable: "route_rules": required field is not set

If I define route table as it crashes and creates a crash.log
resource "baremetal_core_route_table" "tts_tf_apps_routetable" {
    compartment_id = "${var.compartment_ocid}"
    vcn_id = "${baremetal_core_virtual_network.tts_tf_vcn.id}"
    display_name = "tts_tf_routetable"
    route_rules {}
}

**Comment by jmajumde** [comment]
We need address two issue here

1. Ability to create just a route table with 'baremetal_core_route_table' resource specifying route_rules {}

2. Create a new resource 'baremetal_core_route_rule' resource to have a flexibility formcreating rules later as the rest API supports

**Comment by codycushing** [comment]
Based on how this resources is consuming route_rule blocks what we need to support is complete omission of a block resulting in an empty array being posted in the create/update call--both already supported by the api.

**Comment by codycushing** [comment]
Fixed in v2.0.1
