### ISSUE TITLE
How to assign a reserved public ip?

### ISSUE THREAD

**Issue by markxnelson** [oracle/terraform-provider-oci#680]
### Terraform Version
Terraform v0.11.7

### OCI Provider Version
3.11.0

### Description:
I want to assign a reserved public IP to my instance.   I know that there is an existing closed ticket #577 which is a very similar question.  I see on the documentation (https://www.terraform.io/docs/providers/oci/d/core_instance.html) that there is an attribute called `public_ip` but when I try to set that, I get an error. 

Here is a excerpt from my oci_core_instance: 

```
resource "oci_core_instance" "MyKubernetesMaster" {
  availability_domain = "mFEn:PHX-AD-1"
  compartment_id = "${var.compartment_ocid}"
  display_name = "MyKubernetesMaster"
  shape = "${var.InstanceShape}"


  create_vnic_details {
    subnet_id = "ocid1.subnet.oc1.phx.xxxxx"
    display_name = "primaryvnic"
    hostname_label = "kubernetes-master"
    assign_public_ip = "false"
    private_ip = "100.111.141.xx"
    public_ip = "144.25.19.xx"
  }
```

The error is:
```
[Sun Jan 06 09:21:55] marnelso@MARNELSO-mac terraform (master) 
$ terraform plan

Error: oci_core_instance.WebLogicXKubernetesMaster: create_vnic_details.0: invalid or unknown key: public_ip
```

If I do not set the public_ip, just the private_ip, that works, but what actually happens is that it assigns that private IP (which "belongs" to the reserved IP address) to the instance, but it does not attach the reserved public ip to the vnic, so I can't actually use the reserved public ip address to access the instance. 

I hope that is clear - the "reserved public ip" object in OCI has a public and private address.  Normally, to use it, you go into the console and go to the VNIC and assign the reserved public IP to the VNIC, then in the instance, you add the reserved public ip's "private ip" to the interface.  

### Terraform Plan

Assuming you are an Oracle employee, you can ping me on Slack and I can show/give you a plan within the Oracle network.  The tenancy I am using is FastConnected to the Oracle corpnet, so you would not be able to see it from outside anyway, even if you had the API keys, etc....

**Comment by alexng-canuck** [comment]
Hi @markxnelson , 

The `public_ip` attribute is a computed attribute of the instance VNIC that tells you what the public IP address is after one has been assigned. It's not an input value and can't be used to assign public IPs.

For assigning a reserved public IP, the following example gives some hints: 
https://github.com/terraform-providers/terraform-provider-oci/blob/master/docs/examples/networking/public_ip/public_ip.tf

To summarize, you would need to:
- Assign a private IP to a VNIC in that instance
- Find the private IP's OCID using some datasources
- Assign a reserved public IP to that private IP using the above OCID

So to modify your example slightly, it would look like this:
```
resource "oci_core_instance" "MyKubernetesMaster" {
  availability_domain = "mFEn:PHX-AD-1"
  compartment_id = "${var.compartment_ocid}"
  display_name = "MyKubernetesMaster"
  shape = "${var.InstanceShape}"


  create_vnic_details {
    subnet_id = "ocid1.subnet.oc1.phx.xxxxx"
    display_name = "primaryvnic"
    hostname_label = "kubernetes-master"
    assign_public_ip = "false"
    private_ip = "100.111.141.xx"
  }
...
}

# Gets a list of VNIC attachments on the instance
data "oci_core_vnic_attachments" "TFInstanceVnics" {
  compartment_id      = "${var.compartment_ocid}"
  availability_domain = "mFEn:PHX-AD-1"
  instance_id         = "${oci_core_instance.MyKubernetesMaster.id}"
}

# Gets the primary VNIC from the list of attachments
data "oci_core_vnic" "TFInstanceVnic1" {
  vnic_id = "${lookup(data.oci_core_vnic_attachments.TFInstanceVnics.vnic_attachments[0],"vnic_id")}"
}

# Use the primary VNIC's OCID to get a list of private IPs assigned to it
data "oci_core_private_ips" "TFPrivateIps" {
  vnic_id = "${data.oci_core_vnic.TFInstanceVnic1.id}"
}

# Assign a reserved public IP to the private IP
resource "oci_core_public_ip" "ReservedPublicIPAssigned" {
  compartment_id = "${var.compartment_ocid}"
  display_name   = "TFReservedPublicIPAssigned"
  lifetime       = "RESERVED"
  private_ip_id  = "${lookup(data.oci_core_private_ips.TFPrivateIps.private_ips[0],"id")}"
}
```

Hope this helps.

**Comment by codycushing** [comment]
If this did not answer your question feel free to reopen the ticket.

**Comment by markxnelson** [comment]
Thanks, this did seem to work.  It did create a new reserved IP the first time I ran it, rather than using the one that was already there.. but I guess I can live with that.
