### ISSUE TITLE
"oci_identity_compartment" to return OCID of tenancy/root compartment

### ISSUE THREAD

**Issue by olkoko** [oracle/terraform-provider-oci#721]
Invoking OCI provider using Instance Principal Authentication does not require specifying "tenancy_ocid" ("compartment_id" of tenancy's root compartment), it is inherited implicitly from the contexts of the compute instance where terraform was invoked.
This allows to write very lean configuration files with very few input parameters.

On the other hand, most of the OCI resources do have mandatory "compartment_id" argument.
It can be dynamically queried from "oci_identity_compartments" data source, but it requires specifying mandatory "compartment_id" argument (which is often ocid of tenancy).

We need a way to dynamically retrieve details about tenancy's root compartment (including its OCID) without specifying "tenancy_ocid".

One way to do it is to make optional the "id" argument of data source "oci_identity_compartment", so when it is not specified the data source would return details of current root compartment/tenancy.

The other alternative would be creating data source to retrieve information about OCI provider itself (data "oci_provider" "provider_details"?), which among other details would return OCID of tenancy root compartment.

**Comment by alexng-canuck** [comment]
Hi @olkoko,

Thanks for the feedback. 

Regarding:
> One way to do it is to make optional the "id" argument of data source "oci_identity_compartment", so when it is not specified the data source would return details of current root compartment/tenancy.

The `oci_identity_compartment` calls into the `GetCompartment` API from the OCI service and that always requires an `id` argument. So we cannot make `id` optional. Unfortunately, none of the service APIs can give you the root compartment OCID unless you already know the tenancy OCID beforehand.

Othre alternatives would require deriving the tenancy OCID in some way from the instance or instance principal that the configuration is using.

> The other alternative would be creating data source to retrieve information about OCI provider itself (data "oci_provider" "provider_details"?), which among other details would return OCID of tenancy root compartment.

This is non-trivial because the tenancy OCID is hidden from the provider behind the instance principal auth. However, it might be possible to expose tenancy OCID through an instance metadata datasource since details about Instance Principal auth can be retrieved from instance metadata (see https://github.com/terraform-providers/terraform-provider-oci/issues/530).

We will look into this.

**Comment by alexng-canuck** [comment]
For now, I would recommend treating the compartment ID as an input parameter to your configs. That way you have the flexibility of changing the compartment ID if you choose to do so in the future.

You could have some mechanism that gets the compartment ID from the instance metadata (see https://docs.cloud.oracle.com/iaas/Content/Compute/Tasks/gettingmetadata.htm#) using a `curl` command. From there, you could then pre-set the compartment ID as an environment variable prior invoking Terraform.

**Comment by olkoko** [comment]
Thank you. 
Being able to retrieve information about current user, compartment, and tenancy/root compartment will be very useful when running terraform scripts/stacks inside of OCI Resource Manager service, where you do not have direct access to its infrastructure (details [here](https://docs.cloud.oracle.com/iaas/Content/ResourceManager/Concepts/resourcemanager.htm#AuthenticationandAuthorization)).

**Comment by codycushing** [comment]
Here is some provider voodoo that will let you get the compartment your instance is operating within, as well as the parent compartment, which, if not nested, would be the root compartment:
```hcl
data "http" "instance-metadata" {
  url = "http://169.254.169.254/opc/v1/instance/"
}

locals {
  blob = "${replace(data.http.instance-metadata.body, "/\n*/", "")}"
  compartment_id = "${replace(local.blob, "/.*compartmentId\" : \"(.*?)\",.*/", "$1")}"
}

output "instance-compartment" {
  value = "${local.compartment_id}"
}

data "oci_identity_compartment" "instance-compartment" {
  id = "${local.compartment_id}"
}

output "tenancy-ocid" {
  value = "${data.oci_identity_compartment.instance-compartment.compartment_id}"
}
```

**Comment by olkoko** [comment]
Nice trick @codycushing! Totally forgot about instance metadata.

**Comment by tyskjohan** [comment]
This is even more relevant now that Resource Manager has been introduced in the OCI Console.

**Comment by srishtipmishra** [comment]
This is supported in release 3.69.0 of Terraform Provider.

**Comment by srishtipmishra** [comment]
Marking this upstream as service team is working on it.

**Comment by dralquinta** [comment]
Hello, 

What is the current status of this one? 

I'm crashing against the same issue and I came to realize about two things: 

- With latest provider, I'm not even allowed to do name filtering by root compartment name (Something like this)

```shell
data "oci_identity_compartments" "PARENTCOMPARTMENT" {
  compartment_id            = var.tenancy_ocid
  compartment_id_in_subtree = true
  filter {
    name   = "name"
    values = [var.parent_compartment_name]
  }
}
```

In here when providing var.parent_compartment_name to the name of the root compartment, it basically returns a null array

- I came to realize that compartments can only be created programatically on main region. In any other subscribed region, I'll get this error: 
```shell
│ Error: 403-NotAllowed 
│ Provider version: 4.28.0, released on 2021-05-26.  
│ Service: Identity Compartment 
│ Error Message: Compartment name in region SCL must start with prefix false 
│ OPC request ID: 50a2de68ed114e9998fad808f5147452/74DEF2D52BC0A5A9020F5AB2DE365360/D03FF728255130E9A4A35E61B5E9B387 
│ Suggestion: Please retry or contact support for help with service: Identity Compartment
│ 
│ 
│   with oci_identity_compartment.Compartment,
│   on compartment.tf line 8, in resource "oci_identity_compartment" "Compartment":
│    8: resource "oci_identity_compartment" "Compartment" {
│ 
```

- And providing the prefix "false" will cause this side error: 

```shell
╷
│ Error: 403-NotAllowed 
│ Provider version: 4.28.0, released on 2021-05-26.  
│ Service: Identity Compartment 
│ Error Message: Compartment name in region SCL must start with prefix false 
│ OPC request ID: 52315013a406d4d12de0a887eac62dc1/06C7D0EDA5C6AF0AC651757C2E66A0CE/9920928A9C4FC2AFAE2DE6029A956815 
│ Suggestion: Please retry or contact support for help with service: Identity Compartment
│ 
│ 
│   with oci_identity_compartment.Compartment,
│   on compartment.tf line 8, in resource "oci_identity_compartment" "Compartment":
│    8: resource "oci_identity_compartment" "Compartment" {
│ 
╵
```


The data implementation shared above works great with nested compartments from root, but will always fail when trying to get the root ocid passing on the display name. I'm not sure if this is doable from the API perspective, however this is highly desirable. Pushing the ocid hardcoded looks messy at this point. 

Thanks

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
