### ISSUE TITLE
Attaching LPG peer_id after LPG creating forces new LPG

### ISSUE THREAD

**Issue by priteshkp** [oracle/terraform-provider-oci#729]
### 

<details>
# Run this command to get the terraform version:

Terraform v0.11.10
+ provider.oci v3.16.0
+ provider.template v2.1.0

### OCI Provider Version

Terraform v0.11.10
+ provider.oci v3.16.0
+ provider.template v2.1.0

### Description:

If you create a LPG peering in 2 steps, the TF provider attempts to create a new LPG.

### Terraform Plan

You can use the example LPG, just leave out the peer_id:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/docs/examples/networking/local_vcn_peering/local_vcn_peering.tf

Once the LPGs are created, they will be in state 'NEW', which means they're ready for peering.  Add the 'peer_id' to one of them and run terraform plan, it will show you that it's going to recreate the LPG, which is entirely unnecessary.

For some of our infra, our bootstrapping steps document to create LPGs first and then attach the peer. You can do this in 2 steps via console already, and should be supported by terraform as well.

**Comment by kilokahn** [comment]
Thanks for pointing this out @priteshkp! I will discuss with the team internally and identify if this was done for any specific reason.

**Comment by kilokahn** [comment]
@priteshkp - we see that there is no explicit "disconnect" API available from the service to invoke when the `peer_id` property is removed, and hence this modeling. We are following up with the service team on this use case.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
