### ISSUE TITLE
Support kms-encrypted credentials or secrets directly in OCI resources

### ISSUE THREAD

**Issue by anilarora** [oracle/terraform-provider-oci#848]
### Description

Currently, some resources (e.g. oci_database_autonomous_database) take in credential values which can only be in plaintext.  If that value is available as an KMS encrypted value, it requires a two step process:

```
data "oci_kms_decrypted_data" "password" {
  ciphertext = "${var.kms_encrypted_value}"
  crypto_endpoint = "${var.kms_crypto_endpoint}"
  key_id = "${var.kms_key_id}"
}

resource "oci_database_autonomous_database" "example" {

  admin_password = "${data.oci_kms_decrypted_data. password.plaintext}"
  compartment_id = "${var.compartment_id}"
  cpu_core_count = "1"

  ...truncated...
}

```

This unfortunately, ends up putting the plaintext password directly in the statefile as shown in #847.  Instead, it would be nice if we could pass either secret ocid or kms-encrypted values to the OCI resource to avoid exposing the decrypted value in the statefile.

### New or Affected Resource(s)

oci_database_autonomous_database

### Potential Terraform Configuration

```
resource "oci_database_autonomous_database" "example" {

  admin_password = {
    secret_id = "${var.secret_id}"  // required
    secret_version = "${var.secret_version}" // optional
  }

  compartment_id           = "${var.compartment_id}"
  cpu_core_count           = "1"

  ...truncated...
}
```

```
resource "oci_database_autonomous_database" "example" {

  admin_password = {
    kms_encrypted_value = "${var.kms_encrypted_value}"
    kms_crypto_endpoint = "${var.kms_crypto_endpoint}"
    kms_key_id = "${var.kms_key_id}"
  }

  compartment_id           = "${var.compartment_id}"
  cpu_core_count           = "1"

  ...truncated...
}
```

As a first pass at the implementation, the terraform provider could implement the two-step process by calling the appropriate OCI APIs.  In the future, if the actual service supports tighter integration with OCI, the implementation could be updated accordingly.

This would greatly enhance the OCI specific functionality from a security point of view.

**Comment by rcohenma** [comment]
Thank you for your suggestion. We will pass along the request to the relevant service.

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
