### ISSUE TITLE
How to do nested iteration in Terraform

### ISSUE THREAD

**Issue by rahulviswam17** [oracle/terraform-provider-oci#86]
Hi ,
    I've a requirement in Baremetal IAM service to address below scenarios using Terraform :

##1. Add Multiple users and a group  and assign this user the group ( Many to one mapping )
eg:  

    Group1 :
               - User1
               - User2
               - User2

##2. Add Multiple users to multiple groups and assign users to the group ( Many to Many mapping )

  Group1:
             -User1
             -User2
             -User3

  Group2 :
              -User2
              -User3
              -User4

Group3:
             -User4
             -User1
             -User5

## Corresponding JSON format of the above data 
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

{
 "Groups":[{
      "group_name": "Group1"
       "Users": [
                   {
                    "user_name": "User1"
                    },
                   {
                    "user_name": "User2"
                      },
                  {
                     "user_name": "User3"
              }	      
	     ]
           },

{
      "group_name": "Group2"
       "Users": [
             {
            "user_name": "User2"
              },
             {
            "user_name": "User3"
              },
             {
            "user_name": "User4"
              }	      
	     ]
           },	   
{
      "group_name": "Group3"
       "Users": [
             {
            "user_name": "User4"
              },
             {
            "user_name": "User1"
              },
             {
            "user_name": "User5"
              }	      
	     ]
           }	   
	   ]
}

##Questions :

1. I can meet the above requirement easily using a nested forloop using a program say written in python .
But how to I meet the above in Terraform. 

2. I could make the users and group as list in terraform and create them in loop, but how do I assign the user to its respective group, and skip if the group already created ?

**Comment by VAdamec** [comment]
It's more about Terraform usage, not BMC provider, see for example [here](https://blog.gruntwork.io/terraform-tips-tricks-loops-if-statements-and-gotchas-f739bbae55f9) how to do at least some of standard procedures (loops, ...) in Terraform way. Not very nice, but better than nothing.

**Comment by rahulviswam17** [comment]
@VAdamec , I've already tried this. But unfortunately this wouldnt suffice my scenario. 
I've Groups and users to be created and need to to assign users to their respective groups as well in a programmatic way.

eg: something terraform equivalent of below :

for grps in i["Groups"]
   command[ create_group(grp) ]
   for usrs in j["users"]
       command[ create_user(usrs) ]
  command[ assign(grps,usrs,)]
 
In the above example I can create n number of groups and users and able to assign the user to the required groups (input file will be same as the one I posted in my first comment)      

-->The issue is at assigning the users to multiple groups where number/count of users are groups are not same. 

eg: Say I've 3 groups and 10 users spread accross 3 groups, I could create them by passing the values as list, but unable to assign users to group within the same terraformfile


Below is how my TF looks like , this works as far as my number of users and groups are always same, but thats not the case most of the time and so the approach fails as I am not able to handle count of groups in the same resource. Is there a way I can achieve this scenario using one single TF file?

#user creation in batch
resource "baremetal_identity_user" "UsrCreate" {
    count = "${length(distinct(var.usr_list))}"
    name = "${element(distinct(var.usr_list),count.index)}"
    description = "RV: Terraform test user"
}

#Group creation in batch

resource "baremetal_identity_group" "GrpCreate" {
    count = "${length(var.grp_list)}"
    name = "${element(var.grp_list,count.index)}"
    description = "RV: Group managed with TF"

#Assigning Users to group:
resource "baremetal_identity_user_group_membership" "t" {
                compartment_id = "${var.compartment_ocid}"
                count = "${length(var.usr_list)}"
                user_id = "${element(baremetal_identity_user.UsrCreate.*.id,count.index)}"
                group_id = "${element(baremetal_identity_group.GrpCreate.*.id,count.index)}"
                }

**Comment by VAdamec** [comment]
Hm, I'm afraid Terraform declarative approach failing on such operations. You can use some "cheating" with maps, see for example this issue https://github.com/hashicorp/terraform/issues/2114 from user @sprutner (Mar 21st). I didn't test it, looks awful :-)

I'm not sure if this can be used for calling multiple resources (not sure what should be used for count loops). If you have time to play with it please share result ;-)
