### ISSUE TITLE
Support encrypted state files with KMS

### ISSUE THREAD

**Issue by harveylowndes** [oracle/terraform-provider-oci#961]
**Community Note**

- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Description**

There are cases where we may have secrets that are unencrypted on our state file. This means that we will need to encrypt our state file before stashing them in object storage. Other providers allow for this to be done using KMS, where the key can be optionally provided in the backends configuration.

This feature request looks to add a KMS key id to the backend configuration. When present the state is encrypted before it reaches object storage and decrypted when pull from object storage.

**New or Affected Resource(s)**

**Potential Terraform Configuration**
```terraform {
  backend "s3" {
    bucket   = "terraform-state"
    key      = "terraform.tfstate"
    region   = "us-phoenix-1"
    endpoint = "https://mybucketnamespace.compat.objectstorage.us-phoenix-1.oraclecloud.com"
    kms_key-id = "<key id here>"

    skip_region_validation      = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_get_ec2_platforms      = true
    skip_metadata_api_check     = true
    force_path_style            = true
  }
}

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
